### ISSUE TITLE
Losing shader debugging and output info

### ISSUE THREAD

**Issue by Aborres** [baldurk/renderdoc#892] opened 2018-02-27 20:16 UTC
Hi, 

I have been working lately on restructuring my rendering pipeline and I have noticed I have lost most of the data in Renderdoc. 
Now the tool won't show any shader information, any output in the geometry window and not even all the GPU calls will appear in the API calls/Event Browser. 
I have integrated the API into my pipeline thinking that I could be giving the tool a bad time to understand when a frame starts/ends; however, the issue is still there.
I am running it with OpenGL 3.3 atm and I am using the latest version of the tool.

I have been doing some tests lately but I have not managed to make it appear again. 
Do I have to define something special? That info used to appear without further configuration.

Thanks a lot.
P.D.: Appart from my issue, Amazing tool :)

**Comment by baldurk** [comment] 2018-02-27 20:25
Are you able to share your program, or a captured frame for me to look at? It sounds like something serious is going wrong but without more concrete information it's hard to diagnose exactly what.

If you could also go to help -> view diagnostic log and upload the file here that could provide more useful information and might have some useful error messages.

**Comment by Aborres** [comment] 2018-02-27 20:43
Thanks for the quick reply, I have attached the log file to the answer, it didn't allow me to share the .rdc (it is too big) I can send it to you if you have a preferred way. 

I have been looking at the log file and it contains several errors. I am sorry I didn't check it first, I have been looking at the error panel in the program and it has been saying no errors or warnings all this time...

Those functions it is complained about are defined in separated shaders I am attaching to my programs that means each program has 2-3 vertex shaders and 2-3 fragment shaders; however, only one defines the main function and I use the rest of them as libraries for common stuff. 

I have been working on this application for about two years doing this exact thing and I have never encountered this problem before. 

[RenderDoc_2018.02.27_20.11.03.log](https://github.com/baldurk/renderdoc/files/1764584/RenderDoc_2018.02.27_20.11.03.log)

**Comment by baldurk** [comment] 2018-02-27 20:47
Yes the errors & warnings panel in the UI is only intended for errors originally reported during capturing, not internal errors while replaying like this :smile:.

Do you mean that you attach multiple vertex shader objects and multiple fragment shader objects to the same program and link them all together? That's not supported by RenderDoc at the moment - see #657. If you mean just passing multiple shader strings via `glShaderSource` and only one shader object, that should work fine so the problem is something else.

**Comment by Aborres** [comment] 2018-02-27 21:00
I am linking all of them together. Adding some kind of precompilation of the shaders is still one of my TODOs and this is the "native version of an #include in glsl" 🤦‍♂️. I have been doing this for quite some time, I guess the error has been there for more than I thought and I simply didn't notice. 

I am curious how deep can be the impact of these errors on the app, could they break the representation of the pipeline or even affect buffers and textures? 
Do you have plans on adding support for the feature or is it my time to add graph node based materials? 😄

**Comment by baldurk** [comment] 2018-02-27 22:20
Yes without being able to compile the shaders properly almost everything else will break.

Normally this kind of thing is handled with multiple shader sources that are just concatenated together using `glShaderSource` instead of linked from multiple objects. I'm not sure when I will add support for this use case, since it might be quite complex to support and is a very rare edge case.

I'm closing this since it seems like it's a duplicate of the other bug.

**Closed as completed by baldurk** 2018-02-27 22:20 UTC
Labels: Bug, Need More Info

**Comment by Aborres** [comment] 2018-02-27 22:24
Sure, thanks a lot for your time. 

If you accept constructive feedback, I have been dealing with this problem for some time and a pop-up window or something in the error/warning panel telling the user the program was not running properly would have helped :)

Again, thanks a lot and amazing work.
