### ISSUE TITLE
Couldn't capture from a Vulkan app

### ISSUE THREAD

**Issue by wednesday818** [baldurk/renderdoc#1487] opened 2019-08-07 07:08 UTC
## Description

I tried to capture from an Android's Vulkan Sample vulkan.sample.T15_draw_cube from Android Studio. I got this error.
ADRD 019666: [22:42:49]         vk_manager.h( 206) - Error   - Assertion failed: 'm_CurrentResourceMap.empty()'

How do I fix this? thank you.

## Environment

* RenderDoc build: Version v1.4 (built from 214d8522)
* Operating System: Windows 10 launch to Android
* API: Vulkan

Xiaomi MI 9 Qualcomm Snapdragon 855 Adreno (TM)640

**Comment by baldurk** [comment] 2019-08-07 12:41
I don't understand what you mean that you captured "from Android Studio". RenderDoc is not related to Android Studio and actually having it running while trying to use RenderDoc typically completely breaks since Android is very fragile and easy to break.

The assertion you've mentioned is fairly innocuous and only suggests that the application didn't properly release all resources before destroying the vulkan instance. Please outline what real problem you are encountering and please fill in the Repro Steps section so that I know how I can reproduce the problem.

**Comment by baldurk** [comment] 2019-09-09 09:12
Closing this issue due to lack of information or response.

**Closed as completed by baldurk** 2019-09-09 09:12 UTC
Labels: Bug, Need More Info
