### ISSUE TITLE
Application load renderdoc.dll may hang up.

### ISSUE THREAD

**Issue by swordow** [baldurk/renderdoc#1968] opened 2020-07-01 08:59 UTC
## Description
  My app use renderdoc.dll separately. And sometime it will hang up at the TargetControlServer Thread.

## Steps to reproduce
   Load renderdoc.dll with win32 api LoadLibrary, and RENDERDOC_GetAPI with eRENDERDOC_API_Version_1_2_0

## Environment

* RenderDoc version: 1,7
* Operating System: win10
* Graphics API: DX11

## PS
I have looked inside the source code a little, does following code matter?
![IMG20200701_170551](https://user-images.githubusercontent.com/7107003/86225691-2a3bda00-bbbd-11ea-9e8d-1f604a221438.png)

**Comment by swordow** [comment] 2020-07-01 09:10
The code in first image shows that it does not close thread first

**Comment by baldurk** [comment] 2020-07-01 09:45
Please provide actual repro steps that I can follow, the steps you have described are very generic and many applications do that without problems.

**Comment by swordow** [comment] 2020-07-01 10:00
> Please provide actual repro steps that I can follow, the steps you have described are very generic and many applications do that without problems.

Actually, it is a plugin dll. When my app load this plugin with LoadLibrary, the app will call init method in this plugin, and then, in the init method of this plugin dll, it will load renderdoc.dll and get the renderdoc api, and then, the program hangs up sometime.
This problem does not appear often. For the last case, i attached the program with visual studio and got nothing, no avaiable callback frames and the only information i got was that, vs hangs in the TargetControlServer Thread ....

For the whole flow:
app load plugin dll and call init method immediately -> plugin dll load renaderdoc.dll and get renderdoc api immediately -> program hands up...

**Comment by baldurk** [comment] 2020-07-01 11:37
That is still not a set of steps I can use to reproduce the problem, that's a more detailed restatement of the problem. You need to provide me with an example case that shows the problem or explain how I can reproduce the problem myself.

Loading renderdoc.dll yourself should only be done if you know exactly what you are doing, as doing it wrongly can cause any kinds of unexpected problems including crashes and hangs. Does this problem still happen if you launch your program from RenderDoc directly?

How do you know that the program was hung because of that thread? That thread is started by RenderDoc and will continually loop and block waiting for new connections. Seeing it waiting for a connection in visual studio does not mean it caused any hang.

**Comment by swordow** [comment] 2020-07-02 03:02
> That is still not a set of steps I can use to reproduce the problem, that's a more detailed restatement of the problem. You need to provide me with an example case that shows the problem or explain how I can reproduce the problem myself.
> 
> Loading renderdoc.dll yourself should only be done if you know exactly what you are doing, as doing it wrongly can cause any kinds of unexpected problems including crashes and hangs. Does this problem still happen if you launch your program from RenderDoc directly?
> 
> How do you know that the program was hung because of that thread? That thread is started by RenderDoc and will continually loop and block waiting for new connections. Seeing it waiting for a connection in visual studio does not mean it caused any hang.

Yeah, it is not easy to locate the problem and I have build a renderdoc.dll with pdb using branch master, and waiting for the bug  happening and could u keep this issue opening? :-)

**Comment by baldurk** [comment] 2020-07-02 09:00
For what it's worth I have a [symbol server](https://renderdoc.org/symbols) that contains PDBs for all stable builds and nightly builds in case that is useful.

I don't want to leave this issue open indefinitely and it doesn't have any valuable or relevant discussion, so I'll close it now. If you have more information to provide some time in the future you can open a new issue with a reproducible case or more information about the problem.

**Closed as completed by baldurk** 2020-07-02 09:00 UTC
Labels: Bug, Need More Info

**Comment by wumo** [comment] 2022-10-20 02:32
UE4.26 with Renderdoc plugin enabled will hang up loading library quite often.

**Comment by baldurk** [comment] 2022-10-20 09:43
Please do not comment on closed issues.
