### ISSUE TITLE
RenderDoc crashes without a chance for recovery if the GPU driver is disabled in device manager when using Vulkan

### ISSUE THREAD

**Issue by Pokechu22** [baldurk/renderdoc#2460] opened 2022-01-23 06:55 UTC
## Description

Upon disabling the GPU used by a capture in Device Manager, RenderDoc crashes (without the normal crash report screen popping up or the device lost screen popping up, and without a chance to save the capture).  This happens even if the device is enabled immediately afterwards.

Now, it might sound like the fix for this is "don't disable the device; why would you ever do that?", but there are a few situations where I actually have ran into this in practice.  Until recently, NVIDIA removed other drivers from the adapter list in their vulkan layer (RenderDoc disables that by setting the `DISABLE_LAYER_NV_OPTIMUS_1` environment variable, but it affected testing things outside of RenderDoc).  That no longer seems to be an issue as of NVIDIA driver version 10.0.19042.1466, fortunately.  However, I still need to disable the NVIDIA driver if I want to test OpenGL with my integrated Intel GPU (since OpenGL doesn't provide a way of selecting an adapter, or if there is a way, Dolphin doesn't expose it).  Although this may be an infrequent use case, it's annoying to need to remember to save all open RenderDoc captures or else they'll be lost.

This happens with both my NVIDIA GPU and my integrated Intel GPU.  This issue does not happen with D3D11; instead, the error message below appears (and RenderDoc stops displaying things, but it is still possible to save the capture, which is much better behavior than crashing with no chance of recovery).  This issue also doesn't happen if the disabled GPU isn't the one the capture is using.  I haven't tested D3D12 or OpenGL.

> ![image](https://user-images.githubusercontent.com/8334194/150667590-5aebd633-556a-4f97-a6bc-48bf5086214c.png)
>
> This is displayed with D3D11, but _not_ with Vulkan.

## Steps to reproduce

1. Create a capture in RenderDoc.
2. Open device manager (<kbd>Win</kbd>+<kbd>R</kbd>, enter `devmgmt.msc`); you may need to be using an administrator account.
3. Find the current GPU "display adapters".
4. Right-click it.
5. Select "disable device".
6. Right-click the same GPU.
7. Select "enable device".
8. Switch back to RenderDoc.
9. RenderDoc will immediately exit upon being switched to, with no opportunity to save the capture, and no error message.

## Environment

* RenderDoc version: v1.17
* Operating System: Windows 10.0.19042.1466
* Graphics API: Vulkan

**Comment by baldurk** [comment] 2022-01-23 11:38
As mentioned in the linked issue I suspect this is just a case where a device lost error isn't reported and the ICD or perhaps vulkan loader is either crashing or forcibly killing the process, which I've seen before in the ICD at least. I don't expect this is something I can do anything about.

I'll try to reproduce to confirm, but unless this is RenderDoc mishandling a reported device loss I don't expect this is something I will intend to support.

FWIW:

> Until recently, NVIDIA removed other drivers from the adapter list in their vulkan layer

Yes this user-hostile behaviour is why I set the environment variable - rather than removing the device I'd suggest setting that environment variable globally, or removing the registration of the optimus layer.

> However, I still need to disable the NVIDIA driver if I want to test OpenGL with my integrated Intel GPU 

I've never tested on a hybrid system, but as I understand it either the nvidia control panel or windows will let you explicitly override the GPU to be used with OpenGL where you can't select one in code.

**Comment by Pokechu22** [comment] 2022-01-23 19:41
> I've never tested on a hybrid system, but as I understand it either the nvidia control panel or windows will let you explicitly override the GPU to be used with OpenGL where you can't select one in code.

There does seem to be an option in the nvidia control panel for switching the "preferred graphics processor" between "auto-select", "High-performance NVIDIA processor", and "Integrated graphics", but it doesn't seem to actually affect OpenGL.  It also says that "Windows OS now manages the selection of the graphics processor.  Open Windows graphics settings", and the page that opens does work (and it requires explicitly choosing the program to change settings for).

> As mentioned in the linked issue I suspect this is just a case where a device lost error isn't reported and the ICD or perhaps vulkan loader is either crashing or forcibly killing the process, which I've seen before in the ICD at least. I don't expect this is something I can do anything about.

If I do the same thing with Dolphin, I get a bunch of pop-ups about "Failed to submit command buffer." and a bunch of logging of "vkQueueSubmit failed:  (-4: VK_ERROR_DEVICE_LOST)".  If I select "ignore for this session", nothing crashes (but nothing new renders either).  When I try to close Dolphin, it crashes in the call to `vkDestroySwapchainKHR` with a null-pointer dereference somewhere in nvwgf2umx.dll.

**Comment by baldurk** [comment] 2022-01-25 15:31
I wasn't quite able to reproduce this exactly as described, but I believe I saw the same behaviour. For me on my nvidia system it hung indefinitely inside a `vkResetCommandBuffer` call, but that sounds like it might be the same bug since for a while I've been seeing it do that any time I'd expect a device lost error to be reported. I tested on AMD and I did notice that the error handling was incorrect for actually detecting a device lost error (fixed in the first commit above) and that some cases in the code weren't properly handling vkMapMemory returning a NULL pointer (second commit above). However on AMD I still ran into a crash on shutdown inside AMD's driver.

If you're seeing a crash on shutdown on nvidia then I expect that's the same thing which is killing RenderDoc. You could try attaching a debugger to RenderDoc before doing the repro steps to see what the callstack is when it crashes, but I'd assume it's inside `vkDestroySwapchainKHR` as you saw on dolphin.

You could report these issues to the IHVs but I'm not sure this is something they expect to work so I don't know if they will be interested in fixing those crashes. If the vulkan driver reports VK_ERROR_DEVICE_LOST and shuts down cleanly then RenderDoc should handle this correctly and I'll fix any issue I can reproduce where it doesn't, but the device lost handling is only as good as the driver's.

**Closed as completed by baldurk** 2022-01-25 15:31 UTC
Labels: Bug, Unresolved
