### ISSUE TITLE
Using HLSL custom visualization shaders with a Vulkan capture results in a black image with Nvidia drivers

### ISSUE THREAD

**Issue by Pokechu22** [baldurk/renderdoc#2458] opened 2022-01-23 04:31 UTC
## Description

Using an HLSL shader for the "custom" channels view in the texture viewer results in a black image, even after switching back to regular HLSL shaders or RGBA channels.

The [custom visualization docs](https://github.com/baldurk/renderdoc/blob/v1.x/docs/how/how_custom_visualisation.rst) say that Vulkan allows both GLSL and HLSL.

## Steps to reproduce

To generate the attached capture:

1. Download Dolphin and the [lesson08 fifolog](https://fifo.ci/media/dff/Lesson08.dff).
2. Launch Dolphin using RenderDoc.
3. In Dolphin, click "Graphics", and change the backend to Vulkan.
4. In Dolphin, switch to the advanced tab under graphics and check "Enable API Validation Layers" (this is not required to reproduce, but it enables debug symbols and source attachment for the shader)
5. In Dolphin, close the graphics window and open the config window.  Uncheck "Enable Dual Core" (as the fifoplayer doesn't work well with it).
6. In Dolphin, close the graphics window, and then select "open".  Open the Lesson08.dff file from before.
7. Save a capture.  Dolphin can now be closed.

To reproduce:

1. Open [Lesson08_Vulkan.zip](https://github.com/baldurk/renderdoc/files/7919669/Lesson08_Vulkan.zip)
2. Navigate to an internal-resolution draw (in this capture, EID 59).
3. Click on the input texture.
4. In the texture viewer, under channels, select "custom".
5. In the drop-down next to that, enter `RA.glsl` and click the green `+` button (this issue doesn't require creating a new shader; it also works with existing shaders)
6. Enter the following in the new shader:
    ```glsl
    #version 420 core
    
    layout(binding = 7) uniform sampler2DArray tex2DArray;
    layout (location = 0) in vec2 uv;
    layout (location = 0) out vec4 color_out;
    
    void main()
    {
        color_out = vec4(texture(tex2DArray, vec3(uv, 0)).ra, 0, 1);
    }
    ```
7. Click "apply changes"
8. Switch back to the texture viewer.  Everything should render correctly (the texture will appear green/yellow; this is just a shader I have lying around)
9. In the drop-down next to the channel selector, enter `RA.hlsl` and click the green `+` button.
10. Enter the following in the new shader:
    ```hlsl
    SamplerState pointSampler : register(s0);
    Texture2DArray<float4> texDisplayTex2DArray : register(t2);
    
    float4 main(float4 pos : SV_Position, float4 uv : TEXCOORD0) : SV_Target0
    {
        return float4(texDisplayTex2DArray.Sample(pointSampler, uv.xyz).ra, 0, 1);
    }
    ```
11. Click "apply changes"
12. Switch back to the texture viewer.  It may initially appear correct, but resizing the window or changing the selection will result in it being completely black.
13. RenderDoc is now broken: switching back to `RA.glsl` or back to RGBA channels won't fix it, and the preview in the mesh viewer and other views are also broken.  I've also had RenderDoc hang in this state (as in stop responding to input; no crash report was generated when I clicked the X button), but I don't know what causes that.  The problem only way to fix the problem is to close and reopen RenderDoc.

## Environment

* RenderDoc version: v1.17
* Operating System: Windows 10.0.19042.1466
* Graphics API: Vulkan
* GPU: NVIDIA GeForce GTX 1650 Ti, driver version 30.0.14.7141.  This does **not** happen with "Intel(R) UHD Graphics" (driver version 30.0.100.9684).

**Comment by Pokechu22** [comment] 2022-01-23 04:48
This also affects NVIDIA driver version 30.0.15.1123 (the most recent one, from 1/10/2022).

**Comment by Pokechu22** [comment] 2022-01-23 05:01
With an OpenGL capture, HLSL shaders aren't listed, so the issue doesn't occur, but GLSL shaders do work properly (though `layout(binding = 7)` needs to be changed to `layout(binding = 6)` for my shader to work properly).

**Comment by baldurk** [comment] 2022-01-23 11:34
Just to clarify when you say this "does not happen with "Intel(R) UHD Graphics" (driver version 30.0.100.9684)." do you mean it doesn't stop responding, or that you get a proper texture preview? The first I'd expect, the second I would not.

It seems like the documentation needs to be made more clear as you've misunderstood how the custom visualisation shaders are set up. The bindings are **API** specific not **source language** specific. In vulkan, the 2D array texture is bound to binding 7, *regardless of whether you're using GLSL or HLSL*. In the documentation it lists "D3D11 or D3D12 / HLSL" because those are the bindings for D3D, and HLSL is the default and only language used. Similarly it lists "Vulkan / GLSL" because again GLSL is the default language.

Indeed the samplers at bindings s0 and s1 are explicitly called out as "D3D11/D3D12 only". It looks like the docs are out of date because I do provide separate point/linear samplers on vulkan now for HLSL shaders but they are not at bindings 0 and 1.

I should update it to "Vulkan / GLSL or HLSL or any language you use" since I think in theory you could write a custom visualisation shader in spirv-dis assembly or rust or etc, provided you have an appropriate compiler configured. You still have to use binding 7 though, using binding 2 as you've done here will not work because there is no texture bound there and so you're in undefined behaviour land as there's no binding declared for binding 2, and binding 0 is a uniform buffer not a sampler.

If you use the 'insert snippet' menu items it will insert the correct bindings for you to use. In future perhaps I should reflect the incoming custom shader and match it against the expected bindings, at least for vulkan/D3D12 where it can be catastrophic if the bindings are incorrect. That's quite a low priority issue though since that could be complex.

As to the crash/hang, I suspect this is a plain device lost error. I've noticed the same behaviour recently where for some reason nvidia's drivers never return a device lost error, instead continuing on until at some point they hang, or sometimes fatal error inside the ICD itself completely killing the process without a chance to recover or report the error. I suspect that is the cause of #2460 too (or possibly vulkan just doesn't handle GPUs being removed gracefully) but I will need to reproduce to verify.

Aside from clarifying the documentation this doesn't seem like a bug, if you can verify that a correctly set up custom shader works then I think this can be closed.

**Comment by Pokechu22** [comment] 2022-01-23 19:15
> Just to clarify when you say this "does not happen with "Intel(R) UHD Graphics" (driver version 30.0.100.9684)." do you mean it doesn't stop responding, or that you get a proper texture preview? The first I'd expect, the second I would not.

I get a proper texture preview, and editing the shader (e.g. using `ar` instead of `ra`) results in it properly updating... at least initially.  Now that I've messed around with it a bit, it seems it does break eventually (resulting in a completely yellow image), but RenderDoc doesn't crash, and I can switch back to GLSL.

------

If I use this HLSL shader:

```hlsl
SamplerState pointSampler : register(s0);
Texture2DArray<float4> texDisplayTex2DArray : register(t7);

float4 main(float4 pos : SV_Position, float4 uv : TEXCOORD0) : SV_Target0
{
    return float4(texDisplayTex2DArray.Sample(pointSampler, uv.xyz).ra, 0, 1);
}
```

with Vulkan then I don't experience any crash, but I get a solid color instead of the expected result.  Still, not crashing is much better.

------

That said, there is a reason why I had incorrect bindings set up in the HLSL shader: it's because I actually created that shader in a D3D capture (I don't recall whether it was D3D11 or D3D12), using the insert snippet menu for D3D, and then since it appeared in the list while I was using Vulkan, I assumed that it would work correctly.  (Since I wanted self-contained steps to reproduce, though, I didn't include a D3D capture in the steps.)  Using the insert snippet menu with HLSL on Vulkan does work, but if I had already loaded the broken one it would be too late to fix it (at least with NVIDIA drivers).

Would it be possible to store visualization shaders for each graphics API in different folders, so that shaders that use bindings for one API don't show up in another API?  That would make it much harder to accidentally use the wrong bindings (even when switching between OpenGL and Vulkan, since they have different bindings too as I found out above).

**Comment by baldurk** [comment] 2022-01-24 12:17
Note that as mentioned above, that shader is still illegal since there is no sampler binding at 0 on vulkan. I'm surprised the Intel driver copes so well, but that's how undefined behaviour goes - perhaps the way it compiles down mismatching bindings ends up being somewhat compatible enough to work in some cases.

I hadn't thought of the problem of switching between APIs and using cross-pollinated custom visualisation shaders. Unfortunately I can't think of a solution here that works robustly and also doesn't have significant backwards compatibility challenges. Any solution will have to continue to work for people's existing shaders including those in custom locations.

Given that, I think a better fix is to remove the documented bindings and instead require use of custom macros to declare textures. E.g. `Texture2DArray<float4> texDisplayTex2DArray : register(FLOAT_2D_ARRAY);` for HLSL or `layout(binding = FLOAT_2D_ARRAY) uniform sampler2DArray tex2DArray;` for GLSL. That way HLSL shaders can be written to work for  vulkan and D3D, and GLSL shaders can be written to work for vulkan and GL, both without needing any #ifdefs in the user code. This probably also means switching to cbuffers from 'loose' constants in GL/HLSL (though loose constants will have to continue to work for backwards compatibility).

With this bug though I suspect existing shaders will need to be treated as if they are already correct, I don't see any reasonable way around that. I don't think there's any way I can make the bindings match for mismatched shaders like this while still also working for correctly written shaders, without doing some dynamic reflection system which seems overkill, and any system of categorising or filtering shaders by API can't work for existing shaders that don't have any filtering information.

I presume most people end up using shaders written for one API with only that API since otherwise this issue would have been noticed and reported a lot sooner. The best I can do is help prevent this kind of error in future for newly written shaders.

**Comment by Pokechu22** [comment] 2022-01-24 20:14
Macros for declaring textures seems to be a good idea to me.

It might also make sense to create new shaders in a subfolder based on the current API, while allowing shaders that exist in the current location to be used by all APIs (but that might result in a more confusing UX, so maybe that's not worth doing).  Or similarly some kind of filtering tag could be added in the shaders as a comment (and shaders missing that comment could be treated as usable by all APIs); that at least would be easily discoverable when editing the shader.  Perhaps a tagging system could also be used to indicate the types of textures the shader supports (I haven't been bothering with `RENDERDOC_TextureType` because Dolphin almost exclusively uses 2D or 2D array textures, and it seems like it would add additional complexity for shaders I'm mainly creating for quick testing).

**Comment by baldurk** [comment] 2022-01-25 11:02
I don't see much value in adding that kind of thing except as a fix for this bug - and as I say I'd prefer to make custom shaders more easily portable since I can see it being desirable to have shaders which are usable on multiple APIs (certainly between D3D versions, perhaps less so between other APIs). I bind dummy textures on the APIs where unbound textures aren't defined to just read 0s, so any shader which doesn't handle the current texture type would just end up returning empty, but that's up to the user to handle as they wish.

**Closed as completed** 2022-01-31 19:28 UTC
Labels: Bug, Unresolved

**Comment by baldurk** [comment] 2022-01-31 19:29
That commit switches over the documentation and snippet helpers to use pre-defined macros for binding points. As above I can't do anything about existing shaders, they will continue to work, but now most shaders will 'by default' work on any API that supports that particular shading language.
