### ISSUE TITLE
offset 25 is out of the bounds [0, 24] of object ‘baseTypeName’ with type ‘rdcstr’ [-Werror=array-bounds]

### ISSUE THREAD

**Issue by kvark** [baldurk/renderdoc#2283] opened 2021-05-28 04:29 UTC
## Description

Just checking out the fresh version and building it.

## Steps to reproduce

1. git checkout
2. mkdir build && cd build
3. cmake ..
4. make

## Environment

* RenderDoc version: 2ddf567feced415b112c2b929c7216ac22866349
* Operating System: Linux
* Graphics API: N/A

>gcc (Solus) 10.2.0

```
compiling renderdoc_python.cxx
In file included from ../../renderdoc/api/replay/renderdoc_replay.h:56,
                 from renderdoc_python.cxx:4374:
In member function ‘void rdcstr::insert(size_t, const char*, size_t)’,
    inlined from ‘void rdcstr::append(const char*, size_t)’ at ../../renderdoc/api/replay/rdcstr.h:325:61,
    inlined from ‘rdcstr& rdcstr::operator+=(const char*)’ at ../../renderdoc/api/replay/rdcstr.h:602:11,
    inlined from ‘static swig_type_info* TypeConversion<T, isEnum>::GetTypeInfo() [with T = D3D11Pipe::ConstantBuffer; bool isEnum = false]’ at ../../qrenderdoc/Code/pyrenderdoc/pyconversion.h:43:18,
    inlined from ‘static int TypeConversion<T, isEnum>::ConvertFromPy(PyObject*, T&) [with T = D3D11Pipe::ConstantBuffer; bool isEnum = false]’ at ../../qrenderdoc/Code/pyrenderdoc/pyconversion.h:51:44,
    inlined from ‘static int TypeConversion<rdcarray<U>, false>::ConvertFromPy(PyObject*, rdcarray<U>&, int*) [with U = D3D11Pipe::ConstantBuffer]’ at ../../qrenderdoc/Code/pyrenderdoc/pyconversion.h:579:49:
../../renderdoc/api/replay/rdcstr.h:379:11: error: ‘void* memcpy(void*, const void*, size_t)’ offset 25 is out of the bounds [0, 24] of object ‘baseTypeName’ with type ‘rdcstr’ [-Werror=array-bounds]
  379 |     memcpy(str + offset, instr, length);
      |     ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from renderdoc_python.cxx:4378:
../../qrenderdoc/Code/pyrenderdoc/pyconversion.h: In static member function ‘static int TypeConversion<rdcarray<U>, false>::ConvertFromPy(PyObject*, rdcarray<U>&, int*) [with U = D3D11Pipe::ConstantBuffer]’:
../../qrenderdoc/Code/pyrenderdoc/pyconversion.h:42:12: note: ‘baseTypeName’ declared here
   42 |     rdcstr baseTypeName = TypeName<T>();
 ```

**Comment by baldurk** [comment] 2021-05-28 09:05
This is a duplicate of #2187, the warning is a false positive caused by a compiler bug. In that issue there were other messages that were more clearly compiler bugs with impossible offsets listed as being accessed.

As with that bug I can't reproduce the problem with the steps you've given on ubuntu's gcc 10.3.0 - perhaps the bug has been fixed since 10.2.0, although in #2187 the problem may have been caused by passing extra options to the compiler. It might be useful for you to double check that you're not passing any extra settings yourself somehow implicitly, or that your distro hasn't baked in some compile options by default (if that's possible).

**Closed as completed by baldurk** 2021-05-28 09:05 UTC
