### ISSUE TITLE
Feature Request: Plugin system for UI hooks/integration with python

### ISSUE THREAD

**Issue by devshgraphicsprogramming** [baldurk/renderdoc#991] opened 2018-05-20 20:57 UTC
## Description

A plugin system for meshbuffer/drawcall exporters (Vertex Array Object, Draw Descriptor, Draw Data).

Essentially I want to be be able to roll my own exporter as a plugin (script or dll) instead of saving bytes or to CSV.

For example my own model format maps 1:1 with OpenGL VAO spec, and can save atttributes with component counts, and formats nicely as opposed to lets say OBJ, FBX etc. (and can be loaded by my engine).

But this could also be useful for making generic exporters such as OBJ, FBX etc.

This could be useful for people to output draw command input triangles and examine them in their favourite applications or do some further experimentation/rapid prototyping.

## Environment

* RenderDoc build: e.g. v1.0, or 2018-03-12 nightly build.
* Operating System: e.g. Windows 10, Windows 7, Ubuntu Linux, etc
* API: e.g. Vulkan, D3D11, OpenGL, etc

**Comment by baldurk** [comment] 2018-05-21 15:43
I'm not sure having an explicit plugin system is worthwhile. Adding a new interface and plugin architecture would be a lot of work and add an additional maintenance burden if anything in that area changed and you needed to preserve backwards compatibility for the plugins.

I think this is the kind of thing that would be best to implement just in a python script using the existing python API. That has more generality and access to all possible data, and doesn't need another interface added purely for plugins. If there was enough demand then it might be worth adding something to auto-enumerate and execute 'built-in' python scripts on startup, and/or providing UI hooks on things like export menus.

**Comment by devshgraphicsprogramming** [comment] 2018-05-21 16:16
I'm fine with using a python API, but UI hooks for exports is what I'm looking for.
Even if I have to manually edit some .cfg file or put stuff in the right directory (blender style) for RenderDoc to "catch it" I'd be very happy.

Like let me present my usecase:

Triangle Visibility Buffer (Cache Friendly Deferred) / GeomteryFX

You do a lot of triangle index buffer filtering and then you indirect draw the results.

It would be nice to output some of these draws from a capture to some more blender/maya friendly format for examination.
The exact format outputted shouldn't ofcourse be your worry, it should be my worry to crunch the data (VAO, UBO, SSBO) and API state to produce something viewable.

**Comment by baldurk** [comment] 2018-10-23 18:25
I've added a *very early* system for registering persistent python extensions. The idea is that inside your qrenderdoc application data folder you'll have a new `extensions` folder. Within that you can create a python package per extension, with a json file to register it. The idea is you could `git clone` or unzip into this extensions folder as-is without needing anything else, everything is picked up from the filesystem.

So for example if you have a package `rdoc.example` then on windows you'd create `%APPDATA%/qrenderdoc/extensions/rdoc/example/extension.json` and `%APPDATA%/qrenderdoc/extensions/rdoc/example/__init__.py`. The json looks like this:

```json
{
	"extension_api": 1,
	"name": "Example RenderDoc Extension",
	"version": "1.0",
	"minimum_renderdoc": "1.1",
	"description": "An extension that contains various simple examples of how to use the extension API, for learning.\n\nFeatures include:\n* Menu items",
	"author": "Baldur Karlsson <baldurk@baldurk.org>",
	"url": "https://github.com/baldurk/rdoc-example"
}
```

And shows up in the new extension management window like this:

![image](https://user-images.githubusercontent.com/661798/47364018-22315480-d6d0-11e8-9ffa-abaf9949a117.png)

The extension isn't loaded by default, so from here you can load or reload an extension (similar to python modules it can't be unloaded once it's present, unless you restart the program). Once an extension is loaded you can tick `Always Load` and then next time you start renderdoc it will be automatically loaded. This means you don't automatically load any files that are there, you have to opt-in.

When the module is loaded, renderdoc expects a `register()` function that's called with the renderdoc version and the `pyrenderdoc` handle that you get in the interactive shell or when running scripts. From here you can do things like register a menu callback:

```py
import qrenderdoc as qrd

# Try to import PySide2, which won't necessarily be available
try:
	import PySide2.QtWidgets as QtWidgets
except:
	QtWidgets = None

def menu_callback(pyrenderdoc, data):
	if QtWidgets is not None:
		QtWidgets.QMessageBox.information(None, 'Extension Message!',
				'This is a message from the example extension, with data: {}'.format(data))

def register(version, pyrenderdoc):
	print("Registering #2 extension for renderdoc version {}".format(version))

	if QtWidgets is not None:
		print("QtWidgets available")
	else:
		print("No QtWidgets")

	pyrenderdoc.Extensions().RegisterWindowMenu(qrd.WindowMenu.Tools, ["RenderDoc Example", "Display Message"], menu_callback)
	pyrenderdoc.Extensions().RegisterPanelMenu(qrd.PanelMenu.EventBrowser, ["RenderDoc Example", "Display Message"], menu_callback)
	pyrenderdoc.Extensions().RegisterContextMenu(qrd.ContextMenu.EventBrowser_Event, ["Display Event"], menu_callback)

def unregister():
	print("Unregistrating extension")
```

Which gives you a global menu item:

![image](https://user-images.githubusercontent.com/661798/47381863-e52d8800-d6f8-11e8-8288-61e50dfee6ba.png)

A menu item local to a panel:

![image](https://user-images.githubusercontent.com/661798/47381882-efe81d00-d6f8-11e8-81a2-b6322d60d24b.png)

And a context-menu item:

![image](https://user-images.githubusercontent.com/661798/47381904-f9718500-d6f8-11e8-9542-c95cffd39728.png)

And depending on the context you may get extra data like which event was clicked on:

![image](https://user-images.githubusercontent.com/661798/47381923-02faed00-d6f9-11e8-8a03-85ac9ea29ba1.png)

-----

This is still beta quality so there's room for changing/improving it, but I'm interested in feedback on whether this will suit your needs.

One thing is I'm trying to figure out what UI hooks or access you might want that isn't exposed already. I don't want to add loads of optional extensibility everywhere without a strong reason as that adds maintenance burden. If needs be you can always access the Qt directly from python and add custom changes that way.

I also plan to add some helper utility functions for things like message boxes, file dialogs, etc. That avoids needing to access PySide directly as it's an optional dependency for builds.

**Comment by devshgraphicsprogramming** [comment] 2018-10-24 08:36
I think that extra button is great!

as long as I can fill the extension message (or dialog) window with whatever qt lets me, I think I can accomplish what I want :)

I take it that I can fish out different info about the capture through the python API anyway?

**Comment by baldurk** [comment] 2018-10-24 10:03
> as long as I can fill the extension message (or dialog) window with whatever qt lets me, I think I can accomplish what I want :)

I'm not sure what you mean by this. The message box code above is just using Qt directly:

```py
QtWidgets.QMessageBox.information(None, 'Extension Message!',
  'This is a message from the example extension, with data: {}'.format(data))
```

but I plan to expose a simple wrapper for things like messageboxes etc. If you're planning to export a lot of data then you can just use the normal file writing functionality in python.

And yes the only thing changing here is giving you persistent extensions that are loaded at startup, and easy UI hooks/changes. The same API that has been available since v1.0 is used for accessing capture data.

**Comment by devshgraphicsprogramming** [comment] 2018-10-24 10:28
Great!

It seems like I can trigger a python function which can crunch the capture data with a GUI button.

I consider my issue closed :)

**Comment by baldurk** [comment] 2018-10-24 10:58
Cool, thanks. I'm going to leave the issue open a little while longer since some other people expressed interest in a plugin system like this and they might want to give additional feedback.

**Comment by randallrvr** [comment] 2018-12-05 23:48
Following these instructions I get the following when trying to load the extension:

PythonContext.cpp( 628) - Error   - Error importing extension module. ModuleNotFoundError: No module named 'rdoc.example'

Not clear where I go from here, qrenderdoc _seems_ to be looking in the correct place for the module, and it shows up in the Extension Manager

**Comment by baldurk** [comment] 2018-12-05 23:56
Can you post the directory structure you have in your extensions folder? Maybe zip the whole extension folder itself?

**Comment by randallrvr** [comment] 2018-12-06 00:19
Sure, here it is, I trivially renamed the example extension, which will sometimes load the first time.
[extensions.zip](https://github.com/baldurk/renderdoc/files/2651134/extensions.zip)

**Comment by baldurk** [comment] 2018-12-06 00:29
Ah, I always treat the package name as lowercase. For me I get an error message `ModuleNotFoundError: No module named 'analyzeredundantdraws'` which doesn't match the case on disk. I'm not too familiar with python - I thought packages were _always_ lowercase so I applied that as a sanitisation step just in case of windows case-insensitive files. Are uppercase python package names legal? If so I can fix the code to preserve case.

Renaming the `analyzeRedundantDraws` folder to `analyzeredundantdraws` means it loads fine for me. I don't get the problem with `rdoc.example` as you pasted above, which should work fine as it's all lower case. You say it sometimes loads for you, can you give me any more information about when it fails to load?

**Comment by randallrvr** [comment] 2018-12-06 00:41
I'm not too familiar with python either, it never occurred to me the case of the module could be the cause of the error.  I was going to say that rdoc.example failed on reload, but I can't seem to reproduce that now.  Anyway, I will stick to lowercase.

**Comment by zao** [comment] 2018-12-06 10:25
@baldurk Uppercase letters appear in Python module names in the wild. Some results from grepping our software build system reveals for example pyOpenSSL and their `OpenSSL` module and pycrypto and their `Crypto` module.

https://pyopenssl.org/en/stable/
https://www.dlitz.net/software/pycrypto/api/current/

**Comment by baldurk** [comment] 2018-12-06 10:43
OK fair enough, I'll remove the lowercasing then.

I'm going to close this issue as the feature has now been implemented, any further requests for extension APIs/UI customisability or bugs should be opened as separate issues.

**Closed as completed by baldurk** 2018-12-06 10:43 UTC
Labels: Feature, Unresolved
