### ISSUE TITLE
Android 6 not supported, couldn't make JDWP connection

### ISSUE THREAD

**Issue by stolk** [baldurk/renderdoc#900] opened 2018-03-07 03:45 UTC
I am trying to use renderdoc on my Android device.

Per the documentation, I made sure that:
  1. I did not have Android Studio running
  2. The device shows up in adb. (I can do a logcat for it.)

```
bram@ubuntu64:~/Downloads/renderdoc_1.0/bin$ adb devices
List of devices attached
7YRBBDB6B3003105	device
```

When I set the remote context, an Android app is installed, and opens up, and I can select my app in the launch dialog.

However, as I launch, I get:

**Error   - Couldn't make JDWP connection**

**Error   - Failed to inject using JDWP**

```
bram@ubuntu64:~/Downloads/renderdoc_1.0/bin$ ./qrenderdoc 
Log     - QRenderDoc initialising.
Log     - COMMAND: /home/bram/android-sdk-linux/platform-tools/adb '-s 7YRBBDB6B3003105 forward tcp:39970 localabstract:renderdoc_39920'
Log     - COMMAND: /home/bram/android-sdk-linux/platform-tools/adb '-s 7YRBBDB6B3003105 forward tcp:38970 localabstract:renderdoc_38920'
Log     - COMMAND: /home/bram/android-sdk-linux/platform-tools/adb '-s 7YRBBDB6B3003105 shell getprop ro.product.manufacturer'
Log     - COMMAND: /home/bram/android-sdk-linux/platform-tools/adb '-s 7YRBBDB6B3003105 shell getprop ro.product.model'
Log     - COMMAND: /home/bram/android-sdk-linux/platform-tools/adb '-s 7YRBBDB6B3003105 shell setprop debug.vulkan.layers :'
Log     - COMMAND: /home/bram/android-sdk-linux/platform-tools/adb '-s 7YRBBDB6B3003105 shell setprop debug.vulkan.layers :'
Log     - COMMAND: /home/bram/android-sdk-linux/platform-tools/adb '-s 7YRBBDB6B3003105 forward tcp:39970 localabstract:renderdoc_39920'
Log     - COMMAND: /home/bram/android-sdk-linux/platform-tools/adb '-s 7YRBBDB6B3003105 forward tcp:38970 localabstract:renderdoc_38920'
Log     - COMMAND: /home/bram/android-sdk-linux/platform-tools/adb '-s 7YRBBDB6B3003105 shell pm list packages -3'
Log     - COMMAND: /home/bram/android-sdk-linux/platform-tools/adb '-s 7YRBBDB6B3003105 forward tcp:39970 localabstract:renderdoc_39920'
Log     - COMMAND: /home/bram/android-sdk-linux/platform-tools/adb '-s 7YRBBDB6B3003105 forward tcp:38970 localabstract:renderdoc_38920'
Log     - COMMAND: /home/bram/android-sdk-linux/platform-tools/adb '-s 7YRBBDB6B3003105 forward tcp:39970 localabstract:renderdoc_39920'
Log     - COMMAND: /home/bram/android-sdk-linux/platform-tools/adb '-s 7YRBBDB6B3003105 forward tcp:38970 localabstract:renderdoc_38920'
Log     - Checking that APK is debuggable
Log     - COMMAND: /home/bram/android-sdk-linux/platform-tools/adb '-s 7YRBBDB6B3003105 shell dumpsys package com.steenriver.biplane'
Log     - Checking for root access on 7YRBBDB6B3003105
Log     - COMMAND: /home/bram/android-sdk-linux/platform-tools/adb '-s 7YRBBDB6B3003105 root'
Log     - COMMAND: /home/bram/android-sdk-linux/platform-tools/adb '-s 7YRBBDB6B3003105 shell whoami'
Log     - COMMAND: /home/bram/android-sdk-linux/platform-tools/adb '-s 7YRBBDB6B3003105 shell test -e /system/xbin/su && echo found'
Log     - COMMAND: /home/bram/android-sdk-linux/platform-tools/adb '-s 7YRBBDB6B3003105 forward tcp:39970 localabstract:renderdoc_39920'
Log     - COMMAND: /home/bram/android-sdk-linux/platform-tools/adb '-s 7YRBBDB6B3003105 forward tcp:38970 localabstract:renderdoc_38920'
Log     - COMMAND: /home/bram/android-sdk-linux/platform-tools/adb '-s 7YRBBDB6B3003105 forward tcp:39970 localabstract:renderdoc_39920'
Log     - COMMAND: /home/bram/android-sdk-linux/platform-tools/adb '-s 7YRBBDB6B3003105 forward tcp:38970 localabstract:renderdoc_38920'
Log     - COMMAND: /home/bram/android-sdk-linux/platform-tools/adb '-s 7YRBBDB6B3003105 forward tcp:39970 localabstract:renderdoc_39920'
Log     - COMMAND: /home/bram/android-sdk-linux/platform-tools/adb '-s 7YRBBDB6B3003105 forward tcp:38970 localabstract:renderdoc_38920'
Log     - COMMAND: /home/bram/android-sdk-linux/platform-tools/adb '-s 7YRBBDB6B3003105 forward tcp:39970 localabstract:renderdoc_39920'
Log     - COMMAND: /home/bram/android-sdk-linux/platform-tools/adb '-s 7YRBBDB6B3003105 forward tcp:38970 localabstract:renderdoc_38920'
Log     - COMMAND: /home/bram/android-sdk-linux/platform-tools/adb '-s 7YRBBDB6B3003105 shell cmd package resolve-activity -c android.intent.category.LAUNCHER com.steenriver.biplane'
Error   - Didn't find default activity in adb output
Log     - COMMAND: /home/bram/android-sdk-linux/platform-tools/adb '-s 7YRBBDB6B3003105 forward --remove tcp:39021'
Log     - COMMAND: /home/bram/android-sdk-linux/platform-tools/adb '-s 7YRBBDB6B3003105 shell am force-stop com.steenriver.biplane'
Log     - COMMAND: /home/bram/android-sdk-linux/platform-tools/adb '-s 7YRBBDB6B3003105 shell setprop debug.vulkan.layers VK_LAYER_RENDERDOC_Capture'
Log     - COMMAND: /home/bram/android-sdk-linux/platform-tools/adb '-s 7YRBBDB6B3003105 shell mkdir -p /sdcard/Android/data/com.steenriver.biplane'
Log     - COMMAND: /home/bram/android-sdk-linux/platform-tools/adb '-s 7YRBBDB6B3003105 shell setprop debug.rdoc.RENDERDOC_CAPTUREOPTS ababaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaabalaf'
Log     - COMMAND: /home/bram/android-sdk-linux/platform-tools/adb '-s 7YRBBDB6B3003105 shell pm path com.steenriver.biplane'
Log     - COMMAND: /home/bram/android-sdk-linux/platform-tools/adb '-s 7YRBBDB6B3003105 shell ls /data/app/com.steenriver.biplane-1/base.apk
package:/data/app/com.steenriver.biplane-1/split_lib_dependencies_apk.apk
package:/data/app/com.steenriver.biplane-1/split_lib_slice_0_apk.apk
package:/data/app/com.steenriver.biplane-1/split_lib_slice_1_apk.apk
package:/data/app/com.steenriver.biplane-1/split_lib_slice_2_apk.apk
package:/data/app/com.steenriver.biplane-1/split_lib_slice_3_apk.apk
package:/data/app/com.steenriver.biplane-1/split_lib_slice_4_apk.apk
package:/data/app/com.steenriver.biplane-1/split_lib_slice_5_apk.apk
package:/data/app/com.steenriver.biplane-1/split_lib_slice_6_apk.apk
package:/data/app/com.steenriver.biplane-1/split_lib_slice_7_apk.apk
package:/data/app/com.steenriver.biplane-1/split_lib_slice_8_apk.apk
package:/data/app/com.steenriver.biplane-1/split_lib_slice_9/lib/*/libVkLayer_GLES_RenderDoc.so'
Log     - No library found in /data/app/com.steenriver.biplane-1/base.apk
package:/data/app/com.steenriver.biplane-1/split_lib_dependencies_apk.apk
package:/data/app/com.steenriver.biplane-1/split_lib_slice_0_apk.apk
package:/data/app/com.steenriver.biplane-1/split_lib_slice_1_apk.apk
package:/data/app/com.steenriver.biplane-1/split_lib_slice_2_apk.apk
package:/data/app/com.steenriver.biplane-1/split_lib_slice_3_apk.apk
package:/data/app/com.steenriver.biplane-1/split_lib_slice_4_apk.apk
package:/data/app/com.steenriver.biplane-1/split_lib_slice_5_apk.apk
package:/data/app/com.steenriver.biplane-1/split_lib_slice_6_apk.apk
package:/data/app/com.steenriver.biplane-1/split_lib_slice_7_apk.apk
package:/data/app/com.steenriver.biplane-1/split_lib_slice_8_apk.apk
package:/data/app/com.steenriver.biplane-1/split_lib_slice_9/lib/*/libVkLayer_GLES_RenderDoc.so for com.steenriver.biplane - assuming injection is required.
Log     - Setting up to launch the application as a debugger to inject.
Log     - COMMAND: /home/bram/android-sdk-linux/platform-tools/adb '-s 7YRBBDB6B3003105 shell am start -S -D com.steenriver.biplane/'
Log     - COMMAND: /home/bram/android-sdk-linux/platform-tools/adb '-s 7YRBBDB6B3003105 shell ps -A | grep com.steenriver.biplane'
Log     - COMMAND: /home/bram/android-sdk-linux/platform-tools/adb '-s 7YRBBDB6B3003105 shell ps -A | grep com.steenriver.biplane'
Log     - COMMAND: /home/bram/android-sdk-linux/platform-tools/adb '-s 7YRBBDB6B3003105 shell ps -A | grep com.steenriver.biplane'
Log     - COMMAND: /home/bram/android-sdk-linux/platform-tools/adb '-s 7YRBBDB6B3003105 shell ps -A | grep com.steenriver.biplane'
Log     - COMMAND: /home/bram/android-sdk-linux/platform-tools/adb '-s 7YRBBDB6B3003105 shell ps -A | grep com.steenriver.biplane'
Log     - COMMAND: /home/bram/android-sdk-linux/platform-tools/adb '-s 7YRBBDB6B3003105 forward tcp:39970 localabstract:renderdoc_39920'
Log     - COMMAND: /home/bram/android-sdk-linux/platform-tools/adb '-s 7YRBBDB6B3003105 forward tcp:38970 localabstract:renderdoc_38920'
Error   - Couldn't make JDWP connection
Error   - Failed to inject using JDWP
```

**Comment by baldurk** [comment] 2018-03-07 09:55
Going from that log then at least this seems strange:

> `Error   - Didn't find default activity in adb output`

Can you paste the output of `adb shell cmd package resolve-activity -c android.intent.category.LAUNCHER com.steenriver.biplane` as well?

Also to check, when this fails do you get your app launching on the android device with a message "waiting for debugger to connect"? I'm wondering if because of the above it's not launching properly, which then leads to a sort of false positive with the JDWP connection failure, rather than an actual JDWP failure.

**Comment by stolk** [comment] 2018-03-07 16:03
```
$ adb shell cmd package resolve-activity -c android.intent.category.LAUNCHER com.steenriver.biplane
/system/bin/sh: cmd: not found
```
Yes, I do have issues running the Android Studio debugger on this device. I see the "Waiting for debugger" message, and Android Studio then times out. Unfortunately, my other device that does run the debugger, is too old to run the renderdoc app.

**Comment by baldurk** [comment] 2018-03-07 16:09
Ah that is a bit difficult. This seems like it's maybe something deep within the bowels of android and I'm not sure I know what the problem is. If Android Studio times out connecting the debugger my guess is the same problem is applying to renderdoc, since it requires the same connection method.

@cnorthrop @michaelrgb do you have any ideas, about either the failed debug connection or `cmd` being missing?

**Comment by cnorthrop** [comment] 2018-03-07 16:53
It looks like that command was added in 2015:
https://android.googlesource.com/platform/frameworks/native/+/23eb1e20cf59e1238b65cc108f31dfbfd85b2337

I'm not sure what the earliest version of Android to have it would be, but I would guess Nougat (7.0) which was released in 2016.   I've not tested anything before Nougat since that's when Vulkan was first added to the platform.

What version of Android are you using?  You can find it with:
`adb shell getprop ro.build.version.release `

**Comment by stolk** [comment] 2018-03-07 16:56
Ah, Ok, so the device is too old, I think 7.0 or later is req'd.

```
$ adb shell getprop ro.build.version.release
6.0.1
```

I wonder: if I attach to a running app instead of launching one, would I circumvent this shortcoming?

**Comment by stolk** [comment] 2018-03-07 17:04
Oh, one more thing... I noticed that the renderdoc app is uninstalled and installed everytime I start ./qrenderdoc because it thinks it is too old, but then installs the same version.

I can make a separate bug report for that, if you want.

```
Log     - COMMAND: /home/bram/android-sdk-linux/platform-tools/adb '-s 7YRBBDB6B3003105 shell pm dump org.renderdoc.renderdoccmd.arm32'
Warning - RenderDoc server versionCode:versionName (10:5ef2d0bb5e86a37ba6c250987e9dc8c33c26435c) is incompatible with host (10:1.0)
Log     - COMMAND: /home/bram/android-sdk-linux/platform-tools/adb '-s 7YRBBDB6B3003105 shell getprop ro.product.cpu.abi'
Log     - COMMAND: /home/bram/android-sdk-linux/platform-tools/adb '-s 7YRBBDB6B3003105 uninstall org.renderdoc.renderdoccmd'
Log     - COMMAND: /home/bram/android-sdk-linux/platform-tools/adb '-s 7YRBBDB6B3003105 uninstall org.renderdoc.renderdoccmd.arm32'
Log     - COMMAND: /home/bram/android-sdk-linux/platform-tools/adb '-s 7YRBBDB6B3003105 shell pm list packages org.renderdoc.renderdoccmd.arm32'
Log     - COMMAND: /home/bram/android-sdk-linux/platform-tools/adb '-s 7YRBBDB6B3003105 uninstall org.renderdoc.renderdoccmd.arm64'
Warning - recv: ECONNRESET: A connection was forcibly closed by a peer.
Warning - Error reading from socket
Warning - Didn't get proper handshake
Log     - COMMAND: /home/bram/android-sdk-linux/platform-tools/adb '-s 7YRBBDB6B3003105 forward tcp:39970 localabstract:renderdoc_39920'
Log     - COMMAND: /home/bram/android-sdk-linux/platform-tools/adb '-s 7YRBBDB6B3003105 forward tcp:38970 localabstract:renderdoc_38920'
Log     - COMMAND: /home/bram/android-sdk-linux/platform-tools/adb '-s 7YRBBDB6B3003105 shell pm list packages org.renderdoc.renderdoccmd.arm64'
Log     - Uninstall of incompatible server succeeded
Log     - COMMAND: /home/bram/android-sdk-linux/platform-tools/adb '-s 7YRBBDB6B3003105 shell getprop ro.product.cpu.abi'
Log     - Checking for server APK in /home/bram/Downloads/renderdoc_1.0/bin/plugins/android/
Log     - Checking for server APK in /home/bram/Downloads/renderdoc_1.0/bin/../share/renderdoc/plugins/android/
Log     - APKs found: /home/bram/Downloads/renderdoc_1.0/bin/../share/renderdoc/plugins/android/
Log     - COMMAND: /home/bram/android-sdk-linux/platform-tools/adb '-s 7YRBBDB6B3003105 install -r -g "/home/bram/Downloads/renderdoc_1.0/bin/../share/renderdoc/plugins/android/org.renderdoc.renderdoccmd.arm32.apk"'
Log     - COMMAND: /home/bram/android-sdk-linux/platform-tools/adb '-s 7YRBBDB6B3003105 install -r -g "/home/bram/Downloads/renderdoc_1.0/bin/../share/renderdoc/plugins/android/org.renderdoc.renderdoccmd.arm64.apk"'
Warning - recv: ECONNRESET: A connection was forcibly closed by a peer.
Warning - Error reading from socket
Warning - Didn't get proper handshake
Log     - COMMAND: /home/bram/android-sdk-linux/platform-tools/adb '-s 7YRBBDB6B3003105 forward tcp:39970 localabstract:renderdoc_39920'
Log     - COMMAND: /home/bram/android-sdk-linux/platform-tools/adb '-s 7YRBBDB6B3003105 forward tcp:38970 localabstract:renderdoc_38920'
Log     - COMMAND: /home/bram/android-sdk-linux/platform-tools/adb '-s 7YRBBDB6B3003105 shell pm list packages org.renderdoc.renderdoccmd'
Log     - COMMAND: /home/bram/android-sdk-linux/platform-tools/adb '-s 7YRBBDB6B3003105 shell am force-stop org.renderdoc.renderdoccmd.arm32'
Log     - COMMAND: /home/bram/android-sdk-linux/platform-tools/adb '-s 7YRBBDB6B3003105 shell am force-stop org.renderdoc.renderdoccmd.arm64'
```

**Comment by baldurk** [comment] 2018-03-07 17:19
It makes sense to have 7.0 as a minimum for vulkan dev but maybe we could support GLES on older devices? I guess it depends on what the problem is, and how common it is for devs to be running older devices.

It's not possible to attach to a running program as RenderDoc requires its hooks to be present from startup to work properly. Since you're using GLES, you could try linking against the renderdoc library directly - if you extract the relevant library from the provided apks and link to it while building your binaries, then remove any uses of `-lEGL` or `-lGLESv2` or anything like that so that renderdoc's exported GL symbols are used. This is a very messy way of hooking so it might take some doing to get it right, but it avoids the need to set up a debug connection.

For the reinstalling issue, that seems like it's a problem with the 1.0 build unfortunately. It looks like `android:versionName` is set to the commit hash in unofficial builds, but just the version number in stable builds. Unfortunately my stable build scripts weren't set up to pass the cmake variable needed to toggle this behaviour. I'm not sure why the distinction is needed since the commit hash seems like it would work OK in stable builds - @cnorthrop wrote that code so he may be able to shine a light on it. Either way it can be fixed for the next stable release.

FWIW, as long as the renderdoc app is running on the device then the UI will just connect to it without checking for uninstall/reinstall, so that can be used as a workaround to avoid this behaviour.

**Comment by cnorthrop** [comment] 2018-03-08 16:30
Regarding versionName, that came in [PR 747](https://github.com/baldurk/renderdoc/pull/747).  I believe the intent was to allow stable builds to continue working even if the host rolls forward without updating the version code.  The code looks designed to match what the UI displays, the logic for which is in [`qrenderdoc/Windows/MainWindow.cpp#L996`](https://github.com/baldurk/renderdoc/blob/v1.x/qrenderdoc/Windows/MainWindow.cpp#L996).   I'd be curious if it worked if you pass the flag in your Android build.  We can probably just switch to git hash instead, if that's acceptable.

**Comment by baldurk** [comment] 2018-03-08 23:30
I'm not quite sure I understand what you mean when you say it would allow the host to roll forward without updating the version code. If the user ran a newer build whether it's 1.1 or a new nightly/local build, they'd still want to install the matching android build to get the latest code there too.

What I'm not following is why we'd need or want to distinguish between a 1.0 build and a build of 5ef2d0bb5e86a37ba6c250987e9dc8c33c26435c (the commit that's tagged with v1.0). And if we don't, then there's no need to special case anything, we just check versions based on git commit.

The build scripts generally aren't set up to customise the cmake build, instead they set up the codebase with the right environment and then build the same as any other build, although it's of course possible to change.

**Comment by baldurk** [comment] 2018-05-10 17:09
Support has been added for finding the default activity name from a metadata dump, which has been tested to work on Android 6.

Please check with the latest RenderDoc nightly build, and if any more issues arise on Android 6 then please file an issue!

**Closed as completed by baldurk** 2018-05-10 17:09 UTC
Labels: Bug, Unresolved
