### ISSUE TITLE
Vulkan. Intel iris Xe. I can debug pixel only in first pass.

### ISSUE THREAD

**Issue by AdamFull** [baldurk/renderdoc#2591] opened 2022-05-20 19:51 UTC
## Description

Hello. I'm developing an application in vulkan and had to switch from nvidia graphics to intel graphics. I noticed a strange issue when I used renderdoc with 1070ti I could debug a pixel in any renderpass. But on iris Xe, I can only debug a pixel in the first pass, all subsequent ones write only clearColor.

## Steps to reproduce

1. Open renderdoc.
2. Select your .exe file in tab "Launch Application", and set "Queue capture" to frame 1
3. Press "Launch"
4. Open frame
5. Select second pass (your app should be multipass), select "vkCmdDraw"
6. Select any output image and right click to pixel, after that press "History"

## Environment

* RenderDoc version: v1.19
* Operating System: Windows 10
* Graphics API: Vulkan 1.0
* CPU: Intel core i5-11320H
* GPU: Intel Iris Xe Graphics eligible
* Driver: 30.0.101.1960

**Comment by baldurk** [comment] 2022-05-23 09:11
Please provide actual steps that I can follow to reproduce your problem. If you don't include your executable then it is impossible for me to meaningfully follow your steps, listing how to launch a program in the steps to reproduce is not useful because what is important in those steps is the program itself, it makes it impossible for me to see the issue you are actually having.

**Comment by AdamFull** [comment] 2022-06-02 16:22
Hi, sorry it took so long. I'm just launching any vulkan application and i can debug only first render pass. For all another pixel history is unavaliable. Here is screenshot of first pass and second
![image](https://user-images.githubusercontent.com/25034970/171677559-0321b719-e03a-4021-99c9-bae2bb7f5375.png)
![image](https://user-images.githubusercontent.com/25034970/171677664-dead8f88-a04e-44de-bbd6-0619ea7d1290.png)

**Comment by baldurk** [comment] 2022-06-02 16:42
As I asked before please share your application, or indeed any suitable application where this problem reproduces. It is nonsense to say this reproduces for any application at all because your description already assumes the presence of multiple render passes, so any application with a single renderpass would not qualify if the bug only manifests on the second renderpass in a frame.

**Comment by AdamFull** [comment] 2022-06-02 16:56
Here is debug build and source code
https://drive.google.com/file/d/1jIBN7I0BkMsjRcNFFdQNF42yyI2R1cru/view?usp=sharing
https://github.com/AdamFull/VulkanEngine/tree/develop

**Comment by baldurk** [comment] 2022-06-06 13:58
I think I was able to reproduce the problem. I definitely see an issue with pixel history not working, but I was able to debug shaders OK. You used the terms interchangeably even though they are different features so hopefully that is the problem you were talking about.

This seems to be an Intel driver issue so I'm reporting it to them to investigate further.

**Comment by AdamFull** [comment] 2022-06-06 14:29
Thank you very much. I tried a frame debugging utility from intel, and there was the same problem. Should I close the problem?

**Comment by baldurk** [comment] 2022-06-06 14:34
You can close it if you want. Regardless I will continue to investigate with Intel, then either fix the bug in RenderDoc if it's a problem on my side, or try to implement a workaround if it's a driver bug.

**Comment by baldurk** [comment] 2022-06-16 14:54
I've identified a workaround with intel and applied it in that commit, so it should work correctly now.

**Closed as completed** 2022-06-16 14:54 UTC
Labels: Bug, Need More Info
