### ISSUE TITLE
Vulcan Oculus Quest 2 capture hangs at ~10-20% mark

### ISSUE THREAD

**Issue by AbdelNabut** [baldurk/renderdoc#2403] opened 2021-11-03 20:18 UTC
## Description

Pressing the capture button when using the Vulkan API freezes the game and hangs the progress bar at the 10-20% mark. Vulkan is stated as "Active" in RenderDoc initially, but ~5 seconds into the capture, it shifts to "Not Presenting." Launching the game from the RenderDoc Launch Menu also results in "OVRMetricsTool keeps stopping." popping up repeatedly if running OVRMetricsTool in the Oculus Quest. Force quitting it allows the game to load, but the above vulkan capture issue persists. I've tried this in the latest stable, nightly RenderDoc, and in the RenderDoc For Oculus 1.16 fork. Uninstalled and reinstalled numerous times. And enabled and disabled the following player settings in Unity: Optimize Buffer Discards (Vulkan), Phase Sync, Subsampled Layout (Quest 2/Vulkan), Late Latching (Vulkan). Disabling/enabling all of them and/or a combination does not seem to fix the issue.

## Steps to reproduce

![2021-11-03](https://user-images.githubusercontent.com/57773924/140185305-dd2cc130-1f8d-4b69-b12f-34936af99751.png)
![2021-11-03 (1)](https://user-images.githubusercontent.com/57773924/140185306-2046f0c7-369a-4b21-8c64-b97aa5e7d1f4.png)

1) Build my Unity game for Android with the following settings:

Texture Compression: ASTC
ETC2 fallback: 32bit
Export Project: disabled
Build App Bundle: disabled
Create Symbols.zip: disabled
Development Build: enabled
Autoconnect Profiler: enabled
Deep Profiling Support: disabled
Script Debugging: disabled
Scripts Only Build: disabled
Compression Method: LZ4

2) Open Renderdoc 1.16 (stable)/1.17 (nightly)
3) Switch replay context to Oculus Quest 2
4) Wait for quest 2 server to start
5) Once connected, launch recent Quest 2 game build
6) If running OVRMetricsTool, force quit 3-4 times until game resumes loading
7) Once game has loaded in, press capture button
8) Game freezes and capture progress halts at 10-20% mark.

## Environment

* RenderDoc version: 1.16/1.17
* Operating System: Windows 11
* Graphics API: Vulkan

GPU is Nvidia RTX 3090 with the latest Nvidia Driver. CPU is AMD Ryzen 7 5800X, Memory: 64gb 3200mhz ram.

**Comment by baldurk** [comment] 2021-11-03 20:25
Please share your program so that I can run it. If you don't, it is impossible for me to follow your steps to reproduce.

**Comment by AbdelNabut** [comment] 2021-11-03 21:06
Here it is! Looking forward to any potential findings :)

https://drive.google.com/file/d/1CR351VCcoKeoEP_LDkINhnbeGRegffC_/view?usp=sharing

**Comment by tuxerr** [comment] 2021-11-04 19:31
Hey Abdel!
Could you package the APK with MSAA set to 1x (off) and both see if that fixes, and also send us the updated no-MSAA APK? 
For what it's worth, subsampled isn't really supported properly on Renderdoc-Vulkan yet and should be off.

**Comment by AbdelNabut** [comment] 2021-11-05 20:10
Hey @tuxerr, I've been trying to get my build running so that I can test that for you, but it's not loading. I'll get you that build when I get it to load successfully.

**Comment by AbdelNabut** [comment] 2021-11-07 18:24
@tuxerr disabled MSAA, but oddly there is now this new issue with running the project through RenderDoc. It seems like some texture is transposed right in front of the camera. This issue doesn't appear when running the app through Unity's build and run or through the Oculus 'unknown apps' menu. Also, it still allows one screenshot, although possibly with incorrect information. It now freezes as I initially described upon the second screenshot.. bizarre. Here's a link to the latest build: https://drive.google.com/file/d/14aVrMVb6OByqxMKExi4iR0LgsjQ4_ozL/view?usp=sharing

**Comment by baldurk** [comment] 2021-11-08 10:13
I'm not currently able to run any programs on my quest 2 so I can't investigate this, hopefully either tuxerr can help or I can fix whatever is stopping me running programs.

**Comment by baldurk** [comment] 2021-11-12 14:13
OK I'm finally able to run programs again. The original repro seems to be hanging in the driver, but after it runs out of memory anyway (so even if it didn't hang it would likely either crash, or at best fail to capture/produce a broken capture). The new version does capture for me, however I notice that both are built as 32-bit programs. I know the memory available on mobile devices is limited so this won't make a ton of difference, but you still may have VA exhaustion or fragmentation issues so I'd suggest building as 64-bit.

The capture that I can make from the second one does crash on load - it seems like there's some missing code to remove the subsampled bit on replay which should be fixed in that commit, after which it does load and replay correctly for me:

![image](https://user-images.githubusercontent.com/661798/141480297-d9ad773f-547b-4790-89e0-b7b2d413e83e.png)

I don't see any texture issues, but maybe if it's subtle and I'm not sure what it's supposed to look like I'm missing it. Can you explain what you mean about a transposed texture near the camera? do you mean the ground texture is reversed or something?

I also don't understand at all what you mean about screenshots. Is there some screenshot functionality which isn't working when used with RenderDoc?

**Comment by AbdelNabut** [comment] 2021-11-12 15:55
Wish I could get Vulcan working with 64 bit, but building on it with the latest Oculus XR leads to the game build loading infinitely, but I guess that's an issue for another team to handle. But even the 32 bit was running semi-okay on it own. Does Renderdoc use a lot of the Quest's memory? 

Glad you resolved the capture crashing on load. Also my apologies, poor choice of words earlier. What I meant about the textures is that I get this strange issue where the textures are zoomed up very close to the eyes to the point where all I see is green or blue or white as I turn my head. Strange thing is that only happens when loading the game with RenderDoc. Running the build from the Oculus Quest menu worked fine.

Also by screenshot, I meant capture :'] Even with the textures plastered on my eyes, I could still capture a frame one, but the second time would result in RenderDoc hanging and my app crashing. But if RenderDoc is consuming a lot of memory on it's own and the same could be said for my project, I could be running out of memory on the second capture (but if the first works fine, and the second crashes, could that be indicative of a memory leak?)  

EDIT: Also I tried googling VA Exhaustion, since I haven't heard of the term, but I failed to find anything. Would you mind elaborating or throwing some documentation my way?

**Comment by neelbedekar** [comment] 2021-11-12 17:21
@AbdelNabut, do you mind doing a few things to figure out/fix the bug on the Unity end? Also, we should probably move this conversation to Unity or Oculus forums, not Renderdoc, now that it's no longer a Renderdoc issue.

Can you:
1) Disable post-processing in your Unity app, and then create a new 64-bit build? You look to be doing quite a bit of post-processing in there, not to mention that this will be extremely expensive since it doesn't use the Vulkan subpass system anyways, but that's a separate topic.
Ideally you won't get the crash if you disable post-processing entirely. I'd strongly recommend removing it entirely as it probably is eating away an absurd amount of your total per-frame GPU budget here.
2) If 1) fails, can you share an apk of your app after 1), i.e. still with no post-processing at all?

And in general, are you doing anything special with the SRP, like a lot of SRP code changes, or mostly just standard stuff? Are you trying to use the Vulkan/SRP subpass API, etc. or something like that?

To avoid cluttering this Renderdoc forum though, you might want to create a forum post either on the Unity or Oculus forums and we can have this conversation there.

**Comment by baldurk** [comment] 2021-11-12 19:02
The memory overhead is variable and depends on what the application is doing, but yes there is a certain amount of overhead so if the application is using all available memory it will fail. Yes I would definitely recommend checking your code to see why 64-bit builds are failing, and following the suggestions above.

By VA exhaustion I meant either through fragmentation or through high memory use you might have no more space in the process's virtual address (VA) space left to allocate, and so memory allocations may fail. On 32-bit even if more physical memory is available it may not be possible to map any more since you only have (at absolute most) 4GB of VA available, and in practice a fair bit less considering ranges that may be reserved.

I don't see any kind of obvious visual corruption. When I run from RenderDoc I get just a normal view of some heightmap terrain and two hand models for the controllers. I'm not sure why you'd be seeing anything broken but I can't reproduce that.

I do get a failed capture the second time, but it's also out of memory. That could be fragmentation on a 32-bit build, it's not necessarily a memory leak.

Since the only RenderDoc issue seems to be fixed, I'm closing this.

**Closed as completed by baldurk** 2021-11-12 19:02 UTC
Labels: Bug, Need More Info
