### ISSUE TITLE
Debug program behave differently from normal run

### ISSUE THREAD

**Issue by tim37021** [baldurk/renderdoc#323] opened 2016-08-11 12:58 UTC
I have a vulkan program here.
In normal run
vkGetPhysicalDeviceQueueFamilyProperties  queueFamiliesCount=2
with renderdoc
vkGetPhysicalDeviceQueueFamilyProperties  queueFamiliesCount=1

Plus if the program have the validator layers enabled and debug with renderdoc, it will popup many weird errors. (Normal run have no error with validator layers enabled)

**Comment by baldurk** [comment] 2016-08-11 14:29
Yes, this happens by design - currently since RenderDoc does not support multiple queues, it reports that only one queue family is present (it should be the most capable queue present on the real device). This is perfectly legal and programs must be able to handle this since some hardware might only report one queue family.

Last time I checked, the validation layer messages which appear when running with renderdoc are all false positives, but I can check again. If you have a repro case to share that would be very welcome, in case there are some real messages that only appear in certain usage. However for false positives there is nothing I can do my side. I have many messages muted in the validation layer reporting for renderdoc for this reason.

**Comment by srjek** [comment] 2016-08-15 00:49
@baldurk You mentioned renderdoc is hiding queue families because it doesn't support multiple queues, but I noticed that the one queue family it does return can hold up to 16 queues. (Which is also the number of queues supported by my nvidia card for that family) Is that intentional?

**Comment by tim37021** [comment] 2016-08-15 00:55
@srjek @baldurk So I can still run with multiple queue in same family?
Will renderdoc support multiple queue families in the future?

**Comment by baldurk** [comment] 2016-08-15 09:32
Ah thanks for pointing that out @srjek, this is just an oversight on my part - I will change the code so that it only reports one available queue for the single family it reports.

@tim37021 Yes multiple queues (and so queue families) will be supported in future, but it's just a matter of prioritisation. For the moment only a single queue and family can be used, I'll update the faked reporting to reflect that.

**Comment by baldurk** [comment] 2016-08-15 18:39
With those changes above, you should find that the queue family count is reported as 1 correctly.

I've also implemented the API debug muting functionality that's supported on other APIs - by default when RenderDoc's layer is active the validation layer messages won't get through to the application.

Since this should be sorted now and the original report is over expected behaviour, I'm closing this issue. But do let me know if you run into any related problems.

**Closed by baldurk** 2016-08-15 18:39 UTC
