### ISSUE TITLE
Pixel Shader Debugging Picks Random Slice in Output Volume

### ISSUE THREAD

**Issue by Aeva** [baldurk/renderdoc#1154] opened 2018-10-31 19:52 UTC
## Description

Attempting to debug a pixel in a 3D render target selects the correct UV but the render target array index seems to be random.

## Repro steps

I have a draw call that writes to a 32x32x32 3D texture.  The draw call instances a quad 32 times for the slices, and a geometry shader fills out the middle so that the pixel shader writes to each voxel in the output texture.  Nothing else writes to the texture in that frame.  You _might_ be able to repro this with the PostProcessCombineLUTs pass in Unreal.

When I open the render target in the texture viewer, select a pixel (say, 0,0 of slice 0) and press Debug, it will select the correct shader and x/y offset, but the render target array index seems to be random.  Hitting debug a second time will select a different index.  The index seems to be within the valid range, however, so it'll have a value of like 10 or 19 etc.

## Environment

* RenderDoc build: v1.1 (built from c7d5aa86)
* Operating System: Windows 10
* API: D3D11
* GPU: GTX 1080
* Driver Version: 24.21.13.9793

**Comment by baldurk** [comment] 2018-11-01 11:43
I *think* this might be the same issue as #763 but I'd need to get a repro and investigate to be sure. From what you're describing though it sounds like basically the pixel shader debugging is picking a random instance?

When you just click debug from the texture viewer, it picks one fragment that ran at that pixel. To be more precise you can use the pixel history and that will let you select a specific primitive, but in the general case it's not possible to disambiguate if an instanced draw overlaps because when gathering pixel shader inputs I can't tell which is which.

For this specific case I might be able to read SV_RenderTargetArrayIndex in the pixel shader to determine which slice is being rendered to, but I'd need to experiment...

**Comment by Aeva** [comment] 2018-11-02 19:46
When I select a primitive in the history, the context menu always says "Debug Pixel (31, 0) Primitive 1225 at Event 0", but starting debugging that way still always picks a random array index.  But it looks like you already know that.

I don't know enough about how RenderDoc works to say with any confidence if #763 is related or not, but it seems plausible.  Sounds sticky D:

I can try to get a capture that reproduces this in vanilla unreal later.

**Comment by baldurk** [comment] 2018-11-13 18:12
From offline discussion this is a duplicate of #763 so closing. I do have an idea of how to fix both in one fell swoop...

**Closed as completed by baldurk** 2018-11-13 18:12 UTC
Labels: Feature, Unresolved
