### ISSUE TITLE
Can't capture frame because of unknown configuration problems

### ISSUE THREAD

**Issue by 2080717101** [baldurk/renderdoc#1365] opened 2019-04-29 02:20 UTC
## Description
    Hello, I have tried using render doc on my pc, but I cant capture any frames. Renderdoc can popup, but it appears like "Target: localhost - unity[PID 10592];  Connection Status: Established; API: None". And "Captures collected" list is empty. 
     I have tried update my driver, and uninstalling unity and reinstalling angin and again, but nothing works.     I've search from the internet as well, but i notice nobody meets this.
    My friend used the save version of unity and render doc, and his programs works well.   I'm very confused, as render doc is a very useful software for me. 
    I 'm not sure it's a bug or not. Or do anyone have the same situation? Do you have any suggestions? Thank you very much.

## Environment
* RenderDoc build: v1.3(v1.2 cant work either)
* Operating System: Windows 7
* Unity:2017.4.9f1 personal(64bit)
* API: DX11

**Comment by baldurk** [comment] 2019-04-29 09:42
Hi there, please avoid writing text in ``` blocks as it is hard to read.

Can you explain the exact steps you follow and what actually happens vs what you expect to happen? You haven't given enough information to tell what the problem might be, and as you say someone else with the same version of Unity and RenderDoc has it working so either you are doing something differently or else there's something unique to your computer that is causing the problem.

**Comment by 2080717101** [comment] 2019-04-30 02:31
Thank you for your reply!!!!!

Firstly, after I installing unity 2017.4.9f1 personal(64bit)  and render doc (v1.3), I opened a project of Unity.
Then, I start Unity, right click over the Game title, and RenderDoc option is displayed in the menu. I select it. There is a icon appear next to the Maxmize On Play.
After that, I click that icon. It takes a while to start RenderDoc.

Actually, the window is look like this while my friend's computer works like that.
![d2b3176f421a46a6ce260d4ec8b1e51](https://user-images.githubusercontent.com/18326271/56937754-0d2af780-6b31-11e9-918a-2840d18fe18c.jpg)
![5d39bb7ccc53bfafbbec8d53a8af7da](https://user-images.githubusercontent.com/18326271/56937755-0d2af780-6b31-11e9-8e0d-a32991cb2dd6.jpg)
Our unity's and renderdoc's version are same. Our OS is same, win7. Our driver is not same, mine is GTX960-D3D11, his is GTX660.  We open the same project. Is there any other important configuration(maybe unique to my computer) I ignored?? I compare the settings of thase two driver, GTX660 has a Component named nvDevToolS.dll, but GTX960 don't has this. Is that matters?
I think the problem might be the render doc can be waken but can not auto identificate my API. I am very confused.

By the way, I have tried to launch application(from building the same project), the renderdoc works well, the window looks like this.
![bcf4647b9a063941a34ae28f587456c](https://user-images.githubusercontent.com/18326271/56938064-7f500c00-6b32-11e9-93a8-ed2ace180cba.jpg)

My log information is as follows:
![RenderDocLog](https://user-images.githubusercontent.com/18326271/56945032-2b581e00-6b58-11e9-8d36-eadcf8072edf.PNG)

Thank you again for your help.

**Comment by baldurk** [comment] 2019-04-30 08:25
What happens if you launch the Unity editor from RenderDoc using the "Launch Application" panel as normal. Instead of using the "Load RenderDoc" button within Unity?

I believe Unity broke the "Load RenderDoc" support for some versions, maybe for your Unity version as well - though I can't explain why it works for one person but not another.

**Comment by 2080717101** [comment] 2019-04-30 09:32
Thanks.
I just click the Launch Application panel and fill in the Executable Path, which is the path of my .exe. Then, click the bottom Launch. The unity configuration window comes up, I can choose Screen resolution, Graphics quality, Select monitor and some configurations like that,  as normal. And I click Play. 

Then I back to RenderDoc, click the bottom Capture Frame(s) Immediately. The RenderDoc works as normal. In the other word, there is a capture in Captures collected, I can double click it to see more informations. I think that means my Graphic driver works and its API is corrected.

I'm pretty sure about the Unity version that we are the same, but his works so well. I envy him so much. QAQ
Thank you for your reply.

**Comment by baldurk** [comment] 2019-04-30 09:37
I meant if you launch the Unity editor through RenderDoc - your steps made it sound like you were launching the editor on its own, and then using the integration to load RenderDoc. This was broken for a while so trying to avoid it might work in your case.

**Comment by 2080717101** [comment] 2019-04-30 11:45
Ok, I will try.Thanks!!!!!!!!!!!!!!!!!!

**Comment by 2080717101** [comment] 2019-05-05 01:31
Hello, I have tried to launch the Unity editor through RenderDoc.
Here is my log:
`RDOC 009060: [09:24:46]    win32_process.cpp( 519) - Log     - Running process D:\Unity\Editor\Unity.exe
RDOC 009060: [09:24:46]    win32_process.cpp( 604) - Log     - Injecting renderdoc into process 9568
RDOC 009060: [09:24:47]    win32_process.cpp( 390) - Error   - Couldn't find module 'renderdoc.dll' among 103 modules
RDOC 009060: [09:24:47]    win32_process.cpp( 940) - Error   - Can't locate renderdoc.dll in remote PID 9568`

**Comment by baldurk** [comment] 2019-05-06 10:52
Can you please post the full log not just a snippet, and give details on what happens? When you launch Unity does the process continue without RenderDoc injected, or does it exit/crash? Are you using the new Unity Hub launcher or a standalone install?

I installed Unity 2017.4.9 and I can launch and debug it fine here. Without being able to reproduce the problem I'll need more information about exactly what is going wrong.

**Comment by 2080717101** [comment] 2019-05-06 11:12
Sorry.
Firstly, I launch the Unity editor through RenderDoc, click lauch. Then, it appears a window said Renderdoc injection failed. 
![image](https://user-images.githubusercontent.com/18326271/57221395-ac6c5500-7031-11e9-8c9b-39ecafd7685e.png)
I opened the log file.
![image](https://user-images.githubusercontent.com/18326271/57221792-03265e80-7033-11e9-8c94-a42d4b450cff.png)
RenderDoc isn't exit or crash, and isn't work either. I used the standalone install, RenderDoc_1.4_64.msi.

**Comment by baldurk** [comment] 2019-05-06 11:19
You're running RenderDoc 1.4 as Administrator which can interfere with hooking. If you run it as a normal user does that change anything?

**Comment by 2080717101** [comment] 2019-05-06 12:41
Thank you for your apply.
But I‘m not sure about how to operate. When I open(double click) the RenderDoc icon, it is as Administrator already. 
So, I hold down the shift key and right click on the shortcut of RenderDoc. There is an option 'Run as different user' in the manu. I  entered the account and password, then click comfirm. The RenderDoc is running as Administrator, the same as before. I think that's because I only have one account. But for some reason, I can not create any other account on this computer.
Is my operation correct? Or is there any other methods for verification? 
Thanks for your patience.

**Comment by baldurk** [comment] 2019-05-06 15:11
I don't know what your computer's configuration is. Typically for a single user installation the user is in the administrators group but is not directly an adminstrator user - they need to elevate to administrator deliberately via 'run as administrator'. RenderDoc only detects administator access when running directly as an elevated user which is not normal.

Perhaps the problem is a permissions issue, I'd suggest first determining why your user account is not behaving correctly. This might explain why your colleague on the same version can have things working, if this configuration issue is not present on their computer.

**Comment by 2080717101** [comment] 2019-05-07 02:43
I agree with you, maybe that's because of configuration.  I will try more.
Thanks again!!!

**Comment by baldurk** [comment] 2019-06-03 11:54
Closing this issue due to lack of information and evidence that it's a RenderDoc bug.

**Closed as completed by baldurk** 2019-06-03 11:54 UTC
Labels: Bug, Need More Info
