### ISSUE TITLE
Renderdoc crashes when showing preview of a texture (i3, linux, xcb, vulkan)

### ISSUE THREAD

**Issue by Keenuts** [baldurk/renderdoc#2863] opened 2023-02-22 13:56 UTC
Hello!

## Description

Captured a trace for a Vulkan application. Wanted to debug the rendering pipeline. Everything was working fine until I tried to inspect an image in the pipeline inspector. When hovering the 2D image handle in the pipeline inspector, the application crashes.
![crash](https://user-images.githubusercontent.com/4282252/220638307-222c9e31-ac40-4cf9-8e3b-523363245a65.png)

Upon further inspection, the GetOutputWindowDimensions does a null-deref, because xcb_get_geometry_reply failed.

## Steps to reproduce

Can reproduce on any trace (vkcube by ex).
Trying to inspect the cube texture in the pipeline inspector triggers the crash. Seems related to X11/i3 more than the capture.
- run under I3+X11
- open the capture
- select vkCmdDraw call
- go to pipeline State
- hover over the texture

## Environment

* RenderDoc version: f05c4efde8bb82a275b2f81883298e33ef2edd86
* Operating System: debian,  linux, 5.19.11, X11+i3
* Graphics API: vulkan

Thanks!

**Comment by baldurk** [comment] 2023-02-22 14:32
I followed your reproduction steps but it works fine for me as-is. I do not want to try to paper over the problem without properly understanding what is going on.

![image](https://user-images.githubusercontent.com/661798/220652891-c8a4fe77-68d4-4460-a191-bf89a2cbc88a.png)

Does this happen on any other system? Does it happen with both local builds and the official builds from renderdoc.org? Can you provide any more information about what's going wrong or any other configuration settings that might be relevant? I've never used i3 before and I only used it the minimum amount to reproduce the problem.

**Comment by Keenuts** [comment] 2023-02-22 15:37
Hello!

Thanks for looking into it! I understand the reasoning. (btw, vignette is black on my system with this "fix", not showing the texture like on your screenshot).

- i3 version 4.21.1
- renderdoc, can reproduce at head (f05c4ef), or using the distro version (v1.24) (that's how I found the issue)

I just tried renderdoc's binary (v1.25 & v1.24) downloaded from the website, and I have no crash, which is interesting 🙃
ldd shows the your release binary requires a very different set of libraries than the built or debian's version. Not sure why.
Using LLDB on the release binary (breakpoint on xcb_get_geometry_reply just before hovering), I can see some behavior divergance:
 - debian's build directly calls the function, causing a crash.
 - release's binary shows some QT calls to this function before the renderdoc call.
 (don't have debug symbols on both, so limited info sorry).
 
 Is the release build using specific cmake toggles? (just running `cmake -Bbuild -GNinja -H.` on my end)

**Comment by baldurk** [comment] 2023-02-22 15:45
debian's RenderDoc packages are known to be broken and I do not consider them reliable, and I don't recommend that anyone uses them.

In the past on linux the biggest difference I've seen between local compiled versions and my builds is because the stable builds statically link Qt they have a predictable version with no interference, but local builds use the system Qt which may activate plugins or other custom changes. That might also explain why it works for me because my system doesn't have any such customisations so the local Qt build is pretty much the same as the statically linked Qt build.

I'd suggest investigating that and see if you can find any evidence of custom Qt. Especially if you're using debian's Qt packages they may also be broken, so it might be worth building Qt from source yourself and see if that makes a difference (or at least eliminate a possibility). It's also possible this is some kind of regression in Qt between the version I build against and the version you have, though that seems unlikely.

I build locally with roughly the same cmake line, though specifically with debug since that's what I usually do, and with make instead of ninja, but neither of those should make a difference.

I'm not sure what you mean about a vignette?

**Comment by Keenuts** [comment] 2023-02-23 07:58
> debian's RenderDoc packages are known to be broken and I do not consider them reliable, and I don't recommend that anyone uses them.

Ah.. good to know. I tried on my personal computer and I cannot reproduce either, building from HEAD (52e9404961277d1bb1ed03a376b722c2b91e3762), same setup (X11 + i3), but arch instead of debian.
Just updated all packages before building. So if that's an issue with QT, it's been solved (5.15 on my personal computer, 5.7 on debian).

> I'm not sure what you mean about a vignette?

Sorry, french leaking 😊: thumbnail!
![2023-02-23_08-32](https://user-images.githubusercontent.com/4282252/220844200-73973983-2c3c-40c6-b7da-8bcd31c9db52.png)


As for the null deref, shouldn't that be handled more gracefully still? The X11 error is not checked, and pointer blindly deref, even if the function returned an error. (XCB's current implementation seem to always sets the pointer to null on error path, the behavior is just not defined in the comment).
What about at least passing an `xcb_generic_error_t*` instead of NULL, and silently return if the error is set (while setting `w` and `h` to defined values).
(like the code does when the window cannot be found) ?

(The XCB samples don't look at the error either, so probably why it's like that in the first place).

**Comment by baldurk** [comment] 2023-02-24 14:33
It sounds like this is a debian bug then, or maybe a Qt bug if it's only present on the older version. I'm going to close this issue unless it can be reproduced on a known-working setup.

If there's a meaningful situation where a window can fail to query its dimensions then making a change might make sense, but I struggle to see why that would happen. If it fails something is so catastrophically wrong that it is likely hiding a bug elsewhere, e.g. a bad Drawable coming from Qt. If the thumbnail was not rendering for you then it's not OK to just ignore the error.

**Closed as completed by baldurk** 2023-02-24 14:33 UTC
Labels: Bug, Need More Info

**Comment by Maybe707** [comment] 2024-02-11 14:57
I have same issue on Linux with BSPWM. Im using gentoo on 6.6.13 kernel and nvidia rtx 4060 on 535.154.05. Renderdoc builded from source with qt5 flag.

**Comment by baldurk** [comment] 2024-02-12 10:45
Please do not comment on old issues that have been closed.

If you are encountering a bug or are requesting a feature please open [a new issue](https://github.com/baldurk/renderdoc/issues/new/choose). You can reference this issue if you wish, but opening a new issue prevents any confusion of accidentally linking two unrelated issues and means that each issue can be handled in a clean process.
