### ISSUE TITLE
Texture Viewer tab is not showing correct output when replayed on remote device

### ISSUE THREAD

**Issue by gittmi** [baldurk/renderdoc#1420] opened 2019-06-18 08:15 UTC
## Description
I downloaded v1.4 release tar ball for linux. I am able to capture the frame from connected ARM device. When I tried to replay in the same instance(i.e remote) I couldn't see the proper output on TextureViewer tab. When I build the renderdoc from source everything is working fine.
I observed the same issue in v1.2 release binary also. Am I missing anything here to install while running the release binaries?
Captured rdc file is here: [capture_file.tar.gz](https://github.com/baldurk/renderdoc/files/3300461/capture_file.tar.gz)

![TextureViewer](https://user-images.githubusercontent.com/11463393/59664265-56610480-91ce-11e9-84a9-46ee01d4cf7d.png)

## Environment

* RenderDoc build: v1.4 release tar ball, 
* Operating System:  Ubuntu Linux
* API:  OpenGL

**Comment by baldurk** [comment] 2019-06-18 10:17
If the panels stop rendering like that it's usually caused by some device lost type error on the local API. Can you please post the diagnostic log to see if that shows any errors?

You say it works fine when you build from source but I'm unclear which version of the code you're building from source. Are you building the latest code from the v1.x branch, v1.4, v1.2, or something else? If you're building from latest code then perhaps it's a bug that has been fixed since v1.4 was released, you could try the latest nightly build to test that.

Note that distributing binaries on linux is inherently fragile and not properly supported, so using your distribution's packages or a source build yourself is definitely preferred if you have that option. The binary builds are only there for users who don't want to build the source themselves and don't have a distribution package.

**Comment by gittmi** [comment] 2019-06-18 11:30
For building from source also I took v1.4 code. In that case the binary didn't give any such issue.
I am attching the log file of qrenderdoc on linux. 
[qrenderdoc.log](https://github.com/baldurk/renderdoc/files/3301255/qrenderdoc.log)

> Note that distributing binaries on linux is inherently fragile and not properly supported, so using your distribution's packages or a source build yourself is definitely preferred if you have that option. 


Build from source I understood. What do you mean by distribution's packages?

**Comment by baldurk** [comment] 2019-06-18 12:03
That's the stdout from running qrenderdoc, I meant the diagnostic log from help -> view diagnostic log which contains the full output. It doesn't seem like anything has gone wrong though, so my best guess is that there's some kind of incompatibility between the statically linked binary releases and your drivers. This is not really feasible to fix as I would have to be able to reproduce it and I've never seen this kind of error on any of my systems. If you're able to build from source then I recommend that you continue doing that.

Your linux distribution (which you mentioned as Ubuntu) might provide a RenderDoc package which you could use, either officially or unofficially. That saves you having to compile the source yourself and is a tailor-made binary release which will work reliably, unlike the binary releases I make which attempt to work on all distros and thus can have compatibility problems.

Since you're able to build from source and it works then, I'm closing this issue.

**Closed as completed by baldurk** 2019-06-18 12:03 UTC
Labels: Bug, Need More Info
