### ISSUE TITLE
Driver crash, clicking on the auto-fit range button.

### ISSUE THREAD

**Issue by Carandiru0** [baldurk/renderdoc#2240] opened 2021-04-08 22:26 UTC
## Description

When viewing a texture, with ranges outside the normal [0.0 ... 1.0] range. Clicking the "auto-range" button cause the AMD driver (latest) to auto-recover from crash. The state of Renderdoc is undefined, if I click on anything else - RenderDoc crashes with no "crash report" util popping up for RenderDoc. This does not happen in the previous major version of RenderDoc. If the crash reporter decides to show up, I'll definitely send the report over!

## Steps to reproduce

Capture, and view a texture with data outside the normalized range.
Press the auto-range button.

## Environment

* RenderDoc version: 1.13 and latest nightly 2021_04_07_c3ca732a_64
* Operating System: Win 10 (19042)
* Graphics API: Vulkan

Radeon 290, 21.3.1 driver
Vulkan 1.2

**Comment by baldurk** [comment] 2021-04-08 22:39
Please provide an actual reproducible test case, do not assume that the problem is so general that it can be reproduced on any application at all.

**Comment by Carandiru0** [comment] 2021-04-09 15:33
Sorry, I do not understand what you mean by general.
I was able to send a crash report however, and referenced this github issue
for it.
I did not mean anything by my words, the test case here on my machine is
100% reproducible. I have to manually input the maximum value for the
range as a workaround for now.

**Comment by baldurk** [comment] 2021-04-09 15:52
What I mean is your reproduction steps are very vague. They assume that _any_ texture with values outside of [0,1] from any capture of _any_ vulkan program will crash. I doubt that is true, rather I expect the problem is specific to some circumstances that happen in your case. Even if it were generally true that this crash happens in all cases then it does no harm at all to include a specific reproducible test case. That's why I was asking for you to share the test case you have which is reproducible instead of giving steps which make it potentially very hard to reproduce.

If you've included a capture in a crash report then I can look at it on Monday. Otherwise if you haven't I would still need a reproducible test case as often the minidump in the report is not enough to track down the problem.

If you have time in the meantime it would help to check nightly builds between v1.12 and v1.13 to narrow down where the problem started happening, if you say it didn't happen in v1.12. That is entirely up to you though and if you don't have the time to do that it's not a concern, I will investigate either way.

**Comment by baldurk** [comment] 2021-04-12 17:55
I can reproduce this with the submitted capture. It looks like a recent driver regression on AMD's part, it works fine for me on 21.2.3 but breaks on 21.3.1 (and 21.3.2). I can't test it on nvidia since the capture is not feasible to port to a different GPU, but I can also reproduce this with a test program using any 3D texture (2D seems to work fine, 3D is the only one broken - I haven't tried other types) and it works fine on nvidia there.

It works for me on latest and on v1.12. Perhaps you upgraded your graphics drivers and then mistakenly thought that the problem started with the latest RenderDoc version instead of the latest driver?

I'll report the issue to AMD, but I can't see any obvious cause or workaround from my side so I'm going to close this issue as there's (currently) nothing I can do. I'll comment here if I add a workaround given more information from AMD. In the meantime I'd suggest downgrading your driver to the last working version (21.2.3 for me) or avoiding the autofit and histogram features.

**Closed as completed by baldurk** 2021-04-12 17:55 UTC
Labels: Bug, Need More Info

**Comment by Carandiru0** [comment] 2021-04-14 06:33
Thank you Baldur for investigating and isolating this issue. RenderDoc is
such a valuable tool, great work I love RenderDoc!

**Comment by Carandiru0** [comment] 2021-07-06 00:24
Regarding #2240

Well as of now, driver 21.5.2 ( last driver supporting Radeon 290 EOL ) it
still crashes the driver when you try to autofit a volume texture.
Is there anything relatively simple that you can do to Renderdoc to fix the
issue? Viewing volume textures is a common need for my usage with captures.

I'm going to try downgrading to version 21.2.3 as you suggest. Unfortunate,
but needed.

Thanks

**Comment by baldurk** [comment] 2021-07-06 12:20
I've asked AMD about it but last I heard it was a shader compiler problem with no obvious workaround unfortunately. If I hear about one that is simple enough to implement I'll do so, I have a number of other driver bug workarounds, but it may not be possible.

The only thing I can suggest is to manually adjust the range instead of autofitting.
