### ISSUE TITLE
AttributeError: 'renderdoc.PipeState' object has no attribute 'GetConstantBuffer'

### ISSUE THREAD

**Issue by limtexpe** [baldurk/renderdoc#3322] opened 2024-05-18 13:36 UTC
## Description
Hello, I am trying to use the Python API to get the value of the constant buffer, but I received an error: **AttributeError: 'renderdoc.PipeState' object has no attribute 'GetConstantBuffer'**. Should something be modified [here](https://github.com/baldurk/renderdoc/blob/1ad23f64cad5ae8fbe40233b6550ef985ad58941/docs/python_api/examples/renderdoc/fetch_shader.py#L48)?
Thank you in advance!

## Steps to reproduce
```
import renderdoc as rd

def loadCapture(filename):
    # Open a capture file handle
    cap = rd.OpenCaptureFile()

    # Open a particular file - see also OpenBuffer to load from memory
    result = cap.OpenFile(filename, '', None)

    # Make sure the file opened successfully
    if result != rd.ResultCode.Succeeded:
        raise RuntimeError("Couldn't open file: " + str(result))

    # Make sure we can replay
    if not cap.LocalReplaySupport():
        raise RuntimeError("Capture cannot be replayed")

    # Initialise the replay
    result, controller = cap.OpenCapture(rd.ReplayOptions(), None)

    if result != rd.ResultCode.Succeeded:
        raise RuntimeError("Couldn't initialise replay: " + str(result))

    return cap, controller

cap, controller = loadCapture('C:/Users/Desktop/11.rdc')

targets = controller.GetDisassemblyTargets(True)
target = targets[0]

state = controller.GetPipelineState()
pipe = state.GetGraphicsPipelineObject()
entry = state.GetShaderEntryPoint(rd.ShaderStage.Pixel)

cb = state.GetConstantBuffer(rd.ShaderStage.Pixel, 0, 0)

controller.Shutdown()
cap.Shutdown()

rd.ShutdownReplay()
```

## Environment

* RenderDoc version: 1.32
* Operating System: Windows 10
* Graphics API: Direct3D 11

**Comment by baldurk** [comment] 2024-05-18 13:45
You've said that you are using RenderDoc v1.32. Are you absolutely sure that that is the case? This script runs correctly for me on v1.32.

**Comment by limtexpe** [comment] 2024-05-18 13:58
I downloaded the latest code and built it, so I think it should be the most recent version (v1.32)? Is there a python command to check the current version?

**Comment by baldurk** [comment] 2024-05-18 14:07
You should be more careful about reporting bugs because incorrect information can waste time, and there is a reason the version is prompted as part of the template to be sure that it is clear what you are talking about.

The latest code from github is _not_ v1.32 because there have been many changes since that version was released which are all on the current branch. This API has changed and the documentation is not yet up to date as it has not been released in a stable version. The version you are running can be seen both in the title bar of the UI program as well as repeated in the about dialog.

As I mentioned before it is not feasible to give programming assistance/explanation or debugging help when writing python scripts especially if there is nothing wrong with the python API. In future please do not open any issues unless they reproduce on a stable version and can be reproduced without using python.

**Closed as completed by baldurk** 2024-05-18 14:07 UTC
Labels: Bug, Need More Info
