### ISSUE TITLE
Failed to find the global layer 'VK_LAYER_RENDERDOC_Capture' from renderdoc apk when launching the test appliction on oppo device

### ISSUE THREAD

**Issue by linglingzhou** [baldurk/renderdoc#3183] opened 2023-12-21 08:00 UTC
## Description

I was trying to launch some vulkan android app with RenderDoc on oppo device(android 13).
The RenderDoc was installed successfully on android device. But when launch some applications, it crashed immediately. 

I found a similar issue from [github](https://github.com/baldurk/renderdoc/issues/2969).  I used two apk ([jake-kart-vk.apk](https://renderdoc.org/jake-kart-vk.apk), [jake-runner-gles3.apk](https://renderdoc.org/jake-runner-gles3.apk)from the link to test on my oppo device.
The failed log for vk apk.
12-21 10:38:49.153 17225 20465 I Unity   : MemoryManager: Using 'Dynamic Heap' Allocator.
12-21 10:38:49.174 17225 20465 I Unity   : SystemInfo CPU = ARM64 FP ASIMD AES, Cores = 8, Memory = 11383mb
12-21 10:38:49.174 17225 20465 I Unity   : SystemInfo ARM big.LITTLE configuration: 4 big (mask: 0xf0), 4 little (mask: 0xf)
12-21 10:38:49.174 17225 20465 I Unity   : ApplicationInfo com.DefaultCompany.TestKartGameVk version 0.1.0
12-21 10:38:49.175 17225 20465 I Unity   : Built from '2021.3/staging' branch, Version '2021.3.23f1 (213b516bf396)', Build type 'Release', Scripting Backend 'il2cpp', CPU 'arm64-v8a', Stripping 'Enabled'
12-21 10:38:49.300 17225 20465 I Unity   : Company Name: DefaultCompany
12-21 10:38:49.300 17225 20465 I Unity   : Product Name: TestKartGameVk
12-21 10:38:49.303 17225 20465 D vulkan  : searching for layers in '/data/user/0/com.DefaultCompany.TestKartGameVk'
12-21 10:38:49.303 17225 20465 D vulkan  : searching for layers in '/data/app/~~a8k2EFYaYPBQDUGrsdfZ7A==/com.DefaultCompany.TestKartGameVk-oEZoF7Lfs8JmfL6r5njwuw==/lib/arm64'
12-21 10:38:49.303 17225 20465 D vulkan  : searching for layers in '/data/app/~~a8k2EFYaYPBQDUGrsdfZ7A==/com.DefaultCompany.TestKartGameVk-oEZoF7Lfs8JmfL6r5njwuw==/base.apk!/lib/arm64-v8a'

I done some research for the issues. The problem of the issue seems the value of "targetSdkVersion" of application>=30.  '[FILTER_APPLICATION_QUERY](https://developer.android.com/about/versions/11/reference/compat-framework-changes?hl=zh-cn#filter_application_query )' will cause the issue. It is the new change for targetSdkVersion >= 30. When ‘targetSdkVersion’ >= 30, the ‘filter_application_query’ change are enabled automaticly. It will restrict the application from accessing package of other application directly.  For the older ‘targetSdkVersion’, the application can access other application directly. For the ‘targetSdkVersion’ >= 30 or ‘filter_application_query’enabled, the vulkan processing of application will only search the vulkan library from itself and the apps which packages are [visible automatically](https://developer.android.com/training/package-visibility/automatic). On my oppo device, the packages of ‘ org.renderdoc.renderdcocmd’ app is not visible to the application. So the library(libVkLayer_GLES_RenderDoc.so) of ‘ org.renderdoc.renderdcocmd’ apk can’t been found. The renderdoc launch application failed.

Why different results on different devices for the same application which 'targetSdkVersion' >=30? For example, one application can work on vivo device(Android 13). But it failed on oppo. The reason seems that the apps which are visible automatically are different for one test application on different devices. The android system automatically makes some apps visible so that your app can interact with them without needing to [done some changes](https://developer.android.com/training/package-visibility/declaring)( declare "queries" elements) for test application. On my vivo device, the 'org.renderdoc.renderdcocmd.arm64’ is the app which is visible automatically to all application. On oppo, the 'org.renderdoc.renderdcocmd.arm64’ isn't visible automatically to the test application.

I have done some test for the application([jake-kart-vk.apk](https://renderdoc.org/jake-kart-vk.apk)
1. Change the 'targetSdkVersion' from 33 to 28, no "queries" element, disable 'FILTER_APPLICATION_QUERY' of android settings
Result: pass
2. Declare the ["queries"](https://developer.android.com/training/package-visibility/declaring#package-name) element and keep 'targetSdkVersion' as 33
Result: pass
3. Change the 'targetSdkVersion' from 33 to 28, no "queries" element, enable 'FILTER_APPLICATION_QUERY' of android settings
Result: failed, the issue is 'Failed to find layer VK_LAYER_RENDERDOC_Capture'

## Steps to reproduce

1. Run the origin [jake-kart-vk.apk](https://renderdoc.org/jake-kart-vk.apk)
2. Change the application with above changes.

## Environment
* RenderDoc version: 1.28
* Operating System: Ubuntu22.04, oppo (Android 13), vivo( Android 13)
* Graphics API: XXX

**Comment by baldurk** [comment] 2023-12-21 09:29
Since you say yourself this only happens on oppo devices, this is most likely a problem caused by the device itself. Oppo devices in the past have caused _many_ problems with RenderDoc, as unfortunately on Android there is no guarantee that most functionality behaves normally and many vendors either customise or deliberately break functionality that RenderDoc relies on like vulkan layers.

You say you're running RenderDoc v1.18 which is extremely old and there is no reason to use an old version - I would suggest using the latest version. But otherwise this is most likely a device bug and the only way around it is to use a non-broken device like the vivo that you have.

Pete Harris at ARM is going to investigate further to try to confirm.

**Comment by linglingzhou** [comment] 2023-12-21 09:33
Sorry, my renderdoc is 1.28

**Comment by baldurk** [comment] 2023-12-21 09:39
That is more recent but still a couple of versions out of date so it's worth trying on the latest just in case, though as above this is most likely a device bug.

**Comment by baldurk** [comment] 2024-01-10 17:14
This was confirmed to be a device bug and not a RenderDoc issue. A workaround was added in a recent PR from ARM which is now merged which should avoid the problem at least on some devices. If you're still encountering problems with the next nightly build please open a new issue.

**Closed as completed by baldurk** 2024-01-10 17:14 UTC
Labels: Bug, Need More Info
