### ISSUE TITLE
Latest AMD driver breaks RenderDoc v1.1 for Vulkan & DX12

### ISSUE THREAD

**Issue by FelixK15** [baldurk/renderdoc#1143] opened 2018-10-25 15:44 UTC
## Description

I have trouble opening a capture that I took with my vulkan app.

After renderdoc starts to load a capture a message box appears saying
'Failed to open capture for replay: Replaying the capture failed at the API level'.

## Repro steps
I took a capture using the following steps:
   - Select executable in the 'Launch Application' tab
   - Hit the "Lauch" button in the same tab (Allow Fullscreen & Allow VSync are enabled)
   - After the executable has launched, I hit the 'Trigger after Delay' button (with a delay of 0 seconds)
   - I double click the capture to inspect it.

## Environment
I'm using the stable RenderDoc v1.1 on Windows 7 x64.
The Gpu that I use is a RX 480 with the 18.10.1 drivers.

I'm a little bit lost as to what to do now to fix this issue. 
Any hint as what to do would be much appreciated.

**Comment by FelixK15** [comment] 2018-10-25 15:45
[RenderDoc_2018.10.25_17.18.07.log](https://github.com/baldurk/renderdoc/files/2515729/RenderDoc_2018.10.25_17.18.07.log)

**Comment by baldurk** [comment] 2018-10-25 15:47
Unfortunately this is a breakage caused by changes in AMD's newest driver. The new driver causes Vulkan and DX12 captures to completely fail to open on v1.1.

The only solution is to downgrade your drivers to something older than 18.10, or try a nightly build. I can't guarantee the stability of nightly builds by their nature but you might be able to find one that works for you.

I'll leave this issue open to make it more publicly visible until v1.2 ships.

**Comment by FelixK15** [comment] 2018-10-25 15:48
Thank you for your quick response. Quicker than I was able to get coffee, that is remarkable ;)

**Comment by FelixK15** [comment] 2018-10-25 19:06
Quick update: I was able to resolve the issue by reverting the driver using the device manager (**Roll Back Driver** in the **Properties Window** of a given device in the device manager)

I also tried the latest nightly build (2018-10-24) which resulted in the same error as stated above.

**Comment by baldurk** [comment] 2018-10-25 19:17
To clarify, do you mean that the latest nightly build failed to load any vulkan captures with the latest driver? It should be fixed and working, so that's a problem.

**Comment by baldurk** [comment] 2018-12-04 10:12
Closing as this is resolved in v1.2. Note that in v1.2 the RGP interop is now opt-in, so if you want the feature you'll need to enable it manually.

**Closed as completed by baldurk** 2018-12-04 10:12 UTC
Labels: Bug
