### ISSUE TITLE
no stencil values are displayed

### ISSUE THREAD

**Issue by csdjk** [baldurk/renderdoc#2967] opened 2023-06-27 03:54 UTC
## Description

Right-click in the texture view window and no stencil values are displayed

## Steps to reproduce
normal operation
## Environment

* RenderDoc version: v1.27
* Operating System: window10
* Graphics API: dx

![image](https://github.com/baldurk/renderdoc/assets/33519787/377c66ec-a319-4500-a4db-e1a6cfba6dde)

**Comment by Zorro666** [comment] 2023-06-29 09:15
Hi there,

To help diagnose the problem further please could you describe in detail the reproduction steps and the expected result.

It is not clear from the screenshot (of a colour target) what the issue is.

Thank you

**Comment by csdjk** [comment] 2023-06-29 09:22
It's just a regular frame cut game.
capture frame frome Unity, then double-click the frame to find the target DrawIndexed

**Comment by Zorro666** [comment] 2023-06-30 10:17
Hi there,

Here is a RenderDoc capture from a Unity URP scene. The depth & stencil values are being shown when I select a Depth/Stencil texture to show in the Texture Viewer.

I think in the screen shot you posted - you had selected a colour target which would not have depth or stencil data in it. 

In the list of textures in your screen shot then I think the texture "2D Depth Target 12730" is one texture which would depth and stencil data in it.

![image](https://github.com/baldurk/renderdoc/assets/39392/a0563145-7df9-4f39-8da2-55c75c5bf33f)

Thanks

**Comment by csdjk** [comment] 2023-07-01 04:53
How to display Stencil values in decimal

**Comment by Zorro666** [comment] 2023-07-03 08:12
Hi,

I am closing the issue now as it is completed. It didn't quite follow the full template for an issue report and there does not appear to be an issue to diagnose.

It has also started to evolve into a different issue or questions which really should be new issues.

As for seeing the stencil value in decimal. Personally I  do the conversion in my head as I am used to working with 8-bit hexadecimal but there are programmer calculators online or on the desktop or phone which can be used.

**Closed as completed by Zorro666** 2023-07-03 08:12 UTC
