### ISSUE TITLE
renderdoc doesn't  properly replay its own traces on llvmpipe that  were captured with llvmpipe

### ISSUE THREAD

**Issue by gerddie** [baldurk/renderdoc#1586] opened 2019-11-09 09:12 UTC
## Description

When a trace is captured with llvmpipe as a driver an then replayed on this same driver the log issues error messages: 

```
Error   - GL_FRAGMENT_SHADER compile error: 0:41(12): warning: extension `GL_ARB_gpu_shader5' unsupported in fragment shader
0:946(14): error: no matching function for call to `uintBitsToFloat(uvec4)'; candidates are:
0:948(14): error: no matching function for call to `intBitsToFloat(ivec4)'; candidates are:
```
and the replay windows shows only a gray-white checker board pattern. 

## Steps to reproduce

Capture a trace by running qrenderdoc or renderdoc with mesa as OpenGL driver and by setting  

`export LIBLGL_ALWAYS_SOFTWARE=1 `

and then replay that very trace in the same environment. 

## Environment

* RenderDoc version: git-7a436e1463b1d037
* Operating System: Gentoo 
* API: OpenGL 

OpenGL vendor string: VMware, Inc.
OpenGL renderer string: llvmpipe (LLVM 8.0.1, 128 bits)
OpenGL core profile version string: 3.3 (Core Profile) Mesa 20.0.0-devel (git-084431ce45)
OpenGL core profile shading language version string: 3.30

**Comment by gerddie** [comment] 2019-11-09 09:17
According trace: 
[blender-spaceship-eevee-llvm.rdc.gz](https://github.com/baldurk/renderdoc/files/3827099/blender-spaceship-eevee-llvm.rdc.gz)

**Comment by gerddie** [comment] 2019-11-09 09:39
The key point is that `(u)intBitsToFloat` is GLSL 330, but renderdoc forces GLSL 150 + extensions.

**Comment by baldurk** [comment] 2019-11-09 10:28
RenderDoc does use GLSL version 150 for best compatibility, but it should be conditionally enabling the extensions as needed and otherwise having fallback paths.

In this case it does `#extension GL_ARB_gpu_shader5 : enable`. That tries to enable the extension, but if it's not supported issues a warning and carries on as normal. Hence the first line of the errors you listed above. The code then protects the call to `(u)intBitsToFloat` under a preprocessor check that the extension is enabled:

```cpp
#ifdef GL_ARB_gpu_shader5
    if(uintTex)
      color_out = uintBitsToFloat(ucol);
    else if(sintTex)
      color_out = intBitsToFloat(scol);
    else
      color_out = col;
#else
    // without being able to alias bits, we won't get accurate results.
    // a cast is better than nothing though
    if(uintTex)
      color_out = vec4(ucol);
    else if(sintTex)
      color_out = vec4(scol);
    else
      color_out = col;
#endif
```

So it seems like your driver is claiming not to support the extension (which is fine), but is then compiling the part of the code protected by the `#ifdef` anyway? That doesn't make sense to me.

I can look into this more next week but it might be worth you checking to see if this is a driver compiler bug.

**Comment by gerddie** [comment] 2019-11-09 13:13
This is not about the glsl shader you inject, it is about glsl code that comes from the trace captured  on OpenGL 3.3 where  these functions are legal, but ARB_gpu_shader5 is not a requirement.

**Comment by baldurk** [comment] 2019-11-09 14:13
I'm sorry but I don't understand what you're saying. What glsl shader are you talking about that is being 'injected'? (I don't know what that would be referring to). I thought the shader that was failing to compile was RenderDoc's internal texture display shader, which as I've mentioned above is compiled at version 150 and uses ARB_gpu_shader5 optionally.

The capture you shared doesn't use any int<->float bitcasting GLSL functions at all nor does it reference ARB_gpu_shader5 so I'm not sure what you mean about glsl code coming from the capture.

**Comment by gerddie** [comment] 2019-11-09 15:44
What I meant by "injecting" is the internal renderdoc shader, and sorry, I posted the wrong trace. 

The trace attached below contains a shader that specifies `#version 330` and uses 
`intBitsToFloat`. Since this is part of GLSL 330 hence the trace doesn't specify an extension to enable this, but with GLSL 150 this is needed and [ARB_shader_bit_encoding](https://www.khronos.org/registry/OpenGL/extensions/ARB/ARB_shader_bit_encoding.txt) provides these function and is supported on llvmpipe (unlike ARB_gpu_shader5). 

[blender-spaceship-eevee-llvm-3.xml.gz](https://github.com/baldurk/renderdoc/files/3827437/blender-spaceship-eevee-llvm-3.xml.gz)

**Comment by baldurk** [comment] 2019-11-09 16:24
That isn't a capture, it's only an XML dump, so I can't open it to reproduce the problem.

I'm also unclear on where exactly the problem is now. The error messages you posted in the original report indicates that there's an issue using `uintBitsToFloat` as well as `intBitsToFloat`, but the shaders contained in that XML dump don't use `uintBitsToFloat` at all. They also use `floatBitsToInt` which doesn't have any corresponding error message in your original post, and do not reference the `GL_ARB_gpu_shader5` extension at all. If these shaders were failing to compile for these reasons I'd expect different error messages.

As you point out all shaders in that dump declare themselves as `#version 330` which means they don't need to declare any extensions to access the bitcasting functions. Why does it matter what extensions would be needed for a GLSL 150 shader when none of these shaders are declared as `#version 150`? Even if the shaders did declare `#version 150` then that would be the fault of those shaders for not declaring what extensions are used and it's not something RenderDoc should be trying to fix.

Your explanation of the problem is still unclear and it seems inconsistent with the different information you provide. I think you're fixated on what you believe to be the solution, and while it might be that there is a bug there to be fixed I want to understand exactly what is going wrong first before deciding how it should be fixed.

From your original report it seemed to be that RenderDoc's internal texture display shader was failing to compile. That would match up with the line numbers, and the fact that the texture panels don't display properly and only show a checkerboard. You now seem to be saying that this only happens in captures that use these functions otherwise in the captured shaders. Does that mean if you capture a program that doesn't use these - such as the capture you initially uploaded - that everything works correctly and you don't get an error message?

**Comment by gerddie** [comment] 2019-11-11 09:20
Sorry again, I was under the impression the `renderdoccmd convert` would *convert* the file in a way that can be consumed by `renderdoccmd` again, but now I learned that this is not the case and filed #1590 to ask for clarification. I uploaded an XML because I assumed that it would be simpler to just look at the shaders etc. Now it turns out that the according  trace is actually too big to be uploaded here, so 

Now back to the bug: 

- As I wrote in my initial report, it is the *replay* that shows a black-gray checker board pattern, I didn't even look at the textures at this point, so as the title of the bug says: renderdoc is not able to replay traces on OpenGL 3.3 that it captured on OpenGL 3.3 (specifically llvmpipe). 

- When I replay such a trace  with the patch applied I still get the warning `Warning - ARB_gpu_shader5 not supported, pixel picking and saving of integer textures may be inaccurate.`, that's why I assumed that it is not related to these internal shaders because you correctly don't try to create them. But now, looking at the code in `GenerateGLSLShader` the bug is indeed related to some internal shader. 

- The capture I shared above shows the same error message and doesn't replay as expected, it gives only  a white-gray checker board pattern.  

Getting to the shader that is failing I can see now that it contains the line 
```
#extension GL_ARB_gpu_shader5 : enable
```
but preprocessing the shader with glslang already resolves all defines, and I don't know whether the actual driver is used to determine the supported extensions, or whether above line actually might set the define GL_ARB_gpu_shader5. The [GLSL 1.50 language standard](https://www.khronos.org/registry/OpenGL/specs/gl/GLSLangSpec.1.50.pdf) doesn't mention these defines. 

In any case, since [GL_ARB_shader_bit_encoding](https://www.khronos.org/registry/OpenGL/extensions/ARB/ARB_shader_bit_encoding.txt) provides the required bitcast functions at a lower GL version level it would be better to use this extension instead of  [GL_ARB_gpu_shader5](https://www.khronos.org/registry/OpenGL/extensions/ARB/ARB_gpu_shader5.txt) and any drivert that supports the latter should also support the former, so I'll adjust the MR accordingly to always use `ARB_shader_bit_encoding` instead of `ARB_gpu_shader5`.

**Comment by baldurk** [comment] 2019-11-11 09:52
OK I understand the problem now. The issue isn't that there isn't a extension check/fallback at all, the problem as you found is that the check which is there is mistakenly being gobbled up by the glslang preprocess pass that is used to handle the `#include`s, since it acts like it does support the extension. So by the time the source reaches the driver the path that does use `GL_ARB_gpu_shader5` is already baked in.

The solution is to use a parallel `#define BIT_PACKING` or something similar which I set explicitly at source generation time based on whether the actual driver supports `GL_ARB_gpu_shader5`, so that glslang's preprocess matches reality. There's already other cases where I do that, e.g. `TEXSAMPLE_MULTISAMPLE`.

**Comment by gerddie** [comment] 2019-11-11 10:47
In my update MR I simply only add ARB_gpu_shader5 to the shader when it is supported, and as an alternative I also check for and add ARB_shader_bit_encoding, and - as suggested by you - I've added a define HAS_BIT_CONVERSION. With that the trace replays.

**Closed as completed** 2019-11-11 14:50 UTC
Labels: Bug, Unresolved
