### ISSUE TITLE
Frame is black or in confusion on android(HUAWEI P20)

### ISSUE THREAD

**Issue by SambeauWang** [baldurk/renderdoc#1384] opened 2019-05-16 07:51 UTC
## Description
When I capture frame on android(login interface), the frame is block.
![image](https://user-images.githubusercontent.com/22713858/57833385-79258500-77ec-11e9-9eb3-c839fa2e4c52.png)

when I add `librenderdoccmd.so` and `libVkLayer_GLES_RenderDoc.so` to the game, I try to capture frame on game(game interface). The frame is in confusion.
![image](https://user-images.githubusercontent.com/22713858/57835972-5302e380-77f2-11e9-84ee-d583a354bb86.png)

And I try capture on Windows 10(the same game based on cocos). It run well.

And sometimes It will be crash.
![image](https://user-images.githubusercontent.com/22713858/57834938-00282c80-77f0-11e9-9300-c753cdfd6ad2.png)

## Repro steps
1. Open RenderLoc and link to phone
![image](https://user-images.githubusercontent.com/22713858/57833546-cefa2d00-77ec-11e9-8822-5e01816b7057.png)
2. launch the game
3. Capture Frame.

## Environment
Phone: HUAWEI P20
GPU: Mali
Andriod sdk: 28
RenderDoc build:  v1.5
Operating System: Windows 10
API: OpenGL

**Comment by baldurk** [comment] 2019-05-16 09:11
You should not manually add any RenderDoc libraries to the apk, Android is a very fragile platform and the built-in injection is the recommended and most reliable way to get it to hook.

I'll need more information to be able to try and reproduce the problem. I don't have a similar device but I do have one with a Mali GPU. Can you share your apk with me, or a frame capture, so that I can see what is going wrong?

**Comment by SambeauWang** [comment] 2019-05-16 11:23
@baldurk Thank for your help very much! The apk is company product(https://adl.netease.com/d/g/dhxy/c/gwpc?type=android), so i can't share the debug version. The fallow file is the log when i use to capture frame.
[test.log](https://github.com/baldurk/renderdoc/files/3186805/test.log)

**Comment by baldurk** [comment] 2019-05-16 11:45
The log shows a few problems. The biggest one being that there's a GLES 1.1 context being created:

```
Activating new GL context: ARM / Mali-G72 / OpenGL ES-CM 1.1 v1.r14p0-00cet0.7cff926dd83c7c8d932e683f71212050
```

GLES 1.x is not supported, so this could be the source of unexpected problems. The errors later about failing to emulate program introspection I believe are caused by this since GLES 3.2 provides the program introspection functions as core so I wouldn't expect emulation to be happening.

There are a lot of errors indicating bad handling of shader programs which may be an application problem, I'd need to investigate in more detail to see why that is. Similarly with the errors about mapping buffers I can't even guess what causes that.

Without being able to run the program to investigate further this is all I can surmise, but I'd say that the GLES 1.x context could definitely be breaking things. Try removing the use of that within your application and see if that helps.

**Comment by SambeauWang** [comment] 2019-05-17 02:12
@baldurk I try to check whether GLES 1.x is used，but our app only suport 2.0 and above. When I see the Mesh data, I find this problem.
This is the data and model.
![image](https://user-images.githubusercontent.com/22713858/57898136-53e75400-788a-11e9-8d8a-ef3500e97d9d.png)
![image](https://user-images.githubusercontent.com/22713858/57898175-8c872d80-788a-11e9-9199-6825a04497c3.png)
 the VS out data.
![image](https://user-images.githubusercontent.com/22713858/57898210-a32d8480-788a-11e9-93ce-ae893909bdaf.png)
But My Vertex Shader is used like this.
```
attribute vec3 a_position;
attribute vec3 a_normal;
attribute vec4 a_blendWeight;
attribute vec4 a_blendIndex;
attribute vec2 a_texCoord;

uniform vec4 u_matrixPalette[SKINNING_JOINT_COUNT * 3];

void getPosition(out vec4 position)
{
    float blendWeight = a_blendWeight[0];

    int matrixIndex = int (a_blendIndex[0]) * 3;
    vec4 matrixPalette1 = u_matrixPalette[matrixIndex] * blendWeight;
    vec4 matrixPalette2 = u_matrixPalette[matrixIndex + 1] * blendWeight;
    vec4 matrixPalette3 = u_matrixPalette[matrixIndex + 2] * blendWeight;
    
    blendWeight = a_blendWeight[1];
    if (blendWeight > 0.0)
    {
        matrixIndex = int(a_blendIndex[1]) * 3;
        matrixPalette1 += u_matrixPalette[matrixIndex] * blendWeight;
        matrixPalette2 += u_matrixPalette[matrixIndex + 1] * blendWeight;
        matrixPalette3 += u_matrixPalette[matrixIndex + 2] * blendWeight;
        
        blendWeight = a_blendWeight[2];
        if (blendWeight > 0.0)
        {
            matrixIndex = int(a_blendIndex[2]) * 3;
            matrixPalette1 += u_matrixPalette[matrixIndex] * blendWeight;
            matrixPalette2 += u_matrixPalette[matrixIndex + 1] * blendWeight;
            matrixPalette3 += u_matrixPalette[matrixIndex + 2] * blendWeight;
            
            blendWeight = a_blendWeight[3];
            if (blendWeight > 0.0)
            {
                matrixIndex = int(a_blendIndex[3]) * 3;
                matrixPalette1 += u_matrixPalette[matrixIndex] * blendWeight;
                matrixPalette2 += u_matrixPalette[matrixIndex + 1] * blendWeight;
                matrixPalette3 += u_matrixPalette[matrixIndex + 2] * blendWeight;
            }
        }
    }

    vec4 p = vec4(a_position, 1.0);
    position.x = dot(p, matrixPalette1);
    position.y = dot(p, matrixPalette2);
    position.z = dot(p, matrixPalette3);
    position.w = p.w;
}
```
Is The Vertex attribute not response to the vertex data? This is the gl actions(use the nsight in windows).
![image](https://user-images.githubusercontent.com/22713858/57898768-fef90d00-788c-11e9-91ef-cc27e6a36693.png)

**Comment by baldurk** [comment] 2019-05-17 07:09
Without seeing the capture I can only make the same educated guesses. You can look at the VAO state in the pipeline view to see if the buffers and offsets are bound as you expect, and check the buffer contents to verify the data in the mesh view. Similarly you can check the function calls binding to the VAO (if it's modified right before the draw like you've shown, you can see the calls in the API inspector).

Since the position data and blend index data seems to be sensible, my guess is that the uniform `u_matrixPalette` isn't set. This could be caused by the program not reflecting properly due to the GLES 1.x context, which results in no uniform location re-mapping table. Again though I can't be sure unless I see the application or frame capture.

**Comment by SambeauWang** [comment] 2019-05-26 14:07
@baldurk Thank for your help. I check my android projects, and i find the problem that opengl 1.1 cause. When The `AndroidCrashHandler` interface use `getGPUInfo` function, it  will try to create a old opengl context for phone device info.
But I find another problem that it capture one usefull frame after try it much times.  And the connection between PC and android phone will break up. This is RenderDoc_2019_05_14_3791dee7_64 version.
[7.log](https://github.com/baldurk/renderdoc/files/3220385/7.log)


When i try the lastest version and use vs to build x64 release version, I never capture frames. It always crash.
![image](https://user-images.githubusercontent.com/22713858/58382742-7f8fda00-8000-11e9-9ca9-797a48b9476c.png)
[3.log](https://github.com/baldurk/renderdoc/files/3220377/3.log)

**Comment by baldurk** [comment] 2019-05-27 10:02
I'm not really clear on what's going wrong here unfortunately, it seems like the captures being produced are corrupted and maybe truncated - this may have to do with the failures in glMapBufferRange but I can't tell why those calls are failing from the log. There are also still a lot of errors about invalid shader/program use on the application's side which could cause problems.

I know you can't share your apk, but are you able to share the captures that are failing to load? I could maybe tell you more precisely what's wrong, though it might not help find the problem. Otherwise there's not much I can do without more concrete information.

Building the windows version from VS won't change much as all of the relevant code is in the android built, which is hard to set up to build locally because android is a terrible platform. Are you able to reproduce the problem on any other applications which maybe I could run myself to see the issue?

**Comment by baldurk** [comment] 2019-06-25 09:33
I'm closing this since I can't reproduce it and I don't have any more information to go on. If you're able to share a repro case with me or help me get more information to investigate I can do so.

**Closed as completed by baldurk** 2019-06-25 09:33 UTC
Labels: Bug, Need More Info
