### ISSUE TITLE
RenderDoc doesn't recognize the API

### ISSUE THREAD

**Issue by tongchenGithub** [baldurk/renderdoc#1958] opened 2020-06-24 02:16 UTC
## Description
RenderDoc doesn't recognize the API, as it does on both of my computers
![Aaron Swartz](https://raw.githubusercontent.com/tongchenGithub/MarkDownPhotos/master/1.png)
The log is here：
https://github.com/tongchenGithub/MarkDownPhotos/blob/master/RD_log.log

## Steps to reproduce
1. Start the Unity
2. The GameView - & gt;LoadRenderDoc
3. Click the frame capture button to start RenderDoc
4. RenderDoc does not recognize the API

## Environment

* RenderDoc version: 1.8
* Operating System: Windows 10
* Graphics API: DX11

**Comment by baldurk** [comment] 2020-06-24 09:56
Does this reproduce if you launch Unity's editor through RenderDoc directly rather than using the Unity integration? You may have to disable or workaround the "unity hub" as it can interfere with directly launching a Unity editor process.

If it doesn't reproduce that way, this seems like it's most likely caused by a Unity bug in the RenderDoc integration, which must load RenderDoc before creating any graphics device. If it loads RenderDoc after creating a graphics device then no API will be identified. There have been a number of such bugs in the past so make sure you're running the latest Unity version to get any such fixes.

**Comment by barycz** [comment] 2020-07-22 12:00
Hello, I'm not sure if this is relevant, but after a Win10 reinstall I am getting the same issue. After launching our application in render doc, the UI says "API: None" but the application is already swapping frames and rendering as usual. We have never had the integration and were always using render doc in the "Launch Application" mode. The "Diagnostic Log" says it is adding a D3D11 device and frame capturer but our application is DX12 (and I am sure that it worked with my old installation). It also complains about some GUIDs:

![image](https://user-images.githubusercontent.com/2946607/88173518-ff283180-cc22-11ea-9908-1ddb438186d0.png)

Hope that this will help (also that you can help us with this issue :))
Tomas

**Comment by baldurk** [comment] 2020-07-22 12:09
Please do not hijack unrelated issues. Please create a new issue outlining your problem and providing a reproducible test case.

**Comment by barycz** [comment] 2020-07-22 12:11
Sorry, I was not sure if it is unrelated.

**Comment by baldurk** [comment] 2020-07-22 19:17
Closing due to lack of information/activity from original reporter.

**Closed as completed by baldurk** 2020-07-22 19:17 UTC
Labels: Bug, Need More Info
