### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Tanopress** [baldurk/renderdoc#2282] opened 2021-05-27 07:37 UTC
## Description

When I click on a button RenderDock do not respond.
I try different HDD and SSD and USB key and different version of RenderDock but all do not respond when I click on a button.

## Steps to reproduce

1 - Start RenderDock

2 - Click on a button

## Environment

* RenderDoc version: 1.13
* Operating System: Windows 10
* Graphics API: OpenGL
* GPU: RTX 2060

**Comment by baldurk** [comment] 2021-05-27 09:17
If what you describe is accurate and clicking any button at all crashes RenderDoc, I can only guess that this is a system issue and not a RenderDoc bug. There's no way I can reproduce this accurately as I do so accidentally any time I run the program, and I've not heard any similar issues reported from anyone.

I'd suggest that you investigate your own system and make sure you have drivers up to date, no anti-virus/graphics overlay/shell extensions or other system-wide software installed and enabled that might be breaking. If that doesn't work you could either try on a different system or else compile RenderDoc from source and see what the crash is and report an issue with a more specific problem.

I'm closing this issue because the reproduction steps provided suggest a system problem as I say above, and there's no way for more information to even clarify the problem as "any button press will crash RenderDoc" is technically enough information but not a bug I can realistically investigate without access to the system where this is happening.

**Closed as completed by baldurk** 2021-05-27 09:17 UTC
