### ISSUE TITLE
App crashes in the middle ,No information is available regarding crash

### ISSUE THREAD

**Issue by Salma175-ib** [baldurk/renderdoc#1458] opened 2019-07-15 14:17 UTC
RDOC 015364: [17:25:34]         streamio.cpp( 319) - Warning - Error reading from socket
RDOC 015364: [17:25:34]    remote_server.cpp(1931) - Warning - Didn't get proper handshake
QTRD 015364: [17:25:39]              unknown(   0) - Debug   - QWindowsNativeFileDialogBase::onSelectionChange () 0
RDOC 015364: [17:25:41]         streamio.cpp( 319) - Warning - Error reading from socket
RDOC 015364: [17:25:41]    remote_server.cpp(1931) - Warning - Didn't get proper handshake
RDOC 015364: [17:25:48]         streamio.cpp( 319) - Warning - Error reading from socket
RDOC 015364: [17:25:48]    remote_server.cpp(1931) - Warning - Didn't get proper handshake
RDOC 015364: [17:25:48]    android_tools.cpp( 308) - Log     - COMMAND: D:/Softwares/Android/Sdk/platform-tools/adb '-s 1PASH9BL8X9214 shell getprop ro.build.version.sdk'
RDOC 015364: [17:25:48]    android_tools.cpp( 308) - Log     - COMMAND: D:/Softwares/Android/Sdk/platform-tools/adb '-s 1PASH9BL8X9214 shell pm list packages org.renderdoc.renderdoccmd'
RDOC 015364: [17:25:49]    android_tools.cpp( 308) - Log     - COMMAND: D:/Softwares/Android/Sdk/platform-tools/adb '-s 1PASH9BL8X9214 shell getprop ro.product.cpu.abi'
RDOC 015364: [17:25:49]          android.cpp( 631) - Log     - Starting RenderDoc server, supported ABIs:
RDOC 015364: [17:25:49]          android.cpp( 633) - Log     -   - armeabi_v7a
RDOC 015364: [17:25:49]          android.cpp( 633) - Log     -   - arm64_v8a
RDOC 015364: [17:25:49]          android.cpp( 332) - Log     - Checking installed version of org.renderdoc.renderdoccmd.arm32 on 1PASH9BL8X9214
RDOC 015364: [17:25:49]    android_tools.cpp( 308) - Log     - COMMAND: D:/Softwares/Android/Sdk/platform-tools/adb '-s 1PASH9BL8X9214 shell pm dump org.renderdoc.renderdoccmd.arm32'
RDOC 015364: [17:25:49]         streamio.cpp( 319) - Warning - Error reading from socket
RDOC 015364: [17:25:49]    remote_server.cpp(1931) - Warning - Didn't get proper handshake
RDOC 015364: [17:25:50]          android.cpp( 372) - Log     - Installed server version (14:214d85228538e71cc63a0d7fa11dd75b1d56cc81) is compatible
RDOC 015364: [17:25:50]    android_tools.cpp( 308) - Log     - COMMAND: D:/Softwares/Android/Sdk/platform-tools/adb '-s 1PASH9BL8X9214 shell am force-stop org.renderdoc.renderdoccmd.arm32'
RDOC 015364: [17:25:50]    android_tools.cpp( 308) - Log     - COMMAND: D:/Softwares/Android/Sdk/platform-tools/adb '-s 1PASH9BL8X9214 shell am force-stop org.renderdoc.renderdoccmd.arm64'
RDOC 015364: [17:25:51]    android_tools.cpp( 308) - Log     - COMMAND: D:/Softwares/Android/Sdk/platform-tools/adb '-s 1PASH9BL8X9214 forward tcp:39970 localabstract:renderdoc_39920'
RDOC 015364: [17:25:51]    android_tools.cpp( 308) - Log     - COMMAND: D:/Softwares/Android/Sdk/platform-tools/adb '-s 1PASH9BL8X9214 forward tcp:38970 localabstract:renderdoc_38920'
RDOC 015364: [17:25:51]    android_tools.cpp( 308) - Log     - COMMAND: D:/Softwares/Android/Sdk/platform-tools/adb '-s 1PASH9BL8X9214 shell am start -n org.renderdoc.renderdoccmd.arm64/.Loader -e renderdoccmd remoteserver'
QTRD 015364: [17:25:55]              unknown(   0) - Debug   - QWindowsNativeFileDialogBase::onSelectionChange () 0
ADRD 018727: [22:56:01]    remote_server.cpp( 947) - Log     - Connection received from 127.0.0.1.
ADRD 018727: [22:56:01]    remote_server.cpp( 993) - Log     - Refusing inactive connection
ADRD 018727: [22:56:01]    remote_server.cpp( 147) - Log     - Closed inactive connection from 127.0.0.1.
QTRD 015364: [17:25:58]              unknown(   0) - Debug   - QWindowsNativeFileDialogBase::onSelectionChange (QUrl("file:///D:/RenderDoc/iBC_RenderCaptures")) 1
QTRD 015364: [17:25:58]              unknown(   0) - Debug   - QWindowsNativeFileDialogBase::onSelectionChange () 0
QTRD 015364: [17:26:01]              unknown(   0) - Debug   - QWindowsNativeFileDialogBase::onSelectionChange (QUrl("file:///D:/RenderDoc/iBC_RenderCaptures/Frame373.rdc")) 1
QTRD 015364: [17:26:08]              unknown(   0) - Debug   - QWindowsNativeFileDialogBase::onSelectionChange (QUrl("file:///D:/RenderDoc/iBC_RenderCaptures/Frame37.rdc")) 1
QTRD 015364: [17:26:10] PersistantConfig.cpp( 460) - Warning - Got empty path from  "D:/RenderDoc/iBC_RenderCaptures/Frame232.rdc"
ADRD 018727: [22:56:15]    remote_server.cpp( 364) - Log     - Taking ownership of '/storage/emulated/0/Android/data/com.x.i/files/RenderDoc/com.x.i_2019.07.15_17.14_frame232.rdc'.
ADRD 014480: [22:56:15]    posix_network.cpp( 178) - Warning - send: EPIPE: Broken pipe.
ADRD 014480: [22:56:15]         streamio.cpp( 474) - Warning - Error writing to socket
RDOC 015364: [17:27:12]    android_tools.cpp( 308) - Log     - COMMAND: D:/Softwares/Android/Sdk/platform-tools/adb '-s 1PASH9BL8X9214 shell cmd package resolve-activity -c android.intent.category.LAUNCHER com.x.i'
RDOC 015364: [17:27:12]    android_tools.cpp( 308) - Log     - COMMAND: D:/Softwares/Android/Sdk/platform-tools/adb '-s 1PASH9BL8X9214 shell pm dump com.x.i'
RDOC 015364: [17:27:13]    android_tools.cpp( 308) - Log     - COMMAND: D:/Softwares/Android/Sdk/platform-tools/adb '-s 1PASH9BL8X9214 forward --remove tcp:39022'
RDOC 015364: [17:27:14]    android_tools.cpp( 308) - Log     - COMMAND: D:/Softwares/Android/Sdk/platform-tools/adb '-s 1PASH9BL8X9214 shell am force-stop com.x.i'
RDOC 015364: [17:27:14]    android_tools.cpp( 308) - Log     - COMMAND: D:/Softwares/Android/Sdk/platform-tools/adb '-s 1PASH9BL8X9214 shell setprop debug.vulkan.layers VK_LAYER_RENDERDOC_Capture'
RDOC 015364: [17:27:14]    android_tools.cpp( 308) - Log     - COMMAND: D:/Softwares/Android/Sdk/platform-tools/adb '-s 1PASH9BL8X9214 shell setprop debug.vr.profiler 1'
RDOC 015364: [17:27:14]    android_tools.cpp( 308) - Log     - COMMAND: D:/Softwares/Android/Sdk/platform-tools/adb '-s 1PASH9BL8X9214 shell mkdir -p /sdcard/Android/data/com.x.i'
RDOC 015364: [17:27:14]    android_tools.cpp( 308) - Log     - COMMAND: D:/Softwares/Android/Sdk/platform-tools/adb '-s 1PASH9BL8X9214 shell setprop debug.rdoc.RENDERDOC_CAPOPTS abababababppppppaaaaaaaaabababababababab'
RDOC 015364: [17:27:14]    android_tools.cpp( 308) - Log     - COMMAND: D:/Softwares/Android/Sdk/platform-tools/adb '-s 1PASH9BL8X9214 shell pm path com.x.i'
RDOC 015364: [17:27:15]    android_tools.cpp( 308) - Log     - COMMAND: D:/Softwares/Android/Sdk/platform-tools/adb '-s 1PASH9BL8X9214 shell ls /data/app/com.x.i-1//lib/*/libVkLayer_GLES_RenderDoc.so'
RDOC 015364: [17:27:15]          android.cpp( 233) - Log     - No library found in /data/app/com.x.i-1//lib/*/libVkLayer_GLES_RenderDoc.so for com.x.i- assuming injection is required.
RDOC 015364: [17:27:15]          android.cpp( 243) - Log     - Launching package 'com.x.i' with activity 'com.unity3d.player.UnityPlayerActivity'
RDOC 015364: [17:27:15]          android.cpp( 247) - Log     - Setting up to launch the application as a debugger to inject.
RDOC 015364: [17:27:15]    android_tools.cpp( 308) - Log     - COMMAND: D:/Softwares/Android/Sdk/platform-tools/adb '-s 1PASH9BL8X9214 shell am start -S -D -n com.x.i/com.unity3d.player.UnityPlayerActivity '
RDOC 015364: [17:27:16]    android_tools.cpp( 308) - Log     - COMMAND: D:/Softwares/Android/Sdk/platform-tools/adb '-s 1PASH9BL8X9214 shell ps -A | grep com.x.i'
RDOC 015364: [17:27:16]    android_tools.cpp( 308) - Log     - COMMAND: D:/Softwares/Android/Sdk/platform-tools/adb '-s 1PASH9BL8X9214 shell ps | grep com.x.i'
RDOC 015364: [17:27:16]    android_tools.cpp( 308) - Log     - COMMAND: D:/Softwares/Android/Sdk/platform-tools/adb '-s 1PASH9BL8X9214 forward tcp:39970 localabstract:renderdoc_39920'
RDOC 015364: [17:27:16]    android_tools.cpp( 308) - Log     - COMMAND: D:/Softwares/Android/Sdk/platform-tools/adb '-s 1PASH9BL8X9214 forward tcp:38970 localabstract:renderdoc_38920'
RDOC 015364: [17:27:16]    android_tools.cpp( 308) - Log     - COMMAND: D:/Softwares/Android/Sdk/platform-tools/adb '-s 1PASH9BL8X9214 forward tcp:39022 jdwp:19347'
RDOC 015364: [17:27:17]    android_tools.cpp( 308) - Log     - COMMAND: D:/Softwares/Android/Sdk/platform-tools/adb '-s 1PASH9BL8X9214 shell pm path org.renderdoc.renderdoccmd.arm32'
RDOC 015364: [17:27:17]             jdwp.cpp( 160) - Log     - Injecting RenderDoc from library in /data/app/org.renderdoc.renderdoccmd.arm32-1/lib/arm
RDOC 015364: [17:27:17]             jdwp.cpp( 209) - Log     - Got android.app.ApplicationLoaders.getClassLoader signature (Ljava/lang/String;IZLjava/lang/String;Ljava/lang/String;Ljava/lang/ClassLoader;)Ljava/lang/ClassLoader;
ADRD 019347: [22:57:25]    posix_network.cpp( 400) - Log     - Created and bind socket: 37
ADRD 019347: [22:57:25]             core.cpp( 308) - Log     - Listening for target control on 38920
ADRD 019347: [22:57:25]             core.cpp( 351) - Log     - RenderDoc v1.4 Android 32-bit Release (214d85228538e71cc63a0d7fa11dd75b1d56cc81) capturing application
ADRD 019347: [22:57:25]   posix_libentry.cpp(  56) - Log     - Using delay for debugger 0
ADRD 019347: [22:57:25]   posix_libentry.cpp(  69) - Log     - Loading into com.x.i
ADRD 019347: [22:57:25]         gl_hooks.cpp( 223) - Log     - Registering OpenGL hooks
ADRD 019347: [22:57:25]        egl_hooks.cpp( 751) - Log     - Registering EGL hooks
ADRD 019347: [22:57:25]         vk_layer.cpp(  53) - Log     - Registering Vulkan hooks
ADRD 019347: [22:57:25]     android_hook.cpp( 563) - Log     - Applying hooks with interceptor-lib
RDOC 015364: [17:27:21]   target_control.cpp( 566) - Log     - Got remote handshake: com.x.i[19347]
RDOC 015364: [17:27:21]   target_control.cpp( 566) - Log     - Got remote handshake: com.x.i[19347]
ADRD 019347: [22:57:25]     android_hook.cpp( 544) - Warning - Couldn't find __loader_dlopen, falling back to slow path for dlopen hooking
ADRD 019347: [22:57:25]     android_hook.cpp( 785) - Log     - Refreshing android hooks...
ADRD 019347: [22:57:25]     android_hook.cpp( 287) - Warning - Missing required section to hook [vdso]
ADRD 019347: [22:57:25]     android_hook.cpp( 287) - Warning - Missing required section to hook /system/framework/arm/boot.oat
ADRD 019347: [22:57:25]     android_hook.cpp( 287) - Warning - Missing required section to hook /system/framework/arm/boot-core-libart.oat
ADRD 019347: [22:57:25]     android_hook.cpp( 287) - Warning - Missing required section to hook /system/framework/arm/boot-conscrypt.oat
ADRD 019347: [22:57:25]     android_hook.cpp( 287) - Warning - Missing required section to hook /system/framework/arm/boot-okhttp.oat
ADRD 019347: [22:57:25]     android_hook.cpp( 787) - Log     - Refreshed
ADRD 019347: [22:57:25]     android_hook.cpp( 746) - Log     - Fetching 2 original function pointers over 0 libraries
ADRD 019347: [22:57:25]     android_hook.cpp( 762) - Log     - Finished
ADRD 019347: [22:57:25]     android_hook.cpp( 780) - Log     - Called library callbacks - hook registration complete
RDOC 015364: [17:27:27]   target_control.cpp( 802) - Log     - Used API: OpenGLES (Not presenting & supported)
ADRD 019347: [22:57:32]     android_hook.cpp( 785) - Log     - Refreshing android hooks...
ADRD 019347: [22:57:32]     android_hook.cpp( 787) - Log     - Refreshed
ADRD 019347: [22:57:32]        gl_driver.cpp( 963) - Log     - Core context BBDA0340 created with attribs, sharing with context 00000000
ADRD 019347: [22:57:32]     android_hook.cpp( 785) - Log     - Refreshing android hooks...
ADRD 019347: [22:57:32]     android_hook.cpp( 787) - Log     - Refreshed
ADRD 019347: [22:57:32]        gl_driver.cpp( 963) - Log     - Core context BBDA0240 created with attribs, sharing with context 00000000
ADRD 019347: [22:57:32]        gl_common.cpp( 420) - Log     - Checking enabled extensions, running as OpenGL ES 3.2
ADRD 019347: [22:57:32]      gl_emulated.cpp(3002) - Log     - Emulating ARB_clear_buffer_object
ADRD 019347: [22:57:32]      gl_emulated.cpp(3017) - Log     - Emulating ARB_internalformat_query2
ADRD 019347: [22:57:32]      gl_emulated.cpp(3179) - Log     - Emulating EXT_direct_state_access
ADRD 019347: [22:57:32]      gl_emulated.cpp(3266) - Log     - Emulating ARB_direct_state_access
ADRD 019347: [22:57:32]        gl_driver.cpp(1189) - Log     - Activating new GL context: Qualcomm / Adreno (TM) 540 / OpenGL ES 3.2 V@375.0 (GIT@b1f8328, I8a36212832) (Date:03/05/19)
ADRD 019347: [22:57:32]        gl_common.cpp( 463) - Log     - Vendor checks for 32 (Qualcomm / Adreno (TM) 540 / OpenGL ES 3.2 V@375.0 (GIT@b1f8328, I8a36212832) (Date:03/05/19))
ADRD 019347: [22:57:32]        gl_common.cpp( 752) - Warning - Reading from the depth buffer using glReadPixels is not supported (GL_NV_read_depth)
ADRD 019347: [22:57:32]        gl_common.cpp( 756) - Warning - Reading from the stencil buffer using glReadPixels is not supported (GL_NV_read_stencil)
ADRD 019347: [22:57:32]        gl_common.cpp( 760) - Warning - Reading from the packed depth-stencil buffers using glReadPixels is not supported (GL_NV_read_depth_stencil)
ADRD 019347: [22:57:32]     android_hook.cpp( 287) - Warning - Missing required section to hook /system/priv-app/VrDriver/oat/arm/VrDriver.odex
ADRD 019347: [22:57:32]     android_hook.cpp( 333) - Warning - Couldn't open '/system/priv-app/VrDriver/VrDriver.apk!/lib/armeabi-v7a/libvrapiimpl.so' to look for relro!
ADRD 019347: [22:57:32]     android_hook.cpp( 333) - Warning - Couldn't open '/system/priv-app/VrDriver/VrDriver.apk!/lib/armeabi-v7a/libutilpoller.so' to look for relro!
ADRD 019347: [22:57:33]     android_hook.cpp( 333) - Warning - Couldn't open '/system/priv-app/VrDriver/VrDriver.apk!/lib/armeabi-v7a/libpowerlevelswitcher.so' to look for relro!
ADRD 019347: [22:57:33]     android_hook.cpp( 333) - Warning - Couldn't open '/system/priv-app/VrDriver/VrDriver.apk!/lib/armeabi-v7a/libvrintegration.so' to look for relro!
ADRD 019347: [22:57:33]     android_hook.cpp( 785) - Log     - Refreshing android hooks...
ADRD 019347: [22:57:33]     android_hook.cpp( 787) - Log     - Refreshed
ADRD 019347: [22:57:33]        gl_driver.cpp( 963) - Log     - Core context BFA732C0 created with attribs, sharing with context 00000000
ADRD 019347: [22:57:33]        gl_common.cpp( 420) - Log     - Checking enabled extensions, running as OpenGL ES 3.2
ADRD 019347: [22:57:33]      gl_emulated.cpp(3002) - Log     - Emulating ARB_clear_buffer_object
ADRD 019347: [22:57:33]      gl_emulated.cpp(3017) - Log     - Emulating ARB_internalformat_query2
ADRD 019347: [22:57:33]      gl_emulated.cpp(3179) - Log     - Emulating EXT_direct_state_access
ADRD 019347: [22:57:33]      gl_emulated.cpp(3266) - Log     - Emulating ARB_direct_state_access
ADRD 019347: [22:57:33]        gl_driver.cpp(1189) - Log     - Activating new GL context: Qualcomm / Adreno (TM) 540 / OpenGL ES 3.2 V@375.0 (GIT@b1f8328, I8a36212832) (Date:03/05/19)
ADRD 019347: [22:57:33]         gl_hooks.cpp( 150) - Error   - Function glGenPerfMonitorsAMD not supported - capture may be broken
ADRD 019347: [22:57:33]         gl_hooks.cpp( 150) - Error   - Function glSelectPerfMonitorCountersAMD not supported - capture may be broken
ADRD 019347: [22:57:33]         gl_hooks.cpp( 150) - Error   - Function glBeginPerfMonitorAMD not supported - capture may be broken
RDOC 015364: [17:27:29]   target_control.cpp( 802) - Log     - Used API: OpenGLES (Presenting & supported)
ADRD 019347: [22:57:33]        gl_driver.cpp(2593) - Log     - Got a Debug message from GL_DEBUG_SOURCE_API, type GL_DEBUG_TYPE_ERROR, ID 2147483647, severity GL_DEBUG_SEVERITY_HIGH:
ADRD 019347: [22:57:33]        gl_driver.cpp(2593) - Log     - 'buffer object 34 is not zero and buffer size 0 is negative'
ADRD 019347: [22:57:41]        gl_driver.cpp(2593) - Log     - Got a Debug message from GL_DEBUG_SOURCE_API, type GL_DEBUG_TYPE_ERROR, ID 2147483647, severity GL_DEBUG_SEVERITY_HIGH:
ADRD 019347: [22:57:41]        gl_driver.cpp(2593) - Log     - 'buffer object 35 is not zero and buffer size 0 is negative'
ADRD 019347: [22:57:41]         gl_hooks.cpp( 150) - Error   - Function glDeletePerfMonitorsAMD not supported - capture may be broken
RDOC 015364: [17:27:47]   target_control.cpp( 802) - Log     - Used API: OpenGLES (Not presenting & supported)

**Comment by baldurk** [comment] 2019-07-22 11:53
Please provide more information than only the copy-pasted log, the log output rarely provides enough information on its own to diagnose a problem. Describe what you are doing and what happens, as well as your system configuration, and give the steps you take to reproduce the problem. If at all possible including a runnable sample that will demonstrate the problem.

The log does show that some buffer objects are invalidly specified, which may indicate an application error. Be sure to check that your application doesn't have any GL errors when running as this can cause problems with RenderDoc.

**Comment by baldurk** [comment] 2019-08-26 09:06
Closing this issue due to lack of information or response.

**Closed as completed by baldurk** 2019-08-26 09:06 UTC
Labels: Bug, Need More Info
