### ISSUE TITLE
Mesh viewer VS Output information is incorrect when using Vulkan

### ISSUE THREAD

**Issue by Pokechu22** [baldurk/renderdoc#2360] opened 2021-09-07 19:13 UTC
## Description

When using Vulkan, the VS Output information in the mesh viewer is incorrect, showing the same value for all vertices.  This does not affect the result seen when debugging a vertex, nor does this affect the wireframe mesh overlay in the texture viewer.

## Steps to reproduce

To generate the attached capture:

1. Download [Dolphin 5.0-15105](https://dolphin-emu.org/download/dev/4b8b53ac732645f6c0fd3f4b11733cb3d86c9c41/) and the [lesson08 fifolog](https://fifo.ci/media/dff/Lesson08.dff).
2. Launch Dolphin using RenderDoc.
3. In Dolphin, click "Graphics", and change the backend to Vulkan.
4. In Dolphin, switch to the advanced tab under graphics and check "Enable API Validation Layers" (this is not required to reproduce, but it enables debug symbols and source attachment for the shader)
5. In Dolphin, close the graphics window and open the config window.  Uncheck "Enable Dual Core" (as the fifoplayer doesn't work well with it).
6. In Dolphin, close the graphics window, and then select "open".  Open the Lesson08.dff file from before.
7. Save a capture.  Dolphin can now be closed.

To reproduce the actual issue:
1. Download and open [Lesson08_Vulkan_Vtx.zip](https://github.com/baldurk/renderdoc/files/7123791/Lesson08_Vulkan_Vtx.zip)
2. Select EID 19.
3. In the texture viewer, set the overlay to "wireframe mesh".  Note that this renders correctly.  (This step is not required to reproduce the bug.)
4. Switch to the mesh viewer.
5. Observe that although the input vertex data corresponds to a cube, the output vertex data has `gl_PerVertex_var.gl_Position` as `0.00, 0.00, 0.00, 128.00` for all vertices.
6. Observe that switching the preview to VS Out shows only a single point.
7. Observe that when debugging a vertex, the actual calculated result for `gl_PerVertex_var.gl_Position` does vary for each vertex, and is decidedly not 0.

Note that with more complex scenes, the position isn't always `0.00, 0.00, 0.00, 128.00`, but it does still have the same value for all vertices in the mesh.  Also note that this issue does not affect D3D11 or D3D12, and it does not seem to affect OpenGL either.

## Environment

* RenderDoc version: v1.15
* Operating System: Windows 10.0.19042.1165
* Graphics API: Vulkan

**Comment by baldurk** [comment] 2021-09-14 14:20
I believe this is an nvidia driver bug and I've reported it to them. If you're able to reproduce this on a different IHV's driver or if I hear back from them that it's not a bug then I can reopen this, but closing it for now.

I looked at seeing if I could add a seamless workaround but it wouldn't be trivial so it's not worth doing. As a manual workaround if you go into the config editor (tools -> settings -> core -> config editor) and check on the `Vulkan.Debug.DisableBufferDeviceAddress` setting that should force you down a different path which will work.

**Closed as completed by baldurk** 2021-09-14 14:20 UTC
Labels: Bug, Unresolved

**Comment by Pokechu22** [comment] 2021-09-14 17:26
Thanks.  I tried just now with a capture using "Intel(R) UHD Graphics" (version 30.0.100.9684, I think), and that works correctly, so it being an nvidia driver bug seems likely.  <sub>I did need to change Tools -> Settings -> Replay -> GPU Selection Override from "NVIDIA GeForce GTX 1650 Ti" to "Default GPU selection" or else it would report that "Current replaying hardware unsupported or incompatible with captured hardware". (I suspect I changed this before when investigating the issue where "Intel(R) UHD Graphics" doesn't show up under Vulkan outside of RenderDoc which I mentioned in an email.)</sub>

Using `Vulkan.Debug.DisableBufferDeviceAddress` does fix it for the NVIDIA driver too, without causing issues for the Intel driver.  Thanks!

**Comment by baldurk** [comment] 2021-09-14 17:54
Yes indeed, overriding the GPU selection on vulkan is generally not advised since the default selection generally does the right thing (finds the closest matching GPU to what was used during capture) and most non-trivial captures are not currently portable between IHVs or even GPU family for some IHVs.

Glad you got it working though, ideally in future you can disable that chicken bit as use of BDA is generally more performant and reliable than descriptor patching.
