### ISSUE TITLE
Renderdoccmd save image in windows

### ISSUE THREAD

**Issue by JingYongWang** [baldurk/renderdoc#1485] opened 2019-08-06 02:04 UTC
## Description

I analysis game with RenderDoc, and need to dump image
Using internal tool renderdoccmd.exe from RenderDoc by following command,

`renderdoccmd.exe thumb -o test.png -f png D:\RenderDoc\xxx.rdc`

After command, I get a thumbnail that **correctly**,
SO I confused about Issues #1479 what problem I submit
Using RenderDoc GUI and save image, Why I lose alpha data?
And using renderdoccmd get differnet result?
Maybe it problem from application, RenderDoc or something else you said,

There is following step for reproduce
If need more imformation for debug, I'll help as much as I can.

## Environment

game name: PUBG Mobile
apk_name: com.tencent.tmgp.pubgmhd

Enter the game, wait main screen until choose game mode, 
and choose training center to free run there.

screen setting: HDR+、FPS high
Anti-Aliasing can open, but render in phone may strange

RenderDoc 1.4v
Windows 7
OpenGL
GPU: Mail-G76

**Comment by baldurk** [comment] 2019-08-06 15:22
I'm afraid I don't understand precisely what is wrong. The cached thumbnail preview is not related to the replay so I don't understand where it fits in, and you also mention the alpha channel which is also confusing since the thumbnail doesn't contain any alpha at all because it's only for preview.

The thumbnail as saved from renderdoccmd is not related to any replay and shouldn't be used for anything except previewing what the capture looks like. Looking only at the capture when loaded in the analysis UI what is wrong? Does the final swapchain image look incorrect - and if so is it slightly wrong or very broken? Does it look correct but then come out wrong when saved to disk? If so, in what way is it broken?

Screenshots to show what you expect and what you get would be helpful.

I cannot reproduce the problem using your repro steps because I cannot capture a commercial game like PUBG Mobile unless you can share with me a debug build of it. You can contact me privately via email if you can share that.

**Comment by JingYongWang** [comment] 2019-08-06 16:26
Oh, First I understand thumbnail  is not associated to alpha data, because thumbnail  is correct. 
I thought it is the same way to save image but I wrong.
I will discuess with  RD co-worker to clearly explain problem for you.
Maybe our company also block any file even email
If I can , I will contact  you privately and take .rdc file to debug

**Comment by baldurk** [comment] 2019-09-09 09:12
Closing this issue due to lack of information or response.

**Closed as completed by baldurk** 2019-09-09 09:12 UTC
Labels: Bug, Need More Info
