### ISSUE TITLE
Render target texture shows up as black when rendered on previous frame

### ISSUE THREAD

**Issue by dethkrush** [baldurk/renderdoc#1512] opened 2019-09-04 19:42 UTC
## Description

I have an SSAO render target texture that gets rendered on a previous frame and used in the current frame that's getting captured. It's showing up as black in RenderDoc even though in the running game you can clearly see it has pixels in it. I think RenderDoc is assuming that the texture hasn't been rendered this frame, so it thinks it should be black. Instead it should grab the current contents of the render target from memory. Same issue can happen with Temporal AA render targets, it's not correct to assume that they should be black.

## Repro steps
![RenderDocBug_ActualOutput](https://user-images.githubusercontent.com/54912649/64285939-69ec5380-cf11-11e9-9c6a-34062f08fcda.png)
![RenderDocBug_PixelHistory](https://user-images.githubusercontent.com/54912649/64285943-69ec5380-cf11-11e9-98ad-8e37bb2b0e25.png)
![RenderDocBug_TextureUsedAt](https://user-images.githubusercontent.com/54912649/64285945-69ec5380-cf11-11e9-8178-563b3f31c779.png)
![RenderDocBug_ResourceDesc](https://user-images.githubusercontent.com/54912649/64286196-d8c9ac80-cf11-11e9-851c-411cc9a014cc.png)

## Environment

* RenderDoc build: v1.4 214d8522
* Operating System: Windows 10
* API: D3D11

**Comment by dethkrush** [comment] 2019-09-04 19:46
Is there a workaround I can do in code to force capturing of current content from memory? Like a special "D3D11_BIND" flag or "CPUAccessFlags"?

**Comment by baldurk** [comment] 2019-09-04 20:05
There's no need for any special flags, the resource contents from previous frames should be saved by default in recent versions even if there aren't any reads before it is written to. If you're encountering missing previous frame contents then that's a bug but I'll need more information to be able to reproduce and look into it.

Can you share your program with me either here or in private, or else modify a sample program to reproduce the problem that I could then investigate?

**Comment by dethkrush** [comment] 2019-09-04 20:35
Sorry, I can't share anything because I'm working on a AAA game under NDA.

**Comment by dethkrush** [comment] 2019-09-04 20:39
I will probably be able to build a sample app that demonstrates this
behavior after we ship our project.

**Comment by baldurk** [comment] 2019-09-04 20:45
That's understandable, I'm opened to private contact if that's possible as I've worked with game developers before on sharing confidential captures to reproduce bugs. Another option is that if you're willing to run debug builds and help me debug then I can send you tests to try and find out the probelm remotely. It's up to you though of course what you have time for - unfortunately I can't really do anything without knowing what's going wrong exactly.

I ran [this project](https://github.com/TheRealMJP/MSAAFilter) for example which does TAA and uses a texture from the previous frame, and the contents show up correctly.

Could you tell me how the texture is populated with data in the previous frames? E.g. is it rendered to with `OMSetRenderTargets`, or bound as a UAV with `CSSetUnorderedAccessView`, or is it perhaps just copied to with `CopyResource`? It should be marked as 'dirty' internally at that time, which will then cause the capture to save its contents at the start of the captured frame, so perhaps if you tell me how it is modified I can replicate it and reproduce the bug.

**Comment by dethkrush** [comment] 2019-09-04 20:55
It' rendered to from a Compute Shader, bound with CSSetUnorderedAccessView.

**Comment by dethkrush** [comment] 2019-09-04 21:00
The game is also doing lots of Deferred Command Lists on many threads. That usually leads to some Capture/Playback errors. I have to use the option "Capture all Cmd Lists" otherwise RenderDoc doesn't capture anything useful.

**Comment by dethkrush** [comment] 2019-09-04 21:06
I can run some debug builds for you, no problem.

**Comment by baldurk** [comment] 2019-09-04 21:09
If you can run debug builds that would definitely be the most reliable option, as I'm not sure I'd be able to construct a representative demo for what you describe. Looking at what the code is doing for that I don't see why it wouldn't be working, but I might be missing something still.

Can you email me at baldurk@baldurk.org and we'll take this offline?

**Comment by baldurk** [comment] 2019-09-17 21:48
Discussed over email, this seems to have been fixed some time since v1.4 was released and is now working on latest nightlies. Closing the issue.

**Closed as completed by baldurk** 2019-09-17 21:48 UTC
Labels: Bug, Need More Info
