### ISSUE TITLE
Couldn't locate renderdoc target control listening port  ?

### ISSUE THREAD

**Issue by sky3** [baldurk/renderdoc#953] opened 2018-04-12 09:35 UTC
## Description
Hi,
I can not launch an opengl based application using renderdoc. 
In the log file, I observed the following error ?
Did someone already met this error ?

RDOC 012260: [11:29:43]    linux_process.cpp(  88) - Warning - Couldn't locate renderdoc target control listening port between 38920 and 38927 in /proc/13687/net/tcp

Note that I am using Ubuntu 17.10, with driver revision  384.111  for a GTX 1080.

**Comment by baldurk** [comment] 2018-04-13 12:39
Can you give more information about what happens after you launch your application - do you get the renderdoc overlay appearing in your program? Are you able to attach later via file -> attach to running instance, or does your program not appear there at all?

Normally the socket is opened immediately when renderdoc is injected into the target program, but if something went wrong then maybe the socket wouldn't be opened, or maybe it would take too long and you'd hit a timeout.

**Comment by baldurk** [comment] 2018-05-24 10:20
I'm closing this issue now due to lack of information, but if you're able to provide more details to allow me to investigate the problem then comment here and it can be re-opened.

**Comment by noodlecollie** [comment] 2018-05-28 13:40
I get the same problem with my application. I'm running Manjaro 7.1.10 (so Arch underneath), with an Nvidia GTX 1070 running drivers linux414-nvidia 1:396.24-4. RenderDoc itself reports it is v1.0 - I built it from scratch from the AUR (https://aur.archlinux.org/packages/renderdoc/).

When I try and launch the application via RenderDoc, my diagnostic log reports:

```
RDOC 002196: [14:27:03]    linux_process.cpp(  88) - Warning - Couldn't locate renderdoc target control listening port between 38920 and 38927 in /proc/2542/net/tcp
```
I can't actually attach RenderDoc to the running application because the list of programs to attach to is empty. If I refresh that list, it says `Remote connections in progress. Please wait... 0 lookups remaining` and then RenderDoc hangs.

**Comment by baldurk** [comment] 2018-05-28 15:16
Do you get the renderdoc overlay in your program? If you check the modules loaded in it is librenderdoc.so present? I think the hang on the remote connection manager is fixed since v1.0.

**Comment by noodlecollie** [comment] 2018-05-28 15:39
Nope, I don't get any overlay at all. The only response I get from RenderDoc is a popup saying `RenderDoc injection failed` and telling me to check the diagnostic log.

I'm not 100% familiar with checking loaded modules in Linux, but if you mean running `lsmod`, RenderDoc isn't present in that output.

**Comment by baldurk** [comment] 2018-05-28 15:48
OK, so it's definitely not a problem with just the socket. If you do `cat /proc/<pid of program>/maps` it will list where each dynamic library is loaded in the process, if the injection worked at the most basic level then `librenderdoc.so` should be listed in there (more than once).

**Comment by noodlecollie** [comment] 2018-05-28 16:03
Nope, not in that output either.

**Comment by baldurk** [comment] 2018-05-28 16:06
That's really bad..

Can you manually run `LD_PRELOAD=/path/to/librenderdoc.so ./myprogram` and see if you get any errors? It should be loading the library implicitly so I'm not sure why it wouldn't show up in the `maps` list.

**Comment by noodlecollie** [comment] 2018-05-28 16:11
Aha, that gave me the following comment:

```
ERROR: ld.so: object '/usr/lib/librenderdoc.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
```

In which case, I think I know what the problem is: this specific application is 32-bit only, and I'm guessing RenderDoc is installed as 64-bit. Is there a way I can build or download it as 32-bit?

**Comment by baldurk** [comment] 2018-05-28 16:17
Oh right, yes I only support or provide pre-built binaries as 64-bit on linux. The project does compile as 32-bit on windows and android so it should _probably_ work, but it's not something I plan to support so you're on your own with any problems.

It would be up to your distro how you get a package, but if you have Arch you can probably clone & compile straight up.

**Comment by noodlecollie** [comment] 2018-05-28 18:00
I've given a 32-bit compile a try, but apparently I don't have a 32-bit version of the xcb-keysyms library and the AUR (this time) has failed me. I'll have to give it more of an in-depth look. Thanks for the help though.

**Comment by baldurk** [comment] 2018-05-28 18:24
OK cool. I'm going to close this again - it's impossible to say if the original bug was also a 32-bit issue, but it's not something I intend to officially support just due to the testing/support matrix already being huge for linux.

**Closed as completed by baldurk** 2018-05-28 18:24 UTC
Labels: Bug, Need More Info
