### ISSUE TITLE
HLSL "Step forwards Over(F10)" broken starting from v1.22

### ISSUE THREAD

**Issue by Clapeysron** [baldurk/renderdoc#2788] opened 2022-12-06 07:53 UTC
## Description
We use renderdoc in the unity engine to perform single-step debugging for hlsl，but "Step forwards Over(F10)" button broken starting from renderdoc v1.22. The specific performance is that when using "Step forwards Over(F10)" button, hlsl will not jump to the next line but jump into the function. Renderdoc v1.21 works fine, that issue still exists in v1.23.

## Steps to reproduce
Use unity 2021.3.4f1 with HDRP sample project and load renderdoc
Add #pragma enable_d3d11_debug_symbols to shader
Debug into the pixel and press "Step forwards Over(F10)"

I have emailed you the rdc with that issue, choose the drawcall under GBuffer
![image](https://user-images.githubusercontent.com/22258935/205852536-88db0196-cfe9-4aeb-83ae-40657f34d0c5.png)

## Environment
* RenderDoc version: v1.22 & v1.23 both have that issue
* Operating System: Windows 10
* Graphics API: DX11

**Comment by baldurk** [comment] 2022-12-06 11:51
This is a duplicate of #2786 which has been fixed in the latest nightly build.

**Closed as completed by baldurk** 2022-12-06 11:51 UTC
