### ISSUE TITLE
Cant launch application

### ISSUE THREAD

**Issue by andre-ferreira** [baldurk/renderdoc#1464] opened 2019-07-19 13:25 UTC
## Description

Hello! When trying to launch an app trough the renderdoc i get this:
![image](https://user-images.githubusercontent.com/5160177/61538176-c4e4ec80-aa30-11e9-8006-beae1b84993f.png)

Doing an injection to the program works normally.

## Environment

* RenderDoc build: v1.4 and 2019-07-17 nightly build.
* Operating System: Windows 10
* API: OpenGL

**Comment by baldurk** [comment] 2019-07-22 12:24
Can you please post the full log as text please, rather than only a small snippet? The more information I have to work with the more likely and easier it is to find the problem.

Does this happen with all programs you're trying to capture, or only with one specific program? Does the program continue to launch without renderdoc attached or does it exit/crash? What bitness is the program (32-bit/64-bit)?

**Comment by andre-ferreira** [comment] 2019-07-22 15:07
Hi Baldurk!

So here's the log, but i am afraid there isn't much to see:
[log.log](https://github.com/baldurk/renderdoc/files/3418050/log.log)

To answer your questions:
- I have only tested on one program.
- The program crashes after trying to launch (The log of the application doesn't even start)
- The program is x64;

Thanks!

**Comment by baldurk** [comment] 2019-07-22 15:12
If the program crashes on launch that is very likely the cause of the errors. Double check that you have configured the settings necessary to run your program, including any working directory, command line parameters, or environment variable changes that you need.

You can test to see if this is the problem by launching some other program. For example I've uploaded a zip 
[here](https://github.com/baldurk/renderdoc/files/3418086/demos_x64.zip) of the test/demo program I use.

If you're sure that the configuration is correct then I'd recommend using the 'debugger delay' option and attaching your debugger to the process while it's waiting, to see what is causing the crash.

**Comment by baldurk** [comment] 2019-08-26 09:12
Closing this issue due to lack of information or response.

**Closed as completed by baldurk** 2019-08-26 09:12 UTC
Labels: Bug, Need More Info

**Comment by andre-ferreira** [comment] 2020-01-25 12:35
Hi @baldurk,

Sorry for not answering, i was a bit busy at the time.

The issue still persists in v1.6 and i have done what you suggested and the VS debugger breaks even before entering main():

![image](https://user-images.githubusercontent.com/5160177/73121169-fbb33680-3f6e-11ea-8820-d31c56b65146.png)

Unfortunately, it is listed as external code so i dont really know where the crash is coming from.
Exe executes fine without RenderDoc, with or without visual studio.

**Comment by baldurk** [comment] 2020-01-27 10:21
The missing 'External Code' stackframe is a useless visual studio option that is on by default, it can be disabled - I think just by right clicking on it and unticking 'show only my code' or something like that.

Please open a new issue and follow the template to provide a test case that I can use to reproduce the problem. Unless I can reproduce this I can't help you any further, so if you can't share an executable that shows this behaviour I'm afraid you'll need to debug it yourself.
