### ISSUE TITLE
Ctrl+Left/Right buttons are captured by Event Browser while input focus in Shader Editor

### ISSUE THREAD

**Issue by s0501007** [baldurk/renderdoc#1024] opened 2018-06-27 07:48 UTC
## Description

Ctrl+Left/Right buttons are captured by Event Browser while input focus in Shader Editor (doesn't matter if shader was opened for edit from Pipeline State tab, or if shader was created/edited for custom view of texture from Texture Viewer tab)

## Repro steps

Grab any capture. 
Open Pipeline State. 
Select any available shader. 
Hit "Edit" button. 
Click inside shader editor so focus will be inside it.
Press Ctrl+Left/Right - Event Browser will react on these buttons though input focus is in Shader Editor.

## Environment

* RenderDoc v1.0 (built from 5ef2d0bb)
* Operating System: e.g. Windows 8
* API: D3D11, OpenGL

**Comment by baldurk** [comment] 2018-06-27 08:32
Thanks for this report. This is a duplicate of #911, and it has been fixed with the latest code. If you try out any of the recent nightly builds it will contain the fix.

**Closed as completed by baldurk** 2018-06-27 08:32 UTC
