### ISSUE TITLE
RenderDoc 1.16 stops responding when the app uses VulkanMemoryAllocator

### ISSUE THREAD

**Issue by corporateshark** [baldurk/renderdoc#2381] opened 2021-10-02 11:15 UTC
## Description

RenderDoc 1.16 stops responding after capturing a frame of my app which uses VulkanMemoryAllocator. The same app compiled with dedicated allocations (`VMA_DEBUG_ALWAYS_DEDICATED_MEMORY`) does not break RenderDoc.

## Steps to reproduce

1) Compile the app to use VulkanMemoryAllocator with the following options turned off:

`VMA_STATIC_VULKAN_FUNCTIONS `
`VMA_DYNAMIC_VULKAN_FUNCTIONS`

2) Run the app from RenderDoc and press F12 to capture a frame.

3) Observe how RenderDoc stopped responding as in this screenshot.

![image](https://user-images.githubusercontent.com/2510143/135713633-07ce87e1-ffcb-4ba6-a61b-353f0ec448d2.png)

4) Recompile the app with `VMA_DEBUG_ALWAYS_DEDICATED_MEMORY`.

5) Run RenderDoc, capture a frame, observe correct behavior. Same applies when the app does manual memory management without VMA.

* RenderDoc version: 1.16
* Operating System: Windows 10
* Graphics API: Vulkan 1.2

P.S. No Validation layer warnings are generated in any case. The app is tested for a few hours to be stable in any configuration with or without VMA.

**Comment by corporateshark** [comment] 2021-10-02 11:42
Capture: http://linderdaum.com/Capture_Test_SceneGraph_Release_2021_Oct_02.rdc

**Comment by baldurk** [comment] 2021-10-04 11:54
This looks like a driver bug to me. I can reproduce this intermittently with latest public 472.12 drivers, but when using the [vulkan beta drivers 472.02](https://developer.nvidia.com/vulkan-driver) I don't have any problems opening the capture. It's extremely unlikely that it is caused just by using VMA, otherwise an awful lot of programs would be broken.

Can you please test with the 472.02 driver and see if you get the same results? And on another IHV if you can? If you see the same as me then I can report this to nvidia to investigate. It would be helpful if you could post a 'working' capture with `VMA_DEBUG_ALWAYS_DEDICATED_MEMORY` and your program as well if you're able to share it.

**Comment by corporateshark** [comment] 2021-10-04 17:38
@baldurk The driver 472.02 works fine on my machine, the problem is gone. At the moment, I don't have anything from AMD in my direct reach.

Here's the capture with ``VMA_DEBUG_ALWAYS_DEDICATED_MEMORY`` turned on: http://linderdaum.com/Capture_Test_SceneGraph_Debug_2021_Oct_04_VMA_DEBUG_ALWAYS_DEDICATED_MEMORY.rdc

**Comment by baldurk** [comment] 2021-10-05 10:57
For me that capture also fails on 472.12 (and works fine on 472.02), however I don't always get an immediate hang when loading either capture, it sometimes takes a bit of clicking around. So it's possible the `VMA_DEBUG_ALWAYS_DEDICATED_MEMORY` option changes the pattern and you've gotten better results with it due to different hardware or machine setup.

Either way this does seem like something nvidia should investigate. I'll close this issue and report it to them, I can comment here and/or re-open if they find that it's not their bug.

**Closed as completed by baldurk** 2021-10-05 10:57 UTC
Labels: Bug, Need More Info
