### ISSUE TITLE
Python API texsave.comp.whitePoint not working

### ISSUE THREAD

**Issue by 2811299** [baldurk/renderdoc#1501] opened 2019-08-21 08:11 UTC
I want to output depth map images by Renderdoc using Python API,

code snippet like this
```
# # Move to that draw
controller.SetFrameEvent(draw.eventId, True)
pipe: rd.PipeState = controller.GetPipelineState()
texsave = rd.TextureSave()
depth = pipe.GetDepthTarget()
texsave.resourceId = depth.resourceId
texsave.destType = rd.FileType.PNG
texsave.comp.blackPoint = 0.01
texsave.comp.whitePoint = 0.02115
controller.SaveTexture(texsave, 'hahahahahahaha.png')
```
After I execut this python script, I will get a png image, but it's all black which means I think the com.whitePoint not working.

If i load this png image by renderdoc again, I could manually adjust the whitePoint from 1 to like 0.02115, then i can get the depth image, and the image quality is pretty low, not good enough.

So, my question is How can I get a depth image out of renderdoc by python script?

![depth-range](https://user-images.githubusercontent.com/12961255/63414394-58de1580-c42e-11e9-9af3-404d239e8d32.png)
![depth-black](https://user-images.githubusercontent.com/12961255/63414402-5da2c980-c42e-11e9-9001-de277e85fefa.png)

RenderDoc1.4
DX11

I really appreciate it if someone could help me on this.

**Comment by baldurk** [comment] 2019-08-21 09:18
I'm not able to reproduce this. In RenderDoc v1.4 I ran the same script (with different black/white point numbers to account for the different capture but prove that they are working correctly - 0.94095 and 0.97448) and I was able to save a PNG with the correct range.

Can you share more specific repro details, including the capture you're saving from and the PNG you get? It might be something specific from your capture that causes the problem.

**Comment by 2811299** [comment] 2019-08-21 10:01
thanks Baldurk, I can output depth map now, I guess it is because i'm opening the same rdc file by RenderDocUI.exe, it's conflicted or something.
BTW, is there any parameter in Python API which could do exact the same "range auto adjust" just like in the RednerDocUI for depth map?

**Comment by baldurk** [comment] 2019-08-21 10:08
I don't understand what you mean by a conflict. The PNG file is completely separate to the RDC file so it doesn't matter if it's still open.

The range auto adjust can be accomplished by using [ReplayOutput.GetMinMax](https://renderdoc.org/docs/python_api/renderdoc/main_ifaces.html#renderdoc.ReplayOutput.GetMinMax) on a `ReplayOutput` configured to show the texture. It's a little awkward that you need a `ReplayOutput` to obtain it but that's mostly due to historical reasons. You can use `CreateHeadlessWindowingData` to create a dummy `ReplayOutput` without needing a proper window to display on.

I'm closing this since it sounds like your problem was a mistake on your part and not a bug.

**Closed as completed by baldurk** 2019-08-21 10:08 UTC
Labels: Bug, Need More Info
