### ISSUE TITLE
Storage buffers not captured if uploaded during previous frames

### ISSUE THREAD

**Issue by Vitaljok** [baldurk/renderdoc#3372] opened 2024-07-04 18:12 UTC
## Description
> As suggested in Discord, opening the report here.

The other day I was investigating Vulkan `bufferDeviceAddress` feature and “vertex pulling” technique (basically followed [Vulkan Guide](https://vkguide.dev/docs/new_vkguide/chapter_3)).
The results were as expected and application rendered fine on screen. 
However when I tried to capture frames using Renderdoc, it missed all the geometry.

Further investigation showed, that Renderdoc captures buffers only during the frame they are uploaded. Subsequent frames have buffers filled with zeros.

I have put together minimalistic repo that demonstrates the case: https://github.com/Vitaljok/buffer-device-address-bug
> Note: code lacks proper checks, has a lot of hardcoded values.

The essential part in pseudo-code:
```c++
uploadBuffers();

while (true) {
    pushConstants(vertexBufferDeviceAddress);
    bindIndexBuffer();
    drawIndexed();
}
```
## Steps to reproduce
- Compile the project
```
cmake -S . -B build
cmake --build build
```
- Launch executable from Renderdoc
  - set working directory to project root
  - tick "Queue capture", start from frame `0`, # of frames `2`

The capture for `frame 0` has "Copy/Clear Pass" and "Color Pass" properly shows the geometry and buffer contents.
`Frame 1` has only "Color pass" as expected, but vertex buffer is filled with zeros.
Also added my capture files to the root of the repository.

## Environment

* RenderDoc version: v1.33 (cae28932)
* Operating System: Windows 10
* Graphics API: Vulkan 1.3.283.0
* NVIDIA GeForce RTX 3060 Ti, driver 556.12

**Comment by Zorro666** [comment] 2024-07-08 07:11
Thank you for the reproduction. If it helps this problem is specific to v1.33. RenderDoc v1.32 is capturing the storage buffers correctly in your reproduction

**Comment by Zorro666** [comment] 2024-07-08 13:19
Duplicate of #3346 

Fixed in a recent nightly build

**Closed as not planned by Zorro666** 2024-07-08 13:19 UTC
Labels: Bug, Unresolved
