### ISSUE TITLE
Feature question: feasibility of GLSL debugger 

### ISSUE THREAD

**Issue by kakashidinho** [baldurk/renderdoc#1775] opened 2020-03-14 06:55 UTC
## Description

I’m currently working on an in-house OpenGL application for my day to day job. Sometimes I want to step into GLSL code to debug but unfortunately there is no possible tool that could do that. This is actually a question I’m seeking an answer for a long time.
Why GLSL has no debugger but HLSL has for years? Metal also has a shader debugger.

Is it because few devs working on OpenGL? Or some technical challenging preventing it?

I’m curious because if it is because of lack of people’s interest/devs’ contributions, then maybe at some points I would like to try doing it myself. It might be possible if the GLSL is translated to SPIR-V. It also might not be doable but at least I would know the limit that we won’t be able to cross.

## Environment

* RenderDoc version: HEAD
* Operating System: Debian 9
* Graphics API: OpenGL

**Comment by baldurk** [comment] 2020-03-14 09:19
Closing this as a duplicate of #293.

This hasn't been implemented for a combination of factors. Prioritisation and the time investment needed is one, but also because GLSL is a text based format. As you say, it's possible that a subset of GLSL shaders that can be compiled to SPIR-V could be debugged, which can be looked at in future after SPIR-V debugging is supported for Vulkan.

**Closed as completed by baldurk** 2020-03-14 09:19 UTC
