### ISSUE TITLE
Failed to run RenderDoc capture

### ISSUE THREAD

**Issue by JingChangzz** [baldurk/renderdoc#1618] opened 2019-11-27 09:52 UTC
## Description

I want to launch an UE4 Android game from RenderDoc on Windows， but failed
![企业微信截图_157484519366](https://user-images.githubusercontent.com/13314441/69708872-5713a480-1137-11ea-9bb0-89311aff8c5e.png)

The apk is development build.
When I seleted Executable Path，RenderDoc eject：
![企业微信截图_157484495463](https://user-images.githubusercontent.com/13314441/69708546-c89f2300-1136-11ea-9f2c-bd3755a39eb2.png)  

I have tried in three different phones, and all failed.

## Steps to reproduce
I'm sorry that I can't share my applicateion...

## Environment
  
* RenderDoc version: 1.5
* Operating System: Windows 10
* Game Runnning System: Android
* Game engine： Unreal 4

**Comment by baldurk** [comment] 2019-11-27 10:02
The error message you have posted states exactly what the problem is. If you get that message about your android application not being set up for RenderDoc capture this means that it's not debuggable, and so cannot be injected. You must make sure your application's apk is created as debuggable before it can be debugged with RenderDoc.

If your application is already marked as debuggable and the error message is incorrect, you must share an apk that reproduces the problem so that I can investigate it. If you don't want to share your real application then you could create a new simple project in unreal and see if the problem reproduces there. If it does reproduce, you can share that apk, if it doesn't reproduce then you have something to compare against to figure out why your own project is misconfigured.

**Closed as completed by baldurk** 2019-11-27 10:02 UTC
