### ISSUE TITLE
Using Renderdoc API - better ways to determine a replay app?

### ISSUE THREAD

**Issue by sibojia** [baldurk/renderdoc#368] opened 2016-09-20 01:22 UTC
I want to use renderdoc replay api in my own project to do some automatic log analysis. As I can't find much documentation on this, I encountered many problems, and this is one of them: app crashes when running `RENDERDOC_CreateReplayRenderer`. After digging in the source I found that in `win32_libentry` it determines whether the host process is a replay app ONLY by its file name.... I had to rename my program to `renderdoccmd.exe` to make it work. Is it possible to be improved? Or is it I'm not using it the right way... Thanks!

**Comment by baldurk** [comment] 2016-09-20 08:52
Hey, yes I will admit this is totally a hack :(.

The problem is that I need to know very early on (before hooking) whether I'm in the replay application or in something to capture, since I can't rely on function calls from the application to initialise later. This happens inside `DllMain()` which is [kind of restricted on what it can do](https://msdn.microsoft.com/en-us/library/windows/desktop/dn633971(v=vs.85).aspx#general_best_practices) - although I break those rules sometimes when I have no other choice. It's before any function calls from the application to the dll, so I can't simply export a library function to flag an application as replayer.

One solution would be to make a separate build of RenderDoc that doesn't do any work inside `DllMain()` and instead requires explicit initialisation from the outside. I don't really want to start building and distributing something like that, but I wouldn't mind adding it as something which is disabled on a `#define` that you could customise when building locally. However if you're changing a build locally, you could just add your exe name to the list in the hack... We could also just add some substring to the hack which isn't going to appear elsewhere like ".renderdoc.replay.exe" for you to include in your exename, but it's nasty to require a particular .exe naming just to work.

I'm open to suggestions though, if you or anyone has any ideas - as long as it works within the above constraints I'm happy to hear it.

PS, I'm pretty excited you're interested in using the replay API :). It sounds pretty cool and I'd be happy to help you out with anything you run into problems with. This API really isn't documented/bullet-proof yet, it's mostly used to abstract away the UI from the meat of the program, but I think there are some cool possibilities with using it. Bear in mind - it's very likely going to change in breaking ways regularly since I don't try to keep it stable.

**Comment by sibojia** [comment] 2016-09-23 03:23
Thanks very much for your reply! I'm OK with the current solution. Actually I'm desperate for some help cause I'm neither familiar with win32 programming or directx either, but I'm afraid I shouldn't pour out many detailed problems. Anyway I'll describe what I'm doing, any comments or guidance is appreciated!

In [this paper](http://download.visinf.tu-darmstadt.de/data/from_games/), the author extracted scene segmentation data from GTA frames. What I want is the **3D position and orientation** of the scene objects, especially cars. Therefore my custom program needs to:

1. Automatically capture frames from  game periodically
2. Save the rendered frame to image file
3. From each frame, find the drawcall of the car body rendering. (May be inferred from the mesh pattern)
4. Find the 3D bounding box of the car in camera view. (currently I can see SV_POSITION of each vertex in renderdocui, I need all of them in order to find the bounding box)
5. Optionally, render the 3D bounding box to the frame to check correctness

Currently I'm not sure whether to use native win32 or c# framework of renderdocui, and I haven't yet find method of most of the functions above... What I have done is some exploration in rederdocui, and a native win32 application which can list all the drawcalls.

**Comment by baldurk** [comment] 2016-09-23 21:37
I'm not sure if this is best to approach from the win32 or C# side. It depends on your comfort level and whether you want a clean solution vs. just hacking something together.

Capturing the frames and saving the output image can be fairly easily automated. You can queue a capture every 120 frames for example or something, and every capture has an easy to preview 'final image' - you can look at how `renderdoccmd` does its preview and finds the backbuffer.

Identifying the car seems like it's complex, but if you have an idea of how to do that then all the properties of the draw and mesh are freely available.

Getting the bounding box, if you're coding in C# then the bounding box is already calculated in the mesh viewer for input, it should be possible to pull it out. If not then you could maybe use that as a guide of how to calculate it yourself.

Rendering the bounding box would be the hardest, since nothing built-in to renderdoc will do that. However you mostly want to do the same thing as the mesh viewer's preview render, but with less work - ie. removing any background checkerboard, or viewport frustum or axis, etc.

Hopefully that is somehow helpful :). Let me know if you have more specific questions that will be easier for me to answer.

**Comment by sibojia** [comment] 2016-10-03 17:14
I decided to add a window in the current renderdocui c# project to do my works. But when I try to save the texture of the final image I found that it's different from what I see in the texture viewer (looks darker). On the other hand I don't know how to directly export images from the backbuffer. I tried to create bitmap from window handle in a win32 project but the result image is distorted. Would you please help me with this problem? Thanks a lot!

**Comment by baldurk** [comment] 2016-10-03 17:42
For saving a texture you should definitely use the built-in functionality, via `SaveTexture` on the `ReplayRenderer`. Trying to do it via bitmaps or window handles will be quite unreliable.

When you say that it looks darker, can you give an example? I wonder if it might simply be gamma vs linear. Do you have the gamma display checkbox ticked when viewing in the texture viewer? 
![image](https://cloud.githubusercontent.com/assets/661798/19047133/e08a321e-89a0-11e6-9c62-3f42d6cb8f43.png)
If you save as JPG/PNG or other conventional formats, the data will be interpreted as being in sRGB space, so you need to tick the checkbox in the texture viewer to get the equivalent visualisation.

**Comment by sibojia** [comment] 2016-10-04 03:54
![image](https://cloud.githubusercontent.com/assets/6429444/19062015/80911818-8a28-11e6-8495-904ce44b504a.png)
I found that for swapbuffer the checkbox is fixed to be checked.
For other events, the saved images have the same brightness as seen in the texture viewer when the checkbox is ticked, as you said.

**Comment by baldurk** [comment] 2016-10-04 09:54
That's quite strange behaviour, but it does look like the sRGB curve being applied wrongly somewhere.

I can't reproduce this on my local captures of GTA5 - can you share somewhere the capture that produces the above problem?

**Comment by sibojia** [comment] 2016-10-04 17:23
Please download at https://drive.google.com/open?id=0B6qhYXtjS8EgUUNJdWxzc29YOVE . Thanks!

**Comment by baldurk** [comment] 2016-10-04 18:03
Thanks! I've repro'd it - I will look into what's going wrong tomorrow. I think it might be because the backbuffer format is B8G8R8A8_UNORM, but I'll need to check.

**Comment by baldurk** [comment] 2016-10-05 18:22
I think that commit should do the trick, let me know how you get on.

I'm also going to close this issue since the original thing is probably not solvable and you are OK with the current situation. If you have any other problems or bugs, feel free to open a new issue about them. If you need just general help or advice, you can always email me and I'm happy to help.

**Closed by baldurk** 2016-10-05 18:22 UTC
Labels: status: unresolved, type: enhancement

**Comment by sibojia** [comment] 2016-10-06 03:27
OK, thanks a lot!
