### ISSUE TITLE
Crash when load capture log

### ISSUE THREAD

**Issue by mi2think** [baldurk/renderdoc#1295] opened 2019-03-05 07:57 UTC
## Description

Hello, I'm adding vertex array obejct(VAO) support for UnrealEngine 4.18.3. It's seems well in game.  But when I try to capture game frame with RenderDoc, some times it will crash when load capture log at loading state about 69 percent.

## Repro steps

1. capture frame 
2. click capture for loading, then crash

## Environment

* RenderDoc build: e.g. v1.0, or 2018-03-12 nightly build.
* Operating System: e.g. Windows 10, Windows 7, Ubuntu Linux, etc
* API: e.g. Vulkan, D3D11, OpenGL, etc

RenderDoc: V1.2 built from 204724be
OS:   Windows 10
API：OpenGL
Other infos:
GL_VENDOR: NVIDIA Corporation
GL_RENDERER: GeForce GTX 1060 6GB/PCIe/SSE2
GL_VERSION: 3.2.0 NVIDIA 388.13
GL_SHADING_LANGUAGE_VERSION: 1.50 NVIDIA via Cg compiler

I would like upload this capture, but it's size if 88MB, so have a idea?

**Comment by baldurk** [comment] 2019-03-05 09:33
VAOs are definitely supported so I'd need more information to reproduce the problem. If you can upload a sample application, share a UE4 branch with me, or upload the capture that's crashing then I can definitely look into this further.

**Comment by mi2think** [comment] 2019-03-06 02:31
Hi, I have upload the capture log to OneDirve, with shared link: [crash log](https://1drv.ms/f/s!ApORTeyVAhmC9AmBHnuCwySm1XjG). You can download it.

I have to say maybe this carsh is caused by my bugs for implement VAO. So It's very kind  if you point my bug and I hope that's not waste your time.

**Comment by baldurk** [comment] 2019-03-06 12:26
This seems to be caused by a buffer being unbound at the point of draw:

![image](https://user-images.githubusercontent.com/661798/53880461-f1134a00-4008-11e9-9f80-d8f959f61e09.png)

Looking at how the VAO was initialised, a buffer was bound there but it's not present in the capture. The most likely explanation for this is that the buffer was deleted before the draw happened.

![image](https://user-images.githubusercontent.com/661798/53880450-e8227880-4008-11e9-8228-5fdeda6dd134.png)

To debug further I'd need to investigate the application while it's being captured, but I'd suggest first checking to see if you're deleting the buffer that should be b ound.

This shouldn't really cause a crash but unfortunately desktop GL drivers will commonly fall back to treating unbound vertex buffers as memory pointers, and then read invalid memory. Even when using GL core profile where this behaviour is deprecated and invalid.

**Comment by mi2think** [comment] 2019-03-07 02:41
Thanks for your information. I will check my code. 

Emm, RenderDoc for me is good tool used every day, so it's make things inconvenient if losing his help. According to your screenshot, do you fix or avoid this carsh? If so can you send me a copy for me to debug? Thanks!

**Comment by baldurk** [comment] 2019-03-07 09:54
I ran through a debugger and found it was crashing inside the `glDraw*` calls, and I commented them out. So the capture did not replay correctly but I could at least see the state at the draws - since I had a strong suspicion from the crash that this was the problem, as I've seen it before.

**Comment by mi2think** [comment] 2019-03-07 12:16
Hi，After I resolve the problem when render UI, it seems not crashed now! So am I close this issue? The only thing is why didn't it crash in game, but crash when replay it in RenderDoc, since they do use same GL drivers. Thanks for your infomation again!

**Comment by baldurk** [comment] 2019-03-07 12:22
The behaviour of the driver in this area is not very consistent. In game you perhaps had a buffer bound then deleted it, but on replay RenderDoc will never bind the buffer at all. It treads into a weird grey area of the spec. Technically drivers should never use buffer offsets are pointers in core profile GL but because of the way RenderDoc replays only the steps necessary for a frame it can trigger this kind of difference in behaviour because of the buffer deletion.

I'm glad you found your bug, yes I'll close this now.

**Closed as completed by baldurk** 2019-03-07 12:22 UTC
Labels: Bug, Need More Info

**Comment by mi2think** [comment] 2019-03-07 13:44
That's make sense. Thanks!

PS: after I have done this task and testing in mobile phones, the results show VAO dones not improve performance as I expected. e.g. For snapdrgon 835, it only save 0.98ms about 250+ draw calls, even reduced so many API calls.
