### ISSUE TITLE
Unable to replay GLSL program stages that are linked using multiple shaders per stage

### ISSUE THREAD

**Issue by ajurcik** [baldurk/renderdoc#1079] opened 2018-08-11 22:30 UTC
## Description

First, Thank you for such great application.

When replaying a capture, I am unable to view resulting mesh after VS stage if the VS stage consists of multiple GLSL shaders. It seems that the problem is that RenderDoc fails to create a separate program for a shader without `main()`.

In my OpenGL application, I am using a custom framework which provides me with `#include` implementation. In this manner, I am able to share common GLSL code such as per fragment fog computation or clipping by user defined clip planes. When I designed the framework, I decided to split GLSL definitions and declarations as I had problems with re-definitions (sorry, I can't remember the specific issue). This design results into GLSL programs that consist of *common* shaders and per-stage *main* shaders. This design seems to be not suppored by RenderDoc.

## Repro steps

The issue can be reproduced when performing a capture from the attached application.
Steps:
1. Run RenderDoc UI and set parameters according to the attached settings.
2. Launch the setup.
3. Take capture using `F12`.
4. Replay the capture in RenderDoc and see `Mesh Output` -> `VS Output`.
5. **No VS Output should be shown**.

## Environment

* RenderDoc builds: v1.1 and 03c2507a254a22a020c7cfc54e840452cac3c6e6 own local build (VS 2017).
* Operating system: Windows 10
* API: OpenGL

## Attachments

[cv1.zip](https://github.com/baldurk/renderdoc/files/2280579/cv1.zip)
[cv1.dist.zip](https://github.com/baldurk/renderdoc/files/2280592/cv1.dist.zip)
[Debug.cap.txt](https://github.com/baldurk/renderdoc/files/2280580/Debug.cap.txt)

I use debug build of JVM in `Debug.cap` but you can use any Java 8 SE JVM. Similarly, the debug parameters in the command line arguments can be omitted.

**Comment by baldurk** [comment] 2018-08-12 07:32
Thanks for the comprehensive report! This is a duplicate of #657 though so I'm going to close it.

**Closed as completed by baldurk** 2018-08-12 07:32 UTC

**Comment by ajurcik** [comment] 2018-08-12 21:11
Sure. I am sorry, I skimmed through the open issues in order to find a possible duplicate but I missed it.
