### ISSUE TITLE
Crash when Viewing a RenderDoc capture showcasing D9VK train bug in Sonic Adventure 2

### ISSUE THREAD

**Issue by misyltoad** [baldurk/renderdoc#1491] opened 2019-08-09 17:01 UTC
## Description

Hello there!

I was trying to fix this bug https://github.com/Joshua-Ashton/d9vk/issues/292 in D9VK today [which is also one present on Intel's native d3d9 drivers] and I found that any frames that highlight the issue (the train is above the player's head for some reason) crash RenderDoc when trying to view any part of them.

Captures where the d9vk bug is not shown work fine, whereas captures where the d9vk bug is shown break -- I have attempted multiple times.

Other traces work completely fine also.

## Repro steps

1. d3dretrace the [Sonic Adventure 2 trace (clicky)](https://drive.google.com/file/d/1HVdqvLSCwsN6fZyjOOBvxYKSdCpbEXwq/view?usp=sharing) with [d9vk](https://git.froggi.es/joshua/d9vk/-/jobs)
2. Capture on a frame where the train is above the player's head
3. Open [capture (clicky if you want to skip the above)](https://temp.froggi.es/d3dretrace_2019.08.09_16.42_frame5582.rdc)
4. Click on any draw call
5. CRASH!

It's worth noting that on the latest nightly, it doesn't crash but it also doesn't render anything in the texture viewer. It doesn't clear it and I can do a cool Internet Explorer-styled effect when I drag the window size around:
![image](https://user-images.githubusercontent.com/21316711/62795745-547d3880-bacf-11e9-9ee1-a1077a7b3cc5.png)

## Environment

* RenderDoc build: v1.4 and Nightly_2019_08_07
* Operating System: Windows Server 2012 r2
* API: Vulkan
* GPU 1 [primary, in use]: AMD Vega 56 flashed with 64 BIOS
  * Drivers as of 2019/07/31
* GPU 2: Nvidia RTX 2060 SUPER

## Resources
Trace: https://drive.google.com/file/d/1HVdqvLSCwsN6fZyjOOBvxYKSdCpbEXwq/view?usp=sharing
Capture: https://temp.froggi.es/d3dretrace_2019.08.09_16.42_frame5582.rdc
D9VK Builds: https://git.froggi.es/joshua/d9vk/-/jobs

Let me know if you need anything from me! 🐸

**Comment by baldurk** [comment] 2019-08-09 18:38
Thanks for the clear report! Unfortunately I'm having trouble reproducing the problem. The capture is incompatible with my AMD card so I tried to run d3dretrace on my AMD system and I ran into a `VK_ERROR_DEVICE_LOST` within a few frames, before I'd attached renderdoc. I tried on my NV system and it worked fine

Does this only happen for you with your AMD card? I'm wondering if it's device specific and has something to do with the device lost error I see before capturing - the behaviour you describe is consistent with a device lost, but it would be good to double check if you could upload the diagnostic log (help -> view diagnostic log) from the nightly build where it doesn't crash.

**Comment by misyltoad** [comment] 2019-08-13 03:27
Apologies for my delayed reply.

## AMD (Windows, RX Vega 56)

Yes, the RenderDoc log is littered with ``VK_ERROR_DEVICE_LOST`` errors for me, however the trace plays back fine both with and without RenderDoc attached -- just the capture is broken on my end.

[diagnostic.log](https://github.com/baldurk/renderdoc/files/3495161/diagnostic.log)

## NV (Windows, RTX 2060 Super)

Works fine! I probably should have tested this, apologies for not including it in the original report.

[capture from rtx 2060 super](https://temp.froggi.es/sonic_rtx_2060_super.rdc)

[rtx2060_super_diagnostic.log](https://github.com/baldurk/renderdoc/files/3495191/rtx2060_super_diagnostic.log)

**Comment by misyltoad** [comment] 2019-08-13 03:47
Tried to have a bash at finding out where the rendering issue is on the NV capture.

Editing shaders causes a crash. I've attached the report from that.

[renderdoc_report.zip](https://github.com/baldurk/renderdoc/files/3495249/renderdoc_report.zip)

Edit: this was on nightly, I should clarify.

The report highlights this

`RDOC 007160: [03:45:32]   resource_manager.h(1493) - Error   - Assertion failed: 'm_CurrentResourceMap.find(id) != m_CurrentResourceMap.end()' (id=ResourceId::1000000000000004650)`

**Comment by baldurk** [comment] 2019-08-13 10:02
OK I re-tested and looks like I'd messed up the vulkan physical device selection.

I have a system with an NV and AMD card. If both physical devices are available then NV always floats to the top and gets selected by d3dretrace/d9vk. If the AMD card is the only one connected to an output, then I get a `DEVICE_LOST` error within the first few frames. This is what I mistakenly said above was a device lost with AMD. To be clear, this happens when just doing a plain d3dretrace, RenderDoc is not active at all it just dies.

If I selectively disable drivers so that only the AMD device is visible to vulkan when connecting the AMD card to the output, and vice-versa for the NV device, then **both** are able to capture and replay successfully with no errors on the latest nightly build.

I'm also unable to reproduce any errors editing shaders in either case, so I'm unfortunately still not able to reproduce any problem (aside from the above `DEVICE_LOST` which is in the application, not renderdoc).

If you can reliably repro the editing shader crash can you upload the capture from your NV card and give instructions on how to crash it? I can look into that at least, but it will not be the same issue as whatever is causing you to hit `DEVICE_LOST` on your AMD card on load.

**Comment by misyltoad** [comment] 2019-08-13 23:39
I just edit any vertex shader and hit refresh and it crashes for me [in that capture above I linked in the NV section]

What OS and drivers are you getting the device loss on?

**Comment by baldurk** [comment] 2019-08-14 08:32
Ah sorry, I missed the capture you linked above thinking you'd only posted the log file, that's my mistake.

Unfortunately I'm still unable to repro with that capture on both my nvidia systems :(. I tried with v1.4 where the capture was made, the 2019_08_07 nightly as well as with latest code. I edited the vertex shader on the first visible train draw but I was able to refresh and the capture was still fine.

The system where I got the device lost errors is Windows 10 with NV 2080 Ti on driver 431.60 and an RX 480 on driver 19.7.4. But the device lost errors only happen when the AMD card is the one connected to the display and both vulkan drivers are available (so both physical devices are available, with NV always being device 0). The output is here, it renders a few frames _very_ slowly before eventually stopping: [device_lost.log](https://github.com/baldurk/renderdoc/files/3500345/device_lost.log).

I also tested on my main PC, Windows 7 with an NV 1080 Ti on driver 426.06 (vulkan developer driver).

What NV drivers are you using? I wouldn't expect this to be caused by a failure there but it's worth updating to latest just in case if you haven't already.

**Comment by misyltoad** [comment] 2019-08-14 13:24
I'm using
`431.60-desktop-win7-64bit-international-whql`

I also can't replicate the crash after a reboot now... Blegh.
Still not getting any device loss though.

**Comment by baldurk** [comment] 2019-08-14 14:05
I found one problem that was throwing some validation layer errors, I don't have much expectation that it will fix anything but it's worth a try on the next nightly.

One thing I noticed was that both captures you've uploaded are taken from v1.4. Can you try capturing on the latest nightly to see if that works any better for you?

When you say you don't get the crash after a reboot, do you mean the shader editing crash?

**Comment by misyltoad** [comment] 2019-08-14 14:25
> When you say you don't get the crash after a reboot, do you mean the shader editing crash?

Yes

> One thing I noticed was that both captures you've uploaded are taken from v1.4. Can you try capturing on the latest nightly to see if that works any better for you?

I'll have a go at figuring out how to do that on Windows later today, have just been using ENABLE_VULKAN_RENDERDOC_CAPTURE=1 atm

**Comment by baldurk** [comment] 2019-08-14 15:13
You should not be setting environment variables manually. With your repro launching the program is straightforward using the normal workflow for launching executables - launch d3dretrace.exe with the path to the trace as the first command line parameter.

When RenderDoc starts the launch application panel will have a banner if that installation is not currently registered as the active vulkan layer, click on it to re-register.

**Comment by misyltoad** [comment] 2019-08-14 15:17
Thanks for the info, I was not aware of that.

I always just used the env var because the application launcher never worked for me, I'll give it another shot.

**Comment by baldurk** [comment] 2019-09-09 09:17
I'm going to close this issue now since unfortunately I wasn't able to repro the bug on either AMD or NV side. It may be hw or driver specific somehow in which case it'll be hard to track down any such RenderDoc bug. If you're able to find a different repro or something else you want me to try then please feel free to comment here again.

**Closed as completed by baldurk** 2019-09-09 09:17 UTC
Labels: Bug, Need More Info
