### ISSUE TITLE
DirectX 12 command buffer not closed when enable API validation.

### ISSUE THREAD

**Issue by MioMioReimu** [baldurk/renderdoc#3066] opened 2023-09-22 06:58 UTC
## Description
D3D12 validation layer show Reset fails because the command list was not closed. and some resource's barrier cannot show correctly in Resource Inspector, like Texture98 in rdc file. 
Texture 98 firstly used in EID 330, but Resource Inspector show it used in EID 342.
![image](https://github.com/baldurk/renderdoc/assets/4363625/b9773ebb-cd0a-475a-9005-f37169a3bc35)

This validation error will not show when I run my client without renderdoc.

## Steps to reproduce
In My Engine, I use this way to track dx12's resource state. 
firstly I dispatch N command buffer to record parallely in worker threads. after all N command buffers record task finished, then I do resource barriers which resource are used between `k-1` and `k` command buffers at `k - 1` command buffer. these resource barrier are recorded in main thread.
at last I close all N command buffers in main thread.

I have send rdc file to baldurk@baldurk.org, email title is "bugreport: DirectX 12 command buffer not closed when enable API validation.".

## Environment

* RenderDoc version: v1.28 stable
* Operating System: Windows 10
* Graphics API: DirectX 12

**Comment by baldurk** [comment] 2023-09-22 10:12
I didn't receive any email. Looking at my server logs it seems like the message may have been rejected for being too large. Did you try to attach a large rdc file as an attachment instead of uploading it to a fileshare and sending a link to it?

**Comment by MioMioReimu** [comment] 2023-09-26 06:45
very thanks, and I upload it here. https://github.com/MioMioReimu/renderdoc_rdc/blob/main/dx12_cmd_buffer_not_closed.rdc

**Comment by baldurk** [comment] 2023-09-26 09:34
Thanks for sharing that. I don't see anything that would be wrong there, and since the validation errors are captured from the running program (and because of D3D12's limitations they are all in the same single execute) I can't tell exactly what's causing it. I suspect this may be a duplicate of #3042 though that only reproduced for me when capturing the first frame.

Can you test again with the latest nightly build? If the problem still occurs can you share your program so that I can reproduce the problem at capture time?

**Comment by MioMioReimu** [comment] 2023-09-26 10:17
Thanks. it works, latest nightly build fix all. validation error and resource inspector error not show any more.

![image](https://github.com/baldurk/renderdoc/assets/4363625/37b8417b-adb1-402c-8284-8f1bde8308a8)

**Comment by baldurk** [comment] 2023-09-26 10:20
OK, it sounds like you were reporting two different bugs? but if they're both fixed then that's good.

**Closed as completed by baldurk** 2023-09-26 10:20 UTC
Labels: Bug, Need More Info
