### ISSUE TITLE
Crash in Unreal 4.25.4

### ISSUE THREAD

**Issue by YooYongSun1** [baldurk/renderdoc#2101] opened 2020-11-23 03:00 UTC
## Description

Crash in Unreal 4.24.3
When update renderdoc from 1.9 to 1.10, Unreal 4.24.3 crash and report fatal error.
here is the log.

LoginId:99fa34704e9f61c0771f6b9c23ed7b76
EpicAccountId:71547d89d14342e583807981052a5f5a

Unhandled Exception: EXCEPTION_ACCESS_VIOLATION reading address 0x00000000

renderdoc
renderdoc
renderdoc
renderdoc
UE4Editor_D3D11RHI
UE4Editor_D3D11RHI
UE4Editor_SlateRHIRenderer
UE4Editor_SlateCore
UE4Editor_MainFrame
UE4Editor_MainFrame
UE4Editor_UnrealEd
UE4Editor
UE4Editor
UE4Editor
UE4Editor
kernel32
ntdll

## Steps to reproduce

install renderdoc and unreal 4.25.4, enable plugin. restart ue4, it run into crash.

## Environment

* RenderDoc version: V1.10
* Operating System: Win10 Pro
* Graphics API: d3d11

**Comment by baldurk** [comment] 2020-11-23 11:06
Duplicate of #2055, closing.

**Closed as completed by baldurk** 2020-11-23 11:06 UTC
