### ISSUE TITLE
Loading a capture breaks rendering inside RenderDoc (Vulkan)

### ISSUE THREAD

**Issue by hrydgard** [baldurk/renderdoc#1309] opened 2019-03-12 10:37 UTC
The Texture view and mesh viewers and others stop rendering after loading this capture file:

https://www.ppsspp.org/unofficial/broken.zip

Reproduced on the latest renderdoc nightly, 8d5bb1f0bb...

The app passes the VK validation layers nearly perfectly (a couple of unused attributes in a vertex shader is the most serious warning).

Windows 10, Vulkan, Geforce 1070 GTX, NV driver 419.35.

**Comment by baldurk** [comment] 2019-03-12 11:38
All of the descriptor sets are missing their contents, which leads to `VK_ERROR_DEVICE_LOST` trying to draw anything - among other things that causes all of the internal rendering to stop working.

I can't tell from the capture itself why the descriptor sets are missing their contents. Are you able to share repro steps with me that I could follow to capture the program and debug it there? Or if not would you be able to build RenderDoc from source if I made a side branch with verbose logging?

**Comment by hrydgard** [comment] 2019-03-12 15:22
Huh, that's weird. It happens when I load up Sonic Rivals in PPSSPP and take a screenshot ingame, but it's possible there's a way to repro it without having the game. I'll try to find some time to look into it soon.

**Comment by hrydgard** [comment] 2019-03-13 21:30
Alright, here's a repro:

Download the latest 64-bit build of PPSSPP from https://buildbot.orphis.net/ppsspp/  (or build yourself).

Run it once and switch the backend to Vulkan (requires a restart). On the Homebrew & Demos tab, go to the homebrew store and download PSP-Flower.

Now, start from within RenderDoc, launch PSP-Flower and capture a couple of frames (using the button, F12 fails for some reason). When you open these, you'll often if not always reproduce.

I've recently enabled use of a couple of extensions like dedicated allocations, it could have something to do with that.

**Comment by baldurk** [comment] 2019-03-25 17:39
Thanks for that, I see the problem. The issue is that the descriptor pool is getting reset before the capture completes, presumably because renderdoc syncs to the GPU enough that it happens sooner than expected. I don't hold onto the information that I need to complete the capture and it gets lost when the descriptor sets are freed.

I have an idea of how I can fix it, I should be able to get back to you hopefully soon.

btw I've fixed the issue causing F12 to crash - it was triggering a screenshot function in PPSSPP itself and there was a bug triggering with that code.

**Comment by hrydgard** [comment] 2019-03-25 18:14
Sounds promising! No rush :)

My multithreaded rendering seems a bit painful to capture, hehe.

**Comment by baldurk** [comment] 2019-03-26 17:22
Thinking about this a bit more - the proper fix I have in mind will require a bit more of an invasive refactor. I think then I'm going to defer this until after v1.3 is out just so that I don't break things subtly without a good long time to stabilise.

If you want a hack fix in the meantime, this might have some side-effects but works for me at least:

```patch
diff --git a/renderdoc/driver/vulkan/vk_manager.h b/renderdoc/driver/vulkan/vk_manager.h
index 343365ba3..7abc8bce0 100644
--- a/renderdoc/driver/vulkan/vk_manager.h
+++ b/renderdoc/driver/vulkan/vk_manager.h
@@ -326,7 +326,7 @@ public:
     if(IsReplayMode(m_State))
       ResourceManager::RemoveWrapper(ToTypedHandle(Unwrap(obj)));

-    ResourceManager::MarkCleanResource(id);
+    // ResourceManager::MarkCleanResource(id);
     ResourceManager::ReleaseCurrentResource(id);
     VkResourceRecord *record = GetRecord(obj);
     if(record)
```

You'll need to grab latest - I fixed an unrelated bug which you will otherwise hit once this one is fixed.

**Comment by hrydgard** [comment] 2019-03-26 19:03
That's quite alright, thanks for the hack!

I'll leave this open then in anticipation of the refactor.

**Comment by baldurk** [comment] 2019-05-14 18:32
Finally got the proper fix for this in - it should fix the issue of descriptor sets being freed mid-frame capture, and it worked in my testing of the same thing as above. Let me know if it doesn't work for you.

**Closed as completed** 2019-05-14 18:31 UTC
Labels: Bug, Unresolved
