### ISSUE TITLE
Two captures on for a single draw to screen frame

### ISSUE THREAD

**Issue by darkyellow** [baldurk/renderdoc#1571] opened 2019-10-31 19:53 UTC
## Description

I have an application written in Java using LWJGL and GLFW. The render selected is opengl (I have a vulkan renderer which has no issues). The application renders to two frame buffers (3d and UI, both have a render buffer attached for depth) and then takes the textures and renders to default frame buffer (screen). So there are 3 frame buffers in use. I am using render doc to try and debug a uniform buffer issue so nothing actually draws at the moment because the matrixBuffer which has the mvp matrix is full of 0 data.

1) Describe what you see actually happening.

When starting my opengl application using renderdoc and setting the number of captures to 3, I am seeing renderdoc capture 2 captures when the application renders the first frame (the data is initialised before the frame is initially called). One after the GLFW window is created and one when I actually swap buffers and render something to the screen. The next capture happens after I trigger a new screen render to happen after moving the camera. Below is the log file generated by render doc for the first three captures. I added a pause after the window create code to prove the first capture came from there.

```
Log     - Got remote handshake: java [20196]
Log     - Used API: OpenGL (Not presenting & supported)
Log     - Used API: OpenGL (Presenting & supported)
31/10/2019 05:21:02.919 [DEBUG] [org.darkyellow.application.lwjgl.LwjglWindow.<init>()] Creating GLFW window via GLFW.glfwCreateWindow(800, 600, , null,null);
Log     - Got a new capture: 0 (frame 0) (time 1572542462) 8227 byte thumbnail
31/10/2019 05:21:04.920 [DEBUG] [org.darkyellow.application.lwjgl.LwjglWindow.<init>()] Slept 2 seconds
31/10/2019 05:21:04.941 [INFO ] [org.darkyellow.application.lwjgl.LwjglWindow.<init>()] Monitor [293][165] Resolution[1920][1080]
31/10/2019 05:21:05.001 [DEBUG] [org.darkyellow.viewer.Viewer.initialise()] Initialisng application : entry point
31/10/2019 05:21:05.494 [DEBUG] [org.darkyellow.viewer.Viewer$1.run()] Initialise Engine
31/10/2019 05:21:05.498 [DEBUG] [org.darkyellow.viewer.Viewer$1.run()] Building render objects
31/10/2019 05:21:05.541 [DEBUG] [org.darkyellow.viewer.Viewer$1.run()] Finished building render objects
31/10/2019 05:21:05.541 [DEBUG] [org.darkyellow.application.lwjgl.opengl.pass.GlScreenRenderPass.initialise()] *************** Initialise screen frame buffer
31/10/2019 05:21:05.541 [DEBUG] [org.darkyellow.application.lwjgl.opengl.pass.GlRenderPass.initialise()] ************* Initialising FRAME BUFFER[Canvas3d Pass][0]
31/10/2019 05:21:05.556 [DEBUG] [org.darkyellow.application.lwjgl.opengl.pass.GlRenderPass.initialise()] ************* Initialising FRAME BUFFER[Canvas UI Pass][0]
31/10/2019 05:21:05.591 [DEBUG] [org.darkyellow.application.lwjgl.opengl.pass.GlRenderPass.render()] ************* Rendering FRAME BUFFER[Canvas3d Pass][2]
31/10/2019 05:21:05.601 [DEBUG] [org.darkyellow.application.lwjgl.opengl.pass.GlRenderPass.render()] ************* Rendering FRAME BUFFER[Canvas UI Pass][3]
31/10/2019 05:21:05.602 [DEBUG] [org.darkyellow.application.lwjgl.opengl.pass.GlScreenRenderPass.lambda$render$3()] *************** Rending to Screen frame buffer
Log     - Got a new capture: 1 (frame 1) (time 1572542465) 8227 byte thumbnail
31/10/2019 05:21:06.999 [DEBUG] [org.darkyellow.application.lwjgl.opengl.pass.GlRenderPass.render()] ************* Rendering FRAME BUFFER[Canvas3d Pass][2]
31/10/2019 05:21:07.007 [DEBUG] [org.darkyellow.application.lwjgl.opengl.pass.GlRenderPass.render()] ************* Rendering FRAME BUFFER[Canvas UI Pass][3]
31/10/2019 05:21:07.009 [DEBUG] [org.darkyellow.application.lwjgl.opengl.pass.GlScreenRenderPass.lambda$render$3()] *************** Rending to Screen frame buffer
Log     - Got a new capture: 2 (frame 2) (time 1572542467) 8227 byte thumbnail

```

The first capture causes a segmentation fault in renderdoc, the second capture correctly describes the 3d frame buffer as a color pass (although it has a depth render buffer attached too), but the ui frame buffer is not under any pass in renderdoc (its orphoned). For the 3rd capture both the 3d and ui come under a single depth pass label in renderdoc (so not labelled a color pass this time) but the render to screen pass is correctly labelled as a color pass.

2) Describe what you'd expect to see instead.

I am expecting to see a single capture on the first frame because there is a single call to swap buffers and 2 more captures captured after two render commands are executed via a camera move.

## Repro steps

I can't share the application it self as its too complicated but I can share the 3 captures of an example run. I can also share the GLFW config used for creating the window. I can share specific bits of code if required

Captures - 

[java_2019.10.31_19.31.25_frame0.rdc.gz](https://github.com/baldurk/renderdoc/files/3795546/java_2019.10.31_19.31.25_frame0.rdc.gz)
[java_2019.10.31_19.31.25_frame1.rdc.gz](https://github.com/baldurk/renderdoc/files/3795547/java_2019.10.31_19.31.25_frame1.rdc.gz)
[java_2019.10.31_19.31.25_frame2.rdc.gz](https://github.com/baldurk/renderdoc/files/3795548/java_2019.10.31_19.31.25_frame2.rdc.gz)

Config - 

```
GLFW.glfwWindowHint(GLFW.GLFW_RESIZABLE, GL_FALSE);
GLFW.glfwWindowHint(GLFW.GLFW_DECORATED, GL_TRUE);
GLFW.glfwWindowHint(GLFW.GLFW_VISIBLE, GL_FALSE);
GLFW.glfwWindowHint(GLFW.GLFW_RED_BITS, value);
GLFW.glfwWindowHint(GLFW.GLFW_GREEN_BITS, value);
GLFW.glfwWindowHint(GLFW.GLFW_BLUE_BITS, value);
GLFW.glfwWindowHint(GLFW.GLFW_OPENGL_PROFILE, GLFW.GLFW_OPENGL_CORE_PROFILE);
GLFW.glfwWindowHint(GLFW.GLFW_CLIENT_API, GLFW.GLFW_OPENGL_API);
GLFW.glfwWindowHint(GLFW.GLFW_CONTEXT_VERSION_MAJOR, 4);
GLFW.glfwWindowHint(GLFW.GLFW_CONTEXT_VERSION_MINOR, 5);
```

## Environment

The RenderDoc version you are using (including the date or commit hash for nightly builds)

* RenderDoc version: v1.4 packaged with apt
* Operating System: Ubuntu 19.10 (happens on 19.04 too)
* API: Opengl (vulkan works fine)

```
OpenGL vendor string: Intel Open Source Technology Center
OpenGL renderer string: Mesa DRI Intel(R) UHD Graphics 620 (Kabylake GT2) 
OpenGL core profile version string: 4.5 (Core Profile) Mesa 19.2.1
OpenGL core profile shading language version string: 4.50
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile

```

If you need any more information I will try and provide

**Comment by baldurk** [comment] 2019-10-31 20:10
Thank you for providing more information, I'll look into this tomorrow.

Can you please explain though why you have still not used the provided issue template? It is there for a reason, both to provide structure and organisation, as well as to make it easy for me to see that you have provided the required information.

**Comment by darkyellow** [comment] 2019-10-31 20:25
Hi, re the format, sorry I thought I had followed the instructions this time. I entered the details as described below using the headings provided there.

https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues-Bugs.md

I have used the exact format as provided in the new comment so hopefully it is in the right format now.

**Comment by baldurk** [comment] 2019-10-31 20:48
The content of the report is fine but I wanted to know why you hadn't used the template in case there's something about the workflow I can improve, since it's new. I'll try to make it more clear that the template must be used, the documentation you linked explains what each section should include.

**Comment by baldurk** [comment] 2019-11-01 12:29
I only found one minor bug here, that in the frame0 capture the backbuffer size is 0x0 and that leads to creating an invalid texture. It seems that on intel mesa this causes a crash where other drivers report the error and survive. That commit fixes the behaviour so RenderDoc will ensure the texture is at least 1x1.

Other than that as far as I can tell, what is happening makes sense. You said:

> [I start] my opengl application using renderdoc and setting the number of captures to 3

Which isn't _entirely_ clear but going by the filenames it sounds like you're queueing a capture of 3 frames, starting from frame 0. Frame 0 begins when you create your first real context and ends at the first present, which looks to happen internally in glfw and produces the 0x0 empty frame. Then the next two frames are captured.

The reason that frame2.rdc is broken is a bug in v1.4 which has since been fixed as far as I'm aware. GL is a messy and ugly API, and many (most?) functions can be used for both one-time initialisation as well as regular state-setting/update, depending on how the application uses them. As an example with a VAO `glEnableVertexAttribArray` and `glVertexAttribPointer` could be called once at init time to set up the VAO, or they could be called per-drawcall with a single VAO to constantly update the parameters. In v1.4 there was a bug where if these calls were made only once but were recorded as part of a captured frame, they wouldn't then properly be recorded as 'initialisation' for subsequent frames. That's what has happened here, the calls have been captured in frame1.rdc and thus are missing for frame2.rdc leading to bad replay.

This bug was fixed in v1.5 which was released about a month ago, so if you you update to the most recent version of RenderDoc it should no longer produce bad captures or crash. Also unless you have a strong reason to capture the initialisation frames I would suggest using RenderDoc normally and capturing frames after your program has started.

**Closed as completed by baldurk** 2019-11-01 12:29 UTC
Labels: Bug, Unresolved

**Comment by darkyellow** [comment] 2019-11-01 20:08
I will grab the nightly build tomorrow to confirm the capture doesn't seg fault in frame 0

For the other issue with frame 2 I installed v1.5 manually and ran a similar test and it looked the same. Will look again in the nightly build tomorrow

BTW 1.5 seems doesn't render as well as 1.4 for me, I have a hidpi monitor which I run in a lower than max resolution and the app doesn't fit on the screen (the app window is larger than the monitor and I can't make it smaller so that it can fit). When running at the native resolution is looks different to 1.4 scale wise too.

**Comment by baldurk** [comment] 2019-11-01 20:40
FYI [here's the mesa bug I reported](https://gitlab.freedesktop.org/mesa/mesa/issues/2041).

If you're still seeing the missing FBO/VAO set up in frame 2 with v1.5 then I'll need more information on how to reproduce that. Unfortunately the capture itself alone is too late to know why the problem occurred.

Nothing changed between v1.4 and v1.5 in terms of DPI handling, that's all handled by Qt. When you say you installed it manually I guess that you mean that you ran the binary build from renderdoc.org, are you sure that it's actually a difference between v1.4 and v1.5, and not a difference between the apt package built for your distribution and the binary build built by me?

**Comment by darkyellow** [comment] 2019-11-01 20:55
Re the DPI, It is most likely is to do with the packaging, especially after you have said nothing changed between 1.4 and 1.5, but wanted to raise just in case it wasn't.

I will experiment more on the frame 2 item and see if I can provide more repeatable information

**Comment by darkyellow** [comment] 2019-11-02 07:23
Quick update, can confirm the fix for mesa bug works in the nightly, renderdoc no longer crashes when opening a capture with 0x0 back buffer

Also 1.5 does actually fix the pass  being labelled as a depth pass rather than a color pass. I had made a mistake in my testing ( I wasn't testing the same setup). Thanks for all your help
