### ISSUE TITLE
Feature suggest: Show clip distance rejection in History

### ISSUE THREAD

**Issue by darksylinc** [baldurk/renderdoc#2916] opened 2023-04-20 15:08 UTC
## Description

Situation: I met a case where geometry was missing. It didn't make any sense. According to Vertex Output, it should be there. But it wasn't there.

Here's the wireframe:

![01](https://user-images.githubusercontent.com/3395130/233408389-f77eeb41-26c0-4545-aaef-f637946e3aca.png)

**Here we see 6 quads (a 2x3 grid). However there should be 9 (it's rendered as a 3x3 grid).**

The Vertex Output was correctly showing it:

![02](https://user-images.githubusercontent.com/3395130/233406517-e5d1e3a6-f35c-40ae-bf50-66e4352352d2.png)

And if I turned on `Triangle Size (draw)` I could see the drawn triangle was bigger than the wireframe:

![03](https://user-images.githubusercontent.com/3395130/233406700-0f194270-d022-40a1-8784-e54301a77634.png)

So... where is it? Did it fail depth test? Culling? Was the Z/W outside range?
**Unfortunately, pixel history did not show the rejected triangles at all:**

![04](https://user-images.githubusercontent.com/3395130/233407580-e52cd283-1810-4643-bb3a-64a091553ae8.png)

**That's when it hit me: This draw uses gl_ClipDistance.** And it was being rejected by this, because its value was < 0.

It'd be cool if this information could be shown in pixel history to see which pixels were rejected by clip distance.

This would be a quality of life enhancement, a nice-to-have. Nothing priority.

## Environment

* RenderDoc version: 1.22
* Operating System: Linux
* Graphics API: Vulkan

**Comment by baldurk** [comment] 2023-04-20 15:49
I'm going to close this as it feels like it's more or less a duplicate of #808 (which doesn't explicitly mention pixel history but that's one aspect of a larger issue that clip/cull distances are not really debuggable at all except by manually inspecting vertex outputs).

As an aside, I thought about closing that bug in favour of this since it's better explained but that would give an unreasonable expectation of how soon it will be addressed I think.

**Closed as completed by baldurk** 2023-04-20 15:49 UTC
