### ISSUE TITLE
DX12: RenderDoc just displayed the first slice(depth) when rendering to 3D texture

### ISSUE THREAD

**Issue by GraphicsCoder** [baldurk/renderdoc#547] opened 2017-03-20 11:19 UTC
I've encountered an issue that DX12 just displayed the first slice(depth) when rendering to 3D texture such as width(32)*height(32)*depth(2).
Note: I used VS, GS and PS which aimed to set slice index as SV_RenderTargetArrayIndex in GS. But, it wouldn't work well under DX12 mode. But on the contrary, DX11 and Vulkan worked well.
Thanks!

**Comment by baldurk** [comment] 2017-03-21 14:03
I can't reproduce this bug, or I'm misunderstanding. I got a simple capture with a 3D texture that's 32x32x2 and I'm able to switch between both depth slices fine.

Can you give more information about what exactly is going wrong? Are you able to share a program or capture file that reproduces it?

**Comment by GraphicsCoder** [comment] 2017-03-24 09:47
I'm sorry for the delay feedback because of busy these days. And I've attached two versions which aimed to illustrate the issue. The first one is for the DX11 which captured well for depth info, and the other is for the DX12 which lost depth info under 3D texture. Please check the files attached.
Note: There're two render pass:
1. Render to 3D texture which would cause this isse between DX11 and DX12;
2. Target as texture.

Thanks!
[dx11_dx12_rdc.zip](https://github.com/baldurk/renderdoc/files/867413/dx11_dx12_rdc.zip)

**Comment by baldurk** [comment] 2017-04-03 23:15
Hey sorry for the delay. I think f33f9759703547db799dd90f04dd6172e6e813c1 should fix the problem.

Strangely I went back to my 32x32 and it still worked fine, although I don't know why :smile:. Either way, please check the next nightly build when you have a chance.

**Comment by baldurk** [comment] 2017-05-22 10:14
Closing this issue, it should be fixed in v0.34 which includes the above commit.

**Closed by baldurk** 2017-05-22 10:14 UTC
Labels: status: fix to be verified, type: bug
