### ISSUE TITLE
Failing to connect and reproduce OpenGL API

### ISSUE THREAD

**Issue by tyoc213** [baldurk/renderdoc#229] opened 2016-03-24 16:08 UTC
Hi there, Im using https://github.com/tomaka/glium  however I'm having some issues using render doc which I did report https://github.com/tomaka/glium/issues/1442 but in release mode it connects and shows the screen, even it capture frames if I hit F12 which I show

![glium_three](https://cloud.githubusercontent.com/assets/506234/14022809/109c4bb4-f1a7-11e5-833f-89cb072d49a8.PNG)

but when try to double click for example glClearColor the applications stop answering

![glium_quatre](https://cloud.githubusercontent.com/assets/506234/14022830/3667dce6-f1a7-11e5-804e-5b912d906514.PNG)

Here is a log that also shows when I capture different screens and after closing the captured window (not when running, dont know if this even matter, but you can see there that cant create  `simple RC
 or `replay device :(`

[renderdoc_diagnostic_file.txt](https://github.com/baldurk/renderdoc/files/188172/renderdoc_diagnostic_file.txt)

**Comment by baldurk** [comment] 2016-03-24 17:55
I can try and investigate this, it seems like something's going wrong and it's probably cascading further rather than all errors necessarily being valid.

Can you share the binaries of the `opengltut_glium` program you're capturing? So that I can reproduce the problem locally.

**Comment by tyoc213** [comment] 2016-03-24 20:25
Sure here it is in release mode

[opengltut_glium.zip](https://github.com/baldurk/renderdoc/files/188615/opengltut_glium.zip)

Maybe Later I will upload the repo so you can generate it by yourself on release and debug mode.

**Comment by baldurk** [comment] 2016-04-02 17:11
I ran into a couple of issues which might explain what you were seeing - can you try again with latest code or the next nightly build to see if you have more luck?

**Comment by tyoc213** [comment] 2016-04-04 17:32
Now when I run the capture from the launch exe, in debug mode it doesnt show the cube and on release mode the opengl app crash on startup.

**Comment by baldurk** [comment] 2016-04-04 17:43
What is the actual crash you hit in the release app? I didn't try the debug mode version but I can do that, the release mode version worked fine after my fixes for me though - maybe it varies by HW or OS.

**Comment by tyoc213** [comment] 2016-04-04 17:49
mmmm, I think it is something about timming (render doc didnt crash but the example at startup), after 3 launches I got to launch it properly and capture some of the frames, when I double click a capture and  select glDrawArrays(36) renderdoc hangs.

**Comment by baldurk** [comment] 2016-04-04 18:21
Are you able to try with different hardware, from a different IHV? To isolate if any of these issues are hw/driver bugs.

I can't explain the timing problem or intermittent crash, but the hang when selecting the drawcall might be down to the stream-out for the mesh viewer. Try closing the 'mesh output' pane right after opening RenderDoc - before capturing or loading a log. See if that makes any difference.

**Comment by baldurk** [comment] 2016-08-01 19:58
Closing this issue due to lack of info. If there's still a bug here then please provide any information you can about how to repro it and where it happens exactly.

**Closed by baldurk** 2016-08-01 19:58 UTC
Labels: status: to be verified, type: bug
