### ISSUE TITLE
Unreal Engine & RenderDoc

### ISSUE THREAD

**Issue by TheOrestes** [baldurk/renderdoc#338] opened 2016-08-25 06:11 UTC
Hi baldurk,

First of all, thanks a ton for writing such a wonderful tool which I have been using almost daily for my personal opengl project & its definitely helping me a lot. 

With UE4 though, there exists a plugin by which one can trigger start RenderDoc within the editor itself & do analysis. ( https://github.com/Temaran/UE4RenderDocPlugin ) 

However, for some reason, Renderdoc is not able to attach itself to exe generated from the project. If we start game exe created using UE4 engine by the normal way of "Capture Executable", it fails to recognize unreal window for some reason. 

As per the issues associated with UE4 plugin for renderdoc, I am planning to contact plugin author himself. However, am wondering why RenderDoc fails to gather data from an exe generated using UE4. Is this known issue? can you please somehow verify this? 

Thanks once again.

**Comment by baldurk** [comment] 2016-08-25 06:58
Does this happen for any UE4 generated project at all, or just the project you have?

I've certainly captured from packaged UE4 exes before so in principle it should work fine. Since it's free I can try downloading UE4 and testing on a simple tutorial project or something, but if you have an example of binaries that don't work, that would speed up reproducing the bug :smile:.

**Comment by TheOrestes** [comment] 2016-08-25 07:09
Wow! Thanks for the quick response. I am using Renderdoc with nvidia hair works branch for UE4.12.5. so in case you are trying at your end, please use the same version. Let me try with vanilla version of UE4.12.5. At my end . Thursday, 25 August 2016, 00:28PM +05:30 from Baldur Karlsson  notifications@github.com :

**Comment by baldurk** [comment] 2016-08-25 07:13
I just woke up!

Is that this branch? https://github.com/NvPhysX/UnrealEngine/tree/4.12.5-HairWorks1.2

**Comment by TheOrestes** [comment] 2016-08-25 07:28
To be precise, this one : https://github.com/NvPhysX/UnrealEngine/tree/HairWorks

not checked with the branch you posted.

Thanks again!

**Comment by baldurk** [comment] 2016-08-25 13:13
I built it myself and it worked OK with a generated exe. However I did have to enable "Hook into Children" when capturing if I ran the exe in the root folder (`HairWorks_Project.exe`), because for some reason that exe then invokes `Engine\Binaries\Win64\UE4Game.exe ..\..\..\HairWorks_Project\HairWorks_Project.uproject`. If you invoke UE4Game.exe with the path to the `.uproject` directly from RenderDoc, then it works OK by default.

Can you check if that's your problem?

I found a crash with `SOSetTargets` which I'm looking to fix, but since you mentioned OpenGL it might be that you haven't noticed it.

**Comment by TheOrestes** [comment] 2016-08-25 13:58
Hi Baldurk,
Thanks a lot for taking time out for looking into this issue. I will give a shot at what you suggested as soon as I have access to my machine and will revert back with the results. I am using Unreal on Windows and even I encountered a crash however that is when there is hair works asset present in the scene and when using Renderdoc plugin for Unreal( link to GitHub I have already posted). I can provide you call stack for the crash which I encountered.
Would be worth a try using Renderdoc in a level file with hair works asset present ( Hairworks branch has sample levels) in it at your end to see if it's a plugin issue or something to do with Renderdoc and Hairworks combination itself. 
As per OpenGL, that's purely for hobby project ( C++ and Opengl) and it works like a charm over there :-) 
Once again, thanks for all the help.  Thursday, 25 August 2016, 06:43PM +05:30 from Baldur Karlsson  notifications@github.com :

**Comment by baldurk** [comment] 2016-08-25 14:40
Yes I think that's the `SOSetTargets` crash I've fixed. It should be working with the next nightly build.

**Comment by TheOrestes** [comment] 2016-08-26 09:07
Hi Baldurk,
After trying nightly build, I confirm that Hairworks crash is fixed. Also, I am able to attach RenderDoc to a UE4 window with option "Hook into Children" & using "UE4Game.exe" with command line argument. 

The only thing I noticed now was the way profiler shows the data. 

![renderdoc](https://cloud.githubusercontent.com/assets/5098227/17999971/75bb13e2-6b99-11e6-99ba-5b407e61e2a8.png)

With RenderDoc plugin, I get draw call data which is well organized in terms of type of object rendered i.e. Opaque, Transparent. It also clearly shows which render call belongs to which pass. I wonder if this is intended behavior for the standalone version & RenderDoc plugin is doing something extra to sort out the data. 

In any case, after couple of usages it becomes fairly clear which call belongs to which pass, but would be good to have feature in case its missing or is this some feature that needs to be enabled using a flag? 

Regards.

**Comment by baldurk** [comment] 2016-08-26 09:13
Hey, I'm glad the issue is fixed for you! I'll close this issue then.

The labels in the event browser are not a RenderDoc-side issue - it's up to the application to provide these labels, so you'd need to look at UE4 for this. I believe this is controlled by the `GEmitDrawEvents` flag which the UE4 plugin [enables before capturing](https://github.com/Temaran/UE4RenderDocPlugin/blob/c9b4842558ad6083c3efd0381ed1fea707eac0c7/RenderDocPlugin/Source/RenderDocPlugin/Private/RenderDocPluginModule.cpp#L440-L455). There is probably a way to enable it in the standalone build, but I don't know how.

**Closed by baldurk** 2016-08-26 09:13 UTC
Labels: status: to be verified, type: bug

**Comment by TheOrestes** [comment] 2016-08-26 09:18
Thanks for the information & all the help on this one. 
Long live Renderdoc :)
