### ISSUE TITLE
Renderdoc assert on capturing Cinder Vulkan NormalMapping sample

### ISSUE THREAD

**Issue by vinjn** [baldurk/renderdoc#219] opened 2016-03-11 09:18 UTC
```C++
	// we might have work to do (e.g. debug manager creation command buffer) but
	// no queue, if the device is destroyed immediately. In this case we can just
	// skip the submit
	if(m_Queue != VK_NULL_HANDLE)
	{
		VkResult vkr = ObjDisp(m_Queue)->QueueSubmit(Unwrap(m_Queue), 1, &submitInfo, VK_NULL_HANDLE);
		RDCASSERTEQUAL(vkr, VK_SUCCESS);   // <------ hit this
	}
```

```C++
renderdoc.dll!WrappedVulkan::SubmitCmds() Line 410  C++
renderdoc.dll!WrappedVulkan::ApplyInitialContents() Line 1419   C++
renderdoc.dll!WrappedVulkan::ReplayLog(unsigned int frameID=0, unsigned int startEventID=1, unsigned int endEventID=36, ReplayLogType replayType=eReplay_WithoutDraw) Line 1854 C++
renderdoc.dll!VulkanReplay::ReplayLog(unsigned int frameID=0, unsigned int endEventID=36, ReplayLogType replayType=eReplay_WithoutDraw) Line 556    C++
renderdoc.dll!ReplayRenderer::SetFrameEvent(unsigned int frameID=0, unsigned int eventID=36, bool force=false) Line 198 C++
renderdoc.dll!ReplayRenderer_SetFrameEvent(ReplayRenderer * rend=0x0000000025ae1160, unsigned int frameID=0, unsigned int eventID=36, unsigned int force=0) Line 1564   C++
```

https://github.com/cinder/Cinder/tree/vulkan/samples/_vulkan/NormalMapping

How to repro:
* Get [NormalMapping.zip](https://github.com/baldurk/renderdoc/files/168743/NormalMapping.zip)
* Open x64 renderdoc
* Launch NormalMapping.exe from renderdoc
* Capture a frame by F12
* Quit the application
* Assert

**Comment by baldurk** [comment] 2016-03-11 09:21
Thanks for the report! Unless this is a quick fix it will probably need to wait until the week after GDC since I will have no time to investigate/bugfix while there.

**Comment by vinjn** [comment] 2016-03-11 09:35
No hurry:)
Will you have presentation at GDC?

**Comment by vinjn** [comment] 2016-04-05 10:01
Update, assert has gone.
However, the window is empty during replay.

Do you have advice on how to debug this kind of issue so that I can help resolve by myself?

**Comment by baldurk** [comment] 2016-04-05 11:16
I saw that the assert was from the device being lost which suggested something was going quite wrong but I didn't have time to investigate further. I'll check again now if the assert isn't firing, but it could be that the problem is still causing device errors just without the device lost return value.

I'm afraid I can't really give any general advice on how to debug it since I don't really know where the problem lies. I'll just need to find time to investigate in more detail.

**Comment by baldurk** [comment] 2016-04-16 18:56
I fetched cinder and built the NormalMapping sample. Testing on latest renderdoc code on nvidia, the sample seems to capture and replay correctly for me. On AMD I get a crash somewhere in loading - I need to investigate more to see whether it's buggy code on my end or not,

**Comment by baldurk** [comment] 2016-08-02 08:12
Closing for lack of info, as this seems to be working now. If you're still having problems on v0.30 re-open with more detailed repro steps and HW information.

**Closed by baldurk** 2016-08-02 08:12 UTC
Labels: status: need more info, type: bug
