### ISSUE TITLE
Android devices randomly disconnect

### ISSUE THREAD

**Issue by AndyCGYan** [baldurk/renderdoc#2291] opened 2021-06-15 08:52 UTC
## Description

Android devices would randomly disconnect, even when the device and RenderDoc are left idle.

## Steps to reproduce

- Turn off battery and background optimizations for RenderDocCmd
- Select device via "Replay Context" menu on the bottom left
- Observe

The device would disconnect randomly within seconds to minutes, resulting in "Remote server disconnected" status.

qrenderdoc log (personal/device info obfs'd):
```
RDOC 015612: [16:29:54]             core.cpp( 459) - Log     - RenderDoc v1.14 Windows 64-bit Release (50b2cecc50918e6091f4a8b0e68c0854aca636f1) loaded in replay application
RDOC 015612: [16:29:54]             core.cpp( 470) - Warning - Couldn't open socket for target control
RDOC 012468: [16:29:54]             core.cpp( 459) - Log     - RenderDoc v1.14 Windows 64-bit Release (50b2cecc50918e6091f4a8b0e68c0854aca636f1) loaded in replay application
RDOC 012468: [16:29:54]             core.cpp( 470) - Warning - Couldn't open socket for target control
RDOC 012468: [16:29:54]         settings.cpp( 460) - Log     - Loading config from D:\Users\xxx\AppData\Roaming\renderdoc\renderdoc.conf
RDOC 015612: [16:29:54]      crash_handler.h( 150) - Log     - Timer Waiting for crash handling server - 96.451 ms
RDOC 015612: [16:29:54]      crash_handler.h( 156) - Log     - Created crash-handling server \\.\pipe\RenderDocBreakpadServer46581524596
RDOC 015612: [16:29:54]      crash_handler.h(  87) - Log     - Connecting to server \\.\pipe\RenderDocBreakpadServer46581524596
RDOC 015612: [16:29:54]         settings.cpp( 460) - Log     - Loading config from D:\Users\xxx\AppData\Roaming\renderdoc\renderdoc.conf
QTRD 015612: [16:29:54]       qrenderdoc.cpp(  94) - Log     - QRenderDoc initialising.
QTRD 015612: [16:29:54]       qrenderdoc.cpp(  97) - Log     - Running as administrator
RDOC 015612: [16:29:54]    android_tools.cpp( 347) - Log     - Initialising adb using 'D:\AndroidSDK\platform-tools\adb.exe'
RDOC 015612: [16:29:54]      crash_handler.h(  51) - Log     - Re-using crash-handling server \\.\pipe\RenderDocBreakpadServer46581524596
RDOC 015612: [16:29:54]      crash_handler.h(  87) - Log     - Connecting to server \\.\pipe\RenderDocBreakpadServer46581524596
RDOC 015612: [16:29:54]     d3d11_replay.cpp( 125) - Log     - Running replay on Intel / Intel(R) UHD Graphics 630 27.20.100.8190
RDOC 015612: [16:29:54] d3d12_sdk_select.cpp( 217) - Log     - No system D3D12 runtime found at C:\Windows\system32\D3D12Core.dll.
RDOC 015612: [16:29:54]     d3d12_replay.cpp( 110) - Log     - Running replay on Intel / Intel(R) UHD Graphics 630 27.20.100.8190
RDOC 015612: [16:29:54]        vk_replay.cpp(4288) - Log     - Created device.
QTRD 015612: [16:29:54] ToolWindowManager.cpp(1544) - Warning - area parameter ignored for this type
RDOC 015612: [16:29:54]    android_tools.cpp( 321) - Log     - COMMAND: D:\AndroidSDK\platform-tools\adb.exe '-s DEVICEID root'
RDOC 015612: [16:29:54]    android_tools.cpp( 321) - Log     - COMMAND: D:\AndroidSDK\platform-tools\adb.exe '-s DEVICEID shell getprop ro.product.manufacturer'
RDOC 015612: [16:29:55]    android_tools.cpp( 321) - Log     - COMMAND: D:\AndroidSDK\platform-tools\adb.exe '-s DEVICEID shell getprop ro.product.model'
RDOC 015612: [16:29:55]    android_tools.cpp( 321) - Log     - COMMAND: D:\AndroidSDK\platform-tools\adb.exe '-s DEVICEID shell getprop ro.build.version.sdk'
RDOC 015612: [16:29:55]         streamio.cpp( 415) - Warning - Error reading from socket
RDOC 015612: [16:29:55]    remote_server.cpp(1196) - Warning - Didn't get proper handshake
RDOC 015612: [16:29:56]         streamio.cpp( 415) - Warning - Error reading from socket
RDOC 015612: [16:29:56]    remote_server.cpp(1196) - Warning - Didn't get proper handshake
RDOC 015612: [16:29:56]    android_tools.cpp( 321) - Log     - COMMAND: D:\AndroidSDK\platform-tools\adb.exe '-s DEVICEID shell getprop ro.build.version.sdk'
RDOC 015612: [16:29:56]    android_tools.cpp( 321) - Log     - COMMAND: D:\AndroidSDK\platform-tools\adb.exe '-s DEVICEID shell pm list packages org.renderdoc.renderdoccmd'
RDOC 015612: [16:29:56]    android_tools.cpp( 321) - Log     - COMMAND: D:\AndroidSDK\platform-tools\adb.exe '-s DEVICEID shell getprop ro.product.cpu.abi'
RDOC 015612: [16:29:57]          android.cpp(1006) - Log     - Starting RenderDoc server, supported ABIs:
RDOC 015612: [16:29:57]          android.cpp(1008) - Log     -   - armeabi_v7a
RDOC 015612: [16:29:57]          android.cpp(1008) - Log     -   - arm64_v8a
RDOC 015612: [16:29:57]          android.cpp( 275) - Log     - Checking installed version of org.renderdoc.renderdoccmd.arm32 on DEVICEID
RDOC 015612: [16:29:57]    android_tools.cpp( 321) - Log     - COMMAND: D:\AndroidSDK\platform-tools\adb.exe '-s DEVICEID shell pm dump org.renderdoc.renderdoccmd.arm32'
RDOC 015612: [16:29:57]          android.cpp( 316) - Log     - Installed server version (114:50b2cecc50918e6091f4a8b0e68c0854aca636f1) is compatible
RDOC 015612: [16:29:57]    android_tools.cpp( 321) - Log     - COMMAND: D:\AndroidSDK\platform-tools\adb.exe '-s DEVICEID shell am force-stop org.renderdoc.renderdoccmd.arm32'
RDOC 015612: [16:29:57]    android_tools.cpp( 321) - Log     - COMMAND: D:\AndroidSDK\platform-tools\adb.exe '-s DEVICEID shell am force-stop org.renderdoc.renderdoccmd.arm64'
RDOC 015612: [16:29:58]    android_tools.cpp( 321) - Log     - COMMAND: D:\AndroidSDK\platform-tools\adb.exe '-s DEVICEID forward tcp:38969 localabstract:renderdoc_39920'
RDOC 015612: [16:29:58]    android_tools.cpp( 321) - Log     - COMMAND: D:\AndroidSDK\platform-tools\adb.exe '-s DEVICEID forward tcp:38960 localabstract:renderdoc_38920'
RDOC 015612: [16:29:59]    android_tools.cpp( 321) - Log     - COMMAND: D:\AndroidSDK\platform-tools\adb.exe '-s DEVICEID push "D:\Users\xxx\AppData\Roaming\renderdoc\renderdoc.conf" /sdcard/Android/data/org.renderdoc.renderdoccmd.arm64/files/renderdoc.conf'
RDOC 015612: [16:29:59]    android_tools.cpp( 321) - Log     - COMMAND: D:\AndroidSDK\platform-tools\adb.exe '-s DEVICEID shell am start -n org.renderdoc.renderdoccmd.arm64/.Loader -e renderdoccmd remoteserver'
```

Filtered logcat:
```
--------- beginning of main
--------- beginning of system
06-15 16:29:59.322  9808  9808 I renderdoc: @60c8650700000001@ RDOC 009808: [16:29:59]   posix_stringio.cpp( 519) - Warning - Couldn't acquire shared lock to '/sdcard/Android/media/org.renderdoc.renderdoccmd.arm64/files/RenderDoc/RenderDoc_2021.06.15_16.29.59.log': 38
06-15 16:29:59.322  9808  9808 I renderdoc: @60c8650700000002@ RDOC 009808: [16:29:59]             core.cpp( 459) - Log     - RenderDoc v1.14 Android 64-bit Release (50b2cecc50918e6091f4a8b0e68c0854aca636f1) loaded in replay application
06-15 16:29:59.323  9808  9808 I renderdoc: @60c8650700000003@ RDOC 009808: [16:29:59]             core.cpp( 470) - Warning - Couldn't open socket for target control
06-15 16:29:59.323  9808  9808 I renderdoc: @60c8650700000004@ RDOC 009808: [16:29:59]         settings.cpp( 460) - Log     - Loading config from /sdcard/Android/media/org.renderdoc.renderdoccmd.arm64/files/renderdoc.conf
06-15 16:29:59.327  9808  9808 I renderdoccmd: Creating lock m_DrawLock
06-15 16:29:59.327  9808  9808 I renderdoccmd: Creating lock m_CmdLock
06-15 16:29:59.375  9808  9838 I renderdoccmd: android_main android_state->window: 0x0
06-15 16:29:59.377  9808  9838 I renderdoccmd: handle_cmd(10)
06-15 16:29:59.384  9808  9838 I renderdoccmd: handle_cmd(11)
06-15 16:29:59.392  9808  9838 I renderdoccmd: handle_cmd(0)
06-15 16:29:59.408  9808  9838 I renderdoccmd: handle_cmd(1)
06-15 16:29:59.408  9808  9838 I renderdoccmd: APP_CMD_INIT_WINDOW
06-15 16:29:59.408  9808  9838 I renderdoccmd: spawning command thread
06-15 16:29:59.408  9808  9838 I renderdoccmd: Trying to splash
06-15 16:29:59.408  9808  9838 I renderdoccmd: Doing a splash
06-15 16:29:59.409  9808  9840 I renderdoccmd: Entering cmd thread
06-15 16:29:59.409  9808  9840 I renderdoc: @60c8650700000005@ RDOC 009808: [16:29:59]    posix_network.cpp( 422) - Log     - Created and bind socket: 95
06-15 16:29:59.412  9808  9840 I renderdoc: @60c8650700000006@ RDOC 009808: [16:29:59]    remote_server.cpp( 986) - Log     - No whitelist IP ranges configured - using default private IP ranges.
06-15 16:29:59.412  9808  9840 I renderdoc: @60c8650700000007@ RDOC 009808: [16:29:59]    remote_server.cpp( 990) - Log     - Create a config file remoteserver.conf in ~/.renderdoc or %APPDATA%/renderdoc to narrow this down or accept connections from more ranges.
06-15 16:29:59.412  9808  9840 I renderdoc: @60c8650700000008@ RDOC 009808: [16:29:59]    remote_server.cpp( 997) - Log     - Allowing connections from:
06-15 16:29:59.412  9808  9840 I renderdoc: @60c8650700000009@ RDOC 009808: [16:29:59]    remote_server.cpp(1006) - Log     - 10.0.0.0 / 255.0.0.0
06-15 16:29:59.412  9808  9840 I renderdoc: @60c865070000000a@ RDOC 009808: [16:29:59]    remote_server.cpp(1006) - Log     - 172.16.0.0 / 255.240.0.0
06-15 16:29:59.412  9808  9840 I renderdoc: @60c865070000000b@ RDOC 009808: [16:29:59]    remote_server.cpp(1006) - Log     - 192.168.0.0 / 255.255.0.0
06-15 16:29:59.412  9808  9840 I renderdoc: @60c865070000000c@ RDOC 009808: [16:29:59]    remote_server.cpp(1010) - Log     - Allowing execution commands
06-15 16:29:59.412  9808  9840 I renderdoc: @60c865070000000d@ RDOC 009808: [16:29:59]    remote_server.cpp(1014) - Log     - Replay host ready for requests...
06-15 16:29:59.424  9808  9841 I renderdoc: @60c865070000000e@ RDOC 009808: [16:29:59]        vk_replay.cpp(4288) - Log     - Created device.
06-15 16:29:59.446  9808  9838 I renderdoccmd: Done splashing
06-15 16:29:59.446  9808  9838 I renderdoccmd: handle_cmd(6)
06-15 16:29:59.446  9808  9838 I renderdoccmd: doing misc splash
06-15 16:29:59.446  9808  9838 I renderdoccmd: Trying to splash
06-15 16:29:59.446  9808  9838 I renderdoccmd: Doing a splash
06-15 16:29:59.455  9808  9838 I renderdoccmd: Done splashing
06-15 16:30:00.699  9808  9840 I renderdoc: @60c865080000000f@ RDOC 009808: [16:30:00]    remote_server.cpp(1067) - Log     - Connection received from 127.0.0.1.
06-15 16:30:00.699  9808  9840 I renderdoc: @60c8650800000010@ RDOC 009808: [16:30:00]    remote_server.cpp(1090) - Log     - Processing connection
06-15 16:30:00.702  9808  9860 I renderdoc: @60c8650800000011@ RDOC 009808: [16:30:00]    remote_server.cpp( 237) - Log     - Returning OK signal for connection from 127.0.0.1.
06-15 16:30:00.727  9808  9840 I renderdoc: @60c8650800000012@ RDOC 009808: [16:30:00]    remote_server.cpp(1067) - Log     - Connection received from 127.0.0.1.
06-15 16:30:00.727  9808  9840 I renderdoc: @60c8650800000013@ RDOC 009808: [16:30:00]    remote_server.cpp(1090) - Log     - Processing connection
06-15 16:30:00.730  9808  9861 I renderdoc: @60c8650800000014@ RDOC 009808: [16:30:00]    remote_server.cpp( 218) - Log     - Promoting connection from 127.0.0.1 to active.
06-15 16:30:00.730  9808  9861 I renderdoc: @60c8650800000015@ RDOC 009808: [16:30:00]    remote_server.cpp( 237) - Log     - Returning OK signal for connection from 127.0.0.1.
06-15 16:30:00.735  9808  9861 I renderdoc: @60c8650800000016@ __rdoc_internal_android_logcat 349420282
...
06-15 16:30:26.423  9808  9861 I renderdoc: @60c865220000009f@ __rdoc_internal_android_logcat 349445970
06-15 16:30:26.425  9808  9861 I renderdoc: @60c86522000000a0@ RDOC 009808: [16:30:26]         streamio.cpp( 415) - Warning - Error reading from socket
06-15 16:30:26.426  9808  9861 I renderdoc: @60c86522000000a1@ RDOC 009808: [16:30:26]    remote_server.cpp( 907) - Log     - Closing active connection from 127.0.0.1.
06-15 16:30:26.426  9808  9861 I renderdoc: @60c86522000000a2@ RDOC 009808: [16:30:26]    remote_server.cpp( 909) - Log     - Ready for new active connection...
06-15 16:30:34.200  9808  9840 I renderdoc: @60c8652a000000a3@ RDOC 009808: [16:30:34]    remote_server.cpp(1067) - Log     - Connection received from 127.0.0.1.
06-15 16:30:34.201  9808  9840 I renderdoc: @60c8652a000000a4@ RDOC 009808: [16:30:34]    remote_server.cpp(1090) - Log     - Processing connection
06-15 16:30:34.203  9808  9968 I renderdoc: @60c8652a000000a5@ RDOC 009808: [16:30:34]    remote_server.cpp( 237) - Log     - Returning OK signal for connection from 127.0.0.1.
06-15 16:30:42.146  9808  9840 I renderdoc: @60c86532000000a6@ RDOC 009808: [16:30:42]    remote_server.cpp(1067) - Log     - Connection received from 127.0.0.1.
06-15 16:30:42.146  9808  9840 I renderdoc: @60c86532000000a7@ RDOC 009808: [16:30:42]    remote_server.cpp(1090) - Log     - Processing connection
06-15 16:30:42.147  9808  9970 I renderdoc: @60c86532000000a8@ RDOC 009808: [16:30:42]    remote_server.cpp( 237) - Log     - Returning OK signal for connection from 127.0.0.1.
06-15 16:30:50.099  9808  9840 I renderdoc: @60c8653a000000a9@ RDOC 009808: [16:30:50]    remote_server.cpp(1067) - Log     - Connection received from 127.0.0.1.
06-15 16:30:50.099  9808  9840 I renderdoc: @60c8653a000000aa@ RDOC 009808: [16:30:50]    remote_server.cpp(1090) - Log     - Processing connection
06-15 16:30:50.109  9808  9981 I renderdoc: @60c8653a000000ab@ RDOC 009808: [16:30:50]    remote_server.cpp( 237) - Log     - Returning OK signal for connection from 127.0.0.1.
06-15 16:31:13.295  9808  9840 I renderdoc: @60c86551000000ac@ RDOC 009808: [16:31:13]    remote_server.cpp(1067) - Log     - Connection received from 127.0.0.1.
06-15 16:31:13.295  9808  9840 I renderdoc: @60c86551000000ad@ RDOC 009808: [16:31:13]    remote_server.cpp(1090) - Log     - Processing connection
06-15 16:31:13.298  9808  9985 I renderdoc: @60c86551000000ae@ RDOC 009808: [16:31:13]    remote_server.cpp( 237) - Log     - Returning OK signal for connection from 127.0.0.1.
```

ADB server log:
```
adb I 06-15 16:29:50  6628  4896 auth.cpp:417] adb_auth_init...
adb I 06-15 16:29:50  6628  4896 auth.cpp:152] loaded new key from 'D:\Users\xxx\.android\adbkey' with fingerprint xxx
adb I 06-15 16:29:50  6628  9752 transport.cpp:299] DEVICEID: write thread spawning
adb I 06-15 16:29:50  6628 11324 transport.cpp:327] DEVICEID: read thread spawning
adb I 06-15 16:29:50  6628  4896 adb.cpp:141] DEVICEID: already offline
adb W 06-15 16:30:02  6628  4896 sockets.cpp:279] timeout expired while flushing socket, closing
adb W 06-15 16:30:36  6628  4896 sockets.cpp:279] timeout expired while flushing socket, closing
adb W 06-15 16:30:44  6628  4896 sockets.cpp:279] timeout expired while flushing socket, closing
adb W 06-15 16:30:51  6628  4896 sockets.cpp:279] timeout expired while flushing socket, closing
adb W 06-15 16:31:15  6628  4896 sockets.cpp:279] timeout expired while flushing socket, closing
```

## Environment

* RenderDoc version: 1.14 stable
* Operating System: Windows 10 x64
* Graphics API: *unrelated*
* Android device: OPPO Reno6 (ColorOS), OnePlus 8 (LineageOS)

**Comment by baldurk** [comment] 2021-06-15 12:45
I'm not able to reproduce this problem. I tried on all the android devices I have available and leaving them idle for 5 minutes each I didn't see any disconnections - I wasn't quite clear on how long since you said 'seconds to minutes' but I assume 5 minutes should have caught it.

I've also not heard any reports from anyone else with this problem so I assume the issue is something specific to your setup, and given that Android is generally very unreliable it doesn't seem to me like a RenderDoc bug.

I don't have any OPPO or OnePlus devices to test with, so it may be something specific to those devices, since some android manufacturers break their devices in different ways as there's not much guaranteed to be universally available on all Android devices. That said I did test on LineageOS on one device and I wouldn't expect it to be broken since it's usually fairly reliable.

It may be something to do with your host system, I'd suggest trying maybe a different version of adb. You could try to use the version packaged with RenderDoc which should be working. If you have a different PC you could try that would be worth testing, or even swapping the USB cable you're using.

I can leave this open for now since I can't prove it's not a RenderDoc bug, but without being able to replicate it or having a specific indication of a RenderDoc bug this seems likely to be an Android problem and so not something I can do anything about.

**Comment by AndyCGYan** [comment] 2021-06-16 07:22
I expected it to be a setup problem, I just don't know where it could be wrong...

The OnePlus device flashed to an AOSP-based OS should pretty much eliminate the background/battery traits from stock, I reckon.

The adb bundled with your Windows release worked well. I checked the version and it's from Feb 2018, circa platform-tools r27.0.1, and that reminded me of [an issue](https://community.arm.com/developer/tools-software/tools/f/armds-forum/49455/adb-connection-unstable-making-streamline-ga-almost-unusable) I had earlier with ARM's tools, also solved by switching adb version. I then tried r28.0.1 and r28.0.2, and yes similarly only up to r28.0.1 would play well. Switched to another laptop at work and same thing. I could try my personal PC later to eliminate company policy interference.

Why is this a thing though... Any pointer on tracking it down, or should I at this point just redirect it to Google instead?

**Comment by baldurk** [comment] 2021-06-16 09:11
Unfortunately I can't help with any bugs in adb, that's not anything I have control over or knowledge of. You'd need to report those bugs to Google. If changing adb version also fixed a very similar problem with a different tool that strongly suggests this is an adb bug and not a bug in RenderDoc, or possibly that you have a corrupt version of adb (or incompatible with the device? I know adb is very particular about versions and has poor version compatibility).

Since this is almost certainly not a RenderDoc bug and nothing I can do with, I'm closing this. I can only suggest that you report the bug to Google or stick with the versions of adb that you found to work.

**Closed as completed by baldurk** 2021-06-16 09:11 UTC
Labels: Bug, Need More Info
