### ISSUE TITLE
Error opening capture after capture one frame on a Android device

### ISSUE THREAD

**Issue by twotruths** [baldurk/renderdoc#1956] opened 2020-06-23 12:16 UTC
## Description

After capturing a frame on any Android devices, if I just double click on the frame, it would has error opening capture. It would work when I save it to local disk, and then open it again.

## Steps to reproduce

- Connect to a remote Android device.
- Launch any Opengles application.
- Capture a frame, then double click on it without saving to local disk.

It would report "Error opening capture", and has diagnostic log as below:
`Core PID 89284: [19:29:27] remote_server.cpp(1610) - Log - Capture open complete`
`Core PID 89284: [19:29:27] remote_server.cpp(1631) - Error - Capture open failed: File not found`

Have tried that on different machines with different Android devices. No similar problems with older versions.

## Environment

* RenderDoc version: 1.9
* Operating System: Windows 10 64bit
* Graphics API: Opengles

**Comment by baldurk** [comment] 2020-06-23 12:29
This issue does not have enough information to act on.

Your reproduction steps are entirely generic and do not give me enough information to actually reproduce the problem. It is not true that all GLES captures on all Android devices are broken. The problem is likely specific to your application, your devices, or both.

If it happens with many applications then you should provide one such application that does fail, in case the problem is application-specific. You should provide specific details about what devices you've tested, including the Android version of the device. Attach the entire diagnostic log instead of only copy and pasting two lines which give no information whatsoever.

There is also no such version of RenderDoc as 1.9, the latest version that has been released is 1.8. If you are running a nightly build or a custom build from source then it is important that you list what source commit you are running from as otherwise I can't tell what version you are running.

**Comment by baldurk** [comment] 2020-07-22 19:17
Closing due to lack of information/activity from original reporter.

**Closed as completed by baldurk** 2020-07-22 19:17 UTC
Labels: Bug, Need More Info
