### ISSUE TITLE
Color Pass appears black for pixels outside of scissor region

### ISSUE THREAD

**Issue by Masy** [baldurk/renderdoc#2986] opened 2023-07-18 09:12 UTC
## Description

Not sure if this is intentional or not, but when running a color pass that is constrained to a scissor region, all pixels outside of the scissor region appear black instead of the color that is currently stored in there.

## Steps to reproduce

- Configure everything like you would anyways
- Enable scissor test with ``glEnable(GL_SCISSOR_TEST)``
- Set a scissor region that does not cover the whole framebuffer
- call ``glClear(GL_COLOR_BUFFER_BIT)``

Capture: 
[scissor_bug.zip](https://github.com/baldurk/renderdoc/files/12078523/scissor_bug.zip)

Output of RenderDoc vs. Application:
![qrenderdoc_gTHcToGH5F](https://github.com/baldurk/renderdoc/assets/7923485/dd99ebff-f487-45e0-9437-78e61ff74340)
![GLacier_basic_ripUIWMq85](https://github.com/baldurk/renderdoc/assets/7923485/9c0608c1-1295-424f-a36d-f1041d4af453)

## Environment

* RenderDoc version: 1.27
* Operating System: Windows 10
* Graphics API: OpenGL (3.3)

**Comment by baldurk** [comment] 2023-07-19 09:46
This capture looks as expected to me, everything that is drawn within the capture shows up. Where is the rendering supposed to be for any other parts of the screen?

Are you possibly relying on previous rendering to the swapchain backbuffer in other frames to show up in unrendered regions? Since you're rendering directly to it and not rendering in the other regions. That is not supported an applications are expected to fully render to the backbuffer each time. As far as I'm aware guarantees of backbuffers remaining unmodified are not consistent or present in all APIs so relying on its contents being preserved is not something I'd recommend.

**Comment by Masy** [comment] 2023-07-19 13:09
I'm indeed relying on previously rendered frames to still be in the texture when running a color pass, that's why i was wondering why everything outside the scissor region is black. But i'm not relying on the backbuffer to stay the same, since that would cause issues with double/triple buffered windows.

The setup is as follows: The backbuffer is an RGB color buffer only. I'm rendering to a second multisampling RGB framebuffer and a multisampled RGBA framebuffer, and then bind the backbuffer and blend the two multisampled textures with a custom shader.
When rendering, only a part of the multisample framebuffers are cleared for rendering (only the widget's pane which has changed is re-rendered).

I assumed renderdoc would get the content of the texture before the color pass is starting and would display that, but i guess that's not the case.

**Comment by baldurk** [comment] 2023-07-19 13:25
Oh I see I'm sorry, I misunderstood what you were doing. The contents of non-backbuffer textures should definitely be preserved from previous frames as otherwise many applications would break - though perhaps for MSAA textures in particular that's extremely rare so this bug might not have been noticed. This texture does have previous data but it's coming through as all black, and from only a capture I can't tell why that is as whatever problem there is happened at capture time. Are you able to share your application?

As other things to check - does this only happen for multisampled textures? It's possible there's a driver bug or OpenGL limitation since it's not a good API, and it may only affect MSAA textures. Also I notice you're creating your texture as GL_RGB8. Does it work if you use GL_RGBA8 explicitly since that's the real texture format that GL_RGB8 corresponds to?

**Comment by Masy** [comment] 2023-07-19 13:58
Making the color attachments non multisampled or GL_RGBA8 both fix the issue, so the problem seems to be multisampled GL_RGB8 textures only. The output in the Application stays the same either way, apart from the missing AA.

**Comment by baldurk** [comment] 2023-07-19 14:41
It might well be an issue with GL_RGB8 on some drivers then, or a limitation of the GL API for that particular format. Since it's not a real texture format I would suggest using GL_RGBA8 in general since you are paying the cost of it anyway. If you still want me to look into the problem with GL_RGB8 though I can but I would need a reproducible test case of the application itself since I can't diagnose from the capture only.

**Comment by Masy** [comment] 2023-07-19 14:51
I'm fine with switching to GL_RGBA8. Unfortunately, the application is closed source.
I started working on the graphics library in 2019 when i just started to learn c++, so i think the source code wouldn't be any help to you either. I could try to create a proper MRE if you actucally want to try and look into the issue.

**Comment by baldurk** [comment] 2023-07-19 15:10
It's up to you really, it doesn't sound like a RenderDoc bug to me but I can't prove it. Unless I can reproduce this at capture time, I can't investigate this further. If you'd like to close the issue you can, otherwise it will stay open for a month waiting for a repro before it's closed automatically.

**Closed as completed** 2023-07-24 12:40 UTC
Labels: Bug, Need More Info
