### ISSUE TITLE
Program using std::regex crashes with "Warning - send: 111" in renderdoc

### ISSUE THREAD

**Issue by jffmichi** [baldurk/renderdoc#683] opened 2017-07-01 00:34 UTC
Hello,

I am facing a very odd bug probably related to renderdoc on linux: if i run even the simplest program that uses a std::regex in renderdoc, the program crashes when constructing the regex. This happens without any initialization or even linking to a graphics library.

the following code produces the crash:
```
#include <regex>
#include <iostream>

int main(void)
{
	std::cout << "before regex" << std::endl;
	std::regex regex("[a]");
	std::cout << "after regex" << std::endl;
	return 0;
}
```

console output:
```
qrenderdoc 
Log     - QRenderDoc initialising.
before regex
terminate called after throwing an instance of 'std::bad_cast'
  what():  std::bad_cast
Warning - send: 111
```

os: Arch Linux (4.11.7-1-ARCH)
compiler: g++ (GCC) 7.1.1 20170621
renderdoc version: v0.34 (build from ec4899ec)

thank you very much
jffmichi

**Comment by baldurk** [comment] 2017-07-03 11:23
I couldn't reproduce this on a local build but I presume when you say "build from https://github.com/baldurk/renderdoc/commit/ec4899ec72fc94886e0f350c931bc7d2f08891e8" you mean you're using the pre-packaged build from the website, rather than you compiling the code at that revision?

With that I do get the same problem. It seems like the issue is that when I statically link libstdc++ into librenderdoc.so the resulting symbols are getting exported, and that then conflicts with libstdc++ usage in the program. I'll change the build process so those symbols aren't exported, for future nightly builds and stable builds.

**Comment by baldurk** [comment] 2017-07-17 15:46
I tried various things to hide libstdc++'s symbols when statically linked but didn't have any luck. In the end I had to go to using a linker version script to whitelist the symbols I _did_ want to be visible.

Nightly builds from now on (and stable releases) should no longer cause problems with programs using new libstdc++.

**Comment by baldurk** [comment] 2017-08-14 09:29
This should be fixed in nightly builds after the commit above, as well as in the v0.90 release, at least from my testing. Let me know if you're still running into problems.

**Closed by baldurk** 2017-08-14 09:29 UTC
Labels: status: fix to be verified, type: bug
