### ISSUE TITLE
network I/O operation failed

### ISSUE THREAD

**Issue by Dual-Perception-Games** [baldurk/renderdoc#2020] opened 2020-08-20 18:03 UTC
## Description

Hi, I have just started using RD and cannot open the capture files. It seems to capture correctly and the thumbnail appears as expected but when I double click it, or when I quit the application, Instead of opening the file I get a message saying...
"Failed to open capture for replay: Network I/O operation failed.". 

I have managed to save the capture file but cannot open this either locally or remotely.

## Steps to reproduce

As above, I capture a frame, all seems well except the file just wont open. 
1. Open RD
2. Connect to Quest (succesful).
3. Launch game.
4. Timed capture (15 seconds)
5. Thumbnail appears.
6. Double click thumbnail, receive the error above.
7. RD then disconnects from the device.

As I said I'm pretty new to this and come from an artist background so the problem almost certainly rests at my end of things.

I have sent the file over in an email.

## Environment

* RenderDoc version: 1.9
* Operating System: Windows 10
* Graphics API: OpenGLES

GPU: RTX 2080TI 11gb
Driver: 27.21.14.5148
CPU: i7 9700k
RAM: 32gb

**Comment by baldurk** [comment] 2020-08-21 10:36
I can't reproduce this by opening the capture, as it loads fine on my Oculus Quest.

Are you still running the program at the time you open the capture? The quest is quite a memory constrained device and so it's easy to hit an out of memory situation, it's possible that's what is happening with you. If you're loading the capture for replay while your program is still running on the device, try closing the program first before opening the capture.

If you are still unable to open the capture even after a fresh boot of the quest and without your program running, can you attach the diagnostic log from help -> view diagnostic log? That should provide more specific information about what went wrong.

**Comment by Dual-Perception-Games** [comment] 2020-08-21 11:03
Hello,

I’ve managed to get it working though not entirely sure how. I’m just trying a few more runs with it to see if I can narrow down what was causing the issue and I’ll update both yourself and the github thread. 

What I did though was to disable every aspect of bit defender which seemed to work. However, the second time I launched RD it didn’t. I then rebooted and, even with bit defender completely active it again worked. 

I’m now launching a new build from UE4 to the quest and will try again. If that does not work I will reboot the machine and Quest and try again (so recreating this mornings success). If that works I would then suspect that there is some process running on either the quest or PC that is interfering with the process, and the fresh reboot is allowing me to run RD before that process starts.

As I said though, I come from and artist role so I may be way off with my speculations. I’ll update you with the results regardless.

Best regards and thanks.

Dave

**Comment by baldurk** [comment] 2020-08-21 11:08
Yes anti-virus/security software is almost always snake-oil that does little to protect from real threats but often causes problems with legitimate software. I guess you're not able to disable it, but if you can that's certainly worth trying.

**Comment by baldurk** [comment] 2020-09-14 14:20
Closing this issue due to inactivity, and given the above comments it being quite likely that it's not a renderdoc bug at all.

**Closed as completed by baldurk** 2020-09-14 14:20 UTC
Labels: Bug, Need More Info

**Comment by forestrf** [comment] 2021-02-24 02:53
I'm having this issue. It's as if the opening of a capture that I made on my low budget phone is too slow. After double clicking a capture, this is the log of renderdoc:

```
Core     PID  16644: [03:44:25]     android_tools.cpp(321) - Log     - COMMAND: C:\Program Files\RenderDoc/plugins/android/adb '-s ZY322FJX72 shell getprop ro.build.version.sdk'
Core     PID  16644: [03:45:42]    target_control.cpp(831) - Log     - Used API: OpenGLES (Presenting & supported)
Android  PID   3647: [04:45:42]             core.cpp(1844) - Log     - Adding OpenGLES frame capturer for 0x8BAECEC0 / 0x40229808
Android  PID   3647: [04:45:42]             core.cpp(1873) - Log     - Removing frame capturer for 0x8BAECEC0 / 0x944B7008
Android  PID   3647: [04:45:42]             core.cpp(1882) - Log     - Removed last refcount
Android  PID   3647: [04:45:42]             core.cpp(1886) - Log     - Removed active window
UI       PID  16644: [03:46:30]  PersistantConfig.cpp(627) - Warning - Got empty path from  "C:/Users/yop/Desktop/asd.rdc"
Android  PID  31460: [04:46:30]     remote_server.cpp(442) - Log     - Taking ownership of '/storage/emulated/0/Android/data/com.Nukefist.Genokids/files/RenderDoc/com.Nukefist.Genokids_2021.02.24_03.38_frame32.rdc'.
Core     PID  16644: [03:46:35]           rdcfile.cpp(262) - Log     - Opening RDCFile C:/Users/yop/Desktop/asd.rdc
Android  PID  31460: [04:46:35]     remote_server.cpp(399) - Log     - Copying file to local path '/sdcard/Android/data/org.renderdoc.renderdoccmd.arm32/files/RenderDoc/org.renderdoc.renderdoccmd.arm32_2021.02.24_03.46.rdc'.
Android  PID  31460: [04:46:39]     remote_server.cpp(421) - Log     - File received.
Android  PID  31460: [04:46:44]     posix_network.cpp(315) - Warning - Timeout of 5.000000 seconds exceeded in recv
Android  PID  31460: [04:46:44]          streamio.cpp(415) - Warning - Error reading from socket
Android  PID  31460: [04:46:44]     remote_server.cpp(907) - Log     - Closing active connection from 127.0.0.1.
Android  PID  31460: [04:46:44]     remote_server.cpp(909) - Log     - Ready for new active connection...
Core     PID  16644: [03:46:48]     android_tools.cpp(321) - Log     - COMMAND: C:\Program Files\RenderDoc/plugins/android/adb '-s ZY322FJX72 shell setprop security.perf_harden 0'
Core     PID  16644: [03:46:48]    remote_server.cpp(1570) - Log     - Opening capture remotely
Core     PID  16644: [03:46:48]               core.cpp(54) - Log     - Not enabling API validation during replay
Core     PID  16644: [03:46:48]               core.cpp(59) - Log     - Using default GPU replay selection algorithm
Core     PID  16644: [03:46:48]               core.cpp(68) - Log     - Replay optimisation level: Balanced
Core     PID  16644: [03:46:48]     win32_network.cpp(342) - Warning - recv: WSAECONNABORTED: An established connection was aborted by the software in your host machine.
Core     PID  16644: [03:46:48]          streamio.cpp(415) - Warning - Error reading from socket
Core     PID  16644: [03:46:48]    remote_server.cpp(1604) - Log     - Capture open complete
Core     PID  16644: [03:46:48]    remote_server.cpp(1608) - Error   - Error opening capture
```

I tried downloading the capture and I was able to, but it ended up the same way
Logcat shows:
```
02-24 03:44:14.435  1339  1463 W libEGL  : [ANDROID_RECORDABLE] format: 1
02-24 03:44:14.437  1038  1077 I WindowManager: window type TYPE_AOD_DREAM:
02-24 03:44:14.441  3647  3647 I SurfaceView: updateWindow -- setFrame, this = android.view.SurfaceView{afbbe97 VFE...... .F....I. 0,0-720,1280 #7f020000 app:id/unitySurfaceView}
02-24 03:44:14.447  1339  1463 D mali_winsys: EGLint new_window_surface(egl_winsys_display*, void*, EGLSurface, EGLConfig, egl_winsys_surface**, egl_color_buffer_format*, EGLBoolean) returns 0x3000
02-24 03:44:14.449   294   294 I hwcomposer: [JOB] ovl_0 is not enable, do not produce a job
02-24 03:44:14.463  1038  1077 I WindowManager: window type TYPE_AOD_DREAM:
02-24 03:44:14.467   294   294 I hwcomposer: [JOB] ovl_0 is not enable, do not produce a job
02-24 03:44:14.468  5651  5651 D PQ      : [PQ_PROT][PQCust] libpq_cust_base.so absent, libpq_cust.so OK
02-24 03:44:14.469  5651  5651 E PQ      : [PQ][PQWhiteList] libwlparser.so is absent
02-24 03:44:14.470   294  1284 I BufferQueueProducer: [StatusBar](this:0xae8f3000,id:10,api:1,p:1339,c:294) new GraphicBuffer needed
02-24 03:44:14.471  5651  5651 D FPO_MSG : fpoServiceRegister : (0, FpoAggressiveFpsStrategy)
02-24 03:44:14.471   294  1284 D GraphicBuffer: alloc, handle(0xb2383f00) (w:720 h:48 s:720 f:0x1 u:0x000b00) err(0)
02-24 03:44:14.472  1339  1463 D GraphicBuffer: register, handle(0x8fd30900) (w:720 h:48 s:720 f:0x1 u:0x000b00)
02-24 03:44:14.477   294  1648 I BufferQueueProducer: [StatusBar](this:0xae8f3000,id:10,api:1,p:1339,c:294) new GraphicBuffer needed
02-24 03:44:14.477   294  1648 D GraphicBuffer: alloc, handle(0xae6f75c0) (w:720 h:48 s:720 f:0x1 u:0x000b00) err(0)
02-24 03:44:14.478  1339  1463 D GraphicBuffer: register, handle(0x8f2e15c0) (w:720 h:48 s:720 f:0x1 u:0x000b00)
02-24 03:44:14.481  5651  5651 D FileSourceProxy: LOG enable = 0
02-24 03:44:14.482  5651  5651 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 2000 <<<<<<
02-24 03:44:14.485   294   294 D MALI    : eglCreateImageKHR:513: [Crop] 0 0 720 48  img[720 48] 
02-24 03:44:14.485   294   294 D GraphicBuffer: free, handle(0xb2383d80) (w:720 h:1280 s:720 f:0x1 u:0x000b00)
02-24 03:44:14.486   294   294 I hwcomposer: [JOB] ovl_0 is not enable, do not produce a job
02-24 03:44:14.486  1038  1077 I WindowManager: window type TYPE_AOD_DREAM:
02-24 03:44:14.492  5651  5651 D AndroidRuntime: CheckJNI is OFF
02-24 03:44:14.503   294   294 I hwcomposer: [JOB] ovl_0 is not enable, do not produce a job
02-24 03:44:14.524  1038  3515 V ActivityManager: Broadcast: Intent { act=com.google.android.gms.phenotype.UPDATE flg=0x10 pkg=com.google.android.calendar } ordered=false userid=0 callerApp=ProcessRecord{2977fc2 5664:com.google.android.calendar/u0a87}
02-24 03:44:14.528 31460  5158 I renderdoc: @6035bd7e00000f16@ RDOC 031460: [03:44:14]    posix_network.cpp( 315) - Warning - Timeout of 5.000000 seconds exceeded in recv
02-24 03:44:14.529 31460  5158 I renderdoc: @6035bd7e00000f17@ RDOC 031460: [03:44:14]         streamio.cpp( 415) - Warning - Error reading from socket
02-24 03:44:14.530 31460  5158 I renderdoc: @6035bd7e00000f18@ RDOC 031460: [03:44:14]    remote_server.cpp( 907) - Log     - Closing active connection from 127.0.0.1.
02-24 03:44:14.530 31460  5158 I renderdoc: @6035bd7e00000f19@ RDOC 031460: [03:44:14]    remote_server.cpp( 909) - Log     - Ready for new active connection...
02-24 03:44:14.650   294   294 I BufferQueue: [unnamed-294-3899](this:0xae73b000,id:3899,api:0,p:-1,c:-1) BufferQueue core=(294:/system/bin/surfaceflinger)
02-24 03:44:14.651   294   294 I BufferQueueConsumer: [unnamed-294-3899](this:0xae73b000,id:3899,api:0,p:-1,c:294) connect(C): consumer=(294:/system/bin/surfaceflinger) controlledByApp=false
02-24 03:44:14.651   294   294 I BufferQueueConsumer: [unnamed-294-3299](this:0xae73b000,id:3899,api:0,p:-1,c:294) setConsumerName: unnamed-294-3299
02-24 03:44:14.651   294   294 I BufferQueueConsumer: [NavigationBar](this:0xae73b000,id:3899,api:0,p:-1,c:294) setConsumerName: NavigationBar
02-24 03:44:14.651   294   294 I BufferQueueProducer: [](this:0xae73b000,id:3899,api:0,p:-1,c:294) setMaxDequeuedBufferCount: maxDequeuedBuffers = 2
02-24 03:44:14.651   294   294 I BufferQueueConsumer: [NavigationBar](this:0xae73b000,id:3899,api:0,p:-1,c:294) setDefaultBufferSize: width=720 height=96
02-24 03:44:14.658  1339  1339 D Surface : Surface::allocateBuffers(this=0x8fda3000)
02-24 03:44:14.658  1339  1463 D OpenGLRenderer: CanvasContext() 0x9103c940 initialize window=0x8fda3000, title=NavigationBar
02-24 03:44:14.658  1339  1463 D Surface : Surface::connect(this=0x8fda3000,api=1)
02-24 03:44:14.659   294  1301 I BufferQueueProducer: [NavigationBar](this:0xae73b000,id:3899,api:1,p:1339,c:294) connect(P): api=1 producer=(1339:com.android.systemui) producerControlledByApp=true
02-24 03:44:14.659   294   544 D GraphicBuffer: alloc, handle(0xae6f7200) (w:720 h:96 s:720 f:0x1 u:0x000900) err(0)
02-24 03:44:14.659   294   544 D GraphicBuffer: alloc, handle(0xae6f6e40) (w:720 h:96 s:720 f:0x1 u:0x000900) err(0)
02-24 03:44:14.660  1339  1463 W libEGL  : [ANDROID_RECORDABLE] format: 1
```
I don't know how much of the logcat I have to share so I took several lines before and after the recv timeout error

**Comment by baldurk** [comment] 2021-02-24 09:58
Please do not comment on old closed bugs.
