### ISSUE TITLE
Black renderbuffer and inconsistent 'Backface culled' under OpenGL

### ISSUE THREAD

**Issue by Aaron1011** [baldurk/renderdoc#2972] opened 2023-07-02 20:04 UTC
## Description

I'm running the same application as in https://github.com/baldurk/renderdoc/issues/2971, but targeting OpenGL (using the OpenGL backend of https://github.com/gfx-rs/wgpu). Every `glDrawElementsInstanced` call shows a completely black renderbuffer. However, the application runs properly under Renderdoc, and later events in the capture show a correctly-filled in renderbuffer. 

## Steps to reproduce

1. Download [this OpenGL capture file](https://drive.google.com/file/d/1J9oEnwE7t5WLlY_KlTfolnhAlEY2zujm/view?usp=sharing) and open it in Renderdoc
2. Navigate to EID 134: `glDrawElementsInstanced(36, 1)`. You'll need to expand two 'Context3D render pass tabs'
3. In the 'Texture Viewer tab', select the 'FB0' renderbuffer. Note that 'Highlight Drawcall' shows the entire texture highlighted, and 'Depth Test', 'Stencil Test', and 'Backface Cull' all highlight the entire texture in green. Also, 'Pipeline State' shows that both the depth and stencil states are set to 'Always'.
4. Right click on any pixel in the renderbuffer, and click 'History'. Note that the 'EID 134' event shows 'Backface culled', despite the entire texture passing the backface test (in fact, I disabled backface culling entirely from OpenGL).

## Environment

* RenderDoc version: Local build, commit https://github.com/baldurk/renderdoc/commit/c328c3fdf7fb3706e48a66572a6f926ba8bdae92
* Operating System: Linux
* Graphics API: OpenGL (NVIDIA GeForce RTX 3080 Ti)

**Comment by Zorro666** [comment] 2023-07-03 12:30
Hi there

Thank you for the report and capture. 

Currently working to get a system setup (Linux + nVidia GPU) to be able to load and debug the capture.

It might take a couple of weeks before can investigate this issue.

Thank you in advance

**Comment by Zorro666** [comment] 2023-07-12 08:02
Quick note to say so far have not been able to reproduce the pixel history issue. EID 134 is not included in the history. Continuing to debug the issue.

**Comment by Zorro666** [comment] 2023-07-21 16:34
Hi there,

This is looking to be a GLES limitation and not a RenderDoc bug.
From the information in the capture the API being used is GLES (not proper GL) and it was made on an Intel GPU.
The black RenderBuffer in the Texture viewer is because it is an MSAA RenderBuffer and GLES does not support reading the unresolved pixel data. GLES limitations are also affecting the Pixel History.

Replaying the capture on nVidia GPU (Windows or Linux) shows the RenderBuffer data as expected (because the nVidia driver goes beyond the GLES specification).

Windows on nVidia 
![image](https://github.com/baldurk/renderdoc/assets/39392/557e248f-ef68-4fc6-8c68-fb34939565c2)

Linux on nVidia
![image](https://github.com/baldurk/renderdoc/assets/39392/6097461e-0207-44bc-bc99-d80527ea0c1c)

This is the Linux command used to force GL to run on the nVidia GPU
`__NV_PRIME_RENDER_OFFLOAD=1 __GLX_VENDOR_LIBRARY_NAME=nvidia <PATH_TO_QRENDERDOC>`

Potential solutions to explore in your application to overcome the GLES limitation are:
* switch your application to use proper GL and not GLES API
* switch your application to use non-MSAA RenderBuffer
* switch your application to use Texture's instead of RenderBuffer's
* replay the RenderDoc captures on an nVidia GPU

I have recreated the pixel history bug (on Linux only, on Windows it is working as expected) and will be investigating that, however it might turn out to be a GLES limitation

Pixel History : Windows + nVidia
![image](https://github.com/baldurk/renderdoc/assets/39392/de483a68-9b9e-4b79-bd0f-3fffd8ed9f8e)

Pixel History : Linux + nVidia
![image](https://github.com/baldurk/renderdoc/assets/39392/0a2c5f00-42fc-41b1-83e7-9cbe1e41b2e5)

**Closed as completed** 2023-07-24 05:37 UTC
Labels: Bug, Unresolved
