### ISSUE TITLE
Floating point Texture gets viewed as Unorm

### ISSUE THREAD

**Issue by manas-kulkarni** [baldurk/renderdoc#1797] opened 2020-03-27 13:33 UTC
## Description

I have an array of 3D textures with RGBA16F format used inside a pixel shader. The first texture is viewed correctly as a floating-point texture in the Texture Viewer but the rest of them are viewed as unorm. Made sure that they all are in the PIXEL_SHADER_RESOURCE_STATE.

## Steps to reproduce
Cannot share capture but the best way to reproduce the bug is probably trying to view an array of 3D RGBA16F textures. The resource was created in RGBA16_TYPELESS format and SRV, UAV created in RGBA16_FLOAT format.

If the bug is hard to reproduce, I would suggest adding an option through which you can change the data format of the viewed texture manually.

## Environment

* RenderDoc version: 1.7
* Operating System: Windows 10
* Graphics API: D3D12
* GPU: NVIDIA GTX 1080

**Comment by baldurk** [comment] 2020-03-27 17:06
Please provide more detailed reproduction steps. Your steps at the moment only describe your problem at a high level and the purpose of repro steps is to ensure I have everything I need to be able to specifically reproduce your scenario to be able to investigate it.

If you can't share your actual capture even privately, consider constructing a test case that still shows the bug but which you can share.

**Comment by baldurk** [comment] 2020-04-24 08:36
Closing due to lack of information.

**Closed as completed by baldurk** 2020-04-24 08:36 UTC
Labels: Bug, Need More Info

**Comment by colinwackl** [comment] 2020-08-20 15:48
I also have this issue and I think the information is pretty clear. When you have a buffer of format RGBA16_TYPELESS and you are sampling in a pixel shader with an SRV of RGBA16_FLOAT, the texture viewer in Renderdoc will display the format as UNORM.

**Comment by strandborg** [comment] 2020-10-30 07:38
Here's a simple repro using Unity. See EID 1143 for a drawcall that uses the FP16 rendertexture as pixel shader input. Attempting to view that texture shows it as UNORM instead of proper floats.
[Fp16-repro.zip](https://github.com/baldurk/renderdoc/files/5463594/Fp16-repro.zip)

**Comment by strandborg** [comment] 2020-10-30 11:07
Issue is solved. Turns out that the behavior depends on the way the user navigates to the texture viewer: if you select the FP16 texture from the "Inputs" tab of the Texture Viewer, the texture format is taken from the shader resource view format, and things work as expected. However, if you go to Pipeline Stage -> Pixel Shader and click the green arrow on the resource, you'll get the underlying typeless format (which defaults to Unorm).
