### ISSUE TITLE
Wrong capture result with multi OpenGLES context on Android

### ISSUE THREAD

**Issue by qq867346668** [baldurk/renderdoc#1361] opened 2019-04-24 08:48 UTC
## Description

When i am using two opengles context in my application，i found that, opengles instructions from two context was captured in one frame.

## Repro steps

1、Android Application，one SurfaceView which create opengles context using c++,
some View，used as a button。
2、when i capture a frame, Opengl instructions not from SurfaceView are captured。
3、after i remove button views, only SurfaceView is left。The capture result is exactly matched with Opengl instructions from SurfaceView。
My english is poor， hope you can understand what i am saying.

## Environment

* RenderDoc build: 2019-4-18 nightly build.
* Operating System: Windows 7
* API: OpenGLES 2.0

**Comment by baldurk** [comment] 2019-04-24 09:10
I don't understand exactly what the problem is. RenderDoc captures all OpenGL rendering between start and end, since it's usually impossible to know which rendering goes to which window.

This usually isn't a problem since you can look at the rendering you care about, and ignore the rest. The important thing is that only you know which rendering you want.

The default behaviour is to capture from one present (`eglSwapBuffers()`) to the next present. When there are multiple windows then one window is chosen as 'active'. You can change this on android by clicking the 'cycle active window' button in the connection panel.

If your windows are rendering in alternating fashion like this, then the capture will contain the rendering for window A and the rendering for window B:

```
| Render window A frame 1  |
| eglSwapBuffers(Window 1) |
| Render window B frame 1  |
| eglSwapBuffers(Window 2) |   <-- Capture begins here
| Render window A frame 2  |   <-- Capture contains this rendering
| eglSwapBuffers(Window 1) |
| Render window B frame 2  |   <-- Capture also contains this
| eglSwapBuffers(Window 2) |   <-- Capture ends here
| Render window A frame 3  |
| eglSwapBuffers(Window 1) |
| Render window B frame 3  |
| eglSwapBuffers(Window 2) |
```

If that's what you're seeing, then this is expected behaviour and not a bug. If your windows aren't rendering in alternating fashion then you should make sure the active window contains the rendering you want to capture whenever it presents.

If your rendering is completely disconnected from window presentation, you'd need to use the [in-application API](https://renderdoc.org/docs/in_application_api.html), though I don't know how well it will work on Android since Android is a very unreliable and broken platform.

Does this explain what you're seeing? can you explain any more what the problem is?

**Comment by qq867346668** [comment] 2019-04-24 09:43
windows A is i want to capture. 

i added some log to the source, the result like this:

| eglSwapBuffers(Window A) |   <-- Start Frame Capture 
| glClear(mask)  |   <-- call from WindowA
| glBindBuffer() |   <-- call from WindowA
| glBindTexture()  |   <-- call from WindowA
| glBindBuffer() |   <-- from other window
| glDrawElements()  |   <-- call from WindowA
| eglSwapBuffers(Window A) |   <-- End Frame Capture

**Comment by baldurk** [comment] 2019-04-24 09:53
Are you rendering from both contexts at the same time on different threads? That isn't supported. RenderDoc records all GL calls in linear order without considering the thread, so it's assumed that you'll only have one thread making GL calls at a time.

**Comment by qq867346668** [comment] 2019-04-24 10:02
actually, we create a thread to make GL calls for Window A.
not sure other android native window how to use GL call, but certainly not in our thread.
maybe, that's the problem.

I've tried gapid, and it can capture my window's gl calls correctly, not affected by other window.

Will you will fix this?

**Comment by baldurk** [comment] 2019-04-24 10:25
That would explain it, if there are two threads both submitting GL commands then they will be interleaved in an incorrect manner (since it would necessity context switches between each one so they don't pollute each other's state).

I don't have any plans to support multithreaded command submission from GL, no.

**Closed as completed by baldurk** 2019-04-24 10:25 UTC
Labels: Bug, Need More Info
