### ISSUE TITLE
OpenGL: Shader patching for separable  shaders can't handle linking separate source pieces

### ISSUE THREAD

**Issue by gerddie** [baldurk/renderdoc#1622] opened 2019-11-28 18:42 UTC
## Description

When a shader program combines shaders that don't all contain a main function, then the creation of separable shader objects fails, probably because linking such shaders results in missing entry points if the shader part containing the main function is not linked too.

## Steps to reproduce

Replay this trace and see the replay fail because all attempts to create separable shaders fail: 
https://drive.google.com/open?id=1iH-5bi8VrqtBHyiAKW-GdukBTHz22EBQ

## Environment

* RenderDoc version: git head 
* Operating System: Gentoo Linux amd64 
* API: OpenGL 

Driver : mesa OpenGL renderer string: Radeon RX 580 Series (POLARIS10, DRM 3.33.0, 5.3.9-gentoo, LLVM 8.0.1)
OpenGL core profile version string: 4.5 (Core Profile) Mesa 19.1.8

**Comment by baldurk** [comment] 2019-11-28 19:31
Closing as a duplicate of #657.

**Closed as completed by baldurk** 2019-11-28 19:31 UTC
