### ISSUE TITLE
Main thread ID becomes different when running from RenderDoc

### ISSUE THREAD

**Issue by asylum2010** [baldurk/renderdoc#702] opened 2017-07-24 14:00 UTC
I would like to debug a very large program; however it always asserts that the main thread isn't what he expects it to be. Possible explanation: the program queried the main thread ID before RenderDoc hooked in, which then changed the main thread id (dunno how, dunno why).

Is there a workaround for this? Unfortunately a lot of submodules run into this assert, so I can't use the "inject" feature. It is very important because I have serious heisenbugs, which I can't solve easily...

**Comment by baldurk** [comment] 2017-07-24 14:27
This is very much dependent on your code, so I can't give a general answer to this. The problem is that some assumptions which are arguably valid/invalid depending on your point of view don't hold when RenderDoc is injected.

The way RenderDoc creates a process and injects is:

1. Create the process with `CREATE_SUSPENDED`. This means all dependent dlls etc get loaded, but the entry point doesn't run.
2. A thread is injected into the process to call `LoadLibrary("renderdoc.dll")`.
3. Inside renderdoc's DllMain, on `DLL_PROCESS_ATTACH`, I do all of my initialisation to hook etc etc.
4. The process is then resumed, and main/WinMain gets called normally.

The reason I have to do it this way is just because I obviously can't rely on any function call from the user code to initialise my library, like a normal library would.

However the downside is that this causes some behaviour you might not see elsewhere. E.g. I remember a similar problem like this happened before on someone's codebase, where they had dlls that did work inside their DllMain and assumed that would happen on the same thread that then called WinMain. However in this case, that happens for the first time on RenderDoc's temporary remote thread (2. above). This then caused the kind of thread ID problems you're seeing.

So it's not that the main thread ID is being changed, but instead the code assumes that the same thread will be used to run both `DllMain(DLL_PROCESS_ATTACH)` for global initialisers as well as `WinMain()`. Normally that's true but doesn't really have to be...

There isn't really any way to change RenderDoc's behaviour unless you compile a version that isn't designed to be injected, but instead is designed to be linked and initialised/shutdown explicitly from your code.

One possible workaround is to do something similar to the "inject" feature - in your WinMain() before you do anything else, do `LoadLibrary("renderdoc.dll")` manually. Maybe in response to a command line parameter or something. This self-injection then means your init code has run OK before renderdoc affects anything, but it still gets loaded early enough that it will be able to capture any API calls.

**Comment by asylum2010** [comment] 2017-07-24 14:32
Ok, thank you. Although other debugging tools usually replicate the OpenGL32.dll, so the application loads _that_ instead of the driver provided one. Unfortunately, most of these tools are mostly worse/useless.

**Comment by baldurk** [comment] 2017-07-24 15:24
Yeh the problem is there are a number of limitations with that method of replacing the API dll - you need one replacement for each API that might be needed and it's possible that the application will explicitly load the dll from the system path instead of relying on the dll search order. Also it breaks down if you want to support hooking child processes, since the parent process may never load any API dll before creating its children, meaning you never see them.

I'll close this issue now but if you have any further questions let me know - like I say I don't think anything can be changed on the RenderDoc side for this, but I can help you find a workaround that works for your case.

**Closed by baldurk** 2017-07-24 15:24 UTC
Labels: type: question/comment
