### ISSUE TITLE
Replay driver defaults to D3D11 on Oculus Quest

### ISSUE THREAD

**Issue by jdonald** [baldurk/renderdoc#1449] opened 2019-07-10 14:30 UTC
## Description

When replaying on Quest with Vulkan or GLES, we're finding it to incorrectly use or attempt to use the D3D11 API, due to this incomplete implementation starting in `qrenderdoc/Code/ReplayManager.cpp` line 50:

```cpp
  // TODO maybe we could expose this choice to the user?
  int proxyRenderer = -1;
```
then with proxyRenderer set to -1 and effectively proxyDriver set to unknown, downstream in
`renderdoc/core/core.cpp` lines 1108 to 1115 :
```cpp
ReplayStatus RenderDoc::CreateProxyReplayDriver(RDCDriver proxyDriver, IReplayDriver **driver)
{
  // passing RDCDriver::Unknown means 'I don't care, give me a proxy driver of any type'
  if(proxyDriver == RDCDriver::Unknown)
  {
    if(!m_ReplayDriverProviders.empty())
      return m_ReplayDriverProviders.begin()->second(NULL, driver);
  }
```

And the first driver in `m_ReplayDriverProviders` happens to be D3D11 which certainly doesn't make sense for replay on Android.

I looked through existing issues. Replay ticket #1072 on desktop could be related but I'm guessing not really.

## Repro steps

Capture a trace on Oculus Quest and attempt to replay.

## Environment

* RenderDoc 1.4

We're not using nightly due to unrelated issues, but judging from the code this problem exists on the latest trunk as well.

* Operating System: Windows 10 + Oculus Quest Android N

* API: Vulkan, GLES

We have a handful of engineers so I may have lost something in translation. Feel free to request more details if anything is missing and we'll do our best to respond and revise promptly.

**Comment by baldurk** [comment] 2019-07-10 14:43
RenderDoc uses the proxy renderer locally to display textures and meshes transferred to the device to reduce latency. That uses D3D11 by default on windows, but it could be anything. It has no relation to the API captured and replayed on the remote device - which is Vulkan or GLES in the case of Android. #1072 is not related because that's talking about selecting which GPU out of multiple GPUs to replay on, for the proxy renderer any GPU will do as long as it can present to the screen.

Can you take a few steps back and explain what the actual problem you're running into is and give more information about that and if possible how I could reproduce it, without any further analysis? I need to know what the actual bug is to help investigate the problem, the code you've pointed out is working entirely as intended.

**Comment by AitorConffx** [comment] 2019-07-11 11:27
Hi Baldur,

We are trying to get more data from the captures, and for that, we need to prepare some things before the replay driver is created on the replay device. Since the ReplayDriver is the one in charge of getting all data needed, we thought ProxyReplay was misbehaving due to choosing D3D11 instead of Vulkan for the Quest device. From your anwser, I understand that ProxyDriver is just a placeholder for displaying to pc screen what we replay on the remote device. After research on how you approach this, we found that a server/client mode, in which you install renderdoccmd on the replay device to be the server, and the pc renderdoc will be the client. To check that what I am stating is true, the server (renderdoccmd) is similar to qrenderdoc, but without the interface, so whenever we open a capture on the remote server, it will create everything needed there (replay driver, and so on).

Having in mind what we want to do, we would need to modify the apk installed in the Quest device to achieve it. However, we were unable to find were the application is compiled, and after some tests, we run into the following assert (renderdoc/android/android.cpp line 449-452):

`RDCERR(
        "APK folder missing! RenderDoc for Android will not work without it. "
        "Build your Android ABI in build-android in the root to have it "
        "automatically found and installed.");`

The issue is that it's unable to find the apk because it's not compiled nor present. We installed the release version of renderdoc and after looking through the folders, we found that you already provide the apks. My question is, how do we compile those apks for development. We are running everything from VS17.

If any other data is needed, let me know and I will try to provide it.

Thank you

**Comment by baldurk** [comment] 2019-07-11 11:40
The instructions for compiling the android build are [in the documentation](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Compiling.md#android).

I still don't know what your problem is though or what you're trying to accomplish, you're only talking in very vague terms that don't let me understand what's the actual issue. What data are you trying to get out, and why do you think that you need to prepare some things (what things?) before the replay driver is created?

The general architecture is that the UI uses the [replay API](https://github.com/baldurk/renderdoc/blob/v1.x/renderdoc/api/replay/renderdoc_replay.h) to manipulate and analyse captures (which is also exposed via the python bindings). The implementation of this handles any generic functionality like texture saving and then calls down to the [replay driver API](https://github.com/baldurk/renderdoc/blob/v1.x/renderdoc/replay/replay_driver.h) for API-specific functionality.

The replay driver API can be piped over a network to a remote machine (such as an Android device), using only the `IRemoteDriver` remotely and handling windowing and display locally with another API that implements the rest of `IReplayDriver`. This is done by serialising parameters and return data for `IRemoteDriver` over a socket and caching data locally, which is the handled by the [`ReplayProxy`](https://github.com/baldurk/renderdoc/blob/v1.x/renderdoc/core/replay_proxy.h).

**Comment by AitorConffx** [comment] 2019-07-11 13:39
The idea is to get more data from the capture regarding device specific data, in our case from Quest device. For that we need to enable the utility before the driver is created, it won't work otherwise. Similar to how AMD initializes everything needed before the device is created. The main issue was that we thought ProxyReplay was in charge of doing the replay on the remote device, and because Quest only supports Vulkan/OpenGL, having D3D11 driver made no sense and we were unaware if the TODO we found had something to do with why our implementation did not work properly. As you answered in the first comment, ProxyReplay is only used to display to pc, and you confirmed how the actual replay works for remote replays in your second comment. So as far as I know, everything was cleared out for why it did not work, and we can now proceed to change things on our side.
Thank you very much.

**Comment by baldurk** [comment] 2019-07-11 13:56
I _think_ I can close this issue now then?

If there's something else you need please open an issue clearly stating what the problem is.

**Closed as completed by baldurk** 2019-07-11 13:56 UTC
Labels: Bug, Need More Info
