### ISSUE TITLE
[Andorid] Error connecting to debugger 

### ISSUE THREAD

**Issue by MikhailGorobets** [baldurk/renderdoc#3198] opened 2024-01-03 12:29 UTC
## Description
I am encountering the following error when trying to obtain a captcha with RenderDoc on an Android device.
![image](https://github.com/baldurk/renderdoc/assets/25492259/23dc4a42-c558-4db3-9b4e-332b406b32a6)
I have followed all the steps suggested in the message to resolve the error, but it did not help.

## Steps to reproduce
1. Clone repository https://github.com/DiligentGraphics/DiligentEngine?tab=readme-ov-file#cloning
2. Build application `Tutorial01_HelloTriangle` for Android https://github.com/DiligentGraphics/DiligentEngine?tab=readme-ov-file#build_and_run_android
3. Attach the Android device by USB to PC
4. Set `USB Debugging` in developer mode on the Android device
5. Switch `USB Configuration` to `Media Transfer Protocol`
6. Connect to device from RenderDoc
7. Select the appropriate application in ExeculablePath 
8. [optional step] Paste Intent Arguments: `--es mode vk` or `--es mode gles` 
9. Start the application

## Environment

* RenderDoc version: v1.30
* Operating System: Windows 11
* Graphics API: Vulkan/GLES Android 14
* Smartphone: OnePlus 10 Pro (Android: Version 14 Security update: November 5, 2023)
* Android Debug Bridge: 34.0.5-10900879

**Comment by Zorro666** [comment] 2024-01-04 08:11
Thank you for the report. It might well be a device specific issue. 
Are you able to test on a different Android device?
Can you check that this [APK](https://renderdoc.org/jake-kart-vk.apk) works on the device (this APK is known to be debugable on Android devices)

**Comment by MikhailGorobets** [comment] 2024-01-04 08:47
@Zorro666 
The APK file runs on the device, but I can't capture the frame
Unfortunately I don't have any other devices to check.

**Comment by MikhailGorobets** [comment] 2024-01-04 09:14
@Zorro666 
UPD:
I tried to capture a frame on Huawei Nova 5t, and I succeeded on this device.

**Comment by tjr-arm** [comment] 2024-01-10 11:24
@MikhailGorobets 
> I tried to capture a frame on Huawei Nova 5t, and I succeeded on this device.

Could you clarify whether this was with your original APK or the test APK provided by Zorro666?
Separately, would you be able to share your original APK for testing? 
Many thanks

**Comment by MikhailGorobets** [comment] 2024-01-11 08:59
> Could you clarify whether this was with your original APK or the test APK provided by Zorro666?
> Separately, would you be able to share your original APK for testing?
> Many thanks

The frame capture doesn't work in RenderDoc with either Zoro666's APK or my APK file on the OnePlus 10 Pro. On the Huawei Nova 5t, frame capture works with both APK files
My original APK:
https://drive.google.com/file/d/1cMSP3sil0bOFVnPFytpeO3OHkoJy5tAb

**Comment by tjr-arm** [comment] 2024-01-11 14:49
Thank you for the info. I do not have a OnePlus on hand but have tried with an OPPO, which is their parent company - they share many quirks- but I have not been able to reproduce. It certainly looks device specific...

Could you attach Android logs around the time of a capture attempt on the OnePlus (`adb logcat` will suffice)?

This may yet be related to #3183, which is resolved in the latest nightly build. If you are able to rule out this possibility it would be helpful to our investigation  https://renderdoc.org/builds#nightly

**Comment by zhanzhanfu** [comment] 2024-01-24 02:36
I meet this problem too on K50

**Comment by baldurk** [comment] 2024-02-12 11:03
Closing this due to lack of activity from the reporter and no further information to investigate.

If you are the reporter and this bug is still a problem for you, or you are someone finding this issue and you believe this bug is still a problem and you have more information to share, please do not comment here and instead please open [a new issue](https://github.com/baldurk/renderdoc/issues/new/choose). You can reference this issue if you wish, but opening a new issue prevents confusion of accidentally linking two unrelated bugs and means that each issue can be handled in a clean process.

**Closed as completed by baldurk** 2024-02-12 11:03 UTC
Labels: Bug, Need More Info
