### ISSUE TITLE
Renderdoc Vulkan layer works, but running executable stand-alone crashes

### ISSUE THREAD

**Issue by Mercesa** [baldurk/renderdoc#769] opened 2017-10-09 13:40 UTC
As the title says, I can run the Vulkan layer, save a frame, load the frame in Renderdoc. But when trying to run renderdoc stand-alone it will throw an error that there is a read access violation at 0x0000000000000070 at the code referenced below.

Any clue on why the stand-alone might crash but the layer works perfectly?

` 
VULKAN_HPP_INLINE Result Queue::presentKHR( const PresentInfoKHR* pPresentInfo ) const
  {
    return static_cast<Result>( vkQueuePresentKHR( m_queue, reinterpret_cast<const VkPresentInfoKHR*>( pPresentInfo ) ) );
  }
`

**Comment by baldurk** [comment] 2017-10-09 14:42
I don't understand what you mean by running renderdoc stand-alone. Do you mean that your program runs fine when running with renderdoc injected, but then crashes when you run it without renderdoc?

I can't really help diagnose that, with vulkan it's easy to make a mistake with invalid code and by chance renderdoc might be doing something to work-around it - especially if it's a race or timing condition.

**Comment by Mercesa** [comment] 2017-10-09 15:22
When I have the vulkan renderdoc layer enabled. I am able to create snapshots and load these snapshots into renderdoc. When executing my application through renderdoc. It will crash on present. 

Perhaps I am doing something wrong on my end, but it would seem weird that when launching my executable through renderdoc would crash on present, however I will keep this issue updated if I find out what caused it.

**Comment by baldurk** [comment] 2017-10-09 15:31
I'm sorry I'm still not sure what the distinction is - how else do you have the renderdoc layer enabled unless you run through renderdoc? Are you setting the `ENABLE_VULKAN_RENDERDOC_CAPTURE` environment variable manually? That is basically all that renderdoc does to enable the layer so it should behave pretty much identically either way.

If you're getting a crash on present, check if your program always enables the validation layers. There's currently a [100% crash](https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/issues/2070) with the latest validation layers that gets triggered when renderdoc is active - see #755 . I don't know why that would only happen sometimes for you but it sounds similar. The smoking gun would be if the callstack indicated the crash was inside the validation layers, not at the code you pasted.

**Comment by Mercesa** [comment] 2017-10-09 15:43
Ah I see, the application crashes and the callstack shows the core validation as culprit.

Note: I am using LunarG Vulkan c++ base setup project, I am not sure if any settings/variables are specially enabled.

And to explain what I mean with running renderdoc (apologies if it doesn't make too much sense, am a bit tired)

There are two ways I can make snapshots for renderdoc

1. Enable VK_LAYER_RENDERDOC_Capture
2. It makes it able for me to make snapshots when running through visual studio
3. Look up the snapshot, open renderdoc.exe and load the snapshot

Second way

1. Open renderdoc.exe
2. Find my application.exe
3. Press launch and at present it crashes at the core validation layer (I can choose to debug my application and it points to the layer)

The weirdest part, even with core validation enabled, it will still work through visual studio. And it also won't work through the second way I described above.

**Comment by baldurk** [comment] 2017-10-09 15:52
Ohhh right, I understand now. Yes you should never enable the renderdoc layer through the layer list in  `vkCreateInstance` - that can produce unpredictable results and I've seen it crash before. Either set the `ENABLE_VULKAN_RENDERDOC_CAPTURE` variable to 1 manually, or run through renderdoc's UI. Ideally the renderdoc layer would be hidden completely from the enumerated list of layers...

It sounds like perhaps in the first method you are enabling renderdoc's layer _instead_ of the validation layers? Unless your application hits the same validation layers bug - which it doesn't sound like it is - then the crash will only happen when renderdoc's layer *and* the validation layers are enabled. So I think this is just a duplicate of #755.

**Comment by Mercesa** [comment] 2017-10-09 16:02
I am enabling renderdoc's layer WITH the validation layers, this works perfectly fine.

When using the renderdoc UI it will crash either way, it does not matter if I use the renderdoc layer or not in my instance layer list. 

And where do you set the `ENABLE_VULKAN_RENDERDOC_CAPTURE` variable? I think by enabling renderdoc's layer it -also- enables the functionality for me to use the snapshot gui

[Link to callstack screenshot](http://puu.sh/xTTsc/0b5e69a6ec.png)

[Using Vulkan layer here will enable the snapshot gui in the application](http://puu.sh/xTTwt/0bb7287fed.png)

[My application crashing using the UI](http://puu.sh/xTTzS/e353b184a2.png)

**Comment by baldurk** [comment] 2017-10-09 16:11
That's strange as there's definitely a crash if the validation layers process renderdoc's text rendering. Maybe the difference then is that when you enable it together the order of the layers change, so that renderdoc's code doesn't pass through the validation layers - like I say it's kind of unpredictable how it will function and I really don't recommend enabling renderdoc's layer manually like that. It might even vary from one run to another or based on other factors in your installation.

`ENABLE_VULKAN_RENDERDOC_CAPTURE` is an environment variable, so you can configure it in visual studio's options when debugging. I believe this will crash though as this is exactly what renderdoc's UI does to enable the layer.

With this crash there's nothing I can do about it. It's fixed on the latest github code for the validation layers, so when the next SDK ships you'll be able to run as normal. Until then the only solution I'm aware of is just to disable the validation layers in your code when running through renderdoc - it's up to you if you compile them out, or have a command-line flag or similar to temporarily disable them.

**Comment by Mercesa** [comment] 2017-10-09 16:20
Even when disabling ALL layers, it still crashes somewhere in the core validation layer when running the Renderdoc GUI. I will take a look at this another time since as of now I believe I should re-evaluate my whole application's code to ensure I am not making any mistakes myself. 

Though it is still weird the application crashes in the core validation layer when no layers are enabled in my instance.

**Comment by cnorthrop** [comment] 2017-10-09 18:58
Unrelated to your crash, but you don't need to enable `core_validation` and `parameter_validation` separately as they are already included in `standard_validation`, which is a meta-layer.  The desktop loader is filtering out duplicates for you, so they only show up once in the stack.  If you decide to run this code on Android at some point, you'll need to specify each validation layer [separately](https://developer.android.com/ndk/guides/graphics/validation-layer.html#enabling).

**Comment by Mercesa** [comment] 2017-10-09 21:39
Just to update this: Apparently, I was confused about the layers and I set up proper layer messaging now, because of this confusion I also sometimes turned the api validation in renderdoc on and off. 

Having API validation off in Renderdoc and having no debugging layers fixed my problem. And also thanks @cnorthrop for the advice, I will look more into the loader 👍

**Closed as completed** 2017-10-10 08:27 UTC
Labels: Bug, Need More Info
