### ISSUE TITLE
android feature request and a suggestion

### ISSUE THREAD

**Issue by artrointel** [baldurk/renderdoc#2962] opened 2023-06-20 06:41 UTC
## Description

AFAIK the glEGLImageTargetTexture2DOES is used in common for mobile device. Whenever I try to use the RenderDoc to capture frames for debugging with some apps, it shows,
``` 
Captures Disabled. 
Unsupported function used: 
- glEGLImageTargetTexture2DOES
```
I hope the RenderDoc can support the extension if possible. it could be best for user. But if there is a reason why some of extensions cannot be supported, RenderDoc could still capture frames for other gl data except around the texture though.
(Actually user may not interested in capturing the data for unsupported extensions like me)
Or, is there any possible work-around way to capture frames for app debugging with unsupported extensions?

## Environment

* RenderDoc version: v1.27
* Operating System: Windows
* Graphics API: GLES

**Comment by baldurk** [comment] 2023-06-20 10:39
This is a duplicate of #2726, please see that issue for more information. Your application should be checking for what extensions are available before calling their functions, as otherwise it is behaving illegally.

**Closed as completed by baldurk** 2023-06-20 10:40 UTC
