### ISSUE TITLE
Switching between outputs in Texture Viewer does not refresh the image

### ISSUE THREAD

**Issue by pszpetkowski** [baldurk/renderdoc#1566] opened 2019-10-25 16:54 UTC
## Description

There is a minor issue with switching between outputs in Texture Viewer which makes the image refresh only after performing action like selecting the output again or scrolling to zoom in/out. I hope reproduction steps are clear enough, if not I'll edit the issue with recording. I'd consider fixing it myself, but I'm really not familiar with the renderdoc codebase and not that great with C++ / Qt, hence it would take ages for me to submit a MR.

## Repro steps

1. From `Launch Application` tab choose `/usr/bin/vkcube` (installed with `vulkan-tools`) as executable path and other fields can be left with default values (you can also queue capture of few frames and skip step 3).
2. Click the Launch button.
3. Capture some frames.
4. Close the `vkcube` window and activate one of the captures by double click.
5. Go to `Texture Viewer` tab and click on `Colour Pass` at `Event Browser`.
6. Double click `Swapchain Image` and `2D Depth Attachment` at `Outputs` tab.
7. Switch between `2D Depth Attachment` and `Swapchain Image` couple of times and you should notice that the image does not refresh unless you zoom in/out with scroll or click the appropriate image in `Outputs` tab a few times.

## Environment

* RenderDoc build: from 1.5 tarball 
* Operating System: Arch Linux / GNOME / Wayland / Mesa 19.2.2
* API: Vulkan
* apiVersion     = 0x401066  (1.1.102)
* driverVersion  = 79699970 (0x4c02002)
* vendorID       = 0x8086
* deviceID       = 0x5916
* deviceType     = INTEGRATED_GPU
* deviceName     = Intel(R) HD Graphics 620 (Kaby Lake GT2)

**Comment by baldurk** [comment] 2019-10-25 17:28
Having a video recording of exactly what you're seeing would definitely be helpful. I can't repro the problem but it might be fairly system-specific so my system might not be close enough to yours.

Can you clarify something in your repro steps:

> 6. Double click `Swapchain Image` and `2D Depth Attachment` at `Outputs` tab.
> 7. Switch between `2D Depth Attachment` and `Swapchain Image` couple of times and you should notice that the image does not refresh unless you zoom in/out with scroll or click the appropriate image in `Outputs` tab a few times.

When you double click the outputs in 6, you open new locked tabs of those textures. When you say "Switch between [the images]" on step 7, do you mean changing between the tabs, or do you mean that you then go back to the 'current' tab and switch between the active output there by single clicking on the thumbnails?

If you _are_ switching between tabs I could see there being a bug lurking on some systems, though whether it's RenderDoc side or system side I don't know. I only create one output widget and I re-parent it between the tabs if you switch (since the output is fairly expensive so I don't want to create one per tab). It would be interesting to know if you get the same results if you use the 'current' tab and select between the color and depth outputs.

I also notice that you're using Wayland. I've found wayland to be extremely buggy and unreliable, so I would not be surprised at all if this is a wayland bug. It's also not natively supported by RenderDoc. Can you try using normal X.org and see if you still get the same problem following the same steps?

**Comment by pszpetkowski** [comment] 2019-10-25 20:58
Just the quick update, it's definitely not Wayland specific - I have just tried it out under x11 and the problem is exactly the same. I'll post recording of reproduction process tomorrow. I'll also try it out with other environment like KDE, sway and i3.

**Comment by pszpetkowski** [comment] 2019-10-30 22:19
Right, so I finally had time to get back to this. I've attached gif from recording of what's happening here - hopefully it's enough to understand the problem.

![repro_bug](https://user-images.githubusercontent.com/18597734/67903374-a8963700-fb6b-11e9-8c9b-1dd696479cb1.gif)

**Comment by baldurk** [comment] 2019-10-31 10:43
I understand the problem better now but unfortunately I still don't know what could be causing that. My best guess is still some weird window system/driver related issue if it hasn't been reported as more widespread.

It does look like something goes wrong when the window is reparented, but there will be multiple paint events after the reparent which force a re-display and re-present after switching tabs (and that seems to work fine on other OSs or on my tests on linux).

Are you able to test on a different GPU vendor, e.g. NV or AMD with the same system? Or did you have any luck with testing on other windowing environments than GNOME? It's also worth testing to see if this happens on GL or not, that might narrow down the problem if it's Vulkan-specific.

**Comment by baldurk** [comment] 2019-11-29 14:03
Closing this due to lack of information. Without being able to repro the bug and know that it's a RenderDoc bug and not a window system/environment bug, I need enough to track down the problem some other way or narrow down the specific scenario where it can reproduce.

**Closed as completed by baldurk** 2019-11-29 14:03 UTC
Labels: Bug, Need More Info
