### ISSUE TITLE
Launch Application error - BadMatch (invalid parameter attributes)

### ISSUE THREAD

**Issue by rythmkraze** [baldurk/renderdoc#802] opened 2017-11-14 06:28 UTC
Trying to launch an OpenGL4.5 application on Linux, I receive the following error

```
bin 🡒  sudo ./qrenderdoc 
Log     - QRenderDoc initialising.
Warning - adbExePath not set, attempting to call 'adb' in working env
Log     - COMMAND: adb devices
X Error of failed request:  BadMatch (invalid parameter attributes)
  Major opcode of failed request:  155 (GLX)
  Minor opcode of failed request:  34 ()
  Serial number of failed request:  139
  Current serial number in output stream:  137
Warning - send: 111
```

**Comment by baldurk** [comment] 2017-11-14 08:52
You definitely shouldn't run qrenderdoc as root. I'm not too familiar with X but I think that might be a permissions problem.

**Comment by rythmkraze** [comment] 2017-11-14 10:13
Thanks for the quick response. 
Was running qrenderdoc as root to ensure that the error was not due to lack of user permissions. Also the user interface is different(nicer looking) while running as root.

Could you please point me in the right direction to troubleshoot this issue?

**Comment by baldurk** [comment] 2017-11-14 10:21
RenderDoc's code doesn't change the UI at all as root, so that sounds like something with your distro's setup, I can't help with that.

Can you give more information about what's happening:
* Upload somewhere the full output log (you can find it in /tmp/RenderDoc).
* Explain exactly what happens before the crash - e.g. does the target program crash, or are you able to run and capture successfully, and it crashes when loading the capture in qrenderdoc?
* Are you able to share your program, or the capture file?
* What distribution and graphics driver are you using?

**Comment by rythmkraze** [comment] 2017-11-14 13:39
- `/tmp/RenderDoc/` is empty
- `qrenderdoc` simply fails at the very first step to launch the target program and prints the following message. There is nothing to capture since the target program is never launched. Here's the command line version to simplify troubleshooting.

```
bin 🡒  ./renderdoccmd capture $GOPATH/src/bitbucket.org/rythmkraze/opengl/indexedcube/indexedcube
Launching '/home/rkanchan/go/src/bitbucket.org/rythmkraze/opengl/indexedcube/indexedcube'
X Error of failed request:  BadMatch (invalid parameter attributes)
  Major opcode of failed request:  155 (GLX)
  Minor opcode of failed request:  34 ()
  Serial number of failed request:  136
  Current serial number in output stream:  134
Launched as ID 38920
```
- Here's the link to the [target program binary](https://drive.google.com/open?id=11EYb5CYVQqscIotey98LkoDFVlnKOFR4). Its a simple example from an opengl book.

- Graphics Driver
```
Vendor:  Intel Open Source Technology Center
Version:  4.5 (Core Profile) Mesa 17.0.7
Renderer:  Mesa DRI Intel(R) Kabylake GT2 
```
- Operating System
```
Distribution: elementary OS 0.4.1 Loki
Built on: Ubuntu 16.04.3 LTS
Kernel: Linux 4.10.0-38-generic
Arch: x86_64
```

Thanks in advance. Let me know if you need anything else.

**Comment by rythmkraze** [comment] 2017-11-15 19:26
Hey Baldur. Did you get a chance to look into the info provided?

**Comment by baldurk** [comment] 2017-11-15 19:38
Not yet. My best guess right now is that it's the crashing in the vendor checks that create a secondary context to check implementation variances, as mesa has choked on those in the past. But until I can reproduce it I can't tell if it's a mesa bug or my bug. Intel isn't as convenient for me to test with, so I'm going to look at it once I'm done with the feature I'm currently working on.

I try to be quick about investigating bugs but I don't promise turnaround within 24 hours or anything.

**Comment by rythmkraze** [comment] 2017-11-15 19:47
Just wanted to check whether you were able to replicate the issue or not and that you have all the info that you've asked for, that's all :) Not trying to hurry you up. Thanks for responding though.

**Comment by baldurk** [comment] 2017-11-17 12:25
I've just tried to repro this but I'm not having much luck. I don't have the exact same system, my hw is `Mesa DRI Intel(R) HD Graphics 6000 (Broadwell GT3)` but I matched mesa version 17.0.7 exactly.

I wasn't able to run your sample, it quit out with:

```
panic: open indexedcube.vs.glsl: no such file or directory

goroutine 1 [running, locked to thread]:
bitbucket.org/rythmkraze/opengl/glh.LoadShader(0x549a1f, 0x13, 0x0, 0x0)
	/home/rkanchan/go/src/bitbucket.org/rythmkraze/opengl/glh/shader.go:105 +0xb3
main.main()
	/home/rkanchan/go/src/bitbucket.org/rythmkraze/opengl/indexedcube/indexedcube.go:31 +0xe9
```

Which seems like straightforward missing assets, but I couldn't find where they might be online.

On the assumption that it is something to do with the vendor checks, I've pasted an experimental patch below. Can you checkout the repository and build the tip of the `v0.x` branch with this patch applied, and then try again?

Also this time I definitely need to get the debug log. It will be in `/tmp/RenderDoc` but if you look there after closing the program down it will have been cleaned up. The log is created when `qrenderdoc` starts up, and any launched applications write into the same log file. When `qrenderdoc` closes normally it will delete the log file, so if qrenderdoc isn't crashing then you have to fetch the log before closing the program.

----

```patch
diff --git a/renderdoc/driver/gl/gl_common.cpp b/renderdoc/driver/gl/gl_common.cpp
index 1a7c647..f8e850a 100644
--- a/renderdoc/driver/gl/gl_common.cpp
+++ b/renderdoc/driver/gl/gl_common.cpp
@@ -452,6 +452,8 @@ void DoVendorChecks(const GLHookSet &gl, GLPlatform &platform, GLWindowingData c
 {
   const char *vendor = "";
 
+  RDCLOG("Begin DoVendorChecks");
+
   if(gl.glGetString)
     vendor = (const char *)gl.glGetString(eGL_VENDOR);
 
@@ -735,6 +737,8 @@ void DoVendorChecks(const GLHookSet &gl, GLPlatform &platform, GLWindowingData c
           "Reading from the packed depth-stencil buffers using glReadPixels is not supported "
           "(GL_NV_read_depth_stencil)");
   }
+
+  RDCLOG("End Vendor Checks");
 }
 
 const GLHookSet *GLMarkerRegion::gl;
diff --git a/renderdoc/driver/gl/gl_hooks_linux.cpp b/renderdoc/driver/gl/gl_hooks_linux.cpp
index 648213f..0e73eff 100644
--- a/renderdoc/driver/gl/gl_hooks_linux.cpp
+++ b/renderdoc/driver/gl/gl_hooks_linux.cpp
@@ -175,6 +175,21 @@ public:
 
         if(fbcfg)
         {
+          {
+            // Choose FB config with a GLX_VISUAL_ID that matches the X screen.
+            VisualID visualid_correct = DefaultVisual(share.dpy, DefaultScreen(share.dpy))->visualid;
+            for(int i = 0; i < numCfgs; i++)
+            {
+              int visualid;
+              glXGetFBConfigAttrib(share.dpy, fbcfg[i], GLX_VISUAL_ID, &visualid);
+              if((VisualID)visualid == visualid_correct)
+              {
+                fbcfg[0] = fbcfg[i];
+                break;
+              }
+            }
+          }
+
           ret.wnd = glXCreatePbufferProc(share.dpy, fbcfg[0], pbAttribs);
           ret.dpy = share.dpy;
           ret.ctx =
diff --git a/renderdoc/driver/gl/gl_replay_linux.cpp b/renderdoc/driver/gl/gl_replay_linux.cpp
index f534bc0..4e07a0d 100644
--- a/renderdoc/driver/gl/gl_replay_linux.cpp
+++ b/renderdoc/driver/gl/gl_replay_linux.cpp
@@ -173,6 +173,21 @@ ReplayStatus GL_CreateReplayDevice(RDCFile *rdc, IReplayDriver **driver)
     return ReplayStatus::APIInitFailed;
   }
 
+  {
+    // Choose FB config with a GLX_VISUAL_ID that matches the X screen.
+    VisualID visualid_correct = DefaultVisual(dpy, DefaultScreen(dpy))->visualid;
+    for(int i = 0; i < numCfgs; i++)
+    {
+      int visualid;
+      glXGetFBConfigAttrib(dpy, fbcfg[i], GLX_VISUAL_ID, &visualid);
+      if((VisualID)visualid == visualid_correct)
+      {
+        fbcfg[0] = fbcfg[i];
+        break;
+      }
+    }
+  }
+
   GLXContext ctx = NULL;
 
   // try to create all versions from 4.5 down to 3.2 in order to get the
```

**Comment by rythmkraze** [comment] 2017-11-18 10:26
- My bad that I gave you a binary depending on external assets. [Here](https://drive.google.com/open?id=1TNst3I19kd9EjwZJX2ax5k-yBVSZh-Nf) is another binary without any dependencies. 
- I failed to build the v0.x branch due to a missing module `No package 'xcb-keysyms' found` which I was unable to install. Will try again in sometime.
- Based on your instructions I gathered the debug log and have pasted it below

```
simpleclear 🡒  cat /tmp/RenderDoc/RenderDoc_2017.11.18_15.37.56.log 
RDOC 026281: [15:37:56]             core.cpp( 318) - Log     - RenderDoc v0.91 x64 Release (2d8b2cf818746b6a2add54e2fef449398816a40c) loaded in replay application
QTRD 026281: [15:37:56]       qrenderdoc.cpp(  61) - Log     - QRenderDoc initialising.
RDOC 026281: [15:37:56]     entry_points.cpp( 619) - Warning - adbExePath not set, attempting to call 'adb' in working env
RDOC 026281: [15:37:56]     entry_points.cpp( 591) - Log     - COMMAND: adb devices
RDOC 026289: [15:38:04]             core.cpp( 318) - Log     - RenderDoc v0.91 x64 Release (2d8b2cf818746b6a2add54e2fef449398816a40c) capturing application
RDOC 026289: [15:38:04]   posix_libentry.cpp(  79) - Log     - Loading into /home/rkanchan/go/src/bitbucket.org/rythmkraze/opengl/simpleclear/simpleclear
RDOC 026289: [15:38:04]        gl_common.cpp( 406) - Log     - Vendor checks for 0 (Intel Open Source Technology Center / Mesa DRI Intel(R) Kabylake GT2  / 4.5 (Core Profile) Mesa 17.0.7)
RDOC 026289: [15:38:04]      gl_emulated.cpp(1567) - Log     - Emulating EXT_direct_state_access
RDOC 026281: [15:38:04]    posix_network.cpp( 139) - Warning - send: 111
```

**Comment by baldurk** [comment] 2017-11-18 10:59
OK, I'll check the binary on Monday but my expectation is that it's something system-level not application-level, so it might not make a difference.

The log you pasted seems to bear out that it's crashing in the vendor checks, or at least that's order of prints. When you get it compiling I've added more explicit prints around the checks so we'll see for sure. I don't know about your distro but it seems to be ubuntu based, so you could try installing `libxcb-keysyms1-dev` to get xcb-keysyms. There's a full ubuntu apt-get line in `CONTRIBUTING.md`.

**Comment by baldurk** [comment] 2018-03-06 16:00
Without more information I can't investigate this bug any further, so I'm closing this issue. If you have any more to add then please comment here.

**Closed as completed by baldurk** 2018-03-06 16:00 UTC
Labels: Bug, Need More Info
