### ISSUE TITLE
XIO:  fatal IO error 2 (No such file or directory) since 0.90

### ISSUE THREAD

**Issue by newincpp** [baldurk/renderdoc#780] opened 2017-10-22 12:31 UTC
I just got the new version of renderdoc (0.91) and it crash at startup with this error:
```
Log     - QRenderDoc initialising.
Warning - adbExePath not set, attempting to call 'adb' in working env
Log     - COMMAND: adb devices
Warning - The X11 connection broke: Maximum allowed requested length exceeded (code 4)
XIO:  fatal IO error 2 (No such file or directory) on X server ":0.0"
      after 422 requests (418 known processed) with 0 events remaining.
```
First I thought it was problem with my distros configuration but every other graphical program (with QT or not) are working well. So I tried with 0.90 and I get the same error.

Then I tried with 0.34 and everything is working fine.
here is an (edited) strace: https://gist.githubusercontent.com/newincpp/c9c325f62b6036cb7a04a6cb6cf8bb9e/raw/cd6308f31aee090cd309d62267b6a749493a1046/gistfile1.txt

**Comment by baldurk** [comment] 2017-10-22 13:03
I honestly have no idea what to make of this. I've not seen anything like this and I don't really know what the error message even corresponds to (since X11 is several layers of wrapping below any code I write).

An uneducated google search for the error message suggests it might be an X11 bug when dealing with large icons ([1](https://stackoverflow.com/questions/23901229/why-does-qt-crash-when-loading-a-window-icon), [2](https://bugs.launchpad.net/ubuntu/+source/calibre/+bug/1619859)). It fits the timeline, as some of the icons and images did change between 0.34 and 0.91. Maybe it's been fixed in X11 since then, which is why I haven't heard it reported - perhaps you can update your X11 version?

Are you running the binary versions or compiling it yourself? If you're not, try running a locally-built version in case that makes any difference.

Otherwise I don't really know what I can suggest. I can't find out more about the problem if I can't reproduce it, and if it turns out to be an X11 bug then there's not much I'm able to do. All I can recommend is you try to investigate further to see if you can isolate more precisely what the problem is - either by debugging to find out exactly the call that fails and where it comes from, or binary chopping to see which commit started the problems.

**Comment by newincpp** [comment] 2017-10-22 15:03
I tried with 0.90 0.91 in binary and a compiled locally just before opening this issue. all of them have the issue.
I have X11 1.19.3 (which is very recent).
I just tried with another PC with the same distros and X11 1.19.3 and it doesn't have the problem which is very weird.
Now that you are pointing that's a X11 bug I must that I'm on the git version of the X11 driver of amdgpu and the amd branch of the linux kernel which can cause some problems.
I have no time to investigate now but I may find some time next week.

If you can point any file/line where you think I should begin my investigation, that can be very helpful.

**Comment by baldurk** [comment] 2017-10-22 18:54
If it's PC specific that does suggest something else is going wrong. Continuing the assumption that it's icon-size related, do you have DPI or UI scaling enabled that might make Qt create SVG resources at a higher resolution maybe?

I can't point to any file/line just because like I say I don't know how that error corresponds to anything I do. You can look at the history on `qrenderdoc/Resources/` and `qrenderdoc/Code/Resources.*` which should capture most of the changes to the icon files, if it is related to that. If it's something else then I don't know where to begin.

**Comment by newincpp** [comment] 2017-10-22 20:22
I don't have any DPI or UI scaling but I have 4 screen that try to clone my main screen (1920x1080) while none of them can (they are just displaying part of it). Now that you are pointing this, it looks like it can be the source of some X11 problem that looks like this.
What is strange though is that if this strange setup is generating the problem at the X11 level I don't understand why renderdoc is the only program that have the problem. maybe I was unlucky and the problem just showed up with renderdoc ? =/
(unfortunately renderdoc is also the program I use the most with my terminal...).

**Comment by baldurk** [comment] 2018-03-06 15:57
Without some ability to reproduce the bug or more direct information about a bug in renderdoc's code, I can't investigate this bug any further, so I'm closing this issue now. If you have any more to add then please comment here.

**Closed as completed by baldurk** 2018-03-06 15:57 UTC
Labels: Bug, Need More Info
