### ISSUE TITLE
[Vulkan] Trying to use buffer device address results in DEVICE_LOST

### ISSUE THREAD

**Issue by Vincent-P** [baldurk/renderdoc#2199] opened 2021-03-07 10:57 UTC
## Description

I am trying to integrate Buffer Device Addresses into my renderer but Renderdoc doesn't work.
When I launch my application, it stops immediately and Renderdoc reports device lost errors in its own code.
I am actually not sure if the problem is within my code, Vulkan Memory Allocator or Renderdoc...

## Steps to reproduce

In my renderer the device lost happens when I enable device addresses in the VmaAllocatorCreateInfo struct.
I managed to make a simpler example here: https://gist.github.com/Vincent-P/23870603e844ecfcd2a074c317945077.
In the gist I create two resources: a regular image and buffer with device address. It seems that renderdoc triggers a device lost when the image is created. There is no device lost when creating only a buffer.
If the example is too simple It also happens with vulkan-tutorial.com's triangle code if you add a VMA allocator and an image creation.
EDIT: Also device_lost with https://github.com/KhronosGroup/Vulkan-Samples/tree/master/samples/extensions/buffer_device_address so there must something wrong with Renderdoc or my setup.

## Environment

* RenderDoc version: master - d10baafbbaa28e0fe56f5d7f1012cb39876891b7
* Operating System: Windows 10 Pro
* Graphics API: Vulkan 1.2
* Radeon Adrenalin: 21.2.3
* GPU: RX 5700 XT

**Comment by baldurk** [comment] 2021-03-07 12:02
I can't repro this unfortunately but I suspect it's a driver bug, as there have been issues with buffer device address on AMD. On my NV setup the program runs without error and I can load the capture. I only have access to an RX 480 at the moment since the 5700XT I have is too big to fit in my desktop test machines, and surprisingly even on latest drivers the RX 480 doesn't provide `bufferDeviceAddressCaptureReplay` so `bufferDeviceAddress` isn't supported when capturing in RenderDoc.

If you can test this on NV you could confirm it on your side. Otherwise I'll contact AMD to see if they can test it, or when I'm able to use my 5700XT again I can test it myself.

**Comment by Vincent-P** [comment] 2021-03-07 12:27
`bufferDeviceAddressCaptureReplay` is available with the RX 5700 XT.
I don't have others GPU to test unfortunately...

**Comment by baldurk** [comment] 2021-03-19 16:40
I've been able to reproduce this on my 5700 XT finally, but I can't see anything that's wrong so it seems like a driver bug. Unfortunately my contact at AMD has been unable to reproduce the crash on the same GPU, but they are going to look into it further.

Since this seems like a driver issue still though I'm going to close the issue, as I can't find any way of producing a workaround either. There are other outstanding issues with buffer device address that I'm aware of on recent AMD drivers which is why RenderDoc currently disables its use of the extension, so I can only suggest trying to get a different GPU (quite difficult right now) or making do without RenderDoc or the extension (either or).

**Closed as completed by baldurk** 2021-03-19 16:40 UTC
Labels: Bug, Need More Info

**Comment by Vincent-P** [comment] 2021-03-19 17:22
Thanks for you answer!

**Comment by Vincent-P** [comment] 2021-03-22 18:15
Is it possible to disable buffer device capture to work around this issue?
I tried to force `bufferDeviceAddressCaptureReplay` to false both in my code  and in `vk_device_funcs.cpp` but it seems that Renderdoc just assumes that the driver supports capture?

**Comment by baldurk** [comment] 2021-03-22 18:17
No it's not possible, without proper capture/replay of the device addresses the frame capture would crash on load. RenderDoc adds the necessary flags to capture and replay device addresses automatically and there's no way to prevent this.

**Comment by baldurk** [comment] 2021-03-24 09:45
One update from AMD, it seems that enabling RGP integration in the settings (under the 'core' section) avoids the crash at least for this repro case and I've confirmed that I see the same thing. It's unknown why and they're still investigating the bug itself.

**Comment by Vincent-P** [comment] 2021-03-24 17:29
It indeed works in the simple case I've linked before (creation of image and buffer).
But it fails in my second test which is vulkan-tutorial.com's triangle code with the creation of the image and buffer before the main loop. (https://gist.github.com/Vincent-P/0594e57916ba4c025b289c8a04daf389#file-renderdoc_vk_bufferaddress_device_lost_2-cpp-L139)

The application starts correctly but when I press F12 to capture a frame the application stops.
Here is the error in the diagnostic log using Renderdoc v1.12:
```
Core 30624 18:23:45 vk_core.cpp(290) Error Assertion failed: '(vkr) == (VK_SUCCESS)' (vkr=VK_ERROR_DEVICE_LOST, VK_SUCCESS=VK_SUCCESS)
```

**Comment by Cazadorro** [comment] 2021-11-17 16:57
I have a GTX 970, it appears render doc fails for me too because of this (also says device lost).  This is despite code that works otherwise.  It appears merely doing the bare minimum work with buffer_device_address completely causes renderdoc to be inoperable.  We can't use renderdoc anymore for any of our workloads due to how pervasive buffer_device_address is.

**Comment by baldurk** [comment] 2021-11-17 17:01
Please do not comment on old closed issues. If you have a bug, file a new issue and fill out the template appropriately with a reproducible test case.
