### ISSUE TITLE
Crash or corrupted output when saving 3d volume texture mip level

### ISSUE THREAD

**Issue by sebbbi** [baldurk/renderdoc#359] opened 2016-09-15 09:26 UTC
3d volume texture "Save Selected Texture" seems to use selected slice index directly when saving mip levels. Visualization and UI use (slice >> mip) when accessing mip data.

For example when I select mip 1, RenderDoc saves slice * 2. For mip 2, it saves slice * 4, etc. RenderDoc crashes if the slice index overflows the available slices on that particular mip level. No file is generated in this case.

**Comment by sebbbi** [comment] 2016-09-15 09:30
(multiply symbols were missing in bug description, added spaces on both sides to fix)

**Comment by baldurk** [comment] 2016-09-15 15:54
I found a few different bugs and bad behaviours here while looking into this. There were some bugs with handling mips of 3D textures properly, but I also changed the UI so that when you pick a different 3D texture mip, it updates the list of slices to be appropriate for that mip level. Makes things more intuitive.

You can either build your own copy of RenderDoc, or check out the next nightly build which will include these changes. Please let me know if it fixes it for you, I'll close this with the next stable build unless there's anything else.

**Comment by sebbbi** [comment] 2016-09-16 11:33
Tried the nightly build. Unfortunately the mip visualization of 3d textures is now completely broken. It seems that the UI is always showing the upper corner of mip 0 (smaller and smaller region as you increase mip).

**Comment by baldurk** [comment] 2016-09-16 11:39
Hmm, I ran some simple test cases on all three APIs and they seemed to display and save the textures OK. Do you have a capture or program that you can share that shows the broken-ness?

**Comment by sebbbi** [comment] 2016-09-16 12:01
Tested with 0a85203b. The UI is clearly changed. It updates the slice count properly, and multiplies/divides the active slice by 2 when I change the slices. But the visible contents in the window are wrong.

Save is bugged the same way as the visualization. Both always use mip 0 only. No other mips are shown at all. If mip 1 is chosen, it shows 2x2x2 smaller version of mip 0 upper corner. Mip 2 shows 4x4x4 smaller version of mip 0 upper corner. Etc.

Can't unfortunately share a capture, since it is from an unannounced game. Volume texture format=R8 unorm, size=1024x1024x512, mips=4. There's one SRV to sample it as whole (all mips). Additionally I have 4x SRV and 4x UAV to read/write mips separately. The resource viewer shows the full texture resource (all mips).

Reverted back to RenderDoc 0.30 and everything works perfectly. Haven't yet tested with 0.31 stable.

**Comment by baldurk** [comment] 2016-09-16 12:12
OK no problem I understand, it's worth asking :smile:. I'll try and create an identical texture, the one I had was a little bit different.

Just hedging my bets in case I can't repro it easily, and while I have you around - if you use 0.30 can you save the texture to dds (all slices/mips) and open that in the latest build? does that repro the same bug, and if so would you be able to share the texture in isolation?

**Comment by baldurk** [comment] 2016-09-16 16:17
I'm unable to reproduce this behaviour even on the 0a85203b394afeadd37039e640f4c3d0aa7377be nightly. I modified my test application to create a 1024x1024x512 R8_UNORM 4-mip 3D texture. It only creates one single SRV that samples all mips, I didn't create the other SRVs or the UAVs, but I don't _think_ that should change anything.

I put a distinctive pattern in each mip/slice - mip 0 has vertical bars, mip 1 has horizontal bars, mip 2 has diagonal lines and mip 3 is solid. On each mip level the slice patterns shift down from the top sequentially (as in - slice 0 is fully covered in the pattern, slice 1 the pattern starts at y=64, and so on with this repeating every 16 slices so that every slice has at least something).

The only thing I did notice was something that seems to have been there since v0.30 and probably long before, where if you are viewing the texture at < 100% zoom it does linear sampling, and passing the slice index wasn't quite precise enough, so it linear sampled the previous slice faintly. I've added a slight nudge factor which fixes that.

I tested on my NV win7 machine and my AMD win10 machine with the same results. I've uploaded the capture here in case for some reason you get it broken still - [3D_test.zip](https://github.com/baldurk/renderdoc/files/477241/3D_test.zip).

There's quite possibly still an edge case left lurking there but it must be something quite specific. If you want I can make a separate branch for you or specific builds that will add some more logging to see if we can identify what's different in your case.

**Comment by sebbbi** [comment] 2016-09-17 06:21
Did some additional investigation on my side. 

Captures made with 0.30 work with the nightly build. The volume shows correctly and the render output is correct. Saving also works perfectly (dds contains all data).

However, the nightly build seems to capture volume texture contents incorrectly. Volume texture contents in new captures have corrupted mip levels. Also the render output (in RenderDoc) is wrong, meaning that the actual captured data is wrong, not just the visualization. If I reload a capture made with the nightly build, the volume is still wrong and the render output is still wrong. 

Captures made with 0.30 (exactly the same scene and the same build of my game) work properly when loaded to the nightly build. I would guess that something got broken in the data capture, not in the visualization of it.

**Comment by sebbbi** [comment] 2016-09-17 06:24
Also tried to load captures from the nightly build into 0.30, but 0.30 gives me incompatible version error. So I can't test whether the nightly build captures are also corrupted in 0.30.

**Comment by baldurk** [comment] 2016-09-17 06:55
OK I _think_ I have repro'd it now. The key seems to be that the texture contents need to be saved in frame-initial data. My test case was small enough that the individual UpdateSubresource calls to fill out the texture were saved separately, which seems to be OK.

**Comment by sebbbi** [comment] 2016-09-17 07:00
Yes, that 1024x1024x512 atlas is certainly not regenerated fully every frame :)

I do edit it partially (UAV writes), but most of the data remains from the last frame.

**Comment by baldurk** [comment] 2016-09-17 07:20
Ah I didn't mean rather than being regenerated every frame, I meant as opposed to a texture that's updated once at init time and then left immutable so it's never marked as dirty and in need of frame-initial data. But the UAVs should have clued me into that :smile:.

Tracked it down, it was a silly typo when fetching the data, probably a copy-and-paste error. Should be fixed with that commit above, but I'd appreciate you verifying when you're able!

**Comment by sebbbi** [comment] 2016-09-17 08:00
Glad to hear that you found the issue. I will verify with the nightly build on Monday morning.

**Comment by sebbbi** [comment] 2016-09-20 07:06
verified build 45551e58 (2016-09-19).

Everything works perfectly now. The UI is also better (shows actual slice number for mips + faster to scroll through the slices with up/down buttons when coarse mips are selected). Thanks for the improvements! 

I wish other tools developers would fix things as quickly as you do :)

**Comment by baldurk** [comment] 2016-09-20 08:43
Glad it's all working now! :) Sorry for the extra bug you hit along the way.

**Closed by baldurk** 2016-09-20 08:43 UTC
Labels: status: to be verified, type: bug
