### ISSUE TITLE
Invalid mesh preview for simple quad

### ISSUE THREAD

**Issue by Zeblote** [baldurk/renderdoc#918] opened 2018-03-14 00:26 UTC
## Description

Just took a capture and noticed this issue in the mesh preview:

![image](https://user-images.githubusercontent.com/6764788/37376621-5adb0098-2725-11e8-9bbe-0553409b66d8.png)

## Repro steps

Unfortunately I couldn't reproduce the bug yet. I saved the capture and reloaded it, now it looks fine.
Still posting this here in case someone else encountered a simular issue

## Environment

* RenderDoc build: v1.0
* Operating System: Windows 10
* API: D3D11

**Comment by baldurk** [comment] 2018-03-14 10:45
My best guess is that this is leftover highlighting data from a previous drawcall that wasn't properly flushed. If you're able to figure out a reproduction case for it it should be an easy fix.

**Comment by Zeblote** [comment] 2018-03-14 14:34
Yeah, that's totally what happened. I can reproduce the bug now.
https://dl.dropboxusercontent.com/s/19dhx1glcuhb1th/Capture.zip

First select this draw call:
![image](https://user-images.githubusercontent.com/6764788/37408707-f02cac92-279c-11e8-8015-a66e3c5dee3c.png)

Then highlight some random vertex:
![image](https://user-images.githubusercontent.com/6764788/37408818-2bda6a72-279d-11e8-8478-3351e824eac6.png)

Then switch to the next drawcall which is the quad. The highlighting will be messed up:
![image](https://user-images.githubusercontent.com/6764788/37408797-202af7c8-279d-11e8-809a-5d702865fff6.png)

**Comment by baldurk** [comment] 2018-03-14 15:30
Thanks or the ideal repro! This was caused by cached vertex data that wasn't invalidated between the draws in some cases, because the cache key wasn't checking all of the properties. The fix will be in the next nightly build.

**Closed as completed** 2018-03-14 15:29 UTC
Labels: Bug, Need More Info
