### ISSUE TITLE
Wrong shader variable CB extracted from newest version

### ISSUE THREAD

**Issue by sibojia** [baldurk/renderdoc#411] opened 2016-11-01 11:47 UTC
![default](https://cloud.githubusercontent.com/assets/6429444/19888717/6bb0bc7e-a06b-11e6-9d26-a0d021e72eff.PNG)

I've compiled the HEAD commit on master. As shown in the screenshot above, the matWheelWorld CB (event id 2778, VS pipeline state) is different between these two versions of renderdoc. I've confirmed that the old version holds the correct values. The log file can be downloaded from my previous issue #406 . Please have a look, thanks!

**Comment by sibojia** [comment] 2016-11-01 12:31
In the test above I didn't consider that the the log is captured by v0.31 and replayed by v0.32. Yet I tried to capture a frame with newest commit and found the same problem. The new log cannot be replayed by v0.31 program, but when opened with the newest commit, I found the matWheelWorld CB is as follows:

![image](https://cloud.githubusercontent.com/assets/6429444/19889769/d18428a0-a071-11e6-8d49-3daf9ea451d2.png)

the last two rows are zero, which are impossible for a world matrix. You can find a drawcall of wheels easily by looking for 4 calls with the same numIndeces.

**Comment by baldurk** [comment] 2016-11-02 22:40
Thanks for catching this! Due to a refactor constant buffers were looking up the wrong slots for their data. It should be fixed now with that commit.

**Comment by sibojia** [comment] 2016-11-03 03:04
Comfirmed OK. Thanks!

**Comment by BleuBleu** [comment] 2016-11-09 19:40
Hi.

There is still a bit of an issue with that, even in the latest nightly. 

Here is the value of some constants viewer from the debugger (i am debugging a pixel) and the same constants viewed from the constant buffer directly (going through the the pipeline tab). The pipeline tab gives the correct values, but the debugger reads the wrong values, leading to NaN and -Infinities and such while debugging.

![pipeline](https://cloud.githubusercontent.com/assets/6654334/20151947/35d0446a-a68a-11e6-9fb3-0d433ddde6b5.PNG)
![debugger](https://cloud.githubusercontent.com/assets/6654334/20151948/35d828ce-a68a-11e6-9f0f-4701698fb138.png)

-Mat

**Comment by baldurk** [comment] 2016-11-10 10:36
I can't repro this on the original capture, it seems like the wrong-indexing that I fixed for the original bug isn't the cause, it must be something different though possibly related to the same underlying changes.

I'll see if I can find a capture where it breaks but I don't have much to go on. I guess you probably can't share the capture, but does it break on all pixel shaders you try? Is there any pattern or specific case where it breaks down? Was it working on v0.31 or any previous versions, if so are you able to determine roughly what timeframe it broke? Any information to help narrow down on the broken case would be useful.

**Comment by baldurk** [comment] 2016-11-10 10:58
I must be going completely barmy. I'd swear blind that I tried to repro this and it worked fine. Of course when I go and try it on some other captures I immediately see it broken, find it's because of the exact same bug, and now it's broken on the original capture that I tried just 10 minutes ago.

Oh well, aside from my tenuous grip on reality that should hopefully fix the issue with shader debugging.

**Comment by BleuBleu** [comment] 2016-11-10 14:08
Hahaha!

If you still want me to send a capture, let me know! I can take one today.

-Mat

Date: Thu, 10 Nov 2016 02:58:29 -0800

**Comment by baldurk** [comment] 2016-11-10 15:07
I think I have it fixed (I also chased down an unrelated shader debugging bug that I noticed at the same time), but if you are able to share a capture so I can double check that would be much appreciated :).

**Comment by baldurk** [comment] 2016-12-08 11:17
This should be resolved in v0.32, verified over email too. If something's still not working right in the latest build then let me know and I'll re-open and investigate.

**Closed by baldurk** 2016-12-08 11:17 UTC
Labels: status: to be verified, type: bug
