### ISSUE TITLE
Unable to capture the correct mesh data on Android platform

### ISSUE THREAD

**Issue by DaBianYLK** [baldurk/renderdoc#1077] opened 2018-08-10 14:40 UTC
## Description

I was trying to use RenderDoc to capture frame on several android devices, and the meshes captured all corrupted just like below：
![ErrorMesh](https://raw.githubusercontent.com/DaBianYLK/PersonalStudyNotes/master/ImageOfRenderDoc/MeshError_1.png)

![ErrorVertexData](https://raw.githubusercontent.com/DaBianYLK/PersonalStudyNotes/master/ImageOfRenderDoc/MeshError_2.png)

![ErrorReplay](https://raw.githubusercontent.com/DaBianYLK/PersonalStudyNotes/master/ImageOfRenderDoc/MeshError_3.png)

I noticed this error on August 7th, and the RenderDoc's version is Nightly 2018-08-07(Win x64).  And I found that the build on 2018-08-04 has no such problem. Then i fetch the latest version of codes on GitHub and tried to revert the changes on August 6th, the bug no longer showed after I revert the commit below:
[commit 8e2a2b13c17bd6954668d094b5c939c6b41bb103 : Clean up handling of internal resources](https://github.com/baldurk/renderdoc/commit/8e2a2b13c17bd6954668d094b5c939c6b41bb103)

## Environment

* RenderDoc build: 2018-08-07 nightly build.
* Operating System: Windows 10 and Android 6.0
* API: OpenGL ES

**Comment by baldurk** [comment] 2018-08-10 15:31
I'll check this out, thanks for investigating and narrowing it down to a specific commit.

To clarify, if you keep the same capture file and open it in builds before/after the commit does it work or not work depending on the build? Or do you have to capture with the broken build for it to break.

**Comment by DaBianYLK** [comment] 2018-08-11 03:23
The file captured by the broken build does not work with the correct build,  it seems that the vertex data was missing during the capture process.

**Comment by DaBianYLK** [comment] 2018-08-13 02:59
By the way, I tried to replace the text "android:minSdkVersion = 23 android:targetSdkVersion = 23" with  "android:minSdkVersion = 19 android:targetSdkVersion = 19" in  AndroidManifest.xml and comment the "apiVersion < 23" in C++ Codes, then build a version on my own and test it on some Android 5.0 Devices, the build seems works fine. Could you please tell me why the official version of RenderDoc does not support Android 5.0?

There are still many users play our game on some very old devices, it will be better if you can provide offical support of Android 5.0.

**Comment by baldurk** [comment] 2018-08-13 09:46
The main reason is that Android is an extremely fragile and fragmented platform and supporting as much as I already do is already problematic. Expanding support has a cost/benefit tradeoff and it doesn't seem worthwhile to try to handle even older devices especially ones that I have no way of testing. With infinite resources it would be great to support everything, but only about 5% of RenderDoc users use Android at all.

From what I've seen Android 6+ covers around 65-70% of the user-facing market, so I think it's reasonable to expect that developers have access to an Android 6 device. RenderDoc isn't too useful useful for diagnosing bugs caused by driver problems, so the same rendering code running on a newer device is just as valid to capture and replay from my perspective. It's more important that developers have some supported device available, rather than RenderDoc being compatible with every device.

**Comment by DaBianYLK** [comment] 2018-08-14 09:19
Thank you for your reply, I got it.

**Comment by baldurk** [comment] 2018-08-14 16:46
I believe that commit should fix the problem. The default VAO 0 (which is common on all GLES applications and required on GLES 2) wasn't properly having its state saved since I was marking it as internal.

Thanks again for the thorough report!

**Closed as completed** 2018-08-14 16:45 UTC
Labels: Bug, Unresolved
