### ISSUE TITLE
Pixel shader debug doesn't take SV_RenderTargetArrayIndex in account

### ISSUE THREAD

**Issue by deM-on** [baldurk/renderdoc#1527] opened 2019-09-23 04:21 UTC
Pixel shader debug doesn't take correct value for SV_RenderTargetArrayIndex.
It's different (random) every time "Debug" is pressed.

It's easy to reproduce with UE4 InjectTranclusentVolume step.
Scene -> Lights -> DirectLighting -> ShadowedLights -> Weather_Clear.DIrectionalLight_Sun -> InjectTranslucentVolume

Here is capture:
[SV_RenderTargetArrayIndex_Issue.zip](https://github.com/baldurk/renderdoc/files/3640596/SV_RenderTargetArrayIndex_Issue.zip)

**Comment by baldurk** [comment] 2019-09-23 09:09
Thanks, yes this is a duplicate of #763, the shader debugging and pixel history can't distinguish between instances that overwrite the selected pixel, it only disambiguates by primitive ID.

In cases like this where there's SV_RenderTargetArrayIndex as an existing input that could be used to partially solve the problem but a different solution is needed for the general case.

Closing in favour of the older bug.

**Closed as completed by baldurk** 2019-09-23 09:09 UTC

**Comment by deM-on** [comment] 2019-09-24 00:51
I can't agree, these problems are orthogonal. And I fixed that already, going to make pull request.
