### ISSUE TITLE
Failed to replay D3D12 captures

### ISSUE THREAD

**Issue by Evil-Ryu** [baldurk/renderdoc#1984] opened 2020-07-20 08:49 UTC
## Description

Failed to open d3d12 captures due to the creation of some heap was failed.
Tried to debug the issue,  here is the log:

>RDOC 007216: [15:51:36]          rdcfile.cpp( 244) - Log     - Opening RDCFile F:\SponzaTest\Saved\RenderDocCaptures\2020.07.20-15.11.55_frame6046.rdc
RDOC 007216: [15:51:36]          rdcfile.cpp( 307) - Debug   - Opened capture file for read
RDOC 007216: [15:51:36]          rdcfile.cpp( 244) - Log     - Opening RDCFile F:\SponzaTest\Saved\RenderDocCaptures\2020.07.20-15.11.55_frame6046.rdc
RDOC 007216: [15:51:36]          rdcfile.cpp( 307) - Debug   - Opened capture file for read
RDOC 007216: [15:51:36]             core.cpp(  49) - Log     - Not enabling API validation during replay
RDOC 007216: [15:51:36]             core.cpp(  54) - Log     - Using default GPU replay selection algorithm
RDOC 007216: [15:51:36]             core.cpp(  63) - Log     - Replay optimisation level: Balanced
RDOC 007216: [15:51:36]     d3d12_replay.cpp(3739) - Debug   - Creating a D3D12 replay device
RDOC 007216: [15:51:36]     d3d12_replay.cpp(3853) - Log     - Capture was created on nVidia / NVIDIA GeForce GTX 1060 6GB
RDOC 007216: [15:51:36]          amd_rgp.cpp(  76) - Log     - AMD RGP Interop is not enabled
RDOC 007216: [15:51:36]      dxgi_common.cpp(1926) - Log     - Selected nVidia / NVIDIA GeForce GTX 1060 6GB adapter for replay
RDOC 007216: [15:51:36]     d3d12_replay.cpp(3892) - Log     - Creating D3D12 replay device, minimum feature level D3D_FEATURE_LEVEL_12_1
RDOC 007216: [15:51:36]     d3d12_common.cpp( 127) - Debug   - Enabling debug layer
RDOC 007216: [15:51:36]     d3d12_replay.cpp(3941) - Log     - Created device.
RDOC 007216: [15:51:36]     d3d12_replay.cpp( 101) - Log     - Running replay on nVidia / NVIDIA GeForce GTX 1060 6GB 27.21.14.5167
RDOC 007216: [15:51:36] replay_controller.cpp(1974) - Log     - Created replay driver.
RDOC 007216: [15:51:37]     d3d12_replay.cpp( 134) - Log     - nVidia GPU detected - no counters available
RDOC 007216: [15:51:37] d3d12_device_wrap.cpp(1325) - Log     - Remapping committed resource ResourceId::54 from upload to default for efficient replay
D3D12 ERROR: ID3D12Device::CreateHeap: D3D12_HEAP_FLAGS has invalid flag combinations set. The following flags may not all be set simultaneously. Exactly one must be left unset, or all may be left unset when the adapter supports D3D12_RESOURCE_HEAP_TIER_2 or creating a heap in conjunction with D3D12_HEAP_FLAG_SHARED_CROSS_ADAPTER: D3D12_FEATURE_DATA_D3D12_OPTIONS::ResourceHeapTier = D3D12_RESOURCE_HEAP_TIER_1, D3D12_HEAP_FLAG_SHARED_CROSS_ADAPTER = 0, D3D12_HEAP_FLAG_DENY_NON_RT_DS_TEXTURES = 0, D3D12_HEAP_FLAG_DENY_RT_DS_TEXTURES = 1, and D3D12_HEAP_FLAG_DENY_BUFFERS = 0. [ STATE_CREATION ERROR #631: CREATEHEAP_INVALIDMISCFLAGS]
RDOC 007216: [15:51:37] d3d12_device_wrap.cpp(1525) - Error   - Failed on resource serialise-creation, HRESULT: E_INVALIDARG

According to [D3D12 Spec](https://docs.microsoft.com/en-us/windows/win32/api/d3d12/ne-d3d12-d3d12_heap_flags),  at least two of these three flags must be set if your gpu only supports  "heap tier 1 ":

> D3D12_HEAP_FLAG_DENY_BUFFERS
D3D12_HEAP_FLAG_DENY_NON_RT_DS_TEXTURES 
D3D12_HEAP_FLAG_DENY_RT_DS_TEXTURES

Apparently here only 1 of them was set. This should be the root cause.

## Steps to reproduce

Capture on D3D12 and open it on any GPU only supports heap tier 1 should reproduce it,  for NVIDIA it's Kepler to Pascal

## Environment

* RenderDoc version: 1.8
* Operating System: windows 10
* Graphics API: D3D12

**Comment by baldurk** [comment] 2020-07-20 09:09
What you've put for steps to reproduce is not sufficient. It is easy to demonstrate that not all D3D12 captures are universally broken on any GPU that only supports heap tier 1. For example given that the error happens in `ID3D12Device::CreateHeap` then capturing any program that doesn't use that function and only creates committed resources directly will presumably not reproduce the problem.

When outlining the steps to reproduce a problem you need to be as specific as you can and give steps that describe your particular problem exactly. If you can share the capture that fails to load or your program that produces the capture that is the easiest way. Assuming that the problem is very general and giving vague steps doesn't help to figure out the actual problem.

**Comment by Evil-Ryu** [comment] 2020-07-20 09:27
Thanks for the quick replying, I've attached the link of the capture file:
[https://drive.google.com/file/d/18JVFerfuWi7nE34ULci7Qmj6bnlC3XGC/view?usp=sharing](https://drive.google.com/file/d/18JVFerfuWi7nE34ULci7Qmj6bnlC3XGC/view?usp=sharing)

**Comment by baldurk** [comment] 2020-07-20 09:49
I believe this is the same as #1933 caused by the D3D12 runtime returning a nonsense and impossible heap descriptor for heaps created via `OpenExistingHeapFromAddress`. A workaround for that has been added since v1.8 was released, so capturing on a recent nightly build should work.

**Closed as completed by baldurk** 2020-07-20 09:49 UTC
Labels: Bug, Need More Info
