### ISSUE TITLE
(Vulkan) GLSL compiler outputs invalid SPIR-V code

### ISSUE THREAD

**Issue by asylum2010** [baldurk/renderdoc#313] opened 2016-08-04 09:23 UTC
![lal](https://cloud.githubusercontent.com/assets/937925/17396869/9ec916fa-5a35-11e6-8bf4-6de4f7eb97fe.png)

Tried to look at the source code but couldn't find the problem.
Just to be sure I built the latest glslang and my app works fine outside RenderDoc.

**Comment by baldurk** [comment] 2016-08-04 09:29
Can you give more details about exactly what the problem is?

When you say the GLSL compiler - do you mean RenderDoc's internal glslang that it uses for compiling some utility shaders? Which is only the text rendering vertex/fragment shader when injected into a vulkan program.

How do you know that the SPIR-V is invalid? From the screenshot it looks like a message from the vulkan validation layers. Those layers have had numerous false positives in the past, _especially_ for shader validation. I'd want to see some other indication before believing that there is  a real problem and not just a false positive to be fixed.

**Comment by asylum2010** [comment] 2016-08-04 09:40
Probably the internal compiler. yes, compiling something...internal...because it doesn't even reach my shader compilation code.

How do I know...because it says so lol.

**Comment by baldurk** [comment] 2016-08-04 09:48
Well I mean that SPIR-V doesn't have to come from a GLSL compiler, so I wasn't sure what you were necessarily referring to.

Can you be more specific about where you're getting an indication of invalid SPIR-V and when. E.g. "There's a message from the validation layers from inside vkCreateDevice that says 'SPIR-V module is not valid'" or if there's something else happening. If it is the validation layers, then specify which version of the SDK you're running (or if you're compiling the validation layers from source then what revision you built them from).

As I've mentioned, if it's just the validation layers complaining then I believe it to be a false positive and that there's nothing to fix on my side. If there's some other indication of invalid SPIR-V then please give details about that.

**Comment by asylum2010** [comment] 2016-08-04 09:53
Call stack:

![lal2](https://cloud.githubusercontent.com/assets/937925/17397805/093eedb2-5a3a-11e6-90f8-55ab25a67550.png)

**Comment by baldurk** [comment] 2016-08-04 10:04
Yes, so as I've mentioned if this is the only problem I don't believe it is a bug, but just a false positive in the validation layers.

Closing the issue then, but if you have something else then leave another comment.

**Closed by baldurk** 2016-08-04 10:04 UTC

**Comment by srjek** [comment] 2016-08-15 00:43
I'm also having the same issue, and came across this glslang issue that seems related. [https://github.com/KhronosGroup/glslang/issues/307](https://github.com/KhronosGroup/glslang/issues/307). It might be worth watching for when it gets fixed upstream.

 I haven't had it cause any problems yet, but at this point I've only scratched the surface of the Vulkan API.

**Comment by baldurk** [comment] 2016-08-15 17:37
Looks like it is indeed that bug as described from glslang. I'm not clear from the discussion there if it's a glslang-side bug or indeed false positive from the layers, but either way it won't be fixed until either glslang or the layers change.
