### ISSUE TITLE
Swig configuration failure on macOS

### ISSUE THREAD

**Issue by kvark** [baldurk/renderdoc#1107] opened 2018-09-14 18:26 UTC
## Description

When building on macOS, the swig custom step fails:
```bash
Scanning dependencies of target custom_swig
[ 95%] Creating directories for 'custom_swig'
[ 96%] Performing download step (download, verify and extract) for 'custom_swig'
-- Downloading...
   dst='/Users/dmalyshau/Code/renderdoc/build/qrenderdoc/custom_swig-prefix/src/renderdoc-modified-5.zip'
   timeout='none'
-- Using src='https://github.com/baldurk/swig/archive/renderdoc-modified-5.zip'
-- Downloading... done
-- extracting...
     src='/Users/dmalyshau/Code/renderdoc/build/qrenderdoc/custom_swig-prefix/src/renderdoc-modified-5.zip'
     dst='/Users/dmalyshau/Code/renderdoc/build/qrenderdoc/custom_swig-prefix/src/custom_swig'
-- extracting... [tar xfz]
-- extracting... [analysis]
-- extracting... [rename]
-- extracting... [clean up]
-- extracting... done
[ 97%] No patch step for 'custom_swig'
[ 97%] No update step for 'custom_swig'
[ 97%] Performing configure step for 'custom_swig'
configure: error: in `/Users/dmalyshau/Code/renderdoc/build/qrenderdoc/custom_swig-prefix/src/custom_swig':
configure: error: cannot run C compiled programs.
If you meant to cross compile, use `--host'.
See `config.log' for more details
make[2]: *** [qrenderdoc/custom_swig-prefix/src/custom_swig-stamp/custom_swig-configure] Error 1
make[1]: *** [qrenderdoc/CMakeFiles/custom_swig.dir/all] Error 2
```

## Repro steps

Check out the latest v1.0 branch and build on MacOS.

## Environment

* RenderDoc build: v1.0 branch
* Operating System: MacOS 10.14 beta-10
* API: Vulkan

**Comment by baldurk** [comment] 2018-09-14 18:31
This is a duplicate of #1070 - it's some kind of system configuration problem, there's something about macos/xcode that doesn't work by default and needs some setup.

**Closed as completed by baldurk** 2018-09-14 18:31 UTC
