### ISSUE TITLE
Unwrapped texture view

### ISSUE THREAD

**Issue by redorav** [baldurk/renderdoc#1186] opened 2018-11-27 16:37 UTC
## Description

Hi Baldur,

First of all, I'm really looking forward to the new renderdoc! Congratulations on the new milestone :)

I have a new feature request, but I'd like to explain my use case first. In our engine we have a way to see textures on screen. As an option for visualizing the more complex texture like volumes and 2D arrays, there is an option to "unwrap" a texture meaning one can see all the contents as a single 2D texture, without having to click through each individual slice. Cubemaps are even displayed as crosses to see that the ordering of the faces is correct, etc. Unfortunately we cannot debug/inspect the texture contents with our system which is where renderdoc comes in.

I've currently had a case where I would have found it very helpful to see the entire unwrapped texture in the texture viewer, as my texture has a very characteristic format and I can tell slices apart visually, etc. my workflow would be much better like that.

Do you think there's a case, given what I've just said, to add this functionality to renderdoc?

Thanks!

## Environment

* RenderDoc build: v1.1
* Operating System: Windows 7
* API: e.g. D3D11

**Comment by baldurk** [comment] 2018-11-27 18:18
Closing this as it seems like a duplicate of #137 if I'm reading your description right. It's a fair request but it's not been high priority to work on due to the complexity of an implementation that handles all cases properly.

In the meantime if you're motivated this might be a good candidate to implement as a UI extension in python - fetch all the data for all slices/mips and then stitch it into an image you write to disk.

**Closed as completed by baldurk** 2018-11-27 18:18 UTC

**Comment by redorav** [comment] 2018-11-27 18:25
Just to get a bit more information, can the UI extensions feed back to the UI? As in, would I be able to unwrap the textures, then display them back in the texture viewer, or would it only be able to write images back to disk to inspect in an external tool?

**Comment by baldurk** [comment] 2018-11-27 18:36
The extensions have access to everything that you can currently do in the UI, but creating & displaying new textures isn't functionality that's available. With the extensions at the moment your only option would be to write it to disk and either load it back up in a new instance of renderdoc or use another image viewer.

**Comment by redorav** [comment] 2018-11-27 20:12
That's great, thanks for the explanation! I'll wait until 1.2 to test the extension mechanism
