### ISSUE TITLE
A question about RGB Value in Texture Viewer

### ISSUE THREAD

**Issue by lishi0927** [baldurk/renderdoc#832] opened 2017-12-20 15:47 UTC
Recently I use Renderdoc debug my OpenGL program and it really helps me a lot.
But I have a question about the RGB value in texture viewer module. We can get the RGB value in the bottom lab after right click, but i find it's different from my real texture in my computer, which i save the texture and then open in other picture viewer software.
for example:
Renderdoc show the value is (0.28711,0.22363,0.99219), the picture viewer show the value is (150,129,248);

**Comment by baldurk** [comment] 2017-12-20 16:13
RenderDoc shows the pixel values as linear floating point RGB, since it's then consistent with HDR values that go beyond 0.0 - 1.0. Your values seem to be integer relative to 8-bit encoding, which goes from 0 to 255 and most likely in sRGB space.

The values don't quite match up since I think 129 sRGB should be 0.21952, so I'd guess you're not quite comparing apples-to-apples and there's some small interpolation or encoding change along the way.

**Comment by lishi0927** [comment] 2017-12-20 16:39
Thank you for your reply.
It means you have done a gammar correction? But why in another picture the RGB (139,129,254)->(0.4902,0.5088,1.00). I'm a little confused about these and I need the texture value  to debug my program.
Thank you

**Comment by baldurk** [comment] 2017-12-20 16:50
Something is wrong with the values you're picking, `254` is never `1.0` in either linear or sRGB or anything else, and `139` is greater than `129` but `0.4902` is less than `0.5088`. That is more like `127` and `129`.

`129` interpreted as 8-bit becomes `129 / 255 = 0.50588`. If it was linear, that would be the value displayed in RenderDoc.

If it's sRGB data, then the conversion is: `((0.50588 + 0.055)/1.055)^2.4 = 0.219526` which is close but not exactly the same as the value you originally pasted for that (`0.22363`).

For me to give you more information you'd need to detail exactly how you are obtaining the values in a way I can reproduce or explain. Without context I can't say where you are getting the numbers or what they should be.

Unless there is a bug, the best guess I can make is that wherever you are retrieving the integer values is looking at differently encoded or transformed data than RenderDoc is.

**Comment by lishi0927** [comment] 2017-12-20 17:01
Thank you for your explanation. perhaps i have typed wrong value. So when the texture show linear and when the texture show sRGB data. In my debug, I haven't done any configure and the input texture is shown in linear and the output texture is shown in the sRGB data. I haven't use any HDR configuration.
Thank you.

**Comment by baldurk** [comment] 2017-12-21 10:07
I'm not entirely sure what you're asking, if anything. RenderDoc always displays pixel values as linear floating point data, whether they're stored as 8-bit sRGB, or 8-bit linear, or floating point. The underlying format affects what precision is available and what values can be stored, but not how it's displayed.

**Comment by lishi0927** [comment] 2017-12-21 12:45
Thank you for your reply.
I'm sorry about my  presentation. My question is that when I use capture executable, i use f12 get some frame texture, and i see these texture in the texture viewer, they are all in sRGB8_ALPHA8, but i store the normal data in these textures, so i want the origin linear data and needn't gammar correction, I don't use sRGB in my program, so how can i see the origin data to help me debug my program?
thank you.

**Comment by baldurk** [comment] 2017-12-21 16:43
I'm sorry but I still don't quite understand what you mean. If a texture is being reported as sRGB8 then it was created as that format - if you create a texture just as RGBA8 linear that's how it will show up. Even if you don't create any sRGB textures explicitly, the backbuffer of the window is always sRGB.

RenderDoc shows you the data in the textures as it exists. If it displays `0.5` then that's the value contained in the texture - it might be stored as 127 in a linear texture, or as 187 in an sRGB texture, or as a some different bytes in a float texture, but the value is still always `0.5`.

So I'm not sure what information you actually want to get. There is no original data that's hidden - the data that's there is being interpreted according to its format.

Can you share your executable? or a capture? Then I can talk about specifics to your case.

**Comment by lishi0927** [comment] 2017-12-22 13:16
Yeah, the capture show this texture is backbuffer color.
![tim 20171222211420](https://user-images.githubusercontent.com/7486571/34299303-2f0b4d86-e75d-11e7-85ec-7df65ce9d9e8.png)
This is the texture viewer result, it's a normal map. Thank you for your patient explanation.

**Comment by baldurk** [comment] 2017-12-22 13:27
Unfortunately this isn't enough information to explain or help any more than I have. As I mentioned before, the backbuffer is always considered to contain sRGB data, so you will never find linear-stored data there. Whether you interpret the pixels as a normal map, or colour, or any other kind of data doesn't change the way the pixels are stored or the number values they represent - that is always the same.

I still don't understand what your problem is, or what data you want to get that you can't. The backbuffer  image displayed and the pixel values you pick are whatever you have rendered into them - it's up to your code to decide what to render, all RenderDoc does is show you what you rendered.

**Comment by lishi0927** [comment] 2017-12-22 13:38
Could we output a color map in linear-stored data? For example i want to show a normal map in origin data just like the above figure, the normal map is one of our results.

**Comment by baldurk** [comment] 2017-12-22 13:51
How you store the data is up to you, RenderDoc can't do that for you - it just shows what is already there.

If you want a texture stored as linear then you should create one with the GL_RGBA8 and render to that instead. Then the picked values will be interpreted as linear, so picking a pixel that stores 127 will display 0.5 for example.

It looks like possibly your application isn't "gamma correct" anyway, so it's actually just writing linear data without any encoding to the backbuffer that is then interpreted as sRGB. It's a little hard to tell, but e.g. the sky in that screenshot is all `(117, 117, 255)` which as RenderDoc shows is `(0.177, 0.177, 1.0)` when interpreted as sRGB data, but is `(0.458, 0.458, 1.0)` when interpreted as linear data. I don't know why it's not `127` or `128` which would be closer to `0.5`, but I don't know what your rendering is doing.

**Comment by lishi0927** [comment] 2017-12-22 13:54
Thank you. Could we show an output texture not in backbuffer color, my normal map is stored in GL_RGB8.

**Comment by lishi0927** [comment] 2017-12-22 14:16
Could RenderDoc step into the shader to show middle result of one pixel? I see you can inspect a pixel and see every drawcall. It's really interesting and useful about the Shader debug.
 I think RenderDoc helps me a lot.

**Comment by baldurk** [comment] 2017-12-22 14:48
That's a separate issue, it's best not to use one issue report to talk about different things or it becomes difficult to track. But in this case there is already an [issue open for shader debugging on GL](https://github.com/baldurk/renderdoc/issues/293).

Currently shader debugging is only supported on D3D11. GL is the least likely to get full shader debugging since the shader situation on GL is so dire, but it might be able to inherit something from Vulkan by debugging GLSL compiled to SPIR-V. Not all GLSL can be compiled though.

I assume since you're asking about something else the original issue is resolved, so I'll close this now.

**Closed as completed by baldurk** 2017-12-22 14:48 UTC
