### ISSUE TITLE
Texture View does not update

### ISSUE THREAD

**Issue by KuSpa** [baldurk/renderdoc#1152] opened 2018-10-30 19:48 UTC
## Description

![screenshot from 2018-10-30 20-40-23](https://user-images.githubusercontent.com/18664378/47745712-921d7d00-dc84-11e8-8ee2-b9ac3d8ac1df.png)

The Texture Viewer is selected, but the Content stays. See Inputs/Outputs Tabs.

## Repro steps

1. Click the Texture Viewer Tab
2. ???
3. Profit

[capture.zip](https://github.com/baldurk/renderdoc/files/2531352/capture.zip)

## Environment

* RenderDoc build: v.1.1 built from c7d5aa86
* Operating System: 4.15.0-38-generic #41-Ubuntu x86_64 GNU/Linux
* API: OpenGL

**Comment by baldurk** [comment] 2018-10-30 19:59
This happens when the driver has crashed or is otherwise not responding and painting the window. I imagine the same happens if you look at the mesh output tab. It's not intrinsic to the capture itself as if I open the capture here it loads fine.

Can you get the logfile from Help -> View Diagnostic Log and upload that? It might shed some light on what's going wrong. Since you're on linux if there are any messages on the console from the driver that would also be useful (most of it will be from renderdoc which is in the logfile). Also what GPU and driver are you using?

**Comment by KuSpa** [comment] 2018-10-31 17:02
GPU: GTX970ti
GPU-driver: nouveau (doesn't work with nvidia-driver-390 either)
[logs.zip](https://github.com/baldurk/renderdoc/files/2535495/logs.zip)

**Comment by baldurk** [comment] 2018-11-13 17:47
I can reproduce this only with nouveau and a static build of renderdoc (i.e. one of the `tar.gz` packages from renderdoc.org). If I build renderdoc from source it works fine on nouveau, and it works fine in all cases on the proper nvidia driver.

Can you double check that when you're testing the binary nvidia driver that it's definitely running through it? If you look at the renderdoc log when running with it, it will print out the GL vendor information being used for the replay.

I'd strongly recommend using the nvidia binary driver, but if you do want to use nouveau could you try building renderdoc from source and seeing how you get on? it's possible that something with the static linking needed to distribute binaries is interfering with mesa.

**Comment by baldurk** [comment] 2018-12-04 10:24
Closing this issue as the problem in my testing doesn't seem to affect the nvidia binary driver at all, and doesn't affect mesa when compiling from source. If you're able to provide more information as to a case where it fails please feel free to comment here and I can open it up again.

**Closed as completed by baldurk** 2018-12-04 10:24 UTC
Labels: Bug, Need More Info
