### ISSUE TITLE
Discrepancy between Mesh Viewer VS Output and corresponding Vertex Shader debug output

### ISSUE THREAD

**Issue by jojoba0** [baldurk/renderdoc#1604] opened 2019-11-19 21:33 UTC
## Description

I'm investigating an issue where a depth pass would output a given Z-value and a G-Buffer pass afterwards would output a slightly different Z-value. Both shaders are writing the depth using the SV_DepthLessEqual semantic and the same pixel shader code. 

Debugging both pixel shaders for the same pixel, I could retrace a slight difference in the interpolated TEXCOORD1 (.y)

Tracing back the 3 vertices transformed to produce this pixel, I could spot a difference in the y component of TEXCOORD1 in one of the vertices indeed, looking at the Mesh Viewer VS Output (the other attributes are all equal (e.g. POSITION, which I put there just to show that they are similar) : 
- Depth pass (VTX 15): 
POSITION : -738.0711669921875 -949.18304443359375  10.00  3247.029052734375
TEXCOORD1 : 0.91917425394058227539  0.72089284658432006836 -0.01086578331887722015 -0.02022023685276508331

- G-Buffer pass (VTX 15): 
POSITION : -738.0711669921875 -949.18304443359375  10.00  3247.029052734375
TEXCOORD1 : 0.91917425394058227539  0.72089290618896484375 -0.01086578331887722015 -0.02022023685276508331

Seemed simple enough : debug the vertex shader for VTX 15 in both passes and spot the difference. However, when doing so, it appears that the values exported by both vertex shaders are equal, contradicting what is displayed in the Mesh Viewer VS Output : in both cases, register r1.xy is the register storing TEXCOORD1 right before export : 

- Depth pass (VTX 15): 
r1 temporary 	0.9191741943359375, 0.72089290618896484375, -0.01086578425019979477, -0.02022023499011993408

- G-Buffer pass (VTX 15): 
r1 temporary 	0.9191741943359375, 0.72089290618896484375, -0.01086578425019979477, -0.02022023499011993408

So my question is : what could explain this discrepancy between the Mesh Viewer VS Output and the replay of the vertex shader?
What we can notice also is that for a given pass (e.g. the depth pass), the values are not exactly equal (e.g. TEXCOORD1[x] = 0.91917425394058227539 in the Mesh Viewer Output and 0.9191741943359375 in the vertex debugger). 

Debugging the pixel shader seems to indicate that the values for TEXCOORD1 exported by the vertex shader are indeed different for this vertex, which does explain the bug but because the replay of this vertex gives the same result, I have a hard time figuring out where the issue might be.
One additional note : this bug is pretty hard to capture, it happens randomly and most of the time, when triggering a capture, it would not show, which reminds of a timing/synchronization issue more than an issue in the pixel shader. 
However, capturing many consecutive frames, I finally managed to capture it but as stated before, the replay is kind of inconsistent. 

I can check with management if I can provide the full capture if needed but I wanted to explain the issue first, in case something obvious might explain why the Mesh Viewer VS output would be different than the vertex replays. 

Thanks a lot!

## Environment

* RenderDoc version: v1.5
* Operating System: Win10
* API: DX11

GPU info (DXDiag) :
           Card name: NVIDIA GeForce GTX 1080
        Manufacturer: NVIDIA
           Chip type: GeForce GTX 1080
            DAC type: Integrated RAMDAC
         Device Type: Full Device (POST)
          Device Key: Enum\PCI\VEN_10DE&DEV_1B80&SUBSYS_34801462&REV_A1
       Device Status: 0180200A [DN_DRIVER_LOADED|DN_STARTED|DN_DISABLEABLE|DN_NT_ENUMERATOR|DN_NT_DRIVER] 
 Device Problem Code: No Problem
 Driver Problem Code: Unknown
      Display Memory: 105586 MB
    Dedicated Memory: 8079 MB
       Shared Memory: 97507 MB
        Current Mode: 2560 x 1440 (32 bit) (59Hz)
         HDR Support: Not Supported
    Display Topology: Extend
 Display Color Space: DXGI_COLOR_SPACE_RGB_FULL_G22_NONE_P709
     Color Primaries: Red(0.639648,0.330078), Green(0.299805,0.599609), Blue(0.150391,0.059570), White Point(0.313477,0.329102)
   Display Luminance: Min Luminance = 0.500000, Max Luminance = 270.000000, MaxFullFrameLuminance = 270.000000
        Monitor Name: Generic PnP Monitor
       Monitor Model: DELL U2717D
          Monitor Id: DEL40EA
         Native Mode: 2560 x 1440(p) (59.951Hz)
         Output Type: Displayport External
Monitor Capabilities: HDR Not Supported
Display Pixel Format: DISPLAYCONFIG_PIXELFORMAT_32BPP
      Advanced Color: Not Supported
         Driver Name: C:\WINDOWS\System32\DriverStore\FileRepository\nvlei.inf_amd64_30dfb79123399f9b\nvldumdx.dll,C:\WINDOWS\System32\DriverStore\FileRepository\nvlei.inf_amd64_30dfb79123399f9b\nvldumdx.dll,C:\WINDOWS\System32\DriverStore\FileRepository\nvlei.inf_amd64_30dfb79123399f9b\nvldumdx.dll,C:\WINDOWS\System32\DriverStore\FileRepository\nvlei.inf_amd64_30dfb79123399f9b\nvldumdx.dll
 Driver File Version: 26.21.0014.3160 (English)
      Driver Version: 26.21.14.3160
         DDI Version: 12
      Feature Levels: 12_1,12_0,11_1,11_0,10_1,10_0,9_3,9_2,9_1
        Driver Model: WDDM 2.5

**Comment by baldurk** [comment] 2019-11-19 22:24
At a _complete_ guess I'd say that you're running into precision issues. As far as I can see the two values that are different only vary by one ULP:

Depth pass TEXCOORD1.y: 0.72089284658432006836 (0x3f388c6f)
G-Buffer pass TEXCOORD1.y: 0.72089290618896484375 (0x3f388c70)
Difference: 5.960464478e-8, or the LSB in hex.

E.g. sqrt and rcp in D3D among others have 1 ULP tolerance. It's possible to have way more than 1 ULP divergence from the 'perfect' result if ULP errors compound, so only being 1 ULP off is pretty close.

If the vertex shaders aren't identical then the calculation for TEXCOORD1 might be slightly different between the two. This would not necessarily reproduce in RenderDoc's shader debugger since only texture sampling and transcendental functions are run on the GPU, all other operations are run on the CPU at full precision. I'm not clear on whether or not the intermittent appearance was for a precisely identical scene or if you meant it varied while things were moving/animating. If they were, and you're only out by 1 ULP, it could be the rounding was going in and out of sync between the two shaders.

Without steps to reproduce though all I can do is guess. If you can provide a repro case I can double check, but this would be the most likely explanation to me. Try opening the capture on an AMD GPU, or with WARP instead, and see if the bug goes away or the values change.

**Comment by jojoba0** [comment] 2019-11-20 15:39
Thank you very much for your quick and on-spot answer. 
I didn't know that we could replay a capture in RenderDoc with the WARP rasterizer, this is very handy and indeed, the precision issue doesn't occur when in WARP mode. 
I'll try and get my hands on an AMD card and see how it goes. 
Meanwhile, I could confirm that the DXBC assembly participating in TEXCOORD1's computation in both passes is completely similar so our current suspicion is that the compiler merges some instructions together in different ways in both shaders, so I'll try and simplify the shader graph spaghetti having generated this code to see if I can pinpoint which of those instructions introduces the error. 
Thanks for your help!

**Comment by baldurk** [comment] 2019-12-18 11:09
Closing this as it's still unclear if there is any RenderDoc issue here and there's been no further clarifying information. If you're able to share a repro case or more information either here or privately let me know and I can investigate, but as it is there's not much I can do.

**Closed as completed by baldurk** 2019-12-18 11:09 UTC
Labels: Bug, Need More Info
