### ISSUE TITLE
Crash when device is queried for ID3D11Debug interface

### ISSUE THREAD

**Issue by Pombal** [baldurk/renderdoc#718] opened 2017-08-12 09:32 UTC
Some Unreal Engine 4 games like Hellblade crash when attaching Renderdoc. 

The problem is Renderdoc is passing to the game a DummyID3D11Debug interface which the game will try to use and fail with a nullptr access violation. 

I was able to bypass this by returning E_NOINTERFACE when ID3D11Debug is passed as an id to QueryInterface for a WrappedID3D11Device.

I know this usage of Renderdoc is not supported but it seems like there is an underlying issue here that should be fixed and is mostly seen on UE4 games.

**Comment by baldurk** [comment] 2017-08-14 09:40
Hi, can you give more information about what exactly is crashing? The dummy debug is provided so that applications which think they've created a debug device (but renderdoc turned off as it controls debug device creation) can still get a valid interface back. It seems strange for a released game to be using it at all, but even if it did then the dummy interface just silently does nothing.

I'd need more details about the crash to know what should be fixed, as I can't return E_NOINTERFACE for all cases.

**Comment by Pombal** [comment] 2017-08-14 11:11
I don't know what exactly is crashing, I just know it's an access violation after the debug dummy interface is given to the game. The game then goes on to use it and crashes. I've seen it happen for 2 UE4 games now, Hellblade and Euro Fishing.

Perhaps a UE4 sample game built from latest source could show the problem as well.

**Comment by baldurk** [comment] 2017-08-14 11:36
Oh right, sorry I thought it was crashing while using that interface.

From a quick look, I think this is actually an unreal engine bug. There are only a couple of places where `ID3D11Debug` is fetched in the UE codebase, but the important one is this I think:

```cpp
#if PLATFORM_WINDOWS
	IUnknown* RenderDoc;
	IID RenderDocID;
	if (SUCCEEDED(IIDFromString(L"{A7AA6116-9C8D-4BBA-9083-B4D816B71B78}", &RenderDocID)))
	{
		if (SUCCEEDED(Direct3DDevice->QueryInterface(__uuidof(ID3D11Debug), (void**)(&RenderDoc))))
		{
			// Running under RenderDoc, so enable capturing mode
			GDynamicRHI->EnableIdealGPUCaptureOptions(true);
		}
	}
#endif
```

I'm not sure why it checks renderdoc's GUID and then _also_ `ID3D11Debug`, since the latter is redundant and will always return something once you know renderdoc is around. It doesn't actually use the interface though just uses it as a marker/test.

Then in `EnableIdealGPUCaptureOptions` there's code that looks like it might crash if the cvar `r.ShowMaterialDrawEvents` isn't available - there are null checks on some accesses, but not on all of them. That cvar is only defined when `WITH_PROFILEGPU` is defined, which is going to be off on shipping/production builds. So I think this will unintentionally crash when renderdoc is enabled.

If I'm right, then you could also work around it by returning `E_NOINTERFACE` for `IRenderDoc_uuid = {A7AA6116-9C8D-4BBA-9083-B4D816B71B78}`.

I'll double check with someone I know at Epic about my conclusion, but looks like this isn't something I can fix from RenderDoc's side. Plus it will only affect production/shipping builds so as you mentioned this isn't a workflow I go out of my way to support. Since you have a workaround I'll close this issue once I've confirmed the problem is UE4 side.

**Comment by baldurk** [comment] 2017-08-14 13:59
Double checked with someone and yeh this is a UE4 bug, so closing here as there's nothing to do on my side.

**Closed by baldurk** 2017-08-14 13:59 UTC
Labels: status: need more info, type: bug

**Comment by Pombal** [comment] 2017-08-14 18:00
That makes perfect sense, thanks for looking into it :)
