### ISSUE TITLE
RenderDoc (nightly build) crashes when trying to create a vulkan swapchain

### ISSUE THREAD

**Issue by Raikiri** [baldurk/renderdoc#1545] opened 2019-10-08 08:48 UTC
When I'm trying to debug my rendering engine by launching it from within RenderDoc, the window just closes. If I attach a debugger (after launching it from RenderDoc) it turns out that vk::createSwapchainKHR() call crashes in the driver (access violation). If, however, I launch my engine from explorer (or from Visual Studio) and then before creating a Vulkan instance I inject RenderDoc into it, it works fine and I can take captures. Which means that there's something about how RenderDoc launches an application that makes it crash for me. Any suggestions where to look?

My system: windows 10, RenderDoc_2019_10_07_3587ec2e_64 nightly, GTX1060.

**Comment by baldurk** [comment] 2019-10-08 18:35
It sounds like perhaps you haven't configured the right working directory in RenderDoc, by default if you don't choose one it will use the directory the executable is in.

I can't tell you why the crash is happening unless I have more information and ideally I can reproduce the problem. If you can share your program with me either here or privately please do so and I can look to see what the problem is.

**Comment by Raikiri** [comment] 2019-10-09 09:41
I did specify the correct working directory (at least, it works fine when I'm using the exact same config in 1.4). I'm honestly not sure that the problem is in my program itself: it can be in my version of vulkan sdk(latest), nvidia driver or something else. I can make you a test executable if everything else fails, but maybe there is an easier option? Does renderdoc have any options for verbose logging?

**Comment by baldurk** [comment] 2019-10-09 09:54
RenderDoc doesn't have any verbose logging, and if it's crashing inside the driver in `vkCreateSwapchainKHR` then there's not really any logging that would help diagnose that. To isolate if it's something specific to your program you could try capturing a known-working program like vkcube from the SDK or one of Sascha Willems' samples, to see if they crash also. It is most likely that it's something related to your program, even if it's not necessarily an application fault, otherwise myself or someone else would have seen the problem too.

RenderDoc does very little in `vkCreateSwapchainKHR` aside from unwrap the `surface` and `oldSwapchain` handles and pass the call along to the driver, so I'm surprised it works in v1.4 and crashes in a recent build. If you wanted to you could try different nightly builds from the last few months to bisect and narrow down when the problem started happening, but the easiest way for me to investigate the problem is if you can share the executable that's crashing.

I'm assuming also that you don't have any validation warnings or errors with your program, as any of these could cause crashes.

**Comment by Raikiri** [comment] 2019-10-09 11:00
I actually did end up creating a test binary for you, but then I noticed your message and tried running vkcube.exe 
Lo and behold, same behaviour: it runs fine under 1.4 and crashes in nightly build. I'm not entirely amazed by the possibility of me bisecting the exact build that caused it, but if nothing else works, I can do it as I really appreciate your work. I'm running Vulkan SDK 1.1.121.2 if that matters.

**Comment by baldurk** [comment] 2019-10-09 11:05
What nvidia driver version are you running? That's more important than SDK version.

**Comment by Raikiri** [comment] 2019-10-09 11:08
I'm running driver version 436.48 (downloaded from GeForce Experience thingie). Also running bisection now.

**Comment by Raikiri** [comment] 2019-10-09 11:24
So I found that this build works fine:
v1.x branch @ 0d7c7eb2, 2019-08-27
And this build breaks on vkcube.exe for me:
v1.x branch @ 12f08aa4, 2019-08-28

Hope this helps.

**Comment by baldurk** [comment] 2019-10-09 13:02
That helps to narrow it down but I must admit I have no idea what in that range could be causing problems. Not even that there's some code that's innocuous, looking at [the diff](https://github.com/baldurk/renderdoc/compare/0d7c7eb247b829ceb516f05171f0a0e3a54af8ac..12f08aa47fa0cc760b0e1eaf7c6eac097afdeaa2) I don't see any code that will be running during capture of a vulkan program. The changes are all either in another API (GL or D3D11), another platform (Android), or only run at replay time.

Unfortunately that doesn't leave me with any more ideas of what the problem could be. Would you be able to compile those few revisions to bisect even further down than the nightly builds, to see the exact commit that causes problems? I'm not sure what will result from that but it's about the only thing I can think to try.

I did try reproducing the problem with that exact driver and SDK version but I've had no luck. It might be hardware specific (I don't have a 1060) but I doubt it.

**Comment by Raikiri** [comment] 2019-10-09 13:18
There are two changes that seem remotely related: the one in vk_core.cpp and core.cpp but I have honestly no clue what I'm looking at. I have not tried building RenderDoc myself yet, but https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Compiling.md promises it's supposed to be simple so I can give it a shot.

Another thing that can be suspicious is maybe your buildbot software? Like, compiler got updated, changed a dependency somewhere and now my antivirus (microsoft's built-in thing btw) prevents something from happening.

Alternatively, it can be some kind of memory corruption UB that just happens after a certain version because memory layout changed somewhere. I know this statement does not really bring us any closer to the solution, but I'm just out of ideas.

**Comment by baldurk** [comment] 2019-10-09 13:32
The code in `vk_core.cpp` is disabled - `SINGLE_FLUSH_VALIDATE` is always defined off as it's a debugging macro that can be turned on during development to help debug driver/GPU crashes. The code in `core.cpp` only runs in the replay program, not in any captured programs. It might turn out to somehow be related but I can't see right now how it would be, so it doesn't give me any ideas for a potential fix or even a potential test.

The overnight builds are compiled on a VM which has not changed in build environment. The compiler is VS2015 and the only external dependency should be the windows SDK.

Some weird bug that has been revealed by different code generation or layout is certainly possible though as you say it's hard to do anything with that just yet. If you can compile those versions that should tell us more - indeed on windows it's as easy as downloading the source and compiling the .sln.

**Comment by Raikiri** [comment] 2019-10-09 14:39
Yeah I found what it is. Indeed, it's this commit: https://github.com/baldurk/renderdoc/commit/422cd728adc031f76b9d53d43f98d6b105d42a37

What happens here is you initialize replay device for Vulkan driver (core.cpp):
```cpp
      ReplayStatus status = m_ReplayDriverProviders[driverType](NULL, ReplayOptions(), &driver);
```
which is a pointer to this (vk_replay.cpp):
```cpp
ReplayStatus Vulkan_CreateReplayDevice(RDCFile *rdc, const ReplayOptions &opts, IReplayDriver **driver)
```
and it calls this inside of it:
```cpp
  // disable buggy and user-hostile NV optimus layer, which can completely delete physical devices
  // (not just rearrange them) and cause problems between capture and replay.
  Process::RegisterEnvironmentModification(
      EnvironmentModification(EnvMod::Set, EnvSep::NoSep, "DISABLE_LAYER_NV_OPTIMUS_1", ""));
```
You can't repro this problem because you're on a desktop, I presume. I'm on a laptop which uses shmoptimus. It does report me just one physical device normally in all my vulkan application (the one I allow it to run on), actually masking the second one, so it is indeed pretty much inherently wrong by design. However, commenting this call restores RenderDoc functionality for me. I know, this thing is very annoying to deal with. Keep in mind, however, that both my GTX1060 and integrated video (Intel HD 630) are capable of running Vulkan (and vkcube.exe that I'm testing with) and whichever RenderDoc chooses, both should work. 

Here's what RenderDoc output looks like if I comment that environment modification line and run vkcube.exe (it runs):
![image](https://user-images.githubusercontent.com/1657728/66491516-54b9a480-eb0f-11e9-8917-ed6fc2b466f6.png)

And here's what it looks like if I uncommend the line (as in the latest revision, it crashes when I try to launch vkcube.exe):
![image](https://user-images.githubusercontent.com/1657728/66491584-7b77db00-eb0f-11e9-8fa6-462bfd91f946.png)

By the way, fun fact: this also fixes another bug that I noticed: in 1.4 if I launch an application, make a capture, view capture and the try to launch the app again, it fails in exactly the same way. I bet this is because it used to set the same environment variable when replaying that capture and then fails to launch app again afterwards because of it.

Hope this helps.

**Comment by baldurk** [comment] 2019-10-09 14:54
Oh I see, so the `DISABLE_LAYER_NV_OPTIMUS_1` env var is getting set earlier now and then inherited into the child process. In v1.4 it was only set later when the first replay happens and only inherited after that.

So in that case the question then is, if you remove RenderDoc from the equation completely and just run vkcube.exe or your own program with `DISABLE_LAYER_NV_OPTIMUS_1=1` from the command line or visual studio, does vkcube.exe crash? What is the exact callstack - is it crashing in nvidia's driver or Intel's? Perhaps if the optimus layer is disabled the intel GPU is listed first, and it is intel's driver that is crashing.

**Comment by Raikiri** [comment] 2019-10-09 15:03
Indeed it does crash the same way if I set the environment value DISABLE_LAYER_NV_OPTIMUS_1=1 from command line myself. It does, however, run correctly if instead of setting env value, I launch it on either GPU from context menu->"Run with graphics processor" and I can tell that it's actually running on a different gpu this way at least due to huge performance difference. I wonder how many other laptops will fail as well to create a vulkan swapchain with DISABLE_LAYER_NV_OPTIMUS_1=1 set.

**Comment by baldurk** [comment] 2019-10-09 15:07
What is the actual callstack of the crash? What version is your intel GPU's driver?

**Comment by Raikiri** [comment] 2019-10-09 15:13
Here's the callstack:
![image](https://user-images.githubusercontent.com/1657728/66494396-15da1d80-eb14-11e9-85fd-df6928017511.png)
My Intel driver (trying to update it through device manager says that it's the latest available):
![image](https://user-images.githubusercontent.com/1657728/66494564-5a65b900-eb14-11e9-8272-a7840e6ffd11.png)

**Comment by baldurk** [comment] 2019-10-09 15:19
That driver is quite old. I have no idea what device manager does to try and update, I wouldn't trust it since it probably only checks windows update. The Intel website has newer drivers and they may contain a fix for this crash, and if not I'd recommend reporting it to Intel themselves. Otherwise there's not much I can do for a driver bug like this, when it's not RenderDoc related (as you can repro it just by disabling the optimus layer directly).

Disabling the optimus layer is deliberate as otherwise it can cause significant problems between capture and replay. Leaving it enabled is not an option. I didn't actually realise it wasn't being disabled properly on the first run before, that could have caused other problems.

**Closed as completed by baldurk** 2019-10-09 15:19 UTC
Labels: Bug, Need More Info

**Comment by Raikiri** [comment] 2019-10-09 15:24
Even with disabled optimus, why does it even try to run on Intel anyway? Maybe make the optimus-disabling thing a setting instead?

**Comment by baldurk** [comment] 2019-10-09 15:29
With vkcube.exe it will pick the first physical device available, which might be the Intel GPU. Each program will have its own logic for selecting physical devices from those available, disabling the optimus layer just means that they are all listed instead of having some removed - with recent loaders they will be listed in preferential order on Windows.

Disabling optimus is necessary to prevent potential incompatibility between capture and replay where the physical device used in one case isn't available in the other. If the intel driver crashes then that's a problem that needs to be solved within the driver itself - this could happen just as easily if a user disables the optimus layer and wants to use the Intel GPU.

**Comment by Raikiri** [comment] 2019-10-09 15:40
Updating intel driver did fix the issue. Still unsure about disabling optimus for the child process though: if you want to make sure that the replay runs on the same GPU as a capture, then disable optimus for renderdoc process itself and make sure it has all physical devices listed to find the device that the capture was recorded with. What's the point in disabling optimus for the child process? Otherwise it can unnecessarily mess up with how an app runs from within renderdoc and outside of it.

**Comment by baldurk** [comment] 2019-10-09 16:44
Keeping the environment as close as possible between capture and replay is important to minimise the chance of incompatibilities either now or in future. Disabling the optimus layer should work fine, especially now that the loader orders physical devices by GPU preference. You ran into an Intel driver bug which could happen at any time - it just so happened to be hidden by the optimus layer in this case.
