### ISSUE TITLE
Save Image Texture bug

### ISSUE THREAD

**Issue by JingYongWang** [baldurk/renderdoc#1479] opened 2019-08-01 02:41 UTC
## Description

After capture a scene from rednerDoc, I find miss  alpha data in .rdc
when save  image File Format is .png  , I need to do  Alpha mapping - discord
But .png default seeting is Preserve, Alpha mapping field for .png format is disabled,
I change .jpg format to save image with Alpha mapping - discord,
After I success save  .jpg file, save a .png fomat again,
The field about Alpha mapping is lock in discord
I think save imgae field keep the last status, and I can use Alpha discord in png Format.

Is it a bug for .png format can choose alpha discord?
Well it help me save a image file I need.
 

## Environment
Render v1.4
OS: Windows7

**Comment by baldurk** [comment] 2019-08-01 09:04
I'm not sure what the problem you're describing is. The alpha mapping options when saving textures are only relevant for texture formats like jpg or bmp which don't have an alpha channel themselves. With png, dds, and others the alpha channel can be losslessly saved into the texture so there's no need to try and remap it.

What is the actual problem or bug you are seeing?

**Comment by zao** [comment] 2019-08-01 15:08
I did some testing independent of the reporter, doing three exports in sequence from the same texture view of Willems' `particlefire` Vulkan sample. I did all of this with the 1.4 Linux binaries downloaded from the RenderDoc website.

* When exporting a PNG initially, the alpha mapping option is disabled and has the value Preserve.
The exported PNG has the same alpha as the texture.
* When changing to JPG, the alpha mapping option is enabled and I can change it to Discard.
The exported JPG doesn't have any transparency, as is expected.
* When changing back to PNG, the alpha mapping option is disabled but keeps the value Discard.
**The exported PNG appears opaque and has an all-white alpha channel according to GIMP**, not sure if there's an actual alpha channel in the file but both `file` and `ffprobe` says "rgba".

My interpretation is that they have an use case where discarding alpha for PNG on export is what they want but I feel that it's probably out of scope of RenderDoc to unnecessarily mangle output that can be represented in the chosen format.

There is however evidence of an actual bug where a disabled export option has effect on a format it shouldn't have an effect on.

**Comment by baldurk** [comment] 2019-08-01 16:05
Good catch! There was some leftover code that would discard the alpha for PNG (and TGA) by setting it to 255, even though that should not be supported as you point out in the texture save options being disabled.

**Comment by JingYongWang** [comment] 2019-08-05 05:03
Sorry for my poor english and  company **can't upload any code or image file to github**
Thanks for @zao  correctly reproduce experiment for my problem.

@baldurk
I also confused about dump image from RenderDoc GUI and using renderdoccmd.exe
What's the different between both?
Because I  tkink it should get the same .png result, but get different.
Can discuess in here?

**Comment by baldurk** [comment] 2019-08-05 09:42
If the bug you were talking about is the one @zao identified, I'll close this issue as it should be fixed now.

I'm not sure what image output you mean from renderdoccmd. renderdoccmd is not intended for direct use by users it's more of an internal tool. The only image output it has is dumping the thumbnail, which is not replayed but saved at capture time to allow quick preview of the .rdc file in file explorers etc.

If you see any differences between the replayed output and the thumbnail it may be due to non-determinism in the replay, bugs in the application, bugs in RenderDoc, or something else. I'd need to see a reproducible case to investigate.

**Closed as completed by baldurk** 2019-08-05 09:42 UTC
Labels: Bug, Need More Info
