### ISSUE TITLE
SV_Position are exactly NOT Credible

### ISSUE THREAD

**Issue by niepp** [baldurk/renderdoc#1789] opened 2020-03-24 01:46 UTC
## Description
In the drawcall‘s MeshViewer Widget, the mesh's SV_Position are exactly all the same value for a continue vertex segment， while the mesh's Input Position corresponding is not all the same. this is not Credible.
![企业微信截图_15849392587796](https://user-images.githubusercontent.com/7009960/77379281-46a4cb00-6db3-11ea-89b6-a108a1af1000.png)

## Steps to reproduce
1. open a rdc
2. choose the drawcall with eid of 7124.
3. see to mesh viewer widget,  notice the IDX from 480 to 528
  
    the rdc file is large and private, i can send email to you who need it!

## Environment

* RenderDoc version: 1.7
* Operating System: windows 10
* Graphics API: d3d11

**Comment by baldurk** [comment] 2020-03-24 10:38
I don't see any evidence of a RenderDoc bug here, the shader seems to be doing exactly what it should do for those vertices. Can you please explain exactly what is wrong?

**Comment by niepp** [comment] 2020-03-24 13:46
notice vertex from IDX 480 to 528,  the vs input position is not all same,  while the vs output position are all the same, evenly have no float error.  do you think this is credible？

**Comment by baldurk** [comment] 2020-03-24 14:01
Yes I looked at those vertices and I do think it's credible. It's entirely consistent with what your vertex shader is doing with the data for those vertices. If this isn't what you expect then I suggest you look at your shader, but unless you can say directly what the problem is I see no indication of a bug in RenderDoc here so I'm closing this issue.

**Closed as completed by baldurk** 2020-03-24 14:01 UTC
Labels: Bug, Need More Info
