### ISSUE TITLE
Miplevel 0 shown even if other level is bound

### ISSUE THREAD

**Issue by karyon** [baldurk/renderdoc#292] opened 2016-07-05 12:32 UTC
```
    glBindImageTexture(0, someTexture, miplevel, False, 0, GL_READ_ONLY, GL_R32F);
    glDispatchCompute(x, y, z);
```
In the outputs window, miplevel 0 is always shown, regardless of the `miplevel` parameter, which is somewhat incorrect since the shader cannot access level 0 at all in this case.

Additionally i noticed that the `Inputs` pane is never used when using textures as images, even if bound with `GL_READ_ONLY`.

**Comment by karyon** [comment] 2016-07-05 13:06
Two more minor issues:
* When pinning the texture view tab on such an image, selecting a miplevel, and then selecting a draw call (or rather, compute dispatch) that does not use that texture, the selected miplevel is reset to zero. this does not happen when selecting a draw call that uses the texture.
* I have several compute dispatches that calculate the different miplevels. manual mipmapping if you will. When selecting a dispatch call prior to the first call that writes into the texture at hand, it is completely black as expected. But, when selecting any of the dispatch calls that calculate a miplevel, i can see all miplevel's miplevel's contents, even if they are computed in a later call.

**Comment by baldurk** [comment] 2016-07-11 17:42
I managed to get your multiframesampling project compiling (it took a bit of work in itself!), but I don't see anywhere that it binds mip levels to images, and I'd like to have a sample I can work with when fixing these issues.

Do you have something you can push up that I can then build & run?

> Additionally i noticed that the `Inputs` pane is never used when using textures as images, even if bound with `GL_READ_ONLY`.

This one is a bit messy I suppose but I'm not sure there's a better way around this. Really the outputs pane means "resources bound to read/write API binding points - SSBOs and Image load/store" and the inputs means "resources bound to read-only API points, ie. textures".

To avoid API-specific concepts leaking out all over the place, I treat these two things as coarse namespaces and allow the individual APIs to map them to particular things. Picking out images that are bound as read-only in the read-write namespace and moving them over can cause clashes (say you have texture 1 bound and image 1 is read-only. Now what's the read-only resource 1?). It's complicated also by not being able to query out whether an image is specified as read-only in a shader via program introspection. Everything else about the resources that a shader expects can be associated with the shader, but this property of read-only-ness would have to come from the current state bindings, so there's no longer a fixed mapping depending on the shader's bindings.

Hopefully that's an understandable justification for leaving the names and categorisations as-is :). I think renaming them to read-write and read-only instead of output and input is even more confusing, and I don't know if there's a better name for "potentially read-write type resources" to name that category.

**Comment by karyon** [comment] 2016-07-12 10:02
i'm actually amazed you managed to compile it, wow :) you might need to use https://github.com/karyon/gloperate/tree/johannes_hacks, i draw something with GL_PATCHES and the gloperate API didn't provide that.

i pushed https://github.com/karyon/multiframesampling/tree/pushpull_wip_with_miplevels that renders something terribly broken into the miplevels of "pull buffer" and "push buffer" in the ImperfectShadowmap::pull method.

have to go now but will think a bit about the input/output texture thing tonight.

**Comment by baldurk** [comment] 2016-07-12 10:03
Yeh it took quite a while, and a lot of help from @Anteru on cmake stuff :). I came to roughly the same hack on gloperate to get it compiling & running.

Thanks! I'll look at this today.

**Comment by baldurk** [comment] 2016-07-12 18:45
I believe I've fixed a couple of the issues you were running into - first with the bound mip level not being properly picked up from the `glBindImageTexture` call, and second with locked textures having the mip level reset - they should now remain fixed to what you had it locked to, until you change it by e.g. going back to the 'following' tab and showing it up.

With the code you pushed though, I wasn't able to repro the last issue about having the contents of the texture show up at the wrong times - in the capture I made, the image was already full of data before looking at any dispatches that wrote to it. Presumably that's the previous frame's data although it's hard to tell. I didn't ever get it where it was all-black.

**Comment by karyon** [comment] 2016-07-20 07:56
locked textures work as expected now. and when selecting a texture in the output widget, the correct miplevel is opened.

however, the output pane itself still always shows miplevel 0 even if a different miplevel is bound.

i cannot repro the last issue as well. indeed i don't clear those buffers so i don't know what i saw there.

i thought about the naming of the input/output widget and while i understand that it's technically complicated because you can't get this information from the shader bindings, but i still think that having the widget "output" and having widgets in there that are definitely not output is... well, wrong. the name clashes could be solved by actually calling the resources "texture 1" and "image 1". but i don't have any suggestions for a simple implementation this if the program introspection API does not support this.

**Comment by baldurk** [comment] 2016-07-20 09:01
Just to be clear so you don't misunderstand - I'm closing the issue not to stop discussion (we can continue here even after the issue is closed, and open another bug if necessary), but just to clarify that the main bug is fixed now.

The thumbnail panes are just a preview of which texture is in which slot to be a bit easier to pick out at a glance than just a name. It deliberately doesn't track the main texture viewer controls like which mip is selected, the visible range, etc because if you expect one then you end up expecting them all. I think it's better to have a simple preview.

---

As to the input/output categorisation, I don't mean name clashes presenting names to the user - that's easy enough to solve. I mean name clashes internally. When RenderDoc reflects a shader it creates lists of read-only, read-write and uniform buffer resources as well as a mapping of how these can actually be found on the API binding points (in case the resources are mapped sparsely to binding points).

This representation is agnostic of how this actually maps in the specific API, so e.g. the texture viewer can say "Give me the 2nd read-only resource" and that means the same thing everywhere. If we can at any time take a read-write resource and have to move it into read-only without knowing in advance, then it places a significant code burden to be able to handle the fact that there might now be two 2nd read-only resources. Asking for it might give you two binding points. There needs to be a way to disambiguate - perhaps a third category "read-write resources that are treated as read-only". It basically comes down to a lot of special-casing just to handle this one thing, and while it's of course doable I don't think it's worth the maintenance cost. Especially since binding models are the place where all the APIs differ the most already so the code is already fairly complex.

Basically what it comes down to is that a READ_ONLY _image_ is still a read/write resource, just one that you are declaring that you won't write to. It's not the same as a _texture_ which is truly read-only. It's the same principle as passing C parameters by value or reference (`int foo` vs `int &foo`/`int *foo`). The first one is read-only, you can't change the outer value, while the second one is read-write. You can declare a variable as `const int &foo` or `const int *foo` and say that you will only read from it, but this is just a convenience indication for the compiler to enforce to catch bugs - the actual assembly that runs doesn't have any concept of const vs. non-const and indeed in C or C++ you can just cast away the const-ness and write anyway.

It's similar in OpenGL, if you read [ARB_shader_image_load_store](https://www.opengl.org/registry/specs/ARB/shader_image_load_store.txt) you'll see things like `imageLoad` being defined to take a `readonly` annotated image, and `imageStore` takes a `writeonly`. That's because it's not actually a different type of object, it's just a compiler annotation that lets you freely upcast from a read-only or read-write image to a read-only one.

**Closed by baldurk** 2016-07-20 09:01 UTC
Labels: status: to be verified, type: enhancement

**Comment by karyon** [comment] 2016-07-20 09:38
i understand the maintenance cost would be too high. i also see that putting readonly images into the inputs pane is technically not entirely correct. i still do think "outputs" is an oversimplification, but since i don't have a better suggestion (except maybe something like "read/write resources" but that's ugly indeed), i'll have to leave it at that :)

to clarify the thumbnail panes thing, i was not talking about any selection in the main texture view, but rather binding one specific miplevel as an image in opengl. for instance, in my case, i have miplevel 1 bound readonly, miplevel 2 bound writeonly, and miplevel 0 doesn't contain data and is not bound at all. the thumbnail pane in this case shows miplevel 0 (completely black) two times, which is unexpected (and not helpful :) )

although i admit using the miplevels for other data than just filtered values from the lower levels might be an edge use case.

if binding a texture (with all miplevels necessarily), miplevel 0 should probably be shown.

**Comment by baldurk** [comment] 2016-07-20 09:47
Yeh I certainly agree that "outputs" isn't great, it's just the best compromise I have so far. As an extra complication, framebuffer attachments are also listed there which aren't always read/write either - you could even have a read-only depth buffer that's just bound for depth testing :). I'll have in the back of my mind that it needs a better name, maybe one will come to me.

I see what you mean now for the thumbnails. Perhaps I could show the highest bound mip instead of mip 0 in the thumbnail, but I'm a little concerned about it jumping back and forth - I want the thumbnails to consistently be a recognisable image.

The case you're talking about of reading from one mip and writing into another is pretty common though so I might experiment with it - it's just that usually the mips will look about the same in the thumbnail.

There are other edge cases where the thumbnails don't particularly show anything useful, e.g. they typically display in the range 0-1 so depth buffers, images with negative values, etc won't show up usefully. I'm aware of these but I don't want to go down the route of trying to always make the thumbnails show the perfect thing in every case, as that's a huge rabbit hole to go down.
