### ISSUE TITLE
crash when requesting a capture in OpenGL application on Linux

### ISSUE THREAD

**Issue by graphitemaster** [baldurk/renderdoc#778] opened 2017-10-14 22:01 UTC
If I use the automatic capture with a delay I can get any Nth frame without issues, however when using print screen or the request capture button in qrenderdoc my application just crashes with:

```
 segfault at 4 ip 00007f080b3c93c6 sp 00007ffdf01a3bb0 error 4 in libnvidia-glcore.so.384.69
```
tried various capture options to no avail

some information:
renderdoc version: v0.91(built from 02fc28a3)
driver version: nvidia 384.69
opengl context version: 3.2

the way the application is run requires I set `LD_LIBRARY_PATH` to `.` since we have our own
shared objects in the binary path, this shouldn't be a problem I assume?

**Comment by graphitemaster** [comment] 2017-10-14 22:11
ah interesting, further inspection shows this is a result of using the option to capture callstacks...

**Comment by baldurk** [comment] 2017-10-17 23:19
Hi sorry for the delayed response, I was away.

The `LD_LIBRARY_PATH` should be fine, RenderDoc will append to it to locate its own library but it will leave in `.`. It being unique to capture callstacks is weird, especially if the crash is inside nvidia's library. I'll need to try to reproduce this myself and get back to you.

**Comment by baldurk** [comment] 2017-10-23 19:36
I can't reproduce this. I set up a fresh Ubuntu 17.10 install and ran one of [g-truc's opengl 3.2 samples](https://github.com/g-truc/ogl-samples) with nvidia's 384.90 driver, but even with callstack capture enabled everything works fine.

There must be something more going on here - can you try using one of the same samples (I used gl-320-texture-cube) and see if you get the same crash? that would isolate if it's a system-level difference or something with your program.

The weirdest part is that there should be absolutely no difference between queuing a capture and triggering one immediately. Can you clarify if that's still relevant, or if that was actually unrelated and it's really whether callstack capture is enabled or not?

**Comment by samsartor** [comment] 2017-11-09 18:38
I also have this issue. I am running Arch Linux and using the Aur package (RenderDoc v0.91). I am not using Nvidia drivers (laptop with on-board graphics):
```
00:01.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Richland [Radeon HD 8450G] (prog-if 00 [VGA controller])
	Subsystem: Lenovo Richland [Radeon HD 8450G]
	Flags: bus master, fast devsel, latency 0, IRQ 35
	Memory at e0000000 (32-bit, prefetchable) [size=256M]
	I/O ports at 3000 [size=256]
	Memory at f0300000 (32-bit, non-prefetchable) [size=256K]
	[virtual] Expansion ROM at 000c0000 [disabled] [size=128K]
	Capabilities: <access denied>
	Kernel driver in use: radeon
	Kernel modules: radeon
```

Here is what gdb shows during the explosion:
```
GNU gdb (GDB) 8.0.1
This GDB was configured as "x86_64-pc-linux-gnu".
(gdb) run
Starting program: /usr/bin/qrenderdoc 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
Log     - QRenderDoc initialising.
[New Thread 0x7fffe8e5a700 (LWP 18628)]
[New Thread 0x7fffe2399700 (LWP 18629)]
[New Thread 0x7fffe1909700 (LWP 18630)]
[New Thread 0x7fffe1108700 (LWP 18631)]
Warning - adbExePath not set, attempting to call 'adb' in working env
Log     - COMMAND: adb devices
[Thread 0x7fffe1108700 (LWP 18631) exited]
[New Thread 0x7fffe1108700 (LWP 18632)]
[New Thread 0x7fffccbfd700 (LWP 18633)]
[New Thread 0x7fffc7c3a700 (LWP 18641)]
[Thread 0x7fffc7c3a700 (LWP 18641) exited]
[New Thread 0x7fffc7c3a700 (LWP 18644)]
Version: OpenGL 4.1
[Thread 0x7fffc7c3a700 (LWP 18644) exited]
[New Thread 0x7fffc7c3a700 (LWP 18650)]
Log     - Got remote handshake: A3_linux (OpenGL) [18596]
Log     - Got a new capture: 0 (time 1510252056) 45647 byte thumbnail

Thread 1 "qrenderdoc" received signal SIGSEGV, Segmentation fault.
0x00007ffff41be5a1 in __memcpy_ssse3 () from /usr/bin/../lib/libc.so.6
(gdb) backtrace
#0  0x00007ffff41be5a1 in __memcpy_ssse3 () from /usr/bin/../lib/libc.so.6
#1  0x00007ffff5a0787f in QImage::copy(QRect const&) const () from /usr/bin/../lib/libQt5Gui.so.5
#2  0x00005555558b4289 in ?? ()
#3  0x00005555558b0252 in ?? ()
#4  0x00005555558b17ba in ?? ()
#5  0x00005555558b32d9 in ?? ()
#6  0x0000555555794878 in ?? ()
#7  0x0000555555c13f8e in ?? ()
#8  0x0000555555c13bef in ?? ()
#9  0x00007ffff5493662 in QObject::event(QEvent*) () from /usr/bin/../lib/libQt5Core.so.5
#10 0x00007ffff6384f2c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/bin/../lib/libQt5Widgets.so.5
#11 0x00007ffff638ca06 in QApplication::notify(QObject*, QEvent*) () from /usr/bin/../lib/libQt5Widgets.so.5
#12 0x00007ffff5463060 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /usr/bin/../lib/libQt5Core.so.5
#13 0x00007ffff54658b6 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () from /usr/bin/../lib/libQt5Core.so.5
#14 0x00007ffff54be6e4 in ?? () from /usr/bin/../lib/libQt5Core.so.5
#15 0x00007ffff1c4a270 in g_main_context_dispatch () from /usr/bin/../lib/libglib-2.0.so.0
#16 0x00007ffff1c4bf69 in ?? () from /usr/bin/../lib/libglib-2.0.so.0
#17 0x00007ffff1c4bfae in g_main_context_iteration () from /usr/bin/../lib/libglib-2.0.so.0
#18 0x00007ffff54bdcd1 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/bin/../lib/libQt5Core.so.5
#19 0x0000555555788ab2 in ?? ()
#20 0x00007ffff40a9f6a in __libc_start_main () from /usr/bin/../lib/libc.so.6
#21 0x0000555555617d0a in ?? ()
```
The capture still works (saves the file), the application remains running, and I can capture with PrtScn again. All that happens is qrenderdoc crashes.

**Comment by baldurk** [comment] 2017-11-09 18:48
This doesn't sound like the same crash to me at all - it's on a different IHV and the crash happens in a different place.

Can you open a new issue, and provide more information on how to repro the problem? Does it crash if you open the saved capture up later? Does it crash with all applications, or just your own? Sharing the application or the capture would be very helpful - the callstack seems to indicate some internal Qt problem which will be very hard to debug without being able to repro it.

**Comment by baldurk** [comment] 2018-03-06 15:56
Without more information I can't investigate this bug any further, so I'm closing this issue now. If you have any more to add then please comment here.

**Closed as completed by baldurk** 2018-03-06 15:56 UTC
Labels: Bug, Need More Info
