### ISSUE TITLE
OpenGL - RenderDoc crashes when trying to capture raylib example

### ISSUE THREAD

**Issue by raysan5** [baldurk/renderdoc#440] opened 2016-12-07 16:15 UTC
I've been trying to use RenderDoc with raylib examples but when I try to capture (Print Scr) program crashes.

raylib (http://www.raylib.com/, https://github.com/raysan5/raylib) is a simple C library I use to teach videogames programming. It uses internally OpenGL 3.3 Core, initialized using GLFW3 and GLAD for extensions loading. 

I would like to use RenderDoc to show students how raylib works internally but it crashes.

Key parts of OpenGL initialization are:

- [InitGraphicsDevice()](https://github.com/raysan5/raylib/blob/develop/src/core.c#L1446), this [line](https://github.com/raysan5/raylib/blob/develop/src/core.c#L1513) setups graphic context to OpenGL 3.3 Core (note that other versions can also be used but that's the default configuration).
- [rlglLoadExtensions()](https://github.com/raysan5/raylib/blob/develop/src/core.c#L1615), load required extensions using GLAD, [here it is the function implementation](https://github.com/raysan5/raylib/blob/develop/src/rlgl.c#L1368) and here it is [GLAD](https://github.com/raysan5/raylib/blob/develop/src/external/glad.h).

I tried to capture a [basic raylib example](https://github.com/raysan5/raylib/blob/develop/examples/core_basic_window.c). I tried RenderDoc on Windows 64bit, I tried RenderDoc 32bit and 64bit.

Please note that raylib uses F12 by default to get a screenshot, just [disabled this feature](https://github.com/raysan5/raylib/blob/develop/src/core.c#L2127) for testing but keeps crashing.

Also note that it could be related to [extensions loading](https://github.com/raysan5/raylib/issues/162) but not sure.

**Comment by baldurk** [comment] 2016-12-08 11:06
I can't reproduce this locally. Everything seems to work OK, the program launches and I can make captures:

![image](https://cloud.githubusercontent.com/assets/661798/21007567/55846946-bd35-11e6-9b8c-710b4e2d9f81.png)

I get the same result with a local build as with the 0.32 build. I generally recommend using the build that matches your windows - 64bit builds can capture 32bit and 64bit programs.

Can you give any more information on how to repro? what OS version are you on, what hardware are you using? Do you have anything in the logfile (help -> view diagnostic log file)?

If you are able to attach to the program before it crashes, perhaps by using the 'seconds delay' capture option, then it would be useful to know the callstack where the crash happens.

**Comment by raysan5** [comment] 2016-12-08 22:43
Hi @baldurk, thank you very much for checking this out so quickly and excuse me for the lack of so crucial information...

Crash happened on this equipment:
```
CPU:   Intel Core i7 3537U
GPU:   Intel HD Graphics 4000 (Direct3D 11, OpenGL 4.x)
OS:    Windows 10 Pro 64-bit (latest build)
```

I also tried it on a `Surface Pro 3` with this configuration:
```
CPU:    Intel Core i5 4300U
GPU:    Intel HD Graphics 4400 (Direct3D 11, OpenGL 4.3)
OS:     Windows 10 Pro 64-bit (build 14393)
```

The first PC is in my office and I don't have access right now, I'll update this issue with the log ASAP.

On Surface Pro 3 it doesn't crash but I just got a blank screen when running example through RenderDoc (no text, no capture message), it seems textures are not loaded properly. After capturing, no textures are listed and when trying to check pipeline, RenderDoc go to `Not responding`. (Log: [RenderDoc_2016.12.08_13.20.30.log.zip](https://github.com/baldurk/renderdoc/files/640758/RenderDoc_2016.12.08_13.20.30.log.zip))

Checking RenderDoc documentation more carefully I found:

> RenderDoc assumes your hardware/software configuration is able to create a core 4.3 context for replay, and also that `EXT_direct_state_access` and `ARB_buffer_storage` are available, both on replay and in capture.

Supposedly, Intel GPU 4400 supports OpenGL 4.3 and required extensions but not sure about Intel GPU 4000 (it's my office PC) need to check it again.

I remember it also failed on the school equipment, GPUs there are NVIDIA, I will try again and also update the issue with the logs for the different GPUs.

**Comment by baldurk** [comment] 2016-12-08 22:54
It seems like something went wrong in that log - there are references at the end to failing to create contexts, although I don't know if there's any way I can print error messages when they fail to create. That probably explains why it eventually stops responding as I guess everything stalls from there.

Unfortunately something I just noticed and fixed today is that when running a 32-bit program from 64-bit renderdoc, the logs don't get merged properly so the log you posted doesn't have the output from the running program. If you look in %TEMP%\renderdoc while the program is running you should see a separate file.

When you say you get a blank screen with no text, do you mean that RenderDoc's text is missing, or the text from your example?

I don't have an Intel machine handy at the moment to try and repro, but I have found issues with Intel in the past. I'll be interested to see what you have from NV as that's closer to what I can test with here and should be more reliable.

**Comment by raysan5** [comment] 2016-12-08 23:10
Here it is the log and .rdc from the %TEMP%\renderdoc folder: 
[core_basic_window_2016.12.08_23.59.50_frame5188.zip](https://github.com/baldurk/renderdoc/files/640803/core_basic_window_2016.12.08_23.59.50_frame5188.zip)

Blank screen:

<img width="1080" alt="renderdoc_raylib_capture_issue" src="https://cloud.githubusercontent.com/assets/5766837/21031340/2df9c40c-bda3-11e6-842b-ccbd25afd487.png">

On Monday I'll check on some different NVIDIA (Quadro 600, GTX 960) GPUs.

**Comment by raysan5** [comment] 2016-12-09 13:07
Just checked office PC (Intel HD Graphics 4000), the one that crashes on capture. I added the log in previous post but there is not much info on it...

I checked more carefully GPU capabilities and it seems OpenGL 4.3 is just partially supported; `ARB_buffer_storage` is supported but not `EXT_direct_state_access`, probably that's the reason for the crash. 

Here it is a glviewer screenshot:

![capture](https://cloud.githubusercontent.com/assets/5766837/21050025/a3c358f4-be18-11e6-9a50-b96b39ac6571.PNG)

Next week I'll check the NVIDIA GPUs.

**Comment by baldurk** [comment] 2016-12-09 14:03
The EXT_direct_state_access extension is only needed during replay - the capture will fail to open saying the hardware is unsupported if the extension isn't present, or it can't create a 4.3 context. During capture, even plain 3.2 with no extensions available _should_ capture fine.

The logs don't seem to have any interesting errors, but in fact the frame capture opens up OK on my machine (Win10 GTX 970):

![image](https://cloud.githubusercontent.com/assets/661798/21051383/e4d4e5f2-be17-11e6-8a7f-d7b267baea6f.png)

So I guess something is working right, even if it's not displaying properly on screen. I'm not sure what could cause this.

**Comment by raysan5** [comment] 2016-12-15 12:40
Hi @baldurk, here it is some updated information. I checked the example on the following GPUs (all of them under Windows 10 64bit):

- GeForce GTX 690/PCIe/SSE2
- Quadro 600/PCIe/SSE2
- GeForce GTX 750 Ti/PCIe/SSE2
- GeForce GTX 960/PCIe/SSE2
- GeForce GT 730M/PCIe/SSE2

In all this GPUs it work great, here there are the output logs:
 
[raylib_RenderDoc_GeForceGT730M.txt](https://github.com/baldurk/renderdoc/files/654644/raylib_RenderDoc_GeForceGT730M.txt)
[raylib_RenderDoc_GeForceGTX690.txt](https://github.com/baldurk/renderdoc/files/654645/raylib_RenderDoc_GeForceGTX690.txt)
[raylib_RenderDoc_GeForceGTX750Ti.txt](https://github.com/baldurk/renderdoc/files/654643/raylib_RenderDoc_GeForceGTX750Ti.txt)
[raylib_RenderDoc_GeForceGTX960.txt](https://github.com/baldurk/renderdoc/files/654642/raylib_RenderDoc_GeForceGTX960.txt)
[raylib_RenderDoc_Quadro600.txt](https://github.com/baldurk/renderdoc/files/654646/raylib_RenderDoc_Quadro600.txt)

I'll try to test it in some AMD GPU but it seems this issue is mostly related to Intel GPUs.

**Comment by baldurk** [comment] 2016-12-15 17:44
Hi, this makes some sense, if it's limited to Intel GPUs.

I've certainly found Intel drivers unreliable in the past, particularly for opengl. Can you make sure you're running the latest drivers just in case? sometimes that has helped in the past.

At the moment I'm not able to try and repro on my Intel machine, but I might be able to by the end of next week. I'll keep you posted if I find anything.

**Comment by baldurk** [comment] 2017-05-22 11:39
I've not been able to reproduce this, and there's been a fair amount of work on GL the past months including a workaround for at least one Intel bug I ran into. I'm going to close this down but if you're still having trouble let me know and we can see if there's anything else to do - I have a suspicion though that this is just an Intel driver bug.

**Closed by baldurk** 2017-05-22 11:39 UTC
Labels: status: need more info, type: bug
