### ISSUE TITLE
Capturing logs: unable to connect to child process & game crash

### ISSUE THREAD

**Issue by sibojia** [baldurk/renderdoc#403] opened 2016-10-20 17:27 UTC
I'm currently using renderdoc 0.31 64bit on Windows 8.1 (12GB RAM, NVIDIA GT650M), and I want to capture logs by launching "GTAVLauncher.exe" and then hooking into child process "GTA5.exe". I have disabled the system firewall and don't have other firewall softwares installed. The symptoms are:

1. renderdoc successfully injected into "GTA5.exe", and I'm able to capture logs in game by pressing F12. However the logs are not shown in the renderdoc UI after capturing. When double clicked the child process, a new window popped up for a few sec, and then closed. In the logs I found:

    ```
RENDERDOC:  [23:12:08]            hooks.cpp(  49) - Log     - Loaded and hooked into vulkan-1.dll, PID 4740
    RENDERDOC:  [23:12:08]    win32_network.cpp(  88) - Warning - accept: 10038
    RENDERDOC:  [23:12:08]    remote_access.cpp( 253) - Error   - Error in accept - shutting down server
    RENDERDOC:  [23:12:08]     dxgi_wrapped.cpp( 518) - Warning - Querying IDXGIObject for interface: GUID {7abb6563-02bc-47c4-8ef9-acc4795edbcf}
    RENDERDOC:  [23:12:08]      d3d11_hooks.cpp( 255) - Log     - Created wrapped D3D11 device.
```

    I can now only get the log files in the temporary folder.

2. The game crashes after several minutes, no matter I captured any logs or not. When I started the game without renderdoc injected, the RAM usage is about 2GB and stable. With renderdoc, the RAM slowly grows to 4GB, and further playing or capturing logs will cause the game to crash. The capture options are all set to default except the "hook into children" option.

**Comment by baldurk** [comment] 2016-10-20 17:46
Regarding 1. there have been a few reports of this before - see #362 for example. Unfortunately I've not been able to reproduce the problem, and the network error isn't very illuminating.

As mentioned in that issue I've pushed a branch debug-logging which has a lot more verbose logging around the socket communication. Can you build from source on that branch, and get the logs for both the UI side and particularly the game side, to see if there's any more information about what's going wrong? Without a repro case I'm limited in what I can do to investigate or fix.

About 2. this is also not really enough information to go to. It's certainly expected that RenderDoc will add memory overhead, and since it generally scales with VRAM usage which isn't typically shown when running without RenderDoc the 2GB extra figure seems quite plausible. In itself it doesn't explain the crash - I'd need to get a crash dump or callstack or log or something from when it crashes, or be able to reproduce the problem myself.

**Comment by sibojia** [comment] 2016-10-21 10:05
I runned the code under `debug-logging` branch. The relative logs are:
```
RENDERDOC:  [17:00:09]   target_control.cpp( 249) - Log     - Starting TargetControlServerThread with socket, connected and valid 1
RENDERDOC:  [17:00:09]    win32_network.cpp(  90) - Log     - getsockopt returned -1, error 10038
RENDERDOC:  [17:00:09]   target_control.cpp( 276) - Log     - After accept - socket is not connected or not valid at iter 6
```

I don't know the details of the code, just did some little experiments. I printed logs in `win32_network.cpp: Socket::AcceptClient` function, to show the `int err = WSAGetLastError();`.
(I googled the error 10035, it should be normal)
After I clicked the "Capture" button, two log files appeared. I think one of them was from the launcher and the other was from the child. The two logs are:
```
(launcher)
RENDERDOC:  [17:58:03]   target_control.cpp( 249) - Log     - Starting TargetControlServerThread with socket, connected and valid 1
RENDERDOC:  [17:58:03]    win32_network.cpp( 118) - Log     - err: 10035
RENDERDOC:  [17:58:03]    win32_process.cpp( 480) - Log     - Injecting renderdoc into process 5652
RENDERDOC:  [17:58:03]    win32_network.cpp( 118) - Log     - err: 10035
RENDERDOC:  [17:58:03]    win32_network.cpp( 118) - Log     - err: 10035
RENDERDOC:  [17:58:03]    win32_network.cpp( 118) - Log     - err: 10035
RENDERDOC:  [17:58:03]    win32_network.cpp( 118) - Log     - err: 10035
RENDERDOC:  [17:58:03]    win32_network.cpp( 118) - Log     - err: 10035
RENDERDOC:  [17:58:03]    win32_network.cpp( 106) - Log     - s != INVALID_SOCKET // (I also printed log here)
RENDERDOC:  [17:58:03]    win32_network.cpp( 118) - Log     - err: 10035
RENDERDOC:  [17:58:03]    win32_network.cpp( 118) - Log     - err: 10035
... This repeats forever
```
(child)
RENDERDOC:  [17:58:04]             core.cpp( 319) - Log     - RenderDoc v0.32 x64 (NO_GIT_COMMIT_HASH_DEFINED) capturing application
RENDERDOC:  [17:58:04]   win32_libentry.cpp(  66) - Log     - Loading into D:\Games\GTAV\Grand Theft Auto V\GTA5.exe
RENDERDOC:  [17:58:04]            hooks.cpp(  49) - Log     - Loaded and hooked into kernel32.dll, PID 5652
...
RENDERDOC:  [17:58:04]            hooks.cpp(  49) - Log     - Loaded and hooked into vulkan-1.dll, PID 5652
RENDERDOC:  [17:58:04]   target_control.cpp( 249) - Log     - Starting TargetControlServerThread with socket, connected and valid 1
RENDERDOC:  [17:58:04]    win32_network.cpp( 118) - Log     - err: 10035
RENDERDOC:  [17:58:04]    win32_network.cpp( 118) - Log     - err: 10035
RENDERDOC:  [17:58:04]    win32_network.cpp( 118) - Log     - err: 10035
RENDERDOC:  [17:58:04]    win32_network.cpp( 118) - Log     - err: 10035
RENDERDOC:  [17:58:04]    win32_network.cpp(  90) - Log     - getsockopt returned -1, error 10093
RENDERDOC:  [17:58:04]   target_control.cpp( 265) - Log     - Before accept - socket is not connected or not valid at iter 5
RENDERDOC:  [17:58:04]     dxgi_wrapped.cpp( 518) - Warning - Querying IDXGIObject for interface: GUID {7abb6563-02bc-47c4-8ef9-acc4795edbcf}
RENDERDOC:  [17:58:04]      d3d11_hooks.cpp( 267) - Log     - Created wrapped D3D11 device.
...
RENDERDOC:  [17:58:05]      d3d11_debug.cpp( 389) - Error   - Couldn't create pixel shader for RENDERDOC_CopyMSToArray 80070057
...
```
You can notice that the error has changed. I've also seen (error 10038 & after iter 4) and (error 10038 & iter 6). I haven't found a pattern for this...

**Comment by baldurk** [comment] 2016-10-25 10:08
I'm not sure why I wasn't able to earlier, but I was able to actually repro this with GTA 5. It turned out to be a GTA 5 specific bug, the application was calling `WSACleanup()` before it had ever called `WSAStartup()` - which meant that it destroyed the sockets I had created while hooking in initially.

I fixed it just by hooking those two functions and preventing broken applications from doing anything - it just returns an error value without actually doing the cleanup. Hopefully that should fix it now.

As a side note, I *really strongly* recommend against capturing by trying to inject into GTAVLauncher.exe fast enough to then capture the GTA5.exe process. Use the global hook as this is the exact case it's intended for, and it makes hooking very easy.

**Comment by sibojia** [comment] 2016-10-25 13:58
Thanks! I've tried the new version and everything works fine. I haven't used global hooks before, but now I found that it doesn't suffer from this problem, even with versions before this fix. 

As for the memory issue, I haven't seen the game crash now. However I found another problem when I tried to open multiple log files. The system RAM usage kept increasing, about 500mb per file (the log file itself is about 200mb). Is this normal?

**Comment by baldurk** [comment] 2016-10-25 18:18
It's expected that there will be much more memory used than the log file - it's compressed already, and there's more memory needed than just a 1:1 copy of what's on disk.

Are you seeing a continual increase that never stops/slows? I've seen cases where it won't necessarily go back down to the same memory usage after closing a log, but it eventually reaches a steady state. Do you see leaking behaviour where the usage just grows indefinitely?

**Comment by sibojia** [comment] 2016-10-26 07:44
Yes. Previously there was no problem on my laptop (Win 8.1), but now I'm working on a Win 10 desktop computer. When opening the same log file repeatedly, RAM grows from 300MB to 10GB, after that the OS warned low memory. 
![default](https://cloud.githubusercontent.com/assets/6429444/19717372/d329f902-9b92-11e6-9a78-1255adcc746a.PNG)
The image above is the performance monitor of VS 2015 when running from source. I opened a log, closed it, and re-opened it many times. RAM usage dropped a little when closing, but kept growing each time opening.

**Comment by baldurk** [comment] 2016-10-26 08:42
OK that's definitely a bug. My guess would be some D3D11 resource isn't properly released and so the d3d device etc all stays around keeping memory usage after the log is closed.

I'll try reproducing on my own captures of GTA5, but if you are able to upload the exact capture you are seeing the leak that would be helpful. It depends on how specific the bug is.

To keep things easier to follow, I split this into issue #406. I'm going to close this one since the original bug about being unable to connect is fixed now.

**Closed by baldurk** 2016-10-26 08:42 UTC
Labels: status: to be verified, type: bug
