### ISSUE TITLE
IDXGIKeyedMutex::AcquireSync is not handled well in d3d11_initstate.cpp

### ISSUE THREAD

**Issue by UMU618** [baldurk/renderdoc#3022] opened 2023-08-13 14:52 UTC
## Description

[MSDN](https://learn.microsoft.com/en-us/windows/win32/api/dxgi/nf-dxgi-idxgikeyedmutex-acquiresync) says:

AcquireSync can also return the following [DWORD](https://learn.microsoft.com/en-us/windows/desktop/WinProg/windows-data-types) constants. Therefore, you should explicitly check for these constants. If you only use the [SUCCEEDED](https://learn.microsoft.com/en-us/windows/desktop/api/winerror/nf-winerror-succeeded) macro on the return value to determine if AcquireSync succeeded, you will not catch these constants.

- WAIT_ABANDONED - The shared surface and keyed mutex are no longer in a consistent state. If AcquireSync returns this value, you should release and recreate both the keyed mutex and the shared surface.

- WAIT_TIMEOUT - The time-out interval elapsed before the specified key was released.

## Steps to reproduce

This is a code issue.

https://github.com/baldurk/renderdoc/blob/afb4d76dd260c767fed54987f31328e8d60599e4/renderdoc/driver/d3d11/d3d11_initstate.cpp#L197

## Environment

All

**Comment by baldurk** [comment] 2023-08-13 17:30
You have not explained what the actual bug is here.

Can you please explain the bug without referencing the source code, and provide actual steps to reproduce that can be used to reproduce that bug.

**Comment by debuggingbug** [comment] 2023-08-16 06:24
The return value of AcquireSync is not assigned to hr, so this must be a bug.

**Comment by baldurk** [comment] 2023-08-16 09:18
That does not address what I asked for, and explicitly does the opposite by again only referencing the code. Please explain what the actual bug is if you are encountering one.

**Comment by debuggingbug** [comment] 2023-08-17 13:47
When a shared resource has been AcquireSync(1, 0) and is encoding by a consumer , AcquireSync(0, 10) may be return WAIT_TIMEOUT.

**Comment by baldurk** [comment] 2023-08-17 16:09
I'll ask again, please explain what the problem is and share an application where I can reproduce it without making reference to any code or specific functions.

**Comment by baldurk** [comment] 2023-09-13 09:36
Closing this due to lack of activity from the reporter and no further information to investigate.

If you are the reporter and this bug is still a problem for you, or you are someone finding this issue and you believe this bug is still a problem and you have a reproducible test case and more information to share, please do not comment here and instead please open [a new issue](https://github.com/baldurk/renderdoc/issues/new/choose). You can reference this issue if you wish, but opening a new issue prevents confusion of accidentally linking two unrelated bugs and means that each issue can be handled in a clean process.

**Closed as completed by baldurk** 2023-09-13 09:36 UTC
Labels: Bug, Need More Info
