### ISSUE TITLE
Add support for DXIL shaders

### ISSUE THREAD

**Issue by Nielsbishere** [baldurk/renderdoc#1718] opened 2020-02-10 16:18 UTC
## Description

It seems like I am not allowed to use DXIL with RenderDoc. Capturing isn't enabled when doing so. It would be a great feature to be allowed to. I don't necessarily need extensions with DXIL such as raytracing or shader introspection, but I'd very much like to view information the same way as with DXBC. I'm assuming the problem you'd have is that you require a ID3D12ShaderReflection object and you can't use D3DReflect to acquire that. You can however link dxc and use the following code on the compiled blob:

```cpp
IDxcLibrary* lib{};
doHr(DxcCreateInstance(CLSID_DxcLibrary, __uuidof(IDxcLibrary), (void**)&lib));

IDxcBlobEncoding* binBlob{};
doHr(lib->CreateBlobWithEncodingOnHeapCopy(bin.data(), bin.size(), CP_ACP, &binBlob));

IDxcContainerReflection* refl{};
doHr(DxcCreateInstance(CLSID_DxcContainerReflection, __uuidof(IDxcContainerReflection), (void**)&refl));

doHr(refl->Load(binBlob));
doHr(refl->FindFirstPartKind(hlsl::DFCC_DXIL, &shaderIdx));

ID3D12ShaderReflection* shaderRefl{};
doHr(refl->GetPartReflection(shaderIdx, __uuidof(ID3D12ShaderReflection), (void**) &shaderRefl));

//... reflect
// .. Release objects
```
where bin is the binary as an `std::vector<std::uint8>`.

## Steps to reproduce

Get a DX12 binary with DXIL shaders.

## Environment

* RenderDoc version: v1.6 https://github.com/baldurk/renderdoc/commit/0e7f772596035137416be01766c2d61205efc63e
* Operating System: Windows 10 1909 18363.628
* Graphics API: DirectX 12 SM 6.0

**Comment by baldurk** [comment] 2020-02-10 16:26
Yes, you must query for support using `ID3D12Device::CheckFeatureSupport` and `D3D12_FEATURE_SHADER_MODEL` to see what shader models are supported, and it is illegal to use DXIL without that support being reported as available. If you're seeing this error then your code is incorrect and is not checking for support before trying to create a pipeline using DXIL.

**Comment by Nielsbishere** [comment] 2020-02-10 17:43
But SM 6.0 & DXIL is supported on all modern hardware, nvidia has added support to even very old GPUs (I don't fully know about AMD). It runs fine and I have an RTX 2080 Super with latest drivers, so by all standards it should be supported. DXBC (SM 5.0) is not stored for the shaders so cannot be used.

**Comment by baldurk** [comment] 2020-02-10 17:48
It also must be supported by the runtime, hence the feature check. Widely supported isn't the same thing as unconditionally supported.

**Comment by Pursche** [comment] 2020-02-13 14:17
I can't bring much to the conversation, but I would like to second the request to add DXIL support to RenderDoc.

If I understand you correctly Baldurk, his code is wrong because it doesn't query for the shader model support, but RenderDoc being injected is ultimately the reason the runtime reports that DXIL is not supported, is this correct?

My shaders run perfectly fine without injecting RenderDoc, or while debugging using PIX. But I would very much like to be able to completely uninstall PIX and use RenderDoc which is superior in so many ways.

**Comment by baldurk** [comment] 2020-02-13 14:35
Yes RenderDoc is intercepting the query and returning a lower shader model capability than the runtime/driver actually supports. It does this for other things that are unsupported as well like raytracing. My point is that your code could run on a different system where the runtime/driver doesn't support SM6 so you still need to query.

DXIL support is something I'm aware of but I currently don't have an estimate on when it may be supported. I do plan to handle it eventually but unfortunately by its nature DXIL is not particularly tool friendly and is really only intended for use by MS's runtime and drivers, so is going to be quite painful to support. Currently there are higher priority things to look at elsewhere.

**Comment by solid-angle** [comment] 2020-02-13 14:54
There are plenty of valid scenarios where someone might not support anything but DXIL. 

1) Kiosk or location-based system where you have fixed hardware.
2) Demo, sample, or R&D framework where supporting every hardware combination is not the goal. 
3) Most games look at PC scalability fairly late in the process - dropping down to SM5 would be considered PC scalability, and even if your engine can do it, you might not have everything compiling in SM5. Plus compiling two sets of shaders on shader generator systems like UE4 is a huge drag on development speed. 

So it's fine if you've put this on low on the priority list for other reasons, but let's acknowledge there are perfectly valid scenarios to only support SM6/DXIL.

**Comment by baldurk** [comment] 2020-02-13 14:59
Sure to be clear I'm not saying that everyone is forced to support SM5 nor that there aren't cases where it makes sense to only target SM6. What I mean is that you should at least check for it at startup even if all you do is "if less than SM6, fatal error".

**Comment by solid-angle** [comment] 2020-02-13 15:02
Probably, but that seems kind of a minor detail beside the point. 

The problem is people would like to use RenderDoc w/SM6, and RenderDoc doesn't support DXIL. DXIL, like it or not, has become part of the D3D12 ecosystem. 

I feel like this discussion detracted from that core issue.

**Comment by baldurk** [comment] 2020-02-13 15:13
I'm not sure I really understand what you're getting at. I understand that the request is to add DXIL support, that's why this issue is open and marked as an unresolved feature request to track that. It's not as if I'm closing this issue as resolved because the query exists. As I mentioned above I do plan to do it at some stage, and I get that until it's implemented then this is a blocker if you don't have any kind of fallback path.

I explained how to query for DXIL support because this is not only a RenderDoc problem, as if you were to run code that assumed DXIL support on a PC which didn't have it then you'd likely crash. Whether you have a fallback or a fatal error or whatever else is up to what makes sense for you. Having that feature query doesn't have any effect on when DXIL support might be added, so what's the problem with explaining it?

**Comment by Nielsbishere** [comment] 2020-02-13 15:27
Regardless; the GPUs that don't support SM6 are long gone by now (GTX 5xx series which were released 8 years ago) and if they aren't, they wouldn't be able to run the programs anyways (since they don't have enough VRAM). Intel still has integraded cpus that are very old that don't support it, so that could be the only reason to detect it.
Supporting DXIL by itself doesn't mean we want raytracing support. Like I mentioned; you don't have to support every extension. I'd be fine with just debugging DXIL without raytracing and then using pix for the remainder.

**Comment by baldurk** [comment] 2020-02-13 15:50
DXIL does require both hardware and software support, both in terms of a recent enough driver and recent enough version of windows, but I appreciate that it's quite possible you may be reasonably assuming that it's supported and in that case RenderDoc will disable capturing and display an error message. This isn't the only case where not checking for feature support or not checking error messages may trip you up while running under RenderDoc (e.g. trying to use raytracing interfaces will likely crash) which is why I pointed out the recommended way in the API to query for support. Whether you query or not, DXIL isn't supported currently so all it gives you is a nicer way to handle that case (whatever handling that may be).

Again, I understand that the feature request is to support DXIL and I never suggested that this wasn't a valid feature request, I honestly don't understand where anyone has gotten that impression. I also definitely know that it's possible to support DXIL without supporting raytracing and I get that there is value in supporting one without the other. I only mentioned raytracing in the context of another case where RenderDoc will change the reported functionality to less than what the driver supports.

As I mentioned above, supporting DXIL itself without any extensions is still a lot of work and right now it is not a priority to work on. This issue will track any progress and I will update here when DXIL support is implemented, as with any other feature request.

Unfortunately I have limited time and resources and that means I cannot instantly start working on every feature request that is made. I have to make a judgement call based on the amount of work required, the audience and the potential benefit. I appreciate that this is a blocking issue for projects that require DXIL, so for you it may be very important, but only a certain fraction of users are working on such projects so that must be weighed up against the benefit of features for a larger group of users.

**Comment by baldurk** [comment] 2020-06-19 18:02
I've pushed support for DXIL shaders and that commit removes the restriction on capturing and replaying as well as allowing up to SM6.6 from the CheckFeatureSupport query.

If you run into any bugs related to DXIL shaders (and I'm sure there will be some) please file them as new issues with a repro case.

**Closed as completed** 2020-06-19 18:02 UTC
Labels: Feature, Unresolved

**Comment by Nielsbishere** [comment] 2020-06-19 22:58
Thank you very much, will be very useful to me
