### ISSUE TITLE
Can we use RenderDoc to debug native application running on Android?

### ISSUE THREAD

**Issue by gittmi** [baldurk/renderdoc#1609] opened 2019-11-21 15:07 UTC
## Description
Can we use RenderDoc to debug native openGLES application on Android by chnaging the injection part? Currently, JDWP is used to inject .so file into apk. I believe we can't use the same mechanism for native binary.
on Linux I found LD_PRELOAD is used to inject our library. Can we use this mechanism to inject our .so file into native android application? 

## Environment

* RenderDoc version: v1.4
* Operating System: Android
* API: 28

**Comment by baldurk** [comment] 2019-11-21 15:30
You haven't explained what goes wrong, you've only mentioned some implementation details of RenderDoc and said that you "believe" it can't be used without outlining what goes wrong when launching your application. I don't know what you mean by a 'native application' - that term is vaguely defined and in an Android context usually refers to applications written in C/C++ (using android's "native" NDK). Almost all apps that use a graphics API will be written in C/C++ and that is absolutely supported by RenderDoc.

When reporting a bug the issue template is there for a good reason. Your description should explain what you are trying to do (in this case launch an android application for capture) and what goes wrong, and you should fill out the steps to reproduce field (in this case sharing an APK that doesn't launch properly). You should also fill out the environment section properly - you've put a random number in for the API field instead of specifying OpenGL ES.

If you continue to file issues in future without following the issue template properly they will be closed as with any other invalid issue. The reason for requiring a basic level of clarity for issues is to avoid wasting project resources untangling and investigating to even find out what the issue is.

You've said that you're using v1.4, so if you're having trouble I would recommend trying the latest released version of RenderDoc if you run into any problems as it may have a fix for your bug already.

**Comment by gittmi** [comment] 2019-11-22 05:14
Sorry. I am trying to know whether we can debug openGLES C/C++ application binaries (native binaries) on Android platform using RenderDoc. Because, currently on Android, I can see only list of apks available in "Launch application" window to select and debug. I wanted to check with you about possibilities of debugging a native binary instead of apk. 

API number I mentioned for Android API level as 28. I am working on Android P.

**Comment by baldurk** [comment] 2019-11-22 08:40
I'm still not clear on what you're describing, googling for 'android application binaries' or 'android native binaries' doesn't give any clear results. But you say that it's something which is not an apk, so whatever it is that's not supported. RenderDoc only supports capturing from APKs which is how applications are distributed on android.

**Closed as completed by baldurk** 2019-11-22 08:40 UTC
Labels: Bug, Need More Info

**Comment by lejay89** [comment] 2024-05-21 08:22
@baldurk we can also run executable binary on Android just like Linux, for example, /data/test/TestProgram. Will it be supported in the future?

**Comment by baldurk** [comment] 2024-05-21 09:14
Please do not comment on old issues that have been closed.

If you are encountering a bug or are requesting a feature please open [a new issue](https://github.com/baldurk/renderdoc/issues/new/choose). You can reference this issue if you wish, but opening a new issue prevents any confusion of accidentally linking two unrelated issues and means that each issue can be handled in a clean process.
