### ISSUE TITLE
VK_EXT_mesh_shader support

### ISSUE THREAD

**Issue by didito** [baldurk/renderdoc#2743] opened 2022-10-09 01:30 UTC
## Description

It would be great to have support for the new mesh shading extension `VK_EXT_mesh_shader`.

https://www.khronos.org/news/permalink/khronos-releases-vulkan-mesh-shader-pipeline-extension
https://www.khronos.org/blog/mesh-shading-for-vulkan

Hardware and drivers with support from multiple IHVs are out.
There's at least one public example: https://github.com/nvpro-samples/gl_vk_meshlet_cadscene

Besides supporting the new API calls I guess the Pipeline State Viewer would need some work to display the alternative flow and corresponding shader types (task and mesh). But it would be very similar to Compute. Mesh Viewer would likely need some work too.

## Environment

- RenderDoc version: 1.22
- Operating System: Win10 Pro x64 21H2 build 19044.2006
- Graphics API: VK

**Comment by didito** [comment] 2022-10-09 01:35
Of course it would be great if the changes would work for DX12 too

https://microsoft.github.io/DirectX-Specs/d3d/MeshShader.html
https://learn.microsoft.com/en-us/samples/microsoft/directx-graphics-samples/d3d12-mesh-shader-samples-win32/

**Comment by KlingelingelingDerEiermann** [comment] 2022-10-30 12:15
Is this feature planned? I'm happy to help if there's anything to do, but I'm not familiar with the RenderDoc codebase

**Comment by baldurk** [comment] 2022-10-30 14:01
It depends what you mean by planned. The issue is open so this is something I would like to support, but I'm not working on it now or starting work on it next.

**Comment by jmoguill** [comment] 2023-08-01 22:03
Hi, any updates regarding VK_EXT_mesh_shader?

**Comment by baldurk** [comment] 2023-08-02 09:14
If there are any updates then they will be posted on this issue, since this issue is about the feature request for VK_EXT_mesh_shader support.

**Comment by godlikepanos** [comment] 2023-11-06 09:53
@baldurk If you ever start working on mesh shaders and you are in need of content to test, feel free to reach out. There is not much Vulkan + mesh shaders content out there and that's the reason for offering something additional.

**Comment by tomjohnstone** [comment] 2023-11-09 02:49
I have very basic, working D3D12 support for mesh shaders here (among a bunch of other changes):

https://github.com/baldurk/renderdoc/compare/v1.x...tomjohnstone:renderdoc:chook?expand=1#files_bucket

Note: this does not include any UI changes that would be required for a complete feature.

**Comment by tomjohnstone** [comment] 2023-11-09 04:36
> @baldurk If you ever start working on mesh shaders and you are in need of content to test, feel free to reach out. There is not much Vulkan + mesh shaders content out there and that's the reason for offering something additional.

Nanite uses mesh shaders to capitalize on post transform cache when transforming verts

**Comment by baldurk** [comment] 2023-11-17 10:23
Mesh shader support has been merged into latest v1.x. There are likely still some bugs to fix but they should be reported separately. The limitations at the moment are no support for multiview and no equivalent way of visualising mesh inputs at all.

**Closed as completed by baldurk** 2023-11-17 10:23 UTC
Labels: Feature, Unresolved
