### ISSUE TITLE
RenderDoc crashes when trying to view drawcall

### ISSUE THREAD

**Issue by kachnicka** [baldurk/renderdoc#1438] opened 2019-07-03 20:32 UTC
## Description

Under specific circumstances (see Repro steps) RenderDoc goes down on picking drawCommand in the event browser. All other commands are ok. I assume its a "SPIRV -> readable" problem (or a syntax problem of mine, but program is working as intended with no layer reports).

I encountered this error on a large project, but i could reproduce it on draw_textured_cube from Vulkan sdk samples.

## Repro steps

All is needed is to include this kind of construction in vertex shader code. I have correctly working pipeline with VS, GS and FS stage passing information in this fashion, but to make RenderDoc crash its enough to include these lines in VS.
```
#define LIGHT_COUNT 4 

struct LightPosDir
{
	vec4 position;
	vec4 direction;
};
layout(location = 0) out PassData
{
	LightPosDir posDir[LIGHT_COUNT];
} outData;
```
You can copypaste this 
```
	"#define LIGHT_COUNT 4\n"
	"struct LightPosDir\n"
	"{\n"
	"	vec4 position; \n"
	"	vec4 direction; \n"
	"}; \n"
	"layout (location = 2) out PassData\n"
	"{\n"
	"	LightPosDir posDir[LIGHT_COUNT]; \n"
	"} outData; \n"
```
with updated `"#version 450\n"` on top to draw_textured_cube.cpp sample.

[draw_textured_cube_2019.07.03_19.56.34_frame0.rdc.zip](https://github.com/baldurk/renderdoc/files/3356736/draw_textured_cube_2019.07.03_19.56.34_frame0.rdc.zip)

## Environment

* RenderDoc build: v1.4
* Operating System: Windows 10
* API: Vulkan

Cube sample shaders were compiled by glslang coming with 1.1.77.0 Vulkan sdk, my other project crashes compiled by both 1.1.77.0 and 1.1.108.0.

**Comment by baldurk** [comment] 2019-07-03 21:05
The issue is with the shader patching to fetch mesh output data, it isn't properly handling arrays-of-structs in output variables since I've never heard of anyone doing that before, and it generates invalid SPIR-V.

I'll look into fixing the patching tomorrow, in the meantime as a workaround you can close the mesh viewer and it should load OK.

**Comment by baldurk** [comment] 2019-07-04 15:48
Should be fixed with that commit.

**Closed as completed** 2019-07-04 15:48 UTC
Labels: Bug, Unresolved
