### ISSUE TITLE
Fail to replay a 64-bit vulkan capture file on android

### ISSUE THREAD

**Issue by jyangsh** [baldurk/renderdoc#1063] opened 2018-08-03 04:29 UTC
## Description

Fail to replay a 64-bit vulkan capture on android. The capture is captured with a 64-bit apk on android. But the capture is failed to be reloaded by the RenderDoc on android. It looks the RenderDoc is using a 32-bit loader. Please see the log below.
[RenderDoc_2018.08.03_11.57.49.log](https://github.com/baldurk/renderdoc/files/2255944/RenderDoc_2018.08.03_11.57.49.log)

## Repro steps

1. Install a 64-bit vulkan apk on an android device.
2. Capture a trace with RenderDoc
3. Replay the capture with RenderDoc

## Environment

* RenderDoc build: v1.1, or renderdoc_2018_08_02_04dc71ce nightly build.
* Operating System: Android 9
* API: Vulkan

**Comment by baldurk** [comment] 2018-08-03 08:08
Can you post the android logcat log? This log only has the host side which doesn't show what's happening on the device unfortunately.

Also I haven't tested with Android 9, as I don't think it's officially released yet? Are you able to test on a released version of Android (8.1 or lower)?

**Comment by jyangsh** [comment] 2018-08-03 10:51
Here is the logcat log: 
[renderdoc.log](https://github.com/baldurk/renderdoc/files/2257081/renderdoc.log)

I don't have an older android system, so may not try it on released version soon.

**Comment by baldurk** [comment] 2018-08-03 11:09
This looks like it might be caused by the android OOM process killer, but the log isn't very clear since there doesn't seem to be a nice "killing process X due to out of memory" message. There are a lot of warnings about missing initial states for compressed images which is strange, although shouldn't directly cause any problems.

Without seeing the capture I can't tell if this is just because the capture requires a lot of memory to load, more than the device has, or if there's a problem that causes a leak or something like that. Are you able to share the capture file with me either here or privately to [my email](mailto:baldurk@baldurk.org?Subject=RenderDoc%20Issue%20#1063)?

If not, could you try either a simple demo like [Sascha Willems' demos](https://github.com/SaschaWillems/Vulkan) or something your app that's less resource intensive? Just to see if it is something specific to your app/capture or something general on your system.

**Comment by jyangsh** [comment] 2018-08-03 13:55
The app is the game, fortnite(vulkan version). We traced it with LunarG's vktrace tools and trimmed it to one frame. And then, used the RenderDoc to debug the frame, but it failed to be loaded.

**Comment by baldurk** [comment] 2018-08-03 14:59
I don't know what will happen when capturing from vktrace/vkreplay, but I really wouldn't recommend that. I'm not sure why you'd need to do that rather than just capturing directly. It could be that the extra memory caused by something in that process, I don't know.

I'm going to close this issue though as I do not provide support for capturing third party programs that you do not have ownership of. If you have problems with capturing your own program please open a new issue.

**Closed as completed by baldurk** 2018-08-03 14:59 UTC
Labels: Bug, Need More Info
