### ISSUE TITLE
replay is not the same as the captured image

### ISSUE THREAD

**Issue by zhouhuamin** [baldurk/renderdoc#1807] opened 2020-04-01 12:01 UTC
## Description

I capture a game, save rdc file, but replay is not the same as the captured image

## Steps to reproduce

open rdc file,  I will email you the rdc file, because rdc file is too big.  nearly 22M.

## Environment

* RenderDoc version: RenderDoc v1.7 @ dd69f8642, 2020-04-01
* Operating System: Android 9
* Graphics API: OpenGL ES 3.2

**Comment by baldurk** [comment] 2020-04-01 14:56
For future information, it's rude to send 40MB as a direct email attachment. You should upload such files to a file sharing website and share a link instead. It's especially rude to send two identical 40MB emails with duplicated attachments.

The RenderDoc version you have listed is not correct, that build listed is not from today 2020-04-01 it's from 2020-02-12. Lying about what version you are using will make it hard to determine the real bug. Your build is an unstable nightly build from several months ago - please test at least with the latest stable version v1.7, optionally with a recent nightly build if you want to check to see if the bug has been fixed since v1.7.

The captures you sent seem to be using invalid programs which have been created but not linked and have no shaders attached. If this is a renderdoc bug then it's something going wrong at capture time. Please ensure that your program is not invoking any undefined GL behaviour, if there are no errors reported by the driver and the latest stable version of RenderDoc still shows the problem I'd need to investigate the capture time to see more about what's going wrong. Would you be able to share the application with me privately?

**Comment by zhouhuamin** [comment] 2020-04-01 15:36
The RenderDoc reports that glProgramBinaryOES and glGetProgramBinaryOES are not supported. We wrote two functions based on glProgrameBinary. If we don't do this, the game will crash. Is this correct?

**Comment by baldurk** [comment] 2020-04-01 15:48
RenderDoc deliberately forces applications to upload shader source instead of program binaries, since program binaries are driver-specific and opaque. `GL_OES_get_program_binary` is not reported as supported so it's illegal to use `glProgramBinaryOES`, and the `glProgramBinary` variant from GLES 3.0 is emulated to act as if the uploaded binary is incompatible.

If your application uses `glProgramBinary` it **must** then check that the program successfully linked. If a binary is not supported by a driver then the link status will be set to false and you should fall back to uploading shader source. When running under RenderDoc binaries will always be reported as unsupported, but this can happen as well with any driver if the driver's binary format changes or the binary you are uploading was obtained on an incompatible driver.

If your application is using `glProgramBinary` and then not checking for success and uploading shader source as a fallback, then it is invoking undefined behaviour and this would explain the problem.

**Comment by zhouhuamin** [comment] 2020-04-03 11:13
Hi Baldur , Can you easily connect my computer remotely for debugging?

**Comment by baldurk** [comment] 2020-04-03 11:34
No I can't do that at all. Did you make sure that your application has a fallback path that doesn't use `glProgramBinary` or else correctly handles its failure? Are you able to share a reproducible test case with me?

**Comment by zhouhuamin** [comment] 2020-04-03 11:44
This game is quite special. You need to fill in the authentication information. You may not use it? 

Can you use the free TeamViewer software to connect to my computer?  Is it inconvenient for you to install the free TeamViewer software? I can send you the TeamViewer software version

**Comment by zhouhuamin** [comment] 2020-04-03 11:55
If it is convenient, would you come over and take a look? See if you can connect to my computer?

**Comment by baldurk** [comment] 2020-04-03 12:00
If you can't share the program with me then that's fine, but I will not do any remote debugging for many reasons.

You didn't answer my question - is your program correctly handling glProgramBinary failures?

**Comment by zhouhuamin** [comment] 2020-04-03 12:06
I believe my program has been processed correctly, you can not debug, you can open the latest version of RenderDoc tools and try to grab a look, you may find many problems? Then see if there is a better way? What do you think?

**Comment by zhouhuamin** [comment] 2020-04-03 12:12
I have opened the RenderDoc V1.7 program on my computer and connected to the phone. You can check the log information. You do n’t need to debug.

**Comment by baldurk** [comment] 2020-04-03 12:14
I'm afraid I don't understand what you're asking. If the problem is the same as before then the log won't show me enough information, but given what you've said before the problem was most likely that you were using glProgramBinary and not handling its failure correctly.

If you've fixed your program to not use glProgramBinary can you send another capture to me? Again as I said before **do not attach it to the email**, use a file sharing service to email me a link.

**Comment by zhouhuamin** [comment] 2020-04-03 12:21
I use the latest version of RenderDoc V1.7  ：RenderDoc_1.7_64.msi, try to grab again, the game crashes after opening the game, so the most direct way is to let you connect to my computer and see if the log information Useful for you.

**Comment by baldurk** [comment] 2020-04-03 12:32
I will not connect to your computer. Please stop bringing that up as it is not helpful. If you continue to do so I will close this issue.

If the program is crashing that's a different problem than the one that was originally described. It wasn't crashing previously as you were able to get a capture, what has changed since then? Can you give me any details about the crash such as where the callstack indicates it's crashing?

**Comment by zhouhuamin** [comment] 2020-04-03 13:00
I checked the log information with adb logcat and found that the program with process number 25507 hung up somehow and there was no stack information. It really looks like a headache

 

    Line 2242: 04-03 20:50:09.053 25507 25780 I AudioManager: In isBluetoothScoOn(), calling application: com.netease.blqx.mi

    Line 2244: 04-03 20:50:09.064 25507 25718 D native(MiLinkSDK)(misdk): Thread-3=>jni/base/../../common/CombineTCPSocket.cpp:tid-25718 OnReceive nReadCount=160

    Line 2245: 04-03 20:50:09.064 25507 25718 D native(MiLinkSDK)(misdk): Thread-3=>jni/milink/com_mi_milink_sdk_connection_ConnectionImpl.cpp:tid-25718 JNINetworkListener onRec

    Line 2246: 04-03 20:50:09.064 25507 25718 V ConnectionImpl(MiLinkSDK)(misdk): Thread-3=>postEventFromNative msg:onRecv, arg1=0, arg2=0 to SessionNo:2

    Line 2247: 04-03 20:50:09.064 25507 25718 V [No:2]SessionForSimpleChannel_20002(MiLinkSDK)(misdk): Thread-3=>recv data:160

    Line 2248: 04-03 20:50:09.064 25507 25718 V [No:2]ReceiveBuffer(MiLinkSDK)(misdk): Thread-3=>now mBuffer.len=1024,pos=0,recvLen=160

    Line 2249: 04-03 20:50:09.064 25507 25718 V [No:2]ReceiveBuffer(MiLinkSDK)(misdk): Thread-3=>parsePacket start

    Line 2250: 04-03 20:50:09.064 25507 25718 I [No:2]ReceiveBuffer(MiLinkSDK)(misdk): Thread-3=>getPacketLen start, mPosition=160

    Line 2251: 04-03 20:50:09.065 25507 25718 I [No:2]ReceiveBuffer(MiLinkSDK)(misdk): Thread-3=>parseNormalPacket start, packetLen = 160, mPosition=160

    Line 2252: 04-03 20:50:09.065 25507 25718 I [No:2]ReceiveBuffer(MiLinkSDK)(misdk): Thread-3=>parseNormalPacket [packetLen = 160]

    Line 2253: 04-03 20:50:09.066 25507 25831 D         : PlayerBase::PlayerBase()

    Line 2254: 04-03 20:50:09.066 25507 25718 V [No:2]StreamUtil(MiLinkSDK)(misdk): Thread-3=>recv data: len=160

    Line 2255: 04-03 20:50:09.066 25507 25718 V [No:2]StreamUtil(MiLinkSDK)(misdk): Thread-3=>down stream packet: seq=5, encodeType=10, flag=0

    Line 2256: 04-03 20:50:09.066 25507 25831 D         : TrackPlayerBase::TrackPlayerBase()

    Line 2257: 04-03 20:50:09.066 25507 25831 W libOpenSLES: Leaving Object::GetInterface (SL_RESULT_FEATURE_UNSUPPORTED)

    Line 2258: 04-03 20:50:09.066 25507 25831 I libOpenSLES: Emulating old channel mask behavior (ignoring positional mask 0x3, using default mask 0x3 based on channel count of 2)

    Line 2259: 04-03 20:50:09.066 25507 25831 D AudioTrack: set(): streamType 3, sampleRate 48000, format 0x1, channelMask 0x3, frameCount 0, flags #104, notificationFrames -20, sessionId 27753, transferType 0, uid -1, pid -1

    Line 2260: 04-03 20:50:09.066 25507 25831 W AudioTrack: notificationFrames=-20 clamped to the range -1 to -8

    Line 2262: 04-03 20:50:09.067 25507 25718 V ChannelAccount[No:1](MiLinkSDK)(misdk): Thread-3=>getB2Token=JYfJWB/TgyHoHA51XAA76azu9MlItTyCGigWQqdhDgw=

    Line 2263: 04-03 20:50:09.068 25507 25718 V ChannelAccount[No:1](MiLinkSDK)(misdk): Thread-3=>getB2Security=UMAhb0FbUwAP9P1f

    Line 2265: 04-03 20:50:09.069 25507 25718 V [No:2]StreamUtil(MiLinkSDK)(misdk): Thread-3=>mnscode:0, busicode:0, cmd=gamesdk.config.getinitconfig

    Line 2266: 04-03 20:50:09.070 25507 25718 V [No:2]StreamUtil(MiLinkSDK)(misdk): Thread-3=>cmd=gamesdk.config.getinitconfig, hasClientInfo =true

    Line 2267: 04-03 20:50:09.070 25507 25718 V [No:2]StreamUtil(MiLinkSDK)(misdk): Thread-3=>hasBusiContro = false

    Line 2268: 04-03 20:50:09.070 25507 25718 V [No:2]SessionForSimpleChannel_20002(MiLinkSDK)(misdk): Thread-3=> onRecvDownStream cmd=gamesdk.config.getinitconfig mnscode=0 seq=5 and set mNeedClientInfo=false

    Line 2271: 04-03 20:50:09.071 25507 25718 I [No:2]ReceiveBuffer(MiLinkSDK)(misdk): Thread-3=>getPacketLen start, mPosition=0

    Line 2272: 04-03 20:50:09.071 25507 25711 W SessionManagerForSimpleChannel_20002(MiLinkSDK)(misdk): SessionManagerForSimpleChannel_=>processMessage +3

    Line 2273: 04-03 20:50:09.071 25507 25718 I [No:2]ReceiveBuffer(MiLinkSDK)(misdk): Thread-3=>parseNormalPacket start, packetLen = -1, mPosition=0

    Line 2274: 04-03 20:50:09.071 25507 25711 W SessionManagerForSimpleChannel_20002(MiLinkSDK)(misdk): SessionManagerForSimpleChannel_=>SessionOtherEvent RequestMapIsEmpty

    Line 2275: 04-03 20:50:09.071 25507 25711 V SessionManagerForSimpleChannel_20002(MiLinkSDK)(misdk): SessionManagerForSimpleChannel_=>all session request map is empty, stopTimer

    Line 2277: 04-03 20:50:09.072 25507 25718 D native(MiLinkSDK)(misdk): Thread-3=>jni/base/../../kernel/TcpConnection.cpp:tid-25718 Thread looping......

    Line 2278: 04-03 20:50:09.072 25507 25718 D native(MiLinkSDK)(misdk): Thread-3=>jni/base/../../kernel/TcpConnection.cpp:tid-25718 begin to select... sockfd:83 pipefd:81 maxfd:83

    Line 2279: 04-03 20:50:09.073 25507 25831 I AudioTrack: AUDIO_OUTPUT_FLAG_FAST successful; frameCount 0 -> 1536

    Line 2284: 04-03 20:50:09.077 21178 21370 D Avrcp_ext: AudioManager Player: ID:23647 -- type:OpenSL ES AudioPlayer (Buffer Queue) -- u/pid:10409/25507 -- state:started -- attr:AudioAttributes: usage=USAGE_MEDIA content=CONTENT_TYPE_UNKNOWN flags=0x0 tags= bundle=null

    Line 2318: 04-03 20:50:09.083   732  3432 E AudioFlinger: open /proc/25507/cmdline error

    Line 2323: 04-03 20:50:09.086 25507 25831 I AudioManager: In isBluetoothScoOn(), calling application: com.netease.blqx.mi

    Line 2381: 04-03 20:50:09.111 25507 25611 I netease.blqx.m: ProcessProfilingInfo new_methods=302 is saved saved_to_disk=1 resolve_classes_delay=8000

    Line 2390: 04-03 20:50:09.507 25507 25780 W GaidUtils: Google Play services is missing.

    Line 2392: 04-03 20:50:09.581 25507 25507 W SdkDouYinShareAward: unknown function:setLanguage

    Line 2392: 04-03 20:50:09.581 25507 25507 W SdkDouYinShareAward: unknown function:setLanguage

    Line 2393: 04-03 20:50:09.581 25507 25806 E UniSDK AmapLocation: invalid method tag

    Line 2427: 04-03 20:50:10.028 25507 25782 I trace   : StorageToFileProxy [write] info=udid(可提供给平台方协助查询):4e88c054963a3f1b

    Line 2434: 04-03 20:50:10.362 25507 25831 I AudioManager: In isBluetoothScoOn(), calling application: com.netease.blqx.mi

    Line 2436: 04-03 20:50:10.407 25507 25780 I NeoX    : getRealSize p.x=2160 ,p.y=1080

    Line 2437: 04-03 20:50:10.410 25507 25780 I NeoX    : getRealSize p.x=2160 ,p.y=1080

    Line 2440: 04-03 20:50:10.712 25507 25780 W GaidUtils: Google Play services is missing.

    Line 2456: 04-03 20:50:11.731 25507 25780 I trace   : ###################################################################

    Line 2457: 04-03 20:50:11.731 25507 25780 I trace   : JNI [breakpad_callback] start 

    Line 2458: 04-03 20:50:11.731 25507 25780 I trace   : =======================================================

    Line 2459: 04-03 20:50:11.731 25507 25780 I trace   : [handleNCCrash]------jni callback java-----start

    Line 2460: 04-03 20:50:11.731 25507 25780 I trace   : ------------------------------------------------------------

    Line 2461: 04-03 20:50:11.731 25507 25780 I trace   : [handleNCCrash] call game crashCallBack

    Line 2465: 04-03 20:50:11.802  1278  1278 I Zygote  : Process 25507 exited due to signal (11)

    Line 2466: 04-03 20:50:11.803  2096  2138 I ActivityManager: Process com.netease.blqx.mi (pid 25507) has died: fore TOP 

    Line 2473: 04-03 20:50:11.804  2096  2149 W libprocessgroup: kill(-25507, 9) failed: No such process

    Line 2475: 04-03 20:50:11.804  2096  2149 I libprocessgroup: Successfully killed process cgroup uid 10409 pid 25507 in 0ms

    Line 2491: 04-03 20:50:11.814  2096  2147 V UidProcStateHelper: process died:[25507,10409]

    Line 2532: 04-03 20:50:11.908 15033 15091 D PowerKeeper: PerfEngineController:ForegroundInfo{mForegroundPackageName='com.miui.home', mForegroundUid=10045, mForegroundPid=24077, mLastForegroundPackageName='com.netease.blqx.mi', mLastForegroundUid=10409, mLastForegroundPid=25507, mMultiWindowForegroundPackageName='null', mMultiWindowForegroundUid=-1, mFlags=0}

    Line 2542: 04-03 20:50:11.909  3545 28872 D GameBoosterService: onGameStatusChange foreground:ForegroundInfo{mForegroundPackageName='com.miui.home', mForegroundUid=10045, mForegroundPid=24077, mLastForegroundPackageName='com.netease.blqx.mi', mLastForegroundUid=10409, mLastForegroundPid=25507, mMultiWindowForegroundPackageName='null', mMultiWindowForegroundUid=-1, mFlags=0}

    Line 2639: 04-03 20:50:11.942  2096  2154 W ActivityManager: setHasOverlayUi called on unknown pid: 25507

**Comment by baldurk** [comment] 2020-04-03 13:23
You are ignoring questions I ask to help diagnose the problem and that makes things a lot harder. I asked before - what changed in your code between you being able to capture and not? That narrows down the area the problem could be.

The logcat looks like your program has a custom crash handler of some kind. Either use that to get more information about what is failing, or else disable it so that the default crash handler will print a callstack and tell you where the crash is happening.

**Comment by zhouhuamin** [comment] 2020-04-07 12:38
Hello, finally got the rdc file, can you see what the problem is? The file blqx-003.rdc is placed in the following link: https://github.com/zhouhuamin/testcase

Version v1.8 (built from fcb82ae7)

**Comment by baldurk** [comment] 2020-04-07 13:37
The capture linked is corrupted and cannot be opened, it contains some mismatched chunk data that leads to a failure to load. Please confirm that you see the same thing and can't open the capture at all, since there's no way this could be successfully opened on the build you mentioned.

Was this captured on a completely unmodified nightly build of RenderDoc, or was this captured from a customised version of RenderDoc with source changes? If this was captured from an unmodified nightly build then I can't explain what went so wrong unless your application is trampling on RenderDoc's memory. This is another different bug, not related to what you originally described, and if it's a real bug I would definitely need to be able to debug the application at capture time. Unlike the original problem which could theoretically be debugged by running builds with extra logging.

**Comment by zhouhuamin** [comment] 2020-04-08 12:45
Hello,  got the rdc file, can you see what the problem is? The file blqx-004.rdc is placed in the following link: https://github.com/zhouhuamin/testcase

Version v1.8 (built from 1d64fffd)

**Comment by baldurk** [comment] 2020-04-08 13:11
I'm not going to investigate this any more unless you give clear and specific answers to the questions I've already asked. By not answering when I try to help you are wasting my time either deliberately or through carelessness, and I'm not going to continue with a guessing game where I can't get enough information to find the problem.

**Comment by zhouhuamin** [comment] 2020-04-08 13:16
The last file blqx-003.rdc was generated by the customized RenderDoc. The customized code may have problems. It has been deleted, and the latest RenderDoc code has been pulled back for testing. The problem at the beginning can be entered. it is good

**Comment by baldurk** [comment] 2020-04-08 13:29
OK thank you for clarifying that. In future absolutely do not make any local changes to RenderDoc while I'm trying to investigate this to help you, or else I cannot tell what problems are real bugs, what problems are from your program, and what problems are from your changes to RenderDoc.

Have you confirmed that your program is not using glProgramBinary in any way?

**Comment by zhouhuamin** [comment] 2020-04-08 13:39
In the program, glProgramBinary is used, and the source shader used after the failure is relinked. The program seems to be multi-threaded. Do you have any plans for multi-threaded support?

**Comment by baldurk** [comment] 2020-04-08 16:40
Multi-threading is supported on most APIs, OpenGL's threading support is terrible so it's not supported if you're rendering from multiple threads simultaneously. I recently added a hack that may work in some scenarios but it's not guaranteed.

That wouldn't explain the capture that still has programs that don't have any shaders attached and haven't been linked.

Since you can't share your application, can you download and run [this build with extra logging](https://renderdoc.org/1807_logging_build1.zip). Take a capture with it and share both the capture as well as the complete diagnostic log (from Help -> View diagnostic log -> Save).

**Comment by zhouhuamin** [comment] 2020-04-09 14:04
This version crash when I launch my application. my version have a change about RenderDoc, I followed my changes in #1758. I don't know which extension caused this problem.

Attach the log information of this version https://github.com/zhouhuamin/testcase/20200409.log, I hope you will give me a test version after fixing the bug, grab the rdc file and log file and send it to you.

**Comment by baldurk** [comment] 2020-04-09 15:19
You're still talking about running versions with some unknown local changes even after I specifically asked you not to. You are wasting my time through this process and I'm not going to continue this investigation further trying endlessly to obtain your co-operation.

I'm willing to help guide an investigation and work together to gather the necessary information as I understand that not everyone can freely share their programs or their captures. I've done that successfully with many other people. You have consistently omitted important information, avoided answering questions, run custom builds, and changed the discussion of what the bug actually is more than once. You have exhausted my willingness to work with you to determine what the problem is. In future if you do not provide a precise and clear reproducible test case for any issues I will close them, as I won't be drawn into this again.

To anyone else please don't take this as an indication that I'm unwilling to help with bugs. As long as you are willing to co-operate and help me to help you, there is no problem.

**Closed as completed by baldurk** 2020-04-09 15:19 UTC
Labels: Bug, Need More Info
