### ISSUE TITLE
Renderdoc visualization is different from the actual window

### ISSUE THREAD

**Issue by zcorniere** [baldurk/renderdoc#2445] opened 2022-01-10 11:54 UTC
## Description

The actual Vulkan window :
![Screenshot_20220108_204728](https://user-images.githubusercontent.com/44707748/148657741-42018d80-5e5d-4dc3-93c8-fea4b4c04927.png)
The RenderDoc window :
![Screenshot_20220108_204736](https://user-images.githubusercontent.com/44707748/148657742-3df928d3-eaac-4cc0-9802-18c4e1dda368.png)

To be clear, there is a bug in my code because RenderDoc view is the expected one. But shouldn't RenderDoc texture viewer display the same image as the window ?

## Steps to reproduce

Clone this project
https://github.com/EIP-Pivot/editor

On the branch `vulkan_improvement`
`mkdir build && cd build && cmake .. && cmake --build .`

Run it inside RenderDoc

## Environment

* RenderDoc version: stable 1.17
* Operating System: Linux
* Graphics API: Vulkan

I'm running an NVIDIA RTX 3060 Laptop with Vulkan version 1.2.202.

**Comment by baldurk** [comment] 2022-01-10 12:14
RenderDoc does not guarantee that it will work in the presence of undefined behaviour, it's only intended to debug valid uses of the API which are not working as intended. If you have a bug in your program where it may work on one driver and break on another - or in general behave unpredictably depending on how the undefined behaviour works out - it may indeed show up differently in RenderDoc. That's expected, and indeed in that case RenderDoc may even crash depending on what the undefined behaviour is.

This is especially true on Vulkan where the API and driver are not intended to do any kind of error-correction or help and undefined behaviour is easier to hit. You should use the vulkan validation layers and other validation mechanisms to check that your program.

If you fix all the problems with your code and don't believe you have any bugs and RenderDoc is still inconsistent, then that would be a RenderDoc bug so please feel free to open a new issue. I'm afraid though it's not feasible for me to provide general code debugging support, so I'll close this issue.

**Closed as completed by baldurk** 2022-01-10 12:14 UTC

**Comment by zcorniere** [comment] 2022-01-10 12:16
Yeah I understand, sorry for the inconvenience.

**Comment by baldurk** [comment] 2022-01-10 12:23
It's no problem, it's just that there's limits to what I can reasonably investigate and from your description this suggests it's more likely to be an application bug than a RenderDoc bug, As I say it's certainly possible for RenderDoc bugs to cause incorrect display, but that's more likely to be when it displays something _wrong_ vs the application - if it displays what you originally intended then most of the time that's caused by undefined behaviour which RenderDoc ends up hiding by coincidence.
