### ISSUE TITLE
Crashes and validation warnings on AMD hardware

### ISSUE THREAD

**Issue by kd-11** [baldurk/renderdoc#795] opened 2017-11-05 22:27 UTC
This issue has been there for some time now, For the longest time, replaying rpcs3 traces with renderdoc using vulkan usually crashes if textures are used. This affects captures captured on the same device that is also replaying the trace. A snippet of the issues raised by forcing validation layers is as follows

```
RDOC 011088: [01:18:37]          vk_core.cpp(2708) - Warning - [DS:8578/12] vkBindImageMemory(): Binding memory to image 0x23d but vkGetImageMemoryRequirements() has not been called on that image.
RDOC 011088: [01:18:37]          vk_core.cpp(2708) - Warning - [DS:8578/12] vkBindImageMemory(): Binding memory to image 0x243 but vkGetImageMemoryRequirements() has not been called on that image.
RDOC 011088: [01:18:37]          vk_core.cpp(2708) - Warning - [DS:8578/12] vkBindImageMemory(): Binding memory to image 0x246 but vkGetImageMemoryRequirements() has not been called on that image.
RDOC 011088: [01:18:37]          vk_core.cpp(2708) - Warning - [DS:8578/12] vkBindImageMemory(): Binding memory to image 0x254 but vkGetImageMemoryRequirements() has not been called on that image.
RDOC 011088: [01:18:37]          vk_core.cpp(2708) - Warning - [DS:8578/12] vkBindImageMemory(): Binding memory to image 0x259 but vkGetImageMemoryRequirements() has not been called on that image.
RDOC 011088: [01:18:37]          vk_core.cpp(2708) - Warning - [DS:8578/12] vkBindImageMemory(): Binding memory to image 0x25d but vkGetImageMemoryRequirements() has not been called on that image.
RDOC 011088: [01:18:37]          vk_core.cpp(2708) - Warning - [DS:8611/390072370] vkBindImageMemory(): memory size minus memoryOffset is 0x2b000 but must be at least as large as VkMemoryRequirements::size value 0x2f600, returned from a call to vkGetImageMemoryRequirements with image. The spec valid usage text states 'The size member of the VkMemoryRequirements structure returned from a call to vkGetImageMemoryRequirements with image must be less than or equal to the size of memory minus memoryOffset' (https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#VUID-vkBindImageMemory-size-01049)
RDOC 011088: [01:18:37]          vk_core.cpp(2708) - Warning - [DS:8578/12] vkBindImageMemory(): Binding memory to image 0x262 but vkGetImageMemoryRequirements() has not been called on that image.
RDOC 011088: [01:18:37]          vk_core.cpp(2708) - Warning - [DS:8578/12] vkBindImageMemory(): Binding memory to image 0x266 but vkGetImageMemoryRequirements() has not been called on that image.
RDOC 011088: [01:18:37]          vk_core.cpp(2708) - Warning - [DS:8578/12] vkBindImageMemory(): Binding memory to image 0x26a but vkGetImageMemoryRequirements() has not been called on that image.
RDOC 011088: [01:18:37]          vk_core.cpp(2708) - Warning - [DS:8611/390072370] vkBindImageMemory(): memory size minus memoryOffset is 0xae000 but must be at least as large as VkMemoryRequirements::size value 0xb1e00, returned from a call to vkGetImageMemoryRequirements with image. The spec valid usage text states 'The size member of the VkMemoryRequirements structure returned from a call to vkGetImageMemoryRequirements with image must be less than or equal to the size of memory minus memoryOffset' (https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#VUID-vkBindImageMemory-size-01049)
RDOC 011088: [01:18:37]          vk_core.cpp(2708) - Warning - [ParameterValidation:873/9] vkBindImageMemory: returned VK_ERROR_INITIALIZATION_FAILED, indicating that initialization of an object has failed
RDOC 011088: [01:18:37]          vk_core.cpp(2708) - Warning - [MEM:535/180357112] vkCreateImageView(): VkImage object 0x26a used with no memory bound. Memory should be bound by calling vkBindImageMemory(). The spec valid usage text states 'If image is non-sparse then it must be bound completely and contiguously to a single VkDeviceMemory object' (https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#VUID-VkImageViewCreateInfo-image-01020)
RDOC 011088: [01:18:39]   resource_manager.h( 841) - Debug   - Applying initial contents
Exception thrown at 0x00007FFBF1A2FDC5 (amdvlk64.dll) in qrenderdoc.exe: 0xC0000005: Access violation reading location 0x0000000000000008.
```

The access violation there happens when executing a pipeline barrier to initialize image subresources from IMAGE_LAYOUT_UNDEFINED to IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL. It always happens in Apply_InitialState and is almost always reproducible.

Call stack if desired:
![image](https://user-images.githubusercontent.com/15904127/32419822-62b1958c-c291-11e7-9055-92f6e17217d3.png)

I'm on windows 10, R9 270x Crimson 17.9.2 but the issue dates back since the 0.2x days. If you need any more info, let me know.

**Comment by baldurk** [comment] 2017-11-05 22:37
Can you upload the full output log somewhere? just for context. Having memory requirements not be satisfied on replay sounds quite weird - there was an issue in the past where I added some extra usage bits for replay and so the memory requirements changed, but I fixed that a while ago so it should always add the same usage bits on capture and replay.

I've seen this crash before, if the memory bind fails then the initial state barrier is usually the first use that trips up over it, so the memory bind failure is most likely the root cause. It's presumably some edge case as I've not heard of this before when capturing and replaying on the same device - let that be a lesson that I can't fix bugs which don't get reported to me, even if they're long-standing :wink:.

To investigate this I'm going to need a repro case of some kind. Is there any guide for me to set up rpcs3  myself and run it on a simple demo or something that will exhibit the bug?

**Comment by kd-11** [comment] 2017-11-06 10:09
Sample full log https://gist.github.com/kd-11/eaeae4a2e0cc220b07d997804236478d
The issue does not appear with simple tests but I'll keep checking for a simple reproducible case/demo that will reproduce the issue.
And yes, I'm ashamed to admit it was easier to just brush aside the issue as another AMD driver bug

**Comment by kd-11** [comment] 2017-11-06 10:21
Found a simple test case. The homebrew title "hero city 2" exhibits this issue under rpcs3. You can find this demo here http://store.brewology.com/ahomebrew.php?brewid=153

Log output https://gist.github.com/kd-11/fd86386d00b9b0edbd9d4939bc3d8f95

Rpcs3 setup is very easy (nowadays), Just download from the site here https://rpcs3.net/download
Select your target GPU and renderer and the other default options should work just fine.

**Comment by baldurk** [comment] 2017-11-06 10:27
Hmm, that looks like it might be a different issue to me - there are no messages about `vkBindImageMemory` failing and it doesn't look like it crashes in `Apply_InitialState` like the original log - I can't tell where it did actually crash. I'll try to repro this just now, but can you clarify what's happening in that test case?

**Comment by baldurk** [comment] 2017-11-06 11:35
Just to update - I was able to capture & replay OK with "hero city 2" on a few scenes without any crashes. That might be due to different hardware (RX 480 here) or driver (Crimson 17.10.1), but as I mentioned above I'm not sure what exactly I should be running into as the log output you pasted doesn't have any error messages - I get similar validation warnings to you but none of those should be a problem.

**Comment by kd-11** [comment] 2017-11-06 13:01
Hero city 2 doesnt crash, just shows the warnings about BindImageMemory without querying the memoryRequirements. I have yet to find something thats small and easy to reproduce that end up in a segfault. I can provide you with an rdc that will give the exception if you like, and I'd have to ask around first if polaris is affected.

**Comment by baldurk** [comment] 2017-11-06 13:11
Ahh, I see. Yeh that warning is kind of meaningless for renderdoc - that happens for every call to `vkBindImageMemory` I replay. I use the exact same memory requirements that the application did, so even if I did call `vkGetImageMemoryRequirements` I wouldn't be able to change anything since it's too late to change anything.

I suppose I could just call the function and throw away the result (or verify that the requirements are satisfied and print an early warning that the capture is being replayed on incompatible hardware).

**Comment by kd-11** [comment] 2017-11-06 15:18
It might be that the requirements are a match since the replay is on the same device. In fact it crashes when loading after app closes. Looks like the allocated memory does not satisfy offset alignment + size requirements or alignment robs the block of some size. On pitcairn alignment is 2048 bytes for bc3 but something like 32k for bgra8. Bc3 is one of the formats that trigger this for example. The only difference I can see is that you use a large pool and allocate from there while on rpcs3 its always a new memory block and therefore offset parameter is always 0 satisfying the condition of size - offset must fit memoryrequirements.size

**Comment by baldurk** [comment] 2017-11-06 15:31
That's the weird thing, RenderDoc uses 100% the same memory allocation sizes, offsets, bindings as the application does. It doesn't move allocations into a pool or anything, it just replays them 1:1. So if the requirements are satisfied by the application during capture-time, they should also be satisfied at replay-time.

If RPCS3 is always using a new memory block, then that implies the required size is changing. I'm just not sure why it would be - as I mentioned I do add some usage bits for renderdoc's internal work, but I add the same bits on capture and replay. So you might find that with renderdoc enabled your application allocates more than without, but that's necessary to be sure you allocate enough for the requirements to be satisfied during replay.

Of course this all goes out the window if you replay on a different device. The solution for that is in future renderdoc will falsely inflate the requirements to the point where they should satisfy any (reasonable) hw. For now, hw must be similar enough that the requirements are equal or less strict.

If you're able to debug renderdoc a bit, I'd be interested to know if you can find if any parameter is changing when it shouldn't be. In `WrappedVulkan::vkCreateImage` you can add some code right after `ObjDisp(device)->CreateImage` to inspect the memory requirements. That will let you see what the requirements were at capture time (or you might be able to debug yourself in your own code). At replay time, it will go through `WrappedVulkan::Serialise_vkCreateImage` and you can add the same code just after `ObjDisp(device)->CreateImage` again. Maybe that will show up what's changing.

Example patch:

```diff
diff --git a/renderdoc/driver/vulkan/wrappers/vk_resource_funcs.cpp b/renderdoc/driver/vulkan/wrappers/vk_resource_funcs.cpp
index 5d2a173..51e918d 100644
--- a/renderdoc/driver/vulkan/wrappers/vk_resource_funcs.cpp
+++ b/renderdoc/driver/vulkan/wrappers/vk_resource_funcs.cpp
@@ -1179,6 +1179,11 @@ bool WrappedVulkan::Serialise_vkCreateImage(Serialiser *localSerialiser, VkDevic

     VkResult ret = ObjDisp(device)->CreateImage(Unwrap(device), &info, NULL, &img);

+    {
+      VkMemoryRequirements mrq = {};
+      ObjDisp(device)->GetImageMemoryRequirements(Unwrap(device), img, &mrq);
+    }
+
     info.usage = origusage;

     if(ret != VK_SUCCESS)
@@ -1259,6 +1264,11 @@ VkResult WrappedVulkan::vkCreateImage(VkDevice device, const VkImageCreateInfo *
   VkResult ret =
       ObjDisp(device)->CreateImage(Unwrap(device), &createInfo_adjusted, pAllocator, pImage);

+  {
+    VkMemoryRequirements mrq = {};
+    ObjDisp(device)->GetImageMemoryRequirements(Unwrap(device), img, &mrq);
+  }
+
   // SHARING: pCreateInfo sharingMode, queueFamilyCount, pQueueFamilyIndices

   if(ret == VK_SUCCESS)
```

**Comment by kd-11** [comment] 2017-11-06 15:34
Yea. I can do that and have results shortly. If the replay is 1:1 then I agree the size requirement must have changed somehow.

**Comment by kd-11** [comment] 2017-11-06 16:10
Yea, you're right. Putting the same information into VkImageCreateInfo then calling GetMemoryRequirements on it can give wildly varying results on my system. 

Examples
```
RDOC 011688: [19:02:44] vk_resource_funcs.cpp(1187) - Warning - Get requirements [Serialize], fmt=0x2C, w=512, h=512, alignment=32768, size=1398784, type=15
RDOC 011688: [19:02:44] vk_resource_funcs.cpp(1187) - Warning - Get requirements [Serialize], fmt=0x2C, w=512, h=512, alignment=32768, size=1413120, type=15
```

```
RDOC 011688: [19:02:44] vk_resource_funcs.cpp(1187) - Warning - Get requirements [Serialize], fmt=0x2C, w=512, h=512, alignment=32768, size=1404928, type=15
RDOC 011688: [19:02:44] vk_resource_funcs.cpp(1187) - Warning - Get requirements [Serialize], fmt=0x2C, w=512, h=512, alignment=32768, size=1419264, type=15
```

I even logged the requirements during capture from rpcs3 side after vkcreateImage and I'd say most of them match but its not 100%. There are huge discrepancies is some outputs.

example:
Rdc
```
RDOC 010740: [18:52:21] vk_resource_funcs.cpp(1187) - Error   - Get requirements, fmt=0x2C, w=256, h=256, alignment=32768, size=378880, type=15
```
vs rpcs3
```
E {rsx::thread} RSX: Get requirements, fmt=0x2C, w=256, h=256, alignment=32768, size=360448, type=15
```

The validation errors came up always on these kinds of situations so thats looking to be the culprit. Only the alignment is consistent, size is not. Looks like some allocation algorithm at play

**Comment by kd-11** [comment] 2017-11-06 16:29
Confirmed that is the issue. Hacking Serialize_AllocateMemory to allocate slightly more than requested size fixed the crashing and made the validation warnings and errors disappear.

**Comment by baldurk** [comment] 2017-11-06 16:39
Interesting, though that's not going to work for long - e.g. if you start suballocating from a larger memory allocation, you'd end up with overlapping memory use.

From what I can see you're only printing some of the CreateInfo members - format/width/height. Can you also print all of the other members? E.g. `usage` will definitely change the results, so will `tiling` and `mipLevels`/`arrayLayers`, and maybe `flags`.

The spec guarantees that as long as certain members are identical you must get the exact same requirements out. Although that technically only applies within a single instance, in practice it means the same driver will return the same thing for a given query so it should match between capture/replay too. So there must be something in the input params varying if you're getting different results out.

**Comment by kd-11** [comment] 2017-11-06 17:22
Nope. Logged all inputs and still not exact. Even when all members match the size parameter varies alot. This is from the same run
```
E {rsx::thread} RSX: Get requirements, type=1, fmt=0x2C, w=256, h=256, d=1, mipmaps=9, layers=1, samples=1, tiling=0, usage=7, flags=0, initial_layout=0, alignment=32768, size=380928, type=15
E {rsx::thread} RSX: Get requirements, type=1, fmt=0x2C, w=256, h=256, d=1, mipmaps=9, layers=1, samples=1, tiling=0, usage=7, flags=0, initial_layout=0, alignment=32768, size=362496, type=15
```

So is this set
```
E {rsx::thread} RSX: Get requirements, type=1, fmt=0x2C, w=256, h=128, d=1, mipmaps=9, layers=1, samples=1, tiling=0, usage=7, flags=0, initial_layout=0, alignment=32768, size=183808, type=15
E {rsx::thread} RSX: Get requirements, type=1, fmt=0x2C, w=256, h=128, d=1, mipmaps=9, layers=1, samples=1, tiling=0, usage=7, flags=0, initial_layout=0, alignment=32768, size=198144, type=15
E {rsx::thread} RSX: Get requirements, type=1, fmt=0x2C, w=256, h=128, d=1, mipmaps=9, layers=1, samples=1, tiling=0, usage=7, flags=0, initial_layout=0, alignment=32768, size=179712, type=15
E {rsx::thread} RSX: Get requirements, type=1, fmt=0x2C, w=256, h=128, d=1, mipmaps=9, layers=1, samples=1, tiling=0, usage=7, flags=0, initial_layout=0, alignment=32768, size=194048, type=15
```

Whole dump from the section is here https://gist.github.com/kd-11/d8f21571f4b243cbe941566b9b6e26a8.

In fact for `usage=(VK_IMAGE_USAGE_TRANSFER_DST_BIT | VK_IMAGE_USAGE_TRANSFER_SRC_BIT | VK_IMAGE_USAGE_SAMPLED_BIT)` the size value is never the same.

My hack was only to prove that the memory binding failed because the allocation was too small to fit the image created, so its not a real fix, I just used it to illustrate the issue.

Furthermore, the spec specifically omits any guarantees on the size value. Alignment and memoryTypeBits are guaranteed to be the same if some members match, but size is not and in this case they are identical despite the size varying.

The results here are certainly surprising to me. I had no idea that the size could vary by so much given similar input.

**Comment by baldurk** [comment] 2017-11-06 17:47
Yeh sorry, didn't mean to state the obvious I just wanted to clarify that we're on the same page.

Something weird is definitely happening here. If you've isolated it to this case, could you see if you can make a synthetic test case on a branch off RPCS3 that exhibits the bug? E.g. just artificially create a bunch of images even if the application doesn't, with those properties above. Maybe then it's something I could build and run myself.

I also wonder if you're able to repro this bug if you call vkCreateImage in a loop, or if it relies on other vulkan commands in between the image creates to repro fully. That might explain why this isn't so widespread (as otherwise I feel like more people would be hitting this problem).

Also other obvious thing just to eliminate a possibility - try latest driver version 17.11.1.

**Comment by kd-11** [comment] 2017-11-06 18:30
From quick testing (latest driver):
1. If the test game is not affected, duplicating the routine in a loop has no effect (the same inputs give the same output)
2. If the test game is affected, duplicating the routine gives different results every time despite the calls being back-to-back.

Tested with both 10 and 1000 repeats of VkCreateImage followed by VkGetImageMemoryRequirements then VkAllocateMemory then VkBindImageMemory.

Unfortunately its difficult to know what makes it not happen in some cases (usually homebrew games with few unique textures are fine, but even menus for AAA games will cause the differing size value).

As for how widespread it is - it seems to affect older GCN. I've heard of 7800 series, R9 200 series crashing with renderdoc. Polaris and GCN 3 are not affected - I had filed a bug report (for a different issue) with AMD at some point and they were able to replay traces captured using renderdoc on GCN 3 (R9 380). I can only confirm that R9 270x and R9 280x are affected. I'll clean and reinstall the new driver just in case and update if anything changes.

**Comment by kd-11** [comment] 2017-11-06 19:35
Wiped and reinstalled 17.11.1 and I can confirm it does not change the behaviour. It seems as soon as some condition is met the required sizes become slightly variable.

**Comment by baldurk** [comment] 2017-11-06 23:37
Fair enough. It'll still come down to getting a repro to somehow investigate. It definitely sounds like something is weird, but to narrow it down to something fixable or reportable to AMD it would need a repro case.

**Comment by kd-11** [comment] 2017-11-07 07:00
Imo its intentional. The spec allows the size value to vary but is very explicit on alignment and typebits so there might be cases where they thought it desirable. I could try and ask as a general question and see if anyone replies but I dont see them changing the driver while they are within spec.

**Comment by baldurk** [comment] 2017-11-07 10:52
Yeh it sucks but you're right, it's technically spec legal. They're allowed to do it even if it's very inconvenient.

I think the solution then on my side (until I have a proper memory requirement abstraction system in place) is to falsely bump up the reported `size` for images to account for the variance.

Looking at the figures, there are some case where simply aligning `size` up to `alignment` would not be sufficient. E.g. `179712` aligned to `32768` is `196608` - still less than `198144`. So I'd need to go to `alignment*4` in this case, which would produce `262144`.

It's going to mean some waste per image but I don't see any way around that, and hopefully it should be minimised. I'll try and commit this later today for you to test.

**Comment by baldurk** [comment] 2017-11-09 12:04
Sorry for the delay, I was caught up getting the new serialisation merged in. Can you try with that commit and see if it fixes things for you? If there are cases which still exceed I might have to increase the padding already more, but it's already adding an uncomfortable overhead.

**Comment by kd-11** [comment] 2017-11-09 12:49
The crash due to size not being enough to fit seem to be gone. A new serializer? bug has appeared though - you can easily recreate this one by using Hero City 2, a VkImage reference is broken on every trace during replay.

Relevant lines in log:
```
RDOC 007568: [15:41:23]     vk_serialise.cpp( 105) - Warning - Capture may be missing reference to VkImage resource.
Exception thrown: read access violation.
GetWrapped<VkImage_T * __ptr64>(...) returned 0x163.
```

Call stack
![image](https://user-images.githubusercontent.com/15904127/32606082-f6c42de0-c564-11e7-9f45-0ef4bd76ca2d.png)

Full log:
https://gist.github.com/kd-11/abe1279c807922774a56f1bb3dac9ceb

Not sure if I should bother opening another issue for it as it seems unrelated, but it looks like the workaround fixes the memory problems. Cant fully verify until its capable of fully loading the traces though.

**Comment by baldurk** [comment] 2017-11-09 15:13
Sorry about that, yes indeed there were some bugs from the serialisation refactor - sort of to be expected. I've just pushed fixes for the ones I ran into on Hero City 2, let me know how you get on with that now.

**Comment by kd-11** [comment] 2017-11-09 16:16
Looks like its fixed now. Tested a few AAA captures just to be sure. If it does crop up again I'll try to figure out something that gets calculations closer to AMD's requirements and let you know, but its looking good so far.

**Comment by kd-11** [comment] 2017-11-09 16:20
Looks like I spoke too soon. I've hit another assert with broken ref to a commandbuffer
```
RDOC 017392: [19:17:43]   vk_queue_funcs.cpp( 307) - Debug   - Queue Submit partial replay 19288 < 20034
RDOC 017392: [19:17:43]   vk_queue_funcs.cpp( 330) - Debug   - Queue Submit partial replay of 215521 at 9404, using 1000000000000006044
Exception thrown: read access violation.
GetWrapped<VkCommandBuffer_T * __ptr64>(...) returned 0xFFFFFFFFFFFFFFE7.
```

![image](https://user-images.githubusercontent.com/15904127/32616269-f1f55d48-c582-11e7-95a9-8e79365b380e.png)

To reproduce, once the log has loaded, jump to a random color pass and it hits this one.

**Comment by baldurk** [comment] 2017-11-09 16:30
That one I can't reproduce on Hero City 2, I've jumped all over (and there's only one pass in that capture anyway). It's probably going to be more specific to your particular captures and its command buffer setup.

Can you tell me which line it's on in `Serialise_vkQueueSubmit` though? It's cropped off the right side of your screenshot. I don't see anything obvious looking just now but maybe if I narrow down where I should look I'll see something wrong.

edit: actually it's probably not going to be something obvious, looks like the command buffer is just NULL which means it's broken somewhere else in the capture.

**Comment by kd-11** [comment] 2017-11-09 16:40
Line 379, vk_queue_funcs.cpp
To trigger, select the whole pass group to view the combined output and not expand it into individual draw calls. Expanding the passes works just fine.
EDIT; Selecting the draw calls also crashes for me. Maybe something in rpcs3 changed since you got the last build.
EDIT2: Tried an older build and got the same result.

**Closed as completed** 2017-11-09 18:33 UTC
Labels: Bug
