### ISSUE TITLE
Pixel Transfer operations using Pixel Buffer Objects don't get recorded.

### ISSUE THREAD

**Issue by NogginBops** [baldurk/renderdoc#2238] opened 2021-04-07 01:17 UTC
## Description

RenderDoc doesn't record changes to buffers caused by calling pixel transfer operations with a buffer bound to `GL_PIXEL_PACK_BUFFER`. (see [`Pixel Transfer`](https://www.khronos.org/opengl/wiki/Pixel_Transfer) and [`Pixel Buffer Object`](https://www.khronos.org/opengl/wiki/Pixel_Buffer_Object)).

`glReadPixels`, `glReadnPixels`, `glGetTexImage`, `glGetnTexImage`, `glGetTextureImage`, `glGetnCompressedTexImage`, and `glGetCompressedTexImage` all have a special case where they instead of writing to client memory they write to the buffer currently bound to `GL_PIXEL_PACK_BUFFER` using the `void *pixels / void *data` argument as an offset into the pack buffer instead.

`glReadPixels` and `glReadnPixels` copy their data from the read framebuffer ([`glReadBuffer`](https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/glReadBuffer.xhtml)) while the rest of the functions copy data from a texture.

From [documentation](https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/glBindBuffer.xhtml):
`While a non-zero buffer object is bound to the GL_PIXEL_PACK_BUFFER target, the following commands are affected: glGetCompressedTexImage, glGetTexImage, and glReadPixels. The pointer parameter is interpreted as an offset within the buffer object measured in basic machine units.`

## Steps to reproduce

This can be reproduced by doing the following:
(this code is originally not written in c/c++, so there might be translation issues in it)
```c
glActiveTexture(0);
// bind a texture matching the GL_RGBA, GL_FLOAT format and type.
glBindTexture(GL_TEXTURE_2D, someGLTexture);
// bind a large enough buffer, considering texture width, height and format + packing alignment
glBindBuffer(GL_PIXEL_PACK_BUFFER, packBuffer);

// this causes 'packBuffer' to be filled with the data inside of `someGLTexture`.
glGetTexImage(GL_TEXTURE_2D, 0, GL_RGBA, GL_FLOAT, NULL);

// code that then uses the read buffer to render things
// eg. rendering each color of the texture as a point in a vectorscope
```

What **happens** when this code is run is that RenderDoc just ignores that the buffer should be updated with new data, and is left in whatever state it was previously in.
What **should** happen is that the operation actually updates the content of the buffer in question.

I tried poking around in the source seeing if I could have a go at fixing the issue, but it turned out to be slightly more complicated than I would have hoped (mostly because I'm not familiar with the codebase). Though it seems like it's pretty obvious that functions like `glGetTexImage` doesn't get serialized like the rest of the functions (which is on purpose according to #1201, but in this case it fails as it actually **does** affect the capture).

@baldurk If you want I can probably author a fix for this, though I will probably require assistance in how to make the fix as I'm not very familiar with the code (and it might take a while as I have other commitments).
If you don't think it's too much effort to implement yourself then you are more than welcome to.

## Environment

* RenderDoc version: v1.13
* Operating System: Windows 10 Home 19041.867
* Graphics API: OpenGL 4.6

**Comment by baldurk** [comment] 2021-04-07 10:59
I'm not working this week so I'll look into this in more detail next week, but I suspect that this is something I don't want to implement/support. OpenGL is generally a pretty awful API and it does support some obtuse corner cases like this, which are often a lot more of a headache to implement than they are worth. This wouldn't be the only example of that.

**Comment by NogginBops** [comment] 2021-04-07 20:18
I think having a more working recording of OpenGL commands is worthwhile, especially as RenderDoc is pretty much the go-to program for debugging OpenGL applications. The OpenGL documentation and standard itself seems pretty clear on how the pack and unpack buffers work so it doesn't really seem like that much of an edge case to me.

But I guess there is no point in arguing for this point before you've taken a closer look, so I'll wait for next week. 🙂 

If you decide you don't want to implement it, would you then be against a PR fixing this issue or is it fine if someone else fixes it?

**Comment by tksuoran** [comment] 2021-04-10 12:39
FYI I am observing RenderDoc having trouble capturing/showing actual contents of renderbuffer, possibly related to the fact that I do readpixels with pixel pack buffer after the draw calls. In the application I can observe that the asynchronous reads work correctly, however, RenderDoc is not able to show me renderbuffer contents. Sometimes I see nothing, sometimes I see noise, sometimes cycling through Overlay options fixes the issue.

**Comment by baldurk** [comment] 2021-04-10 12:53
Please don't comment on different bugs with another problem. Open a new issue with steps to reproduce the  problem you're seeing.

**Comment by tksuoran** [comment] 2021-04-10 15:59
Okay, sorry, I thought this might be related. I'll open a new bug.

**Comment by NogginBops** [comment] 2021-04-11 10:07
I think this issue is very closely related if not the same issue.
Personally I don't really care too much about the actual `glReadPixels` or `glGetTexImage` appearing in the timeline (although it would be nice), I'm mostly concerned about the data not appearing in the buffer (sorry if that was not clear from the initial issue).

Linking #2242 for relevance.

**Comment by baldurk** [comment] 2021-04-12 19:03
That issue is not related at all and I'm not sure why you got that impression. It's something entirely different and has been fixed now.

Considering this use case and looking more closely at the spec, I do not want to add support for this and would not accept any PR implementing it. I'm primarily concerned with the possible side-effects or unintended interactions with other parts of the code and replay and on different platforms/drivers, as OpenGL especially is incredibly complex and inter-dependent and this could easily cause all sorts of bugs in other places. As you say this is legal according to GL, but this isn't the only thing that is legal but I consider too high a maintenance/complexity burden to support.

**Closed as completed by baldurk** 2021-04-12 19:03 UTC
Labels: Bug, Unresolved

**Comment by NogginBops** [comment] 2021-04-13 13:43
I didn't have time at the time to look at the capture for 2242 and it seems that I misunderstood what the issue was.

This issue is visible in the capture as between EID 237 and 238 there is a call to `glGetTexImage`/`glReadPixels`, but the contents of the buffer bound to `GL_PIXEL_PACK_BUFFER` are not updated. This is not an issue in 2242 because the contents of the buffer is not used in subsequent rendering and instead downloaded to the cpu at a later time.
![image](https://user-images.githubusercontent.com/3778357/114562428-c7f52700-9c6e-11eb-89d5-80591b510309.png)

It's unfortunate that this isn't something you want to support.
Could you please elaborate on the potential issues you see with adding this?
To me this seems like a very isolated of part of the api, so I'm having trouble seeing in what kinds of way handing this could affect other parts (keep in mind I'm not super familiar with the rdc codebase).

I'm still interested in making a fix for this issue in a local repo.
I started poking around in the code, but it was unclear to me how the process of serializing and replaying commands works.
I figured out I needed to record the necessary data, and "replay" that data in some way, but there where quite a few different recording states, so knowing what needed to be done when (stuff like background recording vs actual recording etc). Is there somewhere I should look to understand this more or could you explain how the different parts go together?

**Comment by baldurk** [comment] 2021-04-13 14:14
That's the point really, the readback not being present makes no difference because it doesn't have significant GPU side-effects, which is the expectation for readback functions. Much like any other glGet* functions they're omitted from the capture because they're intended to be CPU facing only.

The concern I have is the same as anything else in GL where the combinatorial complexity of any one feature gets multiplied by everything it can possibly interact with. Making sure this works correctly with multiple contexts, potential state leakage, tracking that state etc is not worth it for a feature this small and low in utility. Bear in mind that from your perspective you perhaps only need one small isolated change and only run it on one machine, but I have to consider all use-cases and all platforms.

I expect that most applications using pixel pack buffers use it only for async readbacks as in the above example and not to then re-use on the GPU since you already have the source texture on the GPU that you can use directly. That means the risk of adding bugs for people by implementing this feature is likely more significant than the cases it will fix. The pixel unpack stuff took a while to get completely bullet proof and that's a feature which is regularly used.

There's no up to date abstract documentation as with the small number of developers even looking at RenderDoc's source let alone writing code it hasn't been worthwhile. The best I can suggest is looking at the existing code and any comments that are there which should be up to date. Sorry I can't spend the time to give more specific guidance on how to implement this because as I mention above the time investment is not worthwhile.

**Comment by NogginBops** [comment] 2021-04-13 15:25
I understand, I will take a look at the code and try and figure it out myself when I have the time. I've seen similar state stuff before so I should be able to figure it out with some reading, I just asked in case there was a good explanation already.
And if I don't get to fixing this I can always use something like Nsight, as that seems to record the updated buffers.
Cheers, and thanks for your work on this software :)
