### ISSUE TITLE
RenderDoc UI process exits instantly on v1.0

### ISSUE THREAD

**Issue by SakibSaikia** [baldurk/renderdoc#902] opened 2018-03-07 19:25 UTC
I updated to ver 1.0 yesterday, and I'm having the trouble with the new version not launching. When viewed in ProcessExplorer, I see qrenderdoc start up, but it exits immediately. I tried a full uninstall and resinstall but the problem persists. A co-worker also has the same issues.

Win 10 Enterprise (10.0.16299 Build 16299)
Core i7-7700K
Radeon RX 570

Thanks!

**Comment by baldurk** [comment] 2018-03-07 19:36
That does sound strange. If the exe starts it's not a missing dependency..

Can you check out the repository and build it locally, to see if debugging will produce more information?

**Comment by SakibSaikia** [comment] 2018-03-07 19:54
I'm seeing this 

Exception thrown at 0x00007FFBD2E22B10 (ntdll.dll) in qrenderdoc.exe: 0xC0000139: Entry Point Not Found.

**Comment by baldurk** [comment] 2018-03-07 19:56
Is that on the installed build or a local build? If it's the installed build, is it possible that renderdoc.dll wasn't properly updated - check the version numbers on the file in case it's been left behind from an older version somehow.

**Comment by SakibSaikia** [comment] 2018-03-07 19:59
That is on a local build with latest (Development/x64)

**Comment by baldurk** [comment] 2018-03-07 20:02
That does seem strange, do you have a callstack where the exception is fired, to know which entry point is missing?

I'll try to think of what I might be using which could be missing. You're on windows 10 so it shouldn't be an OS entry point (and I use windows 7 where it works).

**Comment by SakibSaikia** [comment] 2018-03-07 20:13
The exception is thrown in this line

QApplication application(argc, argv);

I can continue execution until Py_Initialize() at which point it bails out and exits.

**Comment by baldurk** [comment] 2018-03-07 20:25
If the exception is thrown on that line but you can continue past, I guess it isn't the cause of the problem and is handled internally in Qt. Py_Initialize() is called from PythonContext::GlobalInit() several lines down from there so it can't be a fatal exception.

Do you know what causes it to exit under that python call, is there any error printed or exception from visual studio? I've had problems before with python that calls exit(1) if it encounters a problem which is quite annoying for an integrated library - the last time it was because the python libraries weren't found and it hit a fatal error, but the python libraries should be available as they're committed to the repository. Make sure you have python36.zip next to qrenderdoc.exe in your build.

**Comment by SakibSaikia** [comment] 2018-03-07 20:51
It just says 

The thread 0x3f94 has exited with code 1 (0x1).
The thread 0xb94 has exited with code 1 (0x1).
The thread 0x4588 has exited with code 1 (0x1).

... and python36.zip is present next to qrenderdoc.exe

**Comment by SakibSaikia** [comment] 2018-03-07 21:09
FWIW, if I comment out the call to PythonContext::GlobalInit(), I can get it to work. Is python only used for scripting?

**Comment by baldurk** [comment] 2018-03-07 21:30
Yes it's only used for scripting, so this should work as long as you don't use the python shell at all. However I'd really like to find whatever is causing this bug in case anyone else runs into it on v1.0.

I've uploaded a local debug build of python36.dll and python36.pdb here: [python_test.zip](https://github.com/baldurk/renderdoc/files/1790947/python_test.zip) where I've replaced calls to `exit()` with a `__debugbreak()` so you should hopefully be able to get a callstack of where it's exiting, and maybe we can understand what's going wrong.

Can you put those files next to your build and run again, to see what happens?

**Comment by SakibSaikia** [comment] 2018-03-07 21:46
This is the callstack it shows

![image](https://user-images.githubusercontent.com/8186559/37119995-f8870232-220d-11e8-9c4d-4e9aa47173b0.png)

**Comment by SakibSaikia** [comment] 2018-03-07 21:49
Here is the diasm at the point of the break

![image](https://user-images.githubusercontent.com/8186559/37120119-527402e0-220e-11e8-8b4a-b48cf40a0927.png)

**Comment by baldurk** [comment] 2018-03-07 21:53
That indicates that the `site` module failed to import (you can see the string message in the disasm there).

Searching around the internet for possible causes, do you have any python related environment variables set? E.g. `PYTHONHOME` or `PYTHONSCRIPTS` or anything like that? I wonder if it's trying to open an incompatible module from somewhere unexpected.

**Comment by SakibSaikia** [comment] 2018-03-07 22:03
Yep, that was it. `PYTHONHOME` was set to point to set path for python.

**Comment by baldurk** [comment] 2018-03-07 22:05
OK, thank you for taking the time to investigate with me!

It seems like I need to find a way to either ignore any such environment variables or force python36.zip to be loaded first. I think I can probably just safely un-set any such variables in qrenderdoc before initialising python, but I'll need to check.

-----

To anyone encountering this problem and looking for a workaround - unsetting any environment variables like that should fix the problem temporarily until a proper fix is implemented.

**Comment by SakibSaikia** [comment] 2018-03-07 22:10
Yes, that would be great. Thank you for investigating this.

**Comment by baldurk** [comment] 2018-03-07 22:10
Actually if you don't mind testing one thing, it looks like there is a flag to do this. Can you try making this change just before the call to `Py_Initialize` ?

```cpp

  Py_SetProgramName(program_name);

  // add this statement here
  Py_IgnoreEnvironmentFlag = 1;

  Py_Initialize();

  PyEval_InitThreads();
```

**Comment by SakibSaikia** [comment] 2018-03-07 22:15
Works like a charm :)

**Comment by baldurk** [comment] 2018-03-07 22:16
Perfect! I'll commit that change, and leave this issue open for a little while for people to see it and the workaround.

**Closed as completed** 2018-04-03 12:01 UTC
Labels: Bug
